# Abstract {- .unlisted .unnumbered}

Chemokines are emerging as key players in a broad array of biological responses in the brain under physiological, non-inflammatory conditions.
They can be found in all brain cells - from brain-blood barrier endothelium, through all types of glia, to neurons and neural stem cells. 
Neuron-glia crosstalk is also suggested to be modulated by chemokines.
It should be noted that glial cells not only express chemokine receptors, but also can dynamically release them, and thus, influence the activity of neurons or other brain cells.
This orchestration of neuron-glia crosstalk is believed to be essential in maintaining brain homeostasis.
Among them, CX3CL1 and CXCL12 have attracted much attention by demonstrating their role in such phenomena as neurogenesis, neuroprotection, as well as modulation of synaptic transmission and plasticity.<!-- this PhD dissertation will mainly focus on two chemokines, CX3CL1 and CXCL12, together with their corresponding receptors, CX3CR1 and CXCR4, as they are widely distributed in the CNS under non-inflammatory, physiological conditions and involved in an increasing array of functions, such as neurogenesis, neuroprotection, synaptic transmission, synaptic plasticity and behavior//// Among them, CX3CL1 and CXCL12 are particularly important in this regard, as they are constitutively and widely expressed in the CNS, where they act on cellular, synaptic, network, and behavioral levels. // Two of them, CX3CL1 and CXCL12, have particularly received much attention due to their constitutive and widely distributed expression in the CNS, along with their well-documented impact on neurodevelopment, neuroprotection, synaptic transmission, synaptic plasticity, and behavior.-->
The relatively high expression of their receptors, i.e., CX3CR1 and CXCR4, in brain region linked with emotional reactions supports the association between them and neuropsychiatric diseases, such as anxiety or depression. 
Consistently, the impairment of CX3CL1/CX3CR1 and/or CXCL12/CXCR4 signaling led to behavioral of neurobiological consequences, such as impaired learning or anxiety.
Despite this, mechanisms of chemokines in the regions involved in anxiety (such as the amygdala) remain largely unknown.
It would provide critical insight into the physiological mechanisms underlying neuroimmunological interactions in the amygdala.

The aim of this study was to dissect the underlying mechanisms and effects of activation of CX3CR1 and CXCR4 receptors on synaptic transmission and electrophysiological property of neurons in two nuclei of the amygdala - basolateral (BLA) - the main input nucleus, and central (CeA) - the main output nucleus.
To this end, the whole-cell patch clamp technique and extracellular recordings were used. 
In order to confirm the neuronal expression of CX3CR1, the immunohistochemistry stainings was used. by using a combination of electrophysiological and pharmacological approaches, the actions of two chemokines (CX3CL1 and CXCL12) were determined in two nuclei of the amygdala - 
Moreover, this study is trying to dissect the involvement of microglia and astrocytes in these effects.<!-- mechanisms of chemokine-regulated neuron–glia communication in the context of synaptic transmission.-->


Doświadczenia zostały wykonane głównie za pomocą rejestracji elektrofizjologicznej aktywności komórek nerwowych z wykorzystaniem technik whole-cell patch clamp oraz rejestracji polowych długotrwałego wzmocnienia synaptycznego. 
W celu określenia dokładnej lokalizacji receptora CX3CR1 wykonano także barwienia histochemiczne.

W BLA, podanie chemokiny CX3CL1 zwiększyło prąd progowy, prowadząc tym samym do zmniejszonej pobudliwości neuronów głównych (ang. *principal cells*, PCs). 
Temu efektowi towarzyszyła osłabiona plastyczność synaptyczna w synapsach korowo-podstawnobocznych oraz zmniejszona częstotliwość spontanicznych hamujących prądów postsynaptycznych. 
Efekty te blokowane były w obecności antagonisty receptora CX3CR1, AZD8797. 
Również zastosowanie inhibitora aktywności mikrogleju, minocykliny, blokowało efekty podania chemokiny CX3CL1. 
Uzyskane wyniki mogą sugerować, że  aktywacja receptorów CX3CR1 poprzez wpływ na przekaźnictwo GABArgiczne oraz osłabienie pobudliwości komórek podstawowych i procesów plastyczności synaptyczej może modulować pamięć i reakcję emocjonalną. 

W CeA, CX3CL1 zmniejszała oporność błony komórkowej  neuronów regularnie wyładowujących się (ang. *Regular-Spiking neurons*; RS), co skutkowało spadkiem ich pobudliwości. 
Spadek aktywności tych neuronów spowodował zmniejszenie częstotliwości postsynaptycznych prądów hamujących (sIPSCs) rejestrowanych w  neuronach o późnym początku wyładowania (ang. *Late-Firing neurons*; LF).
Efekty te były blokowane w obecności w obecności antagonisty receptorów CX3CR1 AZD8797 lub po zahamowaniu aktywności komórek mikroglejowych minocykliną. 
Sugeruje to, że aktywność sieciowa CeA jest przynajmniej w części modulowana przez aktywację receptorów  CX3CR1. 

Podanie chemokiny CXCL12 w BLA wywoływało nieznaczny wzrost pobudliwości PCs oraz dwukierunkowe zmiany w hamującej transmisji synaptycznej, chociaż  oba te efekty nie uzyskały istotności statystycznej. 
Kierunek zarejestrowanych efektów aktywacji receptora CXCR4 jest zgodny wynikami uzyskanymi przez inną grupę badawczą, która wykazała wzrost przekaźnictwa pobudzającego w BLA po podaniu CXCL12. 

Podanie CXCL12 zwiększyło pobudliwość zarówno neuronów RS jak i LF w CeA. 
Podanie tej chemokiny nasilało również częstotliwość spontanicznych pobudzających prądów synaptycznych rejestrowanych z neuronów RS. 
Efekty te blokowane były przez antagonistę receptora CXCR4, AMD3100.
Aktywacja receptorów CXCR4 zwiększała także częstotliwość spontanicznych postsynaptycznych prądów hamujących rejestrowanych z neuronów RS. 
Natomiast rejestracja z neuronów LF wykazała hamujące działanie  CXCL12 na amplitudę  prądów GABAergicznych. 
Efekt ten był blokowany przez antagonistę receptora CXCR4, jak i przez zablokowanie aktywności astrocytów podaniem fluorocytrynianu. 
Podsumowując, uzyskane wyniki sugerują neuromodulacyjną rolę chemokin w obu badanych jądrach obszaru ciała migdałowatego.
Dalsze badania w tym zakresie mogą prowadzić do lepszego zrozumienia mechanizmów neuroimmunologicznych w ciele migdałowatym i dostarczyć nowych kandydatów dla rozwoju leczenia zaburzeń związanych z funkcjami tej struktury. 


In the BLA, CX3CL1 reduced neuronal excitability of principal cells, the main glutamatergic neurons in this region, constituting around 90% of neuronal population. 
This effect was accompanied by the impaired LTP at cortico-BLA synapses and attenuated GABAergic transmission manifested as a decreased frequency of sIPSCs.
In the CeA, CX3CL1 modulated passive membrane properties in Regular-Spiking neurons, resulting in the attenuation of their spiking and consequently reduced inputs onto Late-Firing cells, manifested as a decreased frequency of sIPSCs.
All those effects were eliminated in the presence of the antagonist of CX3CR1 receptor, AZD8797, or minocycline, the inhibitor of microglial activity.
This points to both network- and microglia-modulated effects.

Regarding CXCL12, despite a trend towards the increase in the excitability and complex modulation of GABAergic transmission, this chemokine did not exert any statistically significant effects in the BLA.
However, CXCL12 enhanced firing in both types of CeA neurons.
Interestingly, there was also trend in CXCL12-induced facilitation of the sEPSCs frequency preferentially onto Regular-Spiking neurons.
Regarding GABAergic transmission, CXCL12 application triggered an increased frequency of sIPSCs onto Regular-Spiking neurons, whereas the amplitude of this events in Late-Firing neurons was reduced. 
Moreover, while its regulation of neuronal excitability was dependent mainly of CXCR4 receptor, the GABAergic transmission was also dependent on astrocytes.
Altogether, findings from this PhD dissertation highlight neuromodulatory role of CX3CL1 and CXCL12 in the amygdala, which is a consequence of their regulation of local neuron-glial communication.
Therefore, these results imply CX3CL1/CX3CR1 and CXCL12/CXCR4 fine-tuning on the network level in the amygdala and the behavioral relevance of their modulation.

A better understanding of the sequence and nature of events that drive neuro-glial communication in the brain, including the amygdala, holds promise for the development of new treatment strategies that could, in a context- and time-dependent manner, modulate the action of specific chemokines to promote brain repair and reduce the neurological impairment.<!-- Continued investigation in this vein will hopefully provide novel insights into neuro-immune mechanisms in the amygdala and yield new targets for developing treatments of amygdala-related disorders.
-->

\newpage

<!-- może się przyda .... 

can orchestrate both neuroprotective and detrimental effects.

are endowed with neuromodulatory actions which make them potential candidates for altering neuronal network excitability in epilepsy.

they  induce  responses  that  are  tightly  adjusted to the homeostatic needs of the neuronal circuitry in the brain.


neuromodulators and coordinators of neuron-glial communication. -->