# Acknowledgments {- .unlisted .unnumbered}

*Składam serdeczne podziękowania **mojemu promotorowi, Panu prof. dr hab. Krzysztofowi Tokarskiemu**
za opiekę i pomoc naukową podczas moich studiów doktoranckich, 
zaangażowanie, przekazaną wiedzę, a także cenne wskazówki i sugestie
udzielone mi w czasie realizacji niniejszej pracy.
Dziękuję również opiekunowi mojego grantu Preludium, **Panu prof. dr hab. Grzegorzowi Hessowi**,
za pomoc oraz cenne uwagi
podczas wykonywanej przeze mnie pracy naukowej

Dziękuję także **koleżankom i kolegom z Zakładu Fizjologii**, 
zawsze chętne udzielanie mi pomocy i tworzenie miłej atmosfery w pracy.
Szczególnie chciałabym podziękować **dr Bartoszowi Bobuli** za wykonanie zewnątrzkomórkowych rejestracji elektrofizjologicznych.

Dziękuję również **Pani dr Izabeli Figiel-Ożóg i Panu prof. dr hab. Jakubowi Włodarczykowi z Pracowni Biofizyki Komórki Instytut Nenckiego w Warszawie** za wykonanie barwień na obecność receptora CX3CR1 w pierwotnych hodowlach neuronalnych ciała migdałowatego. 


W sposób szczególny chciałabym podziekować **moim najbliższym, szczególnie moim Rodzicom, Bartkowi, oraz mojemu bratu** za niewyczerpane pokłady wsparcia, cierpliwości i wiary we mnie.
Byliście przez te lata niczym najlepsza motywacyjna grupa couchów i bez Was ta praca by nie powstała.*


<!--Bez Waszej obecności i wsparcia 
 za nieustanne wsparcie, motywację i cierpliwość,
a także mojej rodzinie i przyjaciołom, którzy
również wspierali mnie i mobilizowali do pracy // Na końcu dziękuję Łukaszowi, Rodzicom, siostrze i przyjaciołom oraz kolegom i koleżankom z Zakładu Neurofizjologii i Chronobiologii, bez których codziennej obecności i wsparcia ta praca by nie powstała.-->


\newpage

