### Chemokines action at synaptic/axonal/dendritic level {#synapse} {#chemokineselectro}

Accumulating data reveals that chemokines modulate neuronal electrical activity through both postsynaptic (i.e., including electrophysiological output following chemokine receptor activation, such as Ca^2+^ transients, intrinsic membrane properties by activation/inactivation of particular channels/receptors) and  presynaptic (i.e., including presence in synaptic vesicle and (co-)release of neuropeptides/neurotransmitters/gliotransmitters) mechanisms (@rostne_2007).
In addition, mounting evidence shows interactions between the chemokine system and "classical" neurotransmitters or neuromodulators. <!-- + glial // indirect effects of glial components, --><!--Considering complexity resulting from differences in postsynaptic cell machinery, including (i) diverse signaling pathways, (ii) a rich repertoire of channels and receptors present among cells expressing a particular chemokine receptor and channels, (iii) dual/opposite action of the same chemokine, (iv) multiple chemokine ligands for particular chemokine receptors or few receptors binding one particular chemokine ligand present at the same cell, as well as possible (v) indirect effects of glial components, chemokines may exert mixed, both pre- and postsynaptic (for example: @guyon_2005) and/or functional outcomes due to chemokine receptor activation may differ in a cell- and circuit-specific manner (for example: @heinisch_2010). -->  
Therefore, this chapter aims to summarize electrophysiological studies, focusing on chemokines' interaction with other systems and glial cells (see: Table 2). <!-- Additionally, based on the premise that dendritic spines are a structural manifestation of synapses, I will briefly outline the evidence that chemokines also regulate these membrane protrusions.-->

#### Glutamate {#Glu}

In the hippocampus, a region crucial for cognition, CX3CL1 was demonstrated to reduce the amplitude of both synaptic [@ragozzino_2006] and AMPA-evoked currents [@ragozzino_2006; @lauro_2008], suggesting a postsynaptic mechanism.
These effects are probably a result of a PKA-related phosphorylation of GluR1 Ser845 [@ragozzino_2006]. <!-- of CX3CR1? -->
Further investigations revealed that CX3CL1 did not act directly on postsynaptic neurons, but instead this chemokine activated microglia, which in turn, released adenosine.
The presence of this molecule<!--?-->led to the inhibition of the glutamatergic transmission by its receptors, adenosine A3 receptor (A~3~R), and to the lesser extend adenosine A1 receptor (A~1~R)  (@lauro_2008, @lauro_2010; @piccinin_2010, see: Fig4B).<!--!!!-->  

Adenosine is an endogenous modulator of brain functions  with increasingly evident actions on synaptic transmission [@ribeiro_2010] or glia [@boison_2010], which acts by binding to its GPCR presynaptic receptor subtypes (A~1~, A~2A~, A~2C~, A~3~) and alter neurotransmitter release probability [@verkhratsky_2009]. <!-- Gliotransmitters include adenosine triphosphate, which, when converted to adenosine, acts on presynaptic adenosine receptors to alter neurotransmitter release probability and short-term plasticity.-->
In the hippocampus, adenosine was demonstrated to decrease the glutamatergic synaptic transmission in these cells, even despite the absence of CX3CL1, suggesting adenosine tonic activity in this structure [@piccinin_2010]. <!-- poprawić ... -->
Further evidence indicates that the activation of A~1~R and A~3~R results in a decrease in synaptic transmission, whereas A~2A~R exerts the opposite effect, manifested as CX3CL1-induced increase of evoked EPSC (eEPSC) in the blockade of A~1~R and A~3~R receptors [@piccinin_2010]. 

CX3CL1 was also shown to trigger D-serine<!--release?-->, NMDAR co-agonist released from glial cells, and potentiate NMDAR function in an A~2A~- and D-serine-dependent manner, which was driven by microglial cells [@scianni_2013]. <!-- okropne zdanie...-->
Therefore, the CX3CL1-induced adenosine release may affect glutamatergic neurotransmission by a mechanism involving a combination of three different AR subtypes and both glutamatergic receptors. 
Nevertheless, the opposite effects of CX3CL1 on AMPAR and NMDAR functions are nicely correlated with the difference between A~3~R/A~1~R and A~2A~R receptors.
Moreover, the depressed glutamatergic transmission following CX3CL1 and adenosine application corresponds with results from studies of synaptic plasticity (see: Section \@ref(LTP)).

In relation to astrocytes, it is increasingly evident that these cells actively participate in synaptic transmission.
For instance, considering the high expression of CXCR4 in astrocytes, pioneering studies have shown that CXCR4 activation triggers a burst of exocytosis, <!--on a millisecond time scale -->leading to the release of Ca^2+^ from internal stores [@cal_2008].
These results further support the notion that astrocytes can respond to external stimuli and communicate *via* fast release of glutamate on a millisecond time scale [@cal_2010]. <!-- Interestingly, astrocytic synaptic-like microvesicles (SLMVs) express vesicular glutamate transporters (VGLUTs), and they can release glutamate by Ca^2+^-dependent regulated exocytosis [@cal_2008]. both in tissue and in cultured astrocytes-->

In addition to glutamate, CXCR4 is also known to release prostaglandins and TNF`r knitr::asis_output("\U03B1")` upon activation by CXCL12 on astrocytes [@bezzi_2001], which has key functional consequences on the neuronal networks as described in the next section (\@ref(scal)). 
Evidence indicates that CXCR4 can also affect NMDAR. 
For instance, CXCR4 receptors were shown to be presynaptically located in hippocampal noradrenergic and glutamatergic nerve endings.
They were connected with presynaptic NMDA receptors, suggesting that CXCR4-NMDAR interactions can regulate both noradrenaline and glutamate exocytosis (@diprisco_2016, see also: \@ref(NE)). 
Moreover, in the cerebellum, CXCR4 activation results in a decrease in NMDAR function, and thus, leads to synaptic depression [@ragozzino_2002], probably by CXCL12-induced reduction in NR2B expression subunit of NMDAR [@nicolai_2010].
CXCR4 is also widely expressed on microglia, and thus being able to react to astrocytic glutamate. <!-- najlepiej rozbudować -->

#### GABA {#GABA}
 
Among chemokines, CXCL12 is the most widely studied and was demonstrated to exert diverse electrophysiological effects in distinct neuronal populations within the same or different structures. 
Specifically, by CXCR4 activation in the dorsal raphe nucleus (DRN), CXCL12 enhanced sIPSC frequency on serotonergic neurons, whereas it reduced sIPSC amplitude in non-serotonergic neurons [@heinisch_2010], suggesting postsynaptic and presynaptic mechanisms, respectively.
Evidence from another electrophysiological study has illustrated that CXCL12 increases the release of GABA from hypothalamic melanin-concentrating hormone (MCH) neurons, which affects the excitability of these cells in a dose-dependent manner [@guyon_2005].
Similarly, in the SN, CXCL12 enhanced the frequency of sIPSCs and mIPSCs, indicating  presynaptic mechanisms, which is consistent with the documented presence of CXCR4 on the GABAergic neurons [@guyon_2006].
Furthermore, following CXCL12 treatment, Purkinje cells in the cerebellum showed an increase in the spontaneous GABAergic activity by CXCR4 activation [@limatola_2000a].
Interestingly, CXCR4 is associated with outward TTX-sensitive G protein-coupled inward rectifying potassium (GIRK) channel.
This current was shown to be prevented by applying the GABA~B~ antagonist, suggesting GABA spillover onto GABA~B~ receptors [@guyon_2007] as well as CXCR4-exerted actions by additional GABAergic receptor.<!-- nie wiem czy tak w ogóle mogę napisać, ale niech będzie...-->

Regarding CX3CL1 actions on GABAergic transmission, this molecule was shown to increase the amplitude of sIPSC and eIPSC, without affecting paired-pulse ratio (PPR).
These effects lead to an increased sensitivity of serotoninergic DRN neurons to GABA inputs, therefore indirectly inhibits serotoninergic neurotransmission [@heinisch_2009].

<!--Such effect has been previously described for another member of the chemokine family, namely CXCL14, shown to inhibit GABA-mediated postsynaptic currents and the GABAergic  tonic currents39. banisadr 2011-->

#### Dopamine {#DA}

CXCL12, together with its corresponding receptor, CXCR4, are constitutively expressed in the dopaminergic neurons (DA) of the SN (see: \@ref(expr)). <!-- ( Banisadr et al., 2000, 2002a, 2005a,b, 2003 ).--><!-- czy ACKR3 też????? -->
Moreover, despite differences in channel modulation between CCL2/CCR2 (a closure of potassium channels) and CXCL12/CXC4 pairs (an increase in the N-type channel, one of high voltage-activated (HVA) channels), they both produce a similar effect: the increase in excitability of dopaminergic neurons of SN, which leads to an enhanced DA release [@guyon_2008a;  @guyon_2009]. <!-- sprawdzić jakie kanały i czy na pewno te /// induced: (i) a depolarization and increased action potential frequency; and (ii) switched the firing pattern of depolarized DA neurons from a tonic to a burst firing mode. This suggests that SDF-1 could increase DA release from neurons. []-->
<!-- Moreover, by using neuronal cultures from SN, it was elegantly shown that CXCL12 alone did not affect DA release, but neurons need prior depolarization (e.i. with the potassium chloride (KCl) solution), which activates the calcium HVA currents, and consequent CXCL12-induced DA secretion [@guyon_2008].-->

These data strongly suggest that the CXCL12 can act directly as a neuromodulator of dopaminergic neuronal electrical activity through the modulation of HVA currents.
Moreover, in the same neuronal population, CXCL12 application leads to an increase in an inward current resistant to tetrodotoxin (TTX).
It was speculated that its source might be glutamate secreted from non-neural cells [@guyon_2006]. 
As CXCR4 was not present on astrocytic cells in the SN [@guyon_2008], thus this inward current likely resulted from the activation of CXCR4 on microglia. 
However, further experiments need to verify this hypothesis.

#### Neuropeptides {#neuropep}  

In addition, CXCL12 was reported to co-localize with neurons releasing neuropeptides, such as vasopressin (AVP)<!-- also called arginine vasopressin--> and melanin-concentrating hormone (MHC) in posterior pituitary neurons, and substance P in DRG neurons (see Sections: \@ref(cell)).<!-- nie wiem co się złego stało z , \@ref(autocrine) --><!-- cytowania? --> 
These findings suggest that CXCL12 cognate receptor, CXCL12, is involved in the autocrine regulation of these neurons.
Consistent with this idea, CXCR4 was described to directly modulate several voltage-dependent channels, including Na^+^ and K^+^ channels of the action potential in MCH neurons [@guyon_2005], or tetrodotoxin-sensitive sodium currents in hypothalamic neurons [@guyon_2005a].
Moreover, this chemokine is packed in small dense vesicles in the nerve terminals of these neurons, which are then released from neuronal cell bodies and terminal nerve endings in a calcium-dependent manner (for example: ). <!-- cytowanie z CXCL12 --> 

Furthermore, electrophysiological recordings of supraoptic neurons have demonstrated that CXCL12 decreases the electrical activity of AVP neurons *via* CXCR4, resulting in modifications in AVP release.
In addition, intracerebroventricular injections of CXCL12 were illustrated to significantly inhibit the release of AVP induced by high plasma osmolarity [@callewaere_2006].


#### Serotonin {#ser}

As described above, both CXCL12 and CX3CL1 were found to modulate GABAergic synaptic transmission onto serotoninergic neurons.
CXCL12 was shown to increase sIPSC frequency, which may inhibit the excitability of serotoninergic cells and the release of its neurotransmitter.
In contrast CX3CL1  increases the amplitude of sIPSCs and eIPSC, without affecting PPR, increasing the sensitivity of serotoninergic neurons to GABA inputs and consequently inhibiting 5-HT neurotransmission  [@heinisch_2009, @heinisch_2011]. 

Thus, despite different mechanisms of modulation of GABAergic transmission, the electrophysiological output is similar, and to date, all chemokines are suggested to inhibit serotoninergic cells in DRN. 

#### Opioids {#opio}

Convincing evidence illustrates that opioid receptors and  CKRs are often co-expressed in the same neuron and can directly interact, thus each influencing the function of the other (see Section: \@ref(cxcl12)). 
The most studied mechanism in this regard is the heterologous desensitization, where the  activation of one type of GPCR receptor leads to the inactivation of another GPCR receptor present in the same cell.
Consistent with this idea, following CXCL12 exposure, the heterologous desensitization of opioid receptors has been linked to functional outcomes at cellular (e.g. reduced chemotaxis [@szabo_2002]) and electrophysiological (e.g. decreased morphine-induced hyperpolarization in PAG neurons in the presence of CXCL12 [@heinisch_2011]) levels. <!-- Phosphorylation is an   essential step for heterologous desensitization. Such phosphorylated   receptors lose their capacity to couple to the   downstream heterotrimeric G protein and   therefore become insensitive to stimulation.   -->

A recent elegant study has provided extensive<!--novel?new?--> evidence that ACKR3 is a chemokine receptor with the ability to bind opioid peptides; however opioid binding did not trigger downstream signaling through this receptor [@meyrath_2020].
Thus, it is suggested that ACKR3 serves scavenger functions for many opioids, especially enkephalins and dynorphins, by reducing their availability for their classical opioid receptors [@meyrath_2020]. 
Accordingly, treatment with ACKR3 agonist LIH383, even at high concentration, did not produce any electrophysiological effect in PAG<!--or locus coruleus?--> neurons, confirming the scavenging function of ACKR3 in this brain region.
Interestingly, in the presence of the ACKR3 agonist, dynorphin A improved its potency towards its classical receptors, which resulted in more significant inhibition of neuronal firing than in the absence of ACKR3 activation [@meyrath_2020]. 
These findings suggest that ACKR3 regulates opioid peptide availability, and consequently its signaling through their classical receptors [@meyrath_2020], adding another level of complexity and fine-tuning to the opioid system but also opens additional therapeutic opportunities.

#### Dendritic spines {#spines}

Synaptic transmission is explicitly related to dendritic spines, as these tiny, actin-rich, postsynaptic protrusions from a dendrite, receive most of the excitatory synaptic input in the brain. 
Functional and structural changes in dendritic spines are also critical for synaptic plasticity (see Section: \@ref(network)), a cellular model of learning and memory. 
It should be noted that their spine morphology is tightly correlated with their synaptic function [@nishiyama_2019]. <!-- Therefore, it is plausible that long-term potentiation (LTP) and depression (LTD), two major forms of synaptic plasticity, are correlated with the spine enlargement and shrinkage, respectively [@nishiyama_2019]. -->
Moreover, the spine morphology is highly dynamic: it could vary within the same dendritic arbor and thus is  interdependently regulated.

In agreement with glial contribution to synaptic functions,<!--może inaczej ująć--> astrocytes [@perezalvarez_2014], microglia [@paolicelli_2011], and oligodendrocytes [@zemmar_2018] are implicated in interactions with dendritic spines in a highly active-dependent manner.

The first evidence of a link between chemokines and dendritic spines was provided by Paolicelli et al. [@paolicelli_2011].
Deficient of CX3CR1 microglia displayed impairment in synaptic pruning, reflected as a transient deficit in excitatory synaptic transmission and a reduced synaptic density as compared to their wild-type littermates, indicating immature synaptic properties. 
These changes were present during the early postnatal stage (P8-P28) and then returned to baseline, highlighting CX3CR1 impact on synaptic pruning during neurodevelopment.
However, these mice were also tested in similar experimental settings in their adulthood (P40) [@zhan_2014]. 
Interestingly, despite unchanged dendritic spine density, neurons from CX3CR1^-/-^ mice displayed a lower frequency of mEPSCs and sEPSCs in comparison to their wild-type littermates. 
These results illustrate that a transient reduction in microglial synaptic pruning during development is sufficient to induce the long-term deficit in synaptic multiplicity, whereas the number of excitatory synapses remained the same [@zhan_2014].
These data support the idea of a critical window during which microglia-mediated synaptic pruning is crucial for proper circuit maturation.
 
Similarly, CX3CL1 impact on dendritic spines was documented investigating newborn cells. 
By using the same strain of mice, it was documented that adult transgenic animals displayed a reduced number of dendritic spines with morphological changes, reflected as enlargement and shortening,  in adult-born granule neurons in the dentate gyrus (DG) [@bols_2018]. 
Despite being ultrastructurally enlarged, synapses at both afferent and efferent levels were depleted of synaptic vesicles, suggesting impaired functionality. <!-- lepiej, ale upewnić się -->

These results are nicely complemented by findings obtained by the following elegant study.
Specifically, adding microglial cells to the hippocampal neuronal culture results in an upregulation of excitatory synaptic currents together with a higher density of dendritic spines.
In constrast, microglial depletion from hippocampal organotypic cultures led to both reduction in the dendritic spine density and excitatory synaptic transmission [@ji_2013]. 
Moreover, in adult mice,  pharmacological inhibition of microglial activation was associated with the prevention of dendritic spine loss in obese mice [@cope_2018].
These findings strongly suggest that microglia are key players in the regulation of the dendritic spine density. 

Moreover, dysfunctions in glutamatergic neurotransmission in CX3CR1 KO mice were further confirmed in CA3-CA1 synapses in hippocampal slices [@basilico_2019]. <!-- ale during development ? -->
Recordings from slices of transgenic mice displayed an immature AMPA/NMDA ratio with defective AMPA components and decreased release probability when compared to wild-type mice.
These results illustrate that neuron–microglia interactions profoundly influence the functional maturation of excitatory presynaptic function. <!-- zmienić -->

CXCL12 is another chemokine that is documented to be involved in dendritic spine modifications [@pitcher_2014,  @festa_2020].<!-- Another chemokine receptor demonstrating an association with dendritic spines is CCR5. -->
Specifically, this chemokine increases dendritic spine density in cerebral cortex human neurons.
For example, CXCR4 activation by CXCL12 was reported to positively regulate neuronal survival and dendritic spine density in cortical neurons.<!-- what deficits? /// citations? -->
However, the molecular mechanisms underlying CXCR4 regulation of dendritic spines are not completely defined [@nash_2019].

However, considering that dendritic spines reflect the structural level of synaptic plasticity along with extensive evidence of chemokine actions on excitatory synaptic transmission and synaptic plasticity, it is tempting to speculate that chemokines actions on dendritic spines are still unexplored. 

Taken together, as expected from their complex expression of cellular pattern and dynamic chemokine-receptor<!--może inne określenie--> interactions, chemokines modulate intrinsic membrane properties, synaptic transmission, and gliotransmission by implementing diverse cell- and region-specific mechanisms. 

### Chemokines action at the network level {#network} 

The finding that chemokines exert a neuromodulatory role in the brain is essential for a better understanding of the complex communication network between neurons and cells from their surrounding microenvironment. 
This section illustrates the emergent concept of chemokine coordination of neural networks, such as neuroendocrine functions, GABA receptor-mediated synaptic transmission, and synchronized oscillatory activity. 

#### Interneurons {#interinter}

All neuronal circuits of higher animals comprise excitatory and inhibitory neurons forming intense feed-forward and feedback connections [@mohler_1990, @ferrante_2009, @roth_2012].
However, the precise control of network operations would not be possible without interneurons.
Although they constitute only 20-30% of all cells in cortical circuits, this small, diverse group of inhibitory neurons enables higher brain functions, such as working memory, cognitive flexibility, attention, or social interaction (for a review: @mederos_2019). 
Through inhibition, GABAergic interneurons can shape the circuit activity controlling (1) frequency of surrounding pyramidal neurons, (2) network excitation level by feed-forward mechanism, and (3) synchronized oscillation events [@mederos_2019]. 

The importance of interneurons in relation to network functioning illustrates the highly controlled manner by which interneurons connect with other neurons [@tremblay_2016]. 
The best-characterized feature of constitutively expressed chemokines in the brain, particularly CXCL12 and CX3CL1, is the regulation of cell and axonal/neurite migration during neurodevelopment.
Noting their documented modulation of GABAergic transmission (see Section: \@ref(GABA)) may indicate that chemokines participate in this process.
Consistently, CXCL12/CXCR4 axis was demonstrated to guide interneurons (for example: @casoni_2012) and promote the maturation of GABAergic neurons during neurodevelopment [@luo_2008].
Moreover, as expected, perturbation of CXCL12/CXCR4 signaling, e.g., in their gradients, leads<!--was revealed to lead--> to premature cortical plate invasion by cortical interneurons and, in the long term, disturbance in their laminar and regional distribution [@lpezbendito_2008], leading to the dysfunctional neural network. 

Disturbances were also present regarding CX3CL1/CX3CR1 pathway, which plays an essential role in neurodevelopment. 
Similar to CXCL12, the CX3CL1/CX3CR1 axis was demonstrated to affect the outgrowth of dopaminergic axons in the forebrain and the laminar positioning of subsets of cortical interneurons [@squarzoni_2014].
Moreover, CX3CR1 deficiency impairs the functional maturation of thalamocortical synapses in the developing barrel cortex, indicating crucial involvement of CX3CL1/CX3CR1 signaling in this process [@hoshiko_2012].
As the CX3CR1 receptor is mainly expressed by microglia, and those cells display a well-documented process of network maturation, called synaptic pruning, microglia are likely to participate in the maturation of synapses. 
Therefore, these findings highlight the importance of chemokines regulation of  proper neural network functioning by their effects on interneurons migration and maturation.

Neuronal growth and synapse formation can also be achieved by a phenomenon called giant depolarizing potentials (GDPs).
GDPs are spontaneous network-driven rhythmic-like large neuronal oscillations in the developing hippocampus, formed by GABA, exerting depolarizing and excitatory actions during postnatal development. 
CXCL12 was reported to tonically inhibit GDPs,  further highlighting the role of this chemokine in neuronal development [@benari_2002].
Moreover, they are modulated by external factors, including chemokines, such as  CXCL12 and CX3CL1 [@meucci_1998; @liu_2003; @sheridan_2014].<!-- może lepiej to sklecić -->

Importantly, Sheridan et al. [@sheridan_2014] reported that the CX3CL1 application in the hippocampus has  opposing effects on glutamate-induced Ca^2+^ transients depending on whether it was applied alone or simultaneously with a GABA~A~ blocker, picrotoxin.
These results highlight the possible modulation of CX3CL1 in regulating the balance between excitation and inhibition on the network level.
However, whether the chemokine system participates in feed-forward inhibition signaling remains an open question for future research.

#### Synaptic plasticity {#plast}

Synaptic plasticity is defined as a molecular form of learning, memory, and development in neural circuits.
It mainly comprises such mechanisms as Hebbian plasticity, synaptic scaling, and adult neurogenesis. 
Among different factors regulating synaptic plasticity, glial cells have been considered key players in maintaining synapse homeostasis [@deluca_2020; @field_2020; @kettenmann_2011; @mederos_2018].

##### Hebbian plasticity - LTP and LTD {#LTP}

Hebbian synaptic plasticity is the earliest and most widely accepted neurobiological theory of memory consolidation. 
According to this concept, a synapse will be strengthened if the presynaptic neuron is active while the postsynaptic neuron is firing, a process called Hebbian modification. 

As mentioned earlier in the section on synaptic transmission (see: \@ref(Glu)), in the CA1 hippocampus, CX3CL1 induced phosphorylation of AMPA subunit GluR1 at postsynaptic sites [@ragozzino_2006], which is one of the hallmarks of the LTD.
Moreover, one group reported  no difference in LTD in the hippocampus between adult wild-type and knockout mice.<!--cytowanie--> 
In contrast, LTD is enhanced in CX3CR1^-/-^ mice at P13 [@paolicelli_2011], suggesting that CX3CL1 has the highest relevance during early postnatal age.

However, similar electrophysiological studies indicated either a complete lack of LTP in knockout mice [@rogers_2011] or a more pronounced LTP than in wild-type counterparts when LTP was induced by a weak stimulation protocol [@maggi_2011]. 
Interestingly, when mice were housed in an enriched environment compared to wild-type mice, they had enhanced plasticity [@maggi_2009].
These results suggest that the absence of  microglia-driven CX3CR1 signaling impedes enrichment effects, possibly due to some shared  mechanisms that warrant further investigation. <!-- coś nie w porządku z tym zdaniem -->
It is speculative that this lack of beneficial response to environmental stimulation might be explained by altered microglia–neurons cross-talk, affecting the circuitry underlying synaptic plasticity.

Regarding the DG, CX3CL1 decreased the LTP at those synapses; however, when GABA~A~ receptors were blocked, the magnitude of the LTP was enhanced [@sheridan_2014], indicating that the CX3CL1-exerted actions may differ based on inhibitory/excitatory balance (see: Table 2). 
Alternatively, noting the CX3CL1-induced potentiation of NMDA function and thereby the increase in calcium transients [@scianni_2013] together with the inhibition of the LTP induction following NMDAR activation, it is also possible that CX3CL1-induced elevated level of intracellular calcium could interfere with the LTP induction [@scianni_2013]. 

These inconsistent findings between laboratories might result from differences in age, gender, diet, housing conditions, or electrophysiological protocols.
Especially age and gender could be relevant, as the same laboratories cannot replicate their results when those variables had differed. 
Hence, effects on synaptic plasticity and behavioral outcomes resulted from the CX3CL1-CX3CR1 axis may be transient and quickly compensated in knockout mice. 

Chemokine regulation of synaptic plasticity is not restricted to the hippocampus. 
CX3CL1 was shown to induce synaptic depression of evoked parallel fibers inputs onto Purkinje neurons [@giovannelli_1998], and mice with CX3CR1^-/-^ receptor deletion were characterized by the LTP in the spinal cord [@bian_2015].
Future research should clarify whether mechanisms underlying CX3CL1-induced synaptic plasticity are general.  
However, it would be implausible, considering that (i) microglia displays many region-specific features, especially when compared in cerebellum and cortex [@stowell_2018], (ii) CX3CR1-induced microglial during development are region-specific [@lowery_2017], as well as (iii) mechanisms governing LTP may differ between structures, for instance, between the hippocampus and spinal cord [@liu_2017].

##### Synaptic scaling {#scal}

In order to prevent the destabilizing component of Hebbian plasticity in network function, neurons are able to sense their excitability and trigger negative-feedback homeostatic mechanisms to counteract perturbations in synaptic activity and restrain it within a dynamical but physiological range [@field_2020]. <!-- computational -->
Recent accumulating data also highlight the essential role of glial cells, as they are equipped with, for instance, glutamate transporters to control the concentration of glutamate and other neurotransmitters in the microenvironment. <!-- może jakoś lepiej napisać --> 
Importantly, stable but flexible neural activity is fundamental for proper brain function and support of animal behavior, depending on a dynamic interface between homeostatic synaptic  plasticity  mechanisms  and  Hebbian  forms  of plasticity [@field_2020; @tremblay_2016].

It is widely accepted that TNF`r knitr::asis_output("\U03B1")` mediates synaptic scaling, a form of homeostatic plasticity leading to the adjustment of synaptic strength [@stellwagen_2006]. 
Glia, mainly astrocytes, have been identified as the main source of TNF`r knitr::asis_output("\U03B1")` in the CNS.
Therefore, by modulating TNF`r knitr::asis_output("\U03B1")` levels, glia participate in homeostatic activity-dependent regulation of synaptic plasticity [@stellwagen_2006].
As it is well-documented that CXCR4 is mainly expressed on astrocytes, CXCL12/CXCR4 pathway is also involved in regulating synaptic plasticity. <!-- cytowanie??? -->
Moreover, evidence also implicated microglia in the regulation of synaptic plasticity, as they release TNF`r knitr::asis_output("\U03B1")` [@pascual_2012]. 

##### Adult neurogenesis

Adult neurogenesis in the rodent brain is thought to reside in two niches, the SVZ adjacent to the lateral ventricles and the subgranular zone (SGZ) located in the DG.
Division, maturation, and forming functional synapses or apoptosis are key processes that need to be tightly controlled to maintain an adequate balance between plasticity and stability.
As expected, more and more data shows an increasing impact of glial cells and chemokines on this phenomenon. 
Consistently, increasing studies implicated both exogenous or exercise-induced CX3CL1 in promoting neurogenesis and  NSC/NPC activity in a microglia-dependent manner, whereas depletion of CX3CR1 resulted in a decreased number of newly generated neurons [@vukovic_2012, @bachstetter_2011, @rogers_2011]. 
Moreover, morphological alternations in mature granule cells were still present in CX3CR1 deficient mice [@bols_2018], suggesting their long-lasting changes.

#### Neuroendocrine circuit {#neuroendo}

The hypothalamus, a brain region comprised of different nuclei and several neuronal populations producing neuropeptides, is critically involved in the regulation of major neuroendocrine functions, including water/food intake, metabolism, and also stress.

Depending on the concentration, CXCL12 is thought to exert opposite effects on the action potential discharge [@guyon_2005], which may have functional consequences on the activity of neuroendocrine networks.
Specifically, CXCR4 is tonically active at low physiological concentrations, constantly exerting its action on MCH neurons.
Under basal conditions, those cells showed more hyperpolarized membrane potential than orexin neurons, which do not express CXCR4 [@eggermann_2003]. 
Moreover, CXCL12/CXCR4/ACKR3 signaling dysfunctions are associated with feeding disorders, such as anorexia.
Consistently, a high-fat diet was reported to increase the expression of CXCL12, its receptors, and neuropeptides, such as enkephalin, galanin, orexin, and MCH in the PVN and perifornical lateral hypothalamus [@poon_2016]. 
Importantly, intracerebroventricular injection of CXCL12 was shown to mimic those effects of the high-fat diet in the hypothalamus, suggesting a vital role of the CXCL12/CXCR4/ACKR3 axis in feeding behavior [@poon_2016]. 

<!-- Some chemokines such as cytokine-induced neutrophil chemoattractant (CINC, the rat counterpart of the human growth-related oncogene, GRO/), neutrophil-activating peptide-1, stromal cell-derived factor (SDF-1) also named CXCL12 and monocyte chemoattractant protein-1 (MCP-1) also named CCL2 have been found to be expressed in the hypothalamus and in the pituitary [10,31,76]. --><!-- CXCL14 protein is present in a subset of hypothalamic neurons and suggest that CXCL14 participates in hypothalamic functions such as control of autonomic nervous systems and/or participates in immune cell recruitment via the median eminence Yamato2011 też feeding ale nie wiem czy to poruszać...-->


#### Functional connectivity

Considering the relevance of chemokines' role in neurodevelopment (i.e., neuronal/axonal migration and synaptic pruning), it can be hypothesized that proper chemokine signaling during neurodevelopment is of high importance to provide functional connectivity between many cortical regions. 
However, to date, there is a scarcity of data on this topic. 
In particular, by measuring connections between hippocampus and prefrontal cortex, mice with deletion of CX3CR1 revealed a decrease in  the  coherence  between  those two structures, compared  to  their wild-type  littermates (@zhan_2014, see Fig 4D).<!-- !-->
Thus, this finding suggests that the depletion of CX3CR1 leads to  a  decrease in  hippocampal–prefrontal connectivity, which may have behavioral consequences, such as anxiety or cognitive impairments [@zhan_2014].  
Moreover, knockout mice showed reduced frontal cortex oscillatory driving to the hippocampus than their wild-type littermates at baseline conditions  [@zhan_2015]. 
It is speculative whether it is the consequence of morphological modifications of microglia depleted of CX3CR1 [@piirainen_2021], but scanty evidence is available so far. <!-- tutaj może poprawić tę drugą część zdania...-->
Nevertheless, these results highlight a fundamental role of CX3CL1 at the network level. 
Hence, considering those findings and accumulating evidence of glial impact on the network, investigating chemokines’ role in neural networks may be an exciting direction in the future.

//// 


<!-- electrophysiological  network ?  
An increasing number of chemokines exhibit extensive regulation across a range of situations where neuronal plasticity is involved; including memory-associated functional plasticity, protective plasticity in the setting of ischemia and maladaptive plasticity such as that underpinning neuropathic pain (Adler et al., 2006; Rostene et al., 2007; McAfoose and Baune, 2009; Old and Malcangio, 2012). Specifically, the role for CX3CL1 in control of hippocampus and Raphe activity suggests that infection-, inflammation-, and/or chronic disease-associated increases in the chemokine could contribute to reduced hippocampal and Raphe output, alterations that could, in turn, precipitate depressed mood and heightened anxiety among other disorders of brain function (Meltzer, 1990; Bast, 2011; Small et al., 2011).- Sheridan2014-->


The role of CXC12 in synaptic transmission is described below and summarized in Table 1.

### CXCL12/CXCR4/ACKR3 

CXCL12 has been shown to play an essential role in brain plasticity during development but also in regulating the activity of various brain circuits in normal and pathological conditions [@merino_2014, @timotijevi_2012, @tiveron_2008a]. <!-- zmienić -->
Furthermore, recent studies have shown that there are several cross-talks between the CXCL12 and with its receptor CXCR4 and other neurotransmitter systems in the brain (e.g. GABA, glutamate and endocannabinoids) [@heinisch_2010a, @heinisch_2011]. <!-- zmienić -->
The neuromodulatory actions of CXCL12 have been observed in various neuronal populations, including the hippocampus [@kasiyanov_2008], cerebellum [@limatola_2000], MCH neurons of the lateral hypothalamus area [@guyon_2005] (LHA), vasopressinergic neurons of the hypothalamus [@callewaere_2006], dopaminergic neurons of the substantia nigra [@guyon_2006], the dorsal raphe nucleus [@heinisch_2010a] and recently the amygdala [@yang_2016]. <!-- zmienić -->
What is particularly interesting, CXCL12 has often similar effects in these various circuits (increase in glutamate and/or GABA synaptic activity), however these effects occur *via* different mechanisms, even within one structure. <!-- zmienić -->
For example, in the dorsal raphe nucleus CXCL12 increases the frequency of recorded spontaneous inhibitory post-synaptic currents (sIPSC) in serotonergic neurons through a presynaptic mechanism, but decreases sIPSC amplitude *via* a postsynaptic mechanism in non-serotonergic neurons [@heinisch_2010a]. <!-- zmienić -->
Moreover, CXCL12 often appears to exert opposite effects on neuronal function depending on its concentration, e.g., in MCH-expressing neurons of the LHA, where the action potential discharge is different depending on the concentration [@guyon_2005]. <!-- zmienić -->
Of particular interest is the observation that pro-inflammatory cytokine stimulation leads to elevated levels of CXCL12 and other chemokines by activation of glial or endothelial cells which in turn release chemokines [@guyon_2014]. 

CXCL12 is stored in vesicle like structures within neurons which seem to be neurotransmitter storage vesicles (Bhattacharyya et al. 2008).
It has been shown that the development of adult DG neural stem cells is regulated by the release of GABA from neurons of this type (Ge et al. 2007; Bhattacharyya et al. 2008). 
Release of CXCL12 within the DG neural stem cell niche is able to enhance GABAergic transmission to neural stem cells (Ge et al. 2007; Bhattacharyya et al. 2008).
We observed that CXCL14 had essentially the opposite effect and could inhibit GABAergic inputs to these cells. The GABAergic input to DG neural stem cells takes the form of both tonic and phasic transmission.
Interestingly, both tonic and phasic effects of synaptically released GABA were inhibited by CXCL14. We also observed that some cells responded to both CXCL12, which enhanced, and CXCL14, which decreased GABAergic transmission to nestin-expressing cells. Hence, it seems likely that CXCL12 and CXCL14 represent ‘up’ and ‘down’ volume controls that can regulate GABA inputs to neural stem cells in a reciprocal fashion. The fact that CXCL14 and CXCL12 are also both contained in DG GABAergic interneurons (Bhatta- charyya et al. 2008) increases the probability of a meaningful connection between the effects of these three molecules in the control of DG neuron development in the adult. By comparison neither CXCL14 nor CXCL12 altered GABAergic transmission to mature granule cells in the DG (Figure S3 and Bhattacharyya et al. 2008).
   
In our previous studies, we concluded that the effects of CXCL12 on DG neural stem cells were likely to be mediated  post-synaptically  (Bhattacharyya et al. 2008). Indeed, CXCR4 receptors are clearly expressed by these cells (Tran et al. 2007; Bhattacharyya et al. 2008). It is also clear from our experiments that adult neural stem cells express the receptor (or at least ‘a receptor’) for CXCL14. Thus, CXCL14 increased [Ca2+]iin these cells, one of the cardinal signs of chemokine receptor signaling. Given the fact that neural progenitor cells express the receptor for CXCL14 and the observation that the chemokine reduces the amplitude of GABAergic PSCs recorded from these cells one might conclude that the effect of CXCL14 is at least partly mediated post-synaptically. However, it is quite possible that a pre-synaptic effect is also involved. Precise identification of the mechanism by which CXCL14 produces its effect will have to await further studies on identifying its receptor and its location in the DG.

Guyon_2006
CXCL12 a increased glutamate release in SN slices, as previously described in other brain structures such as cerebellum (Ragozzino et al . 1998) or hypothalamus (Guyon et al . 2005b). This current was not blocked by TTX, suggesting that it did not involve action potential-dependent release through the glutamate terminals. Glutamatergic terminals on DA neurones arise from the output of the subthalamic nucleus or prefrontal cortex, which are absent from our slices. Increased calcium permeability in terminals might raise the probability of spontaneous release of glutamate or uptake of glutamate might be inhibited at the axon terminal exposed to CXCL12 a . However, sEPSCs recorded in 10 lM bicuculline were unaffected by CXCL12 a . It is therefore likely that CXCL12 a induces glutamate release from glial cells present in the slice.

It is well established that CXCL12 a mobilizes cytosolic calcium following stimulation of CXCR4 in astrocytes and microglia (Tanabe et al . 1997), and that an increased calcium concentration in these cells may cause a massive release of glutamate (Araque et al . 2001). Interestingly, in the SN, the CXCL12 a effect was independent of CXCR4 as it was not blocked by AMD (1 lM) (Fig. 6), consistent with the lack of CXCR4 on astrocytes revealed by immunostaining. The mechanism of action of CXCL12 a on glutamate release thus needs further investigation.


in particular, CXCL12/CXCR4 pair modulates cerebral cortex ( Bagri et al., 2002; Lu et al., 2002; Stumm et al., 2003; Stumm and Höllt, 2007 ) and cerebellar ( Ma et al., 1998; Zou et al., 1998 ) development.

<!--sickness behavior, nie wiem czy nie do behavior-->
The chemokines released bind to CXCR4 present on neurons and induce changes in excitability that could induce an adaptive response to inflammation, leading to “sickness behavior,” characterized by decreased mood, anorexia, and fatigue [@dantzer_2001, @dantzer_2007]. <!-- zmienić -->
Sickness behavior is considered to be the physiological and psychological effect of immune activation during the course of infection, which is primarily mediated by the central action of peripherally released proinflammatory cytokines. <!-- zmienić -->
Given the abundance of chemokines and their receptors in the CNS, it is not surprising that changes of cytokine/chemokine levels during inflammation are causing multiple physiological and behavioral perturbations. <!-- zmienić -->
For example, effects of CXCL12 on dorsal raphe neurons could underlie depressive symptoms frequently observed with inflammation [@maes_1998], as dysfunction of the serotoninergic systems is implicated in depression.<!-- zmienić -->
Similarly, the effects of CXCL12 on MCH neurons which are part of the feeding behavior and metabolism control circuit [@nahon_2006] could explain anorexia. <!-- zmienić -->
These symptoms of sickness behavior are usually reversible when inflammation stops. 
Overall, this chemokine system is one of the key players in the neuro-immune interface that participates in shaping CNS responses to changes in the environment. <!-- zmienić -->

CXCL12 has been shown to act in the brain as a neurotransmitter  (Banisadr et al., 2005) and to be released with GABA from  inhibitory neurons (Bhattacharyya et al., 2008). 
CXCL12 *via* CXCR4 coupled to G~i/o~  has been shown to regulate  neuronal signaling through inhibition of voltage dependent  calcium (Ca  2+  ) currents (Oh et al., 2002), in particular the N-  type channel (Simen et al., 2001).
However, CXCL12 also  activates GIRK channels (Guyon et al., 2005; Guyon and  Nahon, 2007) which GnRH neurons express (Hu et al., 2006;  Klenke et al., 2010). 


  Since  Ca2 qis  considered  the  main  neuromodulator  of . neurotransmitter release  Katz, 1969 , cerebellar slices were 
  
   CXCL12 induces the tumor necrosis factor a (TNF a )-mediated Glu release from astrocytes (Bezzi et al., 2001) and TNF a increases the surface expression of synaptic AMPARs (Beattie et al., 2002) . @lax_2002
   
   Interneurons are guided to the correct cortical layer via CXCL12 gradients while  ACKR3 acts as a sink to collect excess CXCL12.63 

CXCL12/CXCR4 pair modulates cerebral cortex ( Bagri et al., 2002; Lu et al., 2002; Stumm et al., 2003; Stumm and Höllt, 2007 ) and cerebellar ( Ma et al., 1998; Zou et al., 1998 ) development. In adult brain, high expression of CXCR4 has been reported in neuronal progenitor cells in the subventricular region and in the subgranular zone of the hippocampus, the two major niches of neuronal stem cells in the adult brain ( Stumm et al., 2002; Berger et al., 2007 ). The expression of CXCL12 in the hippocampal granular layer regulates the generation and the positioning of new granule neurons ( Abe et al., 2018 ), as well as axonal elongation and sprouting ( Pujol et al., 2005; Lysko et al., 2011; Su et al., 2012 ). According to its role in neurogenesis, the upregulation of CXCL12 upon stroke ( Wang et al., 2012 ), or demyelination ( Carbajal et al., 2011; Patel et al., 2012; Williams et al., 2014 ) contributes to generate new cells and to restore normal CNS functions <!-- tRETTEL2020-->
 
 Pioneer experiments demonstrated that IL8 and CXCL1 potentiate the spontaneous and evoked excitatory transmission in cerebellar neurons by increasing the cytosolic Ca2+levels, whereas CXCL12 depresses the evoked input of the parallel fibers to Purkinje neurons ( Giovannelli et al., 1998; Ragozzino et al., 1998, 2002 ). CXCL12 also induces a presynaptic increase of both glutamatergic and GABAergic neurotransmission onto serotoninergic neurons in the dorsal raphe, onto cortical immature neurons upon transient MCAO and onto dopaminergic neurons of substantia nigra (SN) ( Guyon et al., 2006; Heinisch and Kirby, 2010; Ardelt et al., 2013 ). <!-- trettel-->
 
Confocal imaging of CXCR4 immunostaining as presented in this study  clearly  showed  that  in  neurons  of  the  caudate  putamen  the receptor is mostly located along the plasma membrane of perikarya and dendritic processes.  Furthermore, CXCR4 in  this region is  also expressed in beaded Æbres that resemble varicosed axonal processes. A similar pattern of CXCR4 labelling was observed in the substantia innominata (not shown). This reinforces the hypothesis that CXCR4 activation  could  modulate  synaptic  transmission  (Limatola et  al ., 2000).  Interestingly,  a  markedly  different  cellular  localization  of CXCR4 was observed in neurons from other brain regions such as the lateral   hypothalamus.   In   these   neurons,   CXCR4   labelling   was punctate  and  apparent  throughout  the  cytoplasm  of  the  perikaryon, and was barely visible in dendritic processes. This indicates that the cellular  localization  of CXCR4 may  vary  depending  on  the type  of neurons  that  express  the  receptor.  Although  the  functional  consequences of this observation are unclear at present, it may suggest that speciÆc  cellular  mechanisms  of  CXCR4  addressing  and  trafÆcking could operate in different neuronal populations [@banisadr_2002a]


Indeed, there is mounting evidence which implicates both CX3CL1 and its receptor, CX3CR1, in synaptic plasticity and neuromodulation (Bertollini et al., 2006; Ragozzino et al., 2006; Piccinin et al., 2010; Maggi et al., 2011; Rogers et al., 2011; Roseti et al.,2013; Scianni et al.,2013). <!-- zmienić // In fact, CX3CL1 is a confirmed inhibitor of basal glutamate synaptic activity in the hippocampus [@Bertollini2006]. -->

Regarding electrophysiological effects of CX3CL1 action, hippocampus is the most documented structure, as it has most-known network // a golden structure for electrophysiologist, with high basal levels of CX3CL1 transcript and protein expression. <!-- zmienić The high basal level of CX3CL1 mRNA and protein expression in the hippocampus is suggestive of a physiological, non-inflammatory function. -->
For example, CX3CL1 has been shown to reduce post-synaptic glutamate currents (Meucci et al., 1998; Limatola et al., 2005), involving an increased intracellular calcium and dephosphorylation of the GluR1 AMPA receptor subunit on serine 845 (Ragozzino et al., 2006). <!-- zmienić jeszcze trochę -- SPRAWDZIĆ spontaneous glutamate release and-->
The latter mechanism has been linked to ability of CX3CL1 to inhibit LTP and mimocs long-term depression (LTD) at the CA3–CA1 synapses in acute hippocampal slices (Bertollini et al., 2006; Ragozzino et al., 2006; Maggi et al., 2009).  <!-- zmienić CX3CL1-mediated regulation of glutamate transmission has been shown to be due to its post-synaptic effects on neurons and involves the dephosphorylation of the GluR1 AMPA receptor subunit on serine 845, a mechanism reminiscent of LTD (Ragozzino et al., 2006). //Previous studies have shown that CX3CL1 inhibits LTP and mimics long-term depression (LTD) at the CA3–CA1 synapses in acute hippocampal slices (Bertollini et al., 2006; Ragozzino et al., 2006; Maggi et al., 2009). -->
LTD can play vital roles in the context of memory-associated synaptic plasticity including synaptic scaling and enhanced signal-to-noise ratio mechanisms <!-- CITATION, ZMIENIĆ -->
These synaptic effects are consistent with a direct action of CX3CL1 on neurons most likely exerted through the CX3CR1 receptor, which is reportedly expressed on the dendrites of hippocampal neurons (Meucci et al., 2000; Limatola et al., 2005). <!-- zmienić -->
The ability of CX3CL1 to inhibit glutamate function is thought to be responsible for some of its neuroprotective actions, and provides further support for the chemokine-neuromodulatory role in the CNS [@adler_2005, @callewaere_2007, @guyon_2007]. <!-- not sure if it is my sentence Overall, previous studies indicate a predominantly inhibitory role for CX3CL1, perhaps as a component of neuroprotective synaptic scaling mechanisms necessary for hippocampal memory-associated synaptic plasticity processes (Bertollini et al., 2006; Turrigiano, 2008; Piccinin et al., 2010).-->
Consistent with this hypothesis, neuroprotective ADAM17-mediated increase in in soluble CX3CL1 is observed in multiple settings of glutamatergic neurotransmission where the chemokine is suggested to performa neuroprotective function (Chapman et al., 2000; Tsou et al., 2001; Erichsen et al., 2003; Limatola et al., 2005; Ragozzino et al., 2006; Lauro et al., 2010; Pabon et al., 2011). <!-- zmienić-->

Beyond the hippocampus, CX3CL1 is also documented to reduce the activity of serotonergic neurons in the raphe nucleus through enhanced GABA~A~ receptor-mediated inhibition (Heinisch and Kirby, 2009).<!-- zmienić trochę drugą część -->


LTP-inducing TBS resulted in an up-regulation in CX3CL1 expression after 2 h on the stimulated DG blade compared to the upper unstimulated blade. - Sheridan2014

CX3CL1 has been reportedly up-regulated in several settings of augmented glutamatergic transmission where the chemokine is clearly protective against excitotoxic cell death (Tong et al., 2000; Tarozzo et al., 2002; Limatola et al., 2005; Cipriani et al., 2011; Briones et al., 2014). Moreover, both CX3CL1 and its receptor, CX3CR1, have been shown to be up-regulated in hippocampal neurons after pilocarpine-induced status epilepticus (Yeo et al., 2011), a condition characterized by excessive glutamatergic excitation. Overall, the abundance and expression pattern of CX3CL1 make the chemokine ideally suited for sensing hippocampal glutamate tone. Our data supports a possible role for CX3CL1 in homeostatic mechanisms of synaptic scaling during memory-associated synaptic plasticity.-Sheridan2014

DOSE- SHERIDAN - DISCUSSION

<!-- glia and synaptic plasticity -->
A fundamental property of the mammalian brain is its ability to modify its function based on experience, and thereby to alter subsequent behavior. By changing the strength of transmission at preexisting synapses, transient experiences can be incorporated into the neuronal circuits as persistent memory traces during both development and adulthood. As such, synaptic plasticity is a fundamental mechanism that supports brain function (Buzsáki and Chrobak, 2005). Among the different factors that regulate synaptic plasticity, glial cells have been found to be key players in maintenance of synapse homeostasis (Eroglu and Barres, 2010). The biggest challenge when studying the effects of glial cells on brain activity is isolating the different cell-type components, i.e., neurons vs. glia. Recent research advances using various strategies, such as pharmacological or genetic manipulation and gene expression from viral vectors (Nimmerjahn and Bergles, 2015; Oliveira et al., 2015; Ben Haim and Rowitch, 2017), have allowed researchers to elucidate the role of glial cells in several aspects of brain function, and such knowledge may lead to the development of new therapies and biomarkers for many types of neurological dysfunction (Almad and Maragakis, 2018). [@mederos_2018]<!-- use all of the review -->

<!--zdania może do wykorzystania / inspiracji / Thus, further experiments  identifying the properties and functions of each of neuronal, microglial, astrocytic and, oligodendrocytic compartments remain to be addressed. Additionally, astrocytes are known to secrete chemokines like CCL5 and CCL3 that may bind CCR5 on neurons and mediate synaptic transmission and plasticity through mechanisms ranging from the prevention of extrasynaptic neurotransmitter diffusion and neurotransmitter clearance to the modulation of synaptic release probability -->
<!-- However, as adenosine was suggested to be a downstream element of both CX3CL1 and CXCL16 signaling, along with the facts that CXCL16 was shown to act directly on astrocytes leading to a secretion of CCL2 [@rosito_2012], and microglia, together with astrocytes, were identified as important cellular sources of CCL2, glial modulation of the observed effect is very plausible.///  while CXCL2 was shown to increase glutamatergic postsynaptic transmission in neurons *via* postsynaptic modulation of AMPA receptor in the cerebellum [@lax_2002],  -->