### CX3CL1 {#frak}

#### Structure

CX3CL1, also known as fractalkine, is a unique chemokine on many levels.
First of all, to date, it is the only known member of the CX3C chemokine $\delta$ family <!--((Pan et al., 1997))??.-->
The full-length of this protein (around 95 kDa), consisting of 397 amino acid in human <!-- (Bazan et al., 1997; Pan et al., 1997)--> and 395 amino acid in mice <!-- (Rossi et al., 1998). -->, is also larger than most other chemokines, whose most common size is around 70–80 amino acid. <!-- Fractalkine is a unique chemokine in that it exists in two different forms: a membrane-bound protein tethered to neuronal membranes by a mucine-like stalk (approximately 95 kDa), and a soluble factor released upon cleavage of its N-terminal chemokine domain (approximately 70 kDa) (Garton et al., 2001). Membrane-bound fractalkine has been proposed to act as an adhesion molecule, whereas the diffusible form works as an extracellular chemoattractant promoting cellular migration. This function is shared with other members of the chemokines family, commonly acting as “chemotactic cytokines” during innate and adaptive immunity. The name “chemokines” is precisely derived from this ability to mediate attraction of their responsive cells (Bazan et al., 1997; Comerford andMcColl, 2011; Pan et al., 2011; Zlotnik and Yoshie, 2012).-->
CX3CL1 is comprised of an extracellular 76-amino acid N-terminal domain, a 241-amino acid glycosylated mucin-like stalk, an 18-amino acid transmembrane helix, and a short acid cytoplasmic C-terminal domain.
Together with <!-- add another chemokine-->, fractalkine is present in two different forms: a membrane-anchored form tethered to cell membranes by a mucin-line stalk, and a shorter soluble form realesed upon proteolytic cleavage of its N-terminal chemokine domain [@bajetto_2001 <!--(Garton et al., 2001).-->] *via* the action of several protease.
This enzymes can be a class of metalloproteinases (enzymes containing a disintegrin and metalloproteinase domain) such as ADAM10, and ADAM17 or cysteine protease Cathepsin S (CatS) (TACE: TNF-α-converting enzyme) in both the periphery and CNS (Garton et al., 2001; Hundhausen et al., 2003; Clark et al., 2007; Cook et al., 2010; Jones et al., 2013). <!--poprawić, -->
<!--The soluble N-terminal chemokine domain, which has approximately 70 kDa, can be released from the transmembrane form *via* the action of several metalloproteinases (enzymes containing a disintegrin and metalloproteinase domain) such as ADAM10, and ADAM17 or cysteine protease Cathepsin S (CatS) (TACE: TNF-α-converting enzyme) in both the periphery and CNS (Garton et al., 2001; Hundhausen et al., 2003; Clark et al., 2007; Cook et al., 2010; Jones et al., 2013). <!-- poprawić! --> 
Soluble CX3CL1 acts as a conventional chemokine, promoting migration and activation of CX3CR1-expressing cells, mostly monocytes, whereas membrane bound CX3CL1 acts as an adhesion molecule, mediating leukocyte capture and infiltration (Ransohoff, 2009).<!-- CX3CL1, also named fractalkine, is produced almost exclusively by neurons under phys- iological conditions (Paolicelli et al., 2011; Rogers et al., 2011). It is synthesized as a transmembrane protein, which undergoes a proteolytic cleavage and is afterwards released into the extracellular space as a soluble cytokine, although a chemoattractant role has also been proposed for the membrane-bound form of the protein (Lauro et al., 2006; Song et al., 2013). CX3CR1 is a conventional Gi-protein coupled seven-transmembrane domain receptor that is highly expressed by microglia (Paolicelli et al., 2014; Tremblay et al., 2011; Valero et al., 2016). - Bolos2018 --> 
Moreover, unlike most chemokines, CX3CL1 is constitutively expressed in the CNS with particularly high levels in forebrain structures, including hippocampus, amygdala, cerebral cortex, globus pallidus, striatum, and thalamus (Harrison et al., 1998; Tarozzo et al., 2003). <!-- In the brainstem, a few scattered cells immunoreactive for fractalkine were initially depicted by Tarozzo and colleagues, while significant expression of the protein was subsequently observed in situ (Heinisch and Kirby, 2009; Ruchaya et al., 2012).CX3CL1 is highly expressed on hippocampal neurons in the post-natal and adult rat and declines in old age which has been linked to cognitive decline in rodents (Lyons et al., 2009).///The high basal level of CX3CL1 mRNA and protein expression in the hippocampus is suggestive of a physiological, non- inflammatory function.///Fractalkine is constitutively expressed at high levels by neurons, mostly in forebrain structures such as the hippocampus, amygdala, cerebral cortex, globus pallidus, striatum and thalamus, but also in the olfactory bulb, with almost no expression in the cerebellum, at the mRNA and protein levels in adult mouse in situ (Tarozzo et al., 2003).--> 
Besides neuronal expression of CX3CL1, few studies also detected its transcript and protein level in astrocytes, albeit at lower levels (Hulshof et al., 2003; Sunnemark et al., 2005) <!--Besides this neuronal expression, **fractalkine mRNA and protein was also shown to be constitutively expressed by astrocytes, albeit at lower levels, in adult mouse, rat and human brain in situ (Hulshof et al., 2003; Sunnemark et al., 2005). -->
Another unique feature of this chemokine is that, to date, it appears to be the only ligand of CX3CR1 receptor (Allen et al., 2007).

#### Receptor

CX3CR1 is the G~i~ protein-coupled receptor (GPCR) which specifically interacts with both forms of CX3CL1 with the same affinity <!-- check citation [@Imai1997] and (Harrison et al., 2001). The fractalkine receptor CX3CR1 is a Gi-protein coupled receptor encoded by the Cx3cr1 gene, previously named V28, located on the chromosome 3 in human (Combadiere et al., 1995) and the chromosome 9 in mouse (Combadiere et al., 1998).  --> 
The subunit G~i~ inhibits the production of cAMP, triggering a variety of intracellular second messengers including phosphoinositide 3-kinase (PI3K), protein kinase B (AKT) and nuclear factor kappa-light-chain-enhancer (NFκB),  (Al-Aoukaty et al., 1998; Chandrasekar et al., 2003). <!-- ZMIENIĆ!!!! The fractalkine receptor CX3CR1 is a Gi-protein coupled receptor encoded by the Cx3cr1 gene, previously named V28, located on the chromosome 3 in human (Combadiere et al., 1995) and the chromosome 9 in mouse (Combadiere et al., 1998). The subunit protein Gi inhibits the production of cAMP, triggering a variety of intracellular second messengers including phosphoinositide 3-kinase (PI3K), protein kinase B (AKT) and nuclear factor kappa-light-chain-enhancer of activated B cells (NFκB), which are well-known for mediating a wide range of cellular functions, including apoptosis, proliferation, transcription and migration (Al-Aoukaty et al., 1998; Chandrasekar et al., 2003).-->

In the periphery, CX3CR1 iS expressed by monocytes, dendritic cells, and natural killer cells (Imai et al., 1997; Combadiere et al., 1998; Harrison et al., 1998; Jung et al., 2000). <!-- ZMIENIĆ SCX3CR1 is ubiquitously expressed by monocytes, dendritic cells, and natural killer cells throughout the body (Imai et al., 1997; Combadiere et al., 1998; Harrison et al., 1998; Jung et al., 2000). Since these cells rarely infiltrate the brain parenchyma during normal physiological conditions, resident microglia are considered the only source of CX3CR1 expression and thus the only recipient of fractalkine signaling in the healthy brain (Jung et al., 2000; Mizutani et al., 2012).-->
However, the cell type expression pattern of CX3CR1 in the CNS remains controversial: some reports confine the localization of CX3CR1 microglia [@tarozzo_2003; @cardona_2006 <!--(Bachstetter et al., 2011; Zhan et al., 2014)-->], whereas several studies report CX3CR1 expression on neurons in vitro as well as in brain regions, including the hippocampus, raphe nucleus, nucleus of the solitary tract (NTS) and paraventricular nucleus (PVN) of the hypothalamus, amygdala, cerebral cortex, globus pallidus, striatum and thalamus (Meucci et al., 1998, 2000; Maciejewski- Lenoir et al., 1999; Hatori et al., 2002; Hughes et al., 2002; Tarozzo et al., 2003; Verge et al., 2004; Limatola et al., 2005; Zhuang et al., 2007; Heinisch and Kirby, 2009; Ruchaya et al., 2012, 2014).  <!-- zmienić drugą część zdania -->

**CX3CR1 KO**

The CX3CR1-GFP knock-in mouse line, where the CX3CR1 gene has been replaced by a green fluorescent protein (GFP) reporter (Jung et al., 2000), is one of the most common tools for studying neuron-microglia interaction under physiological conditions ((Lauro et al., 2006; Paolicelli et al.,2011)) see also: \@ref(micro_inter)). @cardona_2006, @jurgens_2012
The reasong for it is that in this model all microglial cells abundantly express GFP, resulting in an exceptional fluorescent labeling of their complex arborization, from cell body to distal processes (Tremblay et al., 2010). <!--zmienić!!!!-->
Since the CX3CR1-GFP homozygous mice (CX3CR1KO/KO) are completely devoid of microglial CX3CR1, and therefore of fractalkine signaling, comparing the heterozygous (CX3CR1KO/+) used for imaging with the homozygous mice also provides a strategy for dissecting the molecular determinants of neuron-microglia communication in a non-invasive manner (Tremblay, 2011; Wolf et al., 2013).  <!--zmienić!!!!-->
The CX3CR1-GFP heterozygous mice may be partially deficient in fractalkine signaling. <!--zmienić!!!!-->
Nevertheless, microglial morphology, dynamic surveillance (Nimmerjahn et al., 2005; Wake et al., 2009), dendritic spine turnover (Parkhurst et al., 2013), and microglial interactions with synaptic elements (Wake et al., 2009; Tremblay et al., 2010) were comparable in vivo between these CX3CR1-GFP heterozygous mice and the Iba1-GFP mice from Hirasawa and colleagues where CX3CR1 is not deleted (Hirasawa et al., 2005). - Paolicelli2014 <!--zmienić!!!!-->





#### Functions in the CNS

##### Neurodevelopment
In physiological conditions, CX3CL1/CX3CR1 signaling is involved in different neural functions both in development (participation in functional maturation of neuronal circuits driving cell positioning) and adulthood (regulation of synaptic plasticity and cognitive functions) [@lauro_2015]. <!-- zmienić -->

##### Adult 



###### Electrophysiological effects

Indeed, there is mounting evidence which implicates both CX3CL1 and its receptor, CX3CR1, in synaptic plasticity and neuromodulation (Bertollini et al., 2006; Ragozzino et al., 2006; Piccinin et al., 2010; Maggi et al., 2011; Rogers et al., 2011; Roseti et al.,2013; Scianni et al.,2013). <!-- zmienić // In fact, CX3CL1 is a confirmed inhibitor of basal glutamate synaptic activity in the hippocampus [@Bertollini2006]. -->

Regarding electrophysiological effects of CX3CL1 action, hippocampus is the most documented structure, as it has most-known network // a golden structure for electrophysiologist, with high basal levels of CX3CL1 transcript and protein expression. <!-- zmienić The high basal level of CX3CL1 mRNA and protein expression in the hippocampus is suggestive of a physiological, non-inflammatory function. -->
For example, CX3CL1 has been shown to reduce post-synaptic glutamate currents (Meucci et al., 1998; Limatola et al., 2005), involving an increased intracellular calcium and dephosphorylation of the GluR1 AMPA receptor subunit on serine 845 (Ragozzino et al., 2006). <!-- zmienić jeszcze trochę -- SPRAWDZIĆ spontaneous glutamate release and-->
The latter mechanism has been linked to ability of CX3CL1 to inhibit LTP and mimocs long-term depression (LTD) at the CA3–CA1 synapses in acute hippocampal slices (Bertollini et al., 2006; Ragozzino et al., 2006; Maggi et al., 2009).  <!-- zmienić CX3CL1-mediated regulation of glutamate transmission has been shown to be due to its post-synaptic effects on neurons and involves the dephosphorylation of the GluR1 AMPA receptor subunit on serine 845, a mechanism reminiscent of LTD (Ragozzino et al., 2006). //Previous studies have shown that CX3CL1 inhibits LTP and mimics long-term depression (LTD) at the CA3–CA1 synapses in acute hippocampal slices (Bertollini et al., 2006; Ragozzino et al., 2006; Maggi et al., 2009). -->
LTD can play vital roles in the context of memory-associated synaptic plasticity including synaptic scaling and enhanced signal-to-noise ratio mechanisms <!-- CITATION, ZMIENIĆ -->
These synaptic effects are consistent with a direct action of CX3CL1 on neurons most likely exerted through the CX3CR1 receptor, which is reportedly expressed on the dendrites of hippocampal neurons (Meucci et al., 2000; Limatola et al., 2005). <!-- zmienić -->
The ability of CX3CL1 to inhibit glutamate function is thought to be responsible for some of its neuroprotective actions, and provides further support for the chemokine-neuromodulatory role in the CNS [@adler_2005, @callewaere_2007, @guyon_2007]. <!-- not sure if it is my sentence Overall, previous studies indicate a predominantly inhibitory role for CX3CL1, perhaps as a component of neuroprotective synaptic scaling mechanisms necessary for hippocampal memory-associated synaptic plasticity processes (Bertollini et al., 2006; Turrigiano, 2008; Piccinin et al., 2010).-->
Consistent with this hypothesis, neuroprotective ADAM17-mediated increase in in soluble CX3CL1 is observed in multiple settings of glutamatergic neurotransmission where the chemokine is suggested to performa neuroprotective function (Chapman et al., 2000; Tsou et al., 2001; Erichsen et al., 2003; Limatola et al., 2005; Ragozzino et al., 2006; Lauro et al., 2010; Pabon et al., 2011). <!-- zmienić-->

Beyond the hippocampus, CX3CL1 is also documented to reduce the activity of serotonergic neurons in the raphe nucleus through enhanced GABA~A~ receptor-mediated inhibition (Heinisch and Kirby, 2009).<!-- zmienić trochę drugą część -->



LTP-inducing TBS resulted in an up-regulation in CX3CL1 expression after 2 h on the stimulated DG blade compared to the upper unstimulated blade. - Sheridan2014

**DOSE**
At levels reached during inflammatory conditions, CX3CL1 signaling has previously been associated with activation of pro-survival and anti-apoptotic pathways through phosphorylation of molecules such as Akt, as well as activation of MAP kinases such as p-38 and Erk1/2 (p44/42; Maciejewski-Lenoir et al., 1999; Meucci et al., 2000; Cambien et al., 2001; Deiva et al., 2004; Klosowska et al., 2009; Lyons et al., 2009)

While previous studies have shown that CX3CL1 causes an increase in intracellular calcium in neurons and other cell types (Oh et al., 2002; Deiva et al., 2004; Ragozzino et al., 2006) this effect of CX3CL1 becomes apparent at concentrations of 25 nM and higher (Oh et al., 2002; Deiva et al., 2004), well above the levels we investigated here and we observed no such increase in intracellular calcium. At a concentration of 2 nM, in both neurons and non-neurons, CX3CL1 pre-incubation suppressed glutamate-mediated rises in intracellular calcium levels. These data are in good agreement with previous findings of a protective effect of inflammatory levels of CX3CL1 against glutamate excitotoxicity and glutamate NMDA receptor activation, in particular (Meucci et al., 1998; Deiva et al., 2004; Limatola et al., 2005), although, unlike the current work, the latter effect was linked to increased intracellular calcium (Ragozzino et al., 2006). Calcium oscillations in both neuronal and non-neuronal cells are important for cellular growth, migration and synaptic structural refinement (Katz and Shatz, 1996; Komuro and Rakic, 1998; Spitzer et al., 2000). Thus, the dampening of such signaling by CX3CL1 is suggestive of a role in stability of network connectivity and activity. Overall, the current data along with information in the published literature reveal that a role for CX3CL1 in control of glutamate-mediated excitatory neurotransmission during excitotoxic events can be extended to situations of synaptic plasticity required for normal functions such as memory formation.

CX3CL1 has been reportedly up-regulated in several settings of augmented glutamatergic transmission where the chemokine is clearly protective against excitotoxic cell death (Tong et al., 2000; Tarozzo et al., 2002; Limatola et al., 2005; Cipriani et al., 2011; Briones et al., 2014). Moreover, both CX3CL1 and its receptor, CX3CR1, have been shown to be up-regulated in hippocampal neurons after pilocarpine-induced status epilepticus (Yeo et al., 2011), a condition characterized by excessive glutamatergic excitation. Overall, the abundance and expression pattern of CX3CL1 make the chemokine ideally suited for sensing hippocampal glutamate tone. Our data supports a possible role for CX3CL1 in homeostatic mechanisms of synaptic scaling during memory-associated synaptic plasticity.-Sheridan2014

**GABA A**
The GABA~A~ receptor/chloride channel blocker, picrotoxin, used in the current studies would decrease GABAergic inhibitory transmission promoting depolarization in some cells with corresponding increases in intracellular calcium (Antonucci et al., 2012). Thus, the current work suggests GABA~A~ receptor/chloride channel activity within the hippocampal neuronal network must be intact for CX3CL1 to attenuate glutamatergic neurotransmission or LTP. 
This situation is remarkably similar to that described for CX3CL1 inhibition of serotonergic neurons of the Raphe nucleus (Heinisch and Kirby, 2009). While this effect may relate to basal inhibitory tone, CX3CL1 could actually be enhancing GABAA receptor function. For example, CX3CL1 enhances phosphorylation and activation of Akt in neurons and this serine/threonine kinase has been associated with phosphorylation of the GABAA beta2 receptor subunit, a modification that enhances activity of the receptor (Meucci et al., 2000; Wang et al., 2003). Moreover, several signaling systems can enhance GABAmediated inhibition through promotion of rapid insertion of GABA~A~ receptors into the post-synaptic plasma membrane (Wan et al., 1997; Nusser et al., 1998; Mizoguchi et al., 2003; Jovanovic et al., 2004) - Sheridan2014



####### Microglia
it is believed that the binding of soluble CX3CL1 to its receptor CX3CR1 maintains microglia in a ‘‘resting” or ‘‘off” state (Bachstetter et al., 2011; Valero et al., 2016), although chemoattractant properties have been demonstrated for the membrane-bound form of CX3CL1 (Lauro et al., 2006; Song et al., 2013).Accordingly, microglia of CX3CR1-/- mice show impaired migration during development (Pagani et al., 2015; Paolicelli et al., 2011), together with a partially activated phenotype during adulthood (Reshef et al., 2014). -Bolos2018

Recently it has been established in vitro and in vivo, that the acute activation of dorsal horn microglia by inflammaory insult or sciatic nerve impairments result in a release of CatS from microglia, which liberates FKN from dorsal horn of spinal cord neurons (Clark and Malcangio, 2012; Clark et al., 2010, 2009). 

###### Behaviour
Of note, there is great controversy regarding the behavioral phenotype of *CX3CR1-/-* mice in the literature (Paolicelli et al., 2014). For instance, reports of impairment (Rogers et al., 2011), improvement (Maggi et al., 2011; Reshef et al., 2014) or no changes (Serchov et al., 2015) in hippocampal-dependent learning have been reported. In each study involving behavioral studies with these animals, the relevance of housing conditions, animal gender and age, feeding and behavioral test protocols is brought to light (Gemma and Bachstetter, 2013). Regarding the regulation of emotional behavior, previous evidence shows that the connectivity of brain regions involved in the regulation of mood disorders is impaired in CX3CR1-/- animals (Squarzoni et al., 2014). Although other authors detected no depressive-like phenotype of these mice in the sucrose preference (Milior et al., 2016) or in the TST (Hellwig et al., 2016), male and female animals were grouped and tested together. Here we report that 4-month- old female CX3CR1-/- mice show a hyperactive, anxiolytic-like and depressive-like phenotype, in agreement with previous data indicating altered social behavior in these mice (Zhan et al., 2014). Interestingly, although stress resilience has been described in CX3CR1-/- mice (Rimmerman et al., 2017; Yirmiya et al., 2015), other authors found that these animals show greater depressive- like behavior in response to inflammation compared to WT coun- terparts (Corona et al., 2013). - Bolos2018

Several behavioral comorbidities, such as anxiety, depression, and other mood disorders, commonly occur in mice with CX3CR1 deletion.

<!-- unused sentences:
The full-length molecule is also larger than most other chemokines, containing approximately 373 amino acid residues compared to the more common 70–80 amino acid size. // The 95 kDa full-length protein is a type I transmembrane protein consisting of  N-terminal chemokine domain, a 241-amino acid glycosylated mucin-like stalk, an 18-amino acid transmembrane region and an intracellular C- terminal domain.
It is converted to a soluble form on cleavage from the plasma membrane, through the action of metalloproteinases  (ADAM 10 and ADAM17 on leukocytes) (Hundhausen et al., 2003) or  cysteine protease Cathepsin S (CatS) which is expressed and released by microglial cells in the spinal cord (Clark et al., 2007; Meucci et al., 2000; Ransohoff, 2002).
The approximately 70 kDa soluble N-terminal chemokine domain can be released from the full-length protein via the action of several metalloproteinases such as cathepsin S, ADAM10, and ADAM17 (TACE: TNF-α-converting enzyme) in both the periphery and CNS (Garton et al., 2001; Hundhausen et al., 2003; Clark et al., 2007; Cook et al., 2010; Jones et al., 2013). 


The high basal level of CX3CL1 mRNA and protein expression in the hippocampus is suggestive of a physiological, non-inflammatory function. Indeed, there is mounting evidence which implicates both CX3CL1 and its receptor, CX3CR1, in synaptic plasticity and neuromodulation (Bertollini et al., 2006; Ragozzino et al., 2006; Piccinin et al., 2010; Maggi et al., 2011; Rogers et al., 2011; Roseti et al.,2013; Scianni et al.,2013). For example, CX3CL1 has been shown to reduce spontaneous glutamate release and post-synaptic glutamate currents (Meucci et al., 1998; Limatola et al., 2005). The latter effect has been linked to increased intracellular calcium and dephosphorylation of the GluR1 AMPA receptor subunit (Ragozzino et al., 2006). These synaptic effects are consistent with a direct action of CX3CL1 on neurons most likely exerted through the CX3CR1 receptor, which is reportedly expressed on the dendrites of hippocampal neurons (Meucci et al., 2000; Limatola et al., 2005). Overall, previous studies indicate a predominantly inhibitory role for CX3CL1, perhaps as a component of neuroprotective synaptic scaling mechanisms necessary for hippocampal memory-associated synaptic plasticity processes (Bertollini et al., 2006; Turrigiano, 2008; Piccinin et al., 2010). Consistent with this hypothesis, neuroprotective ADAM17-mediated increase in in soluble CX3CL1 is observed in multiple settings of glutamatergic neurotransmission where the chemokine is suggested to performa neuroprotective function (Chapman et al., 2000; Tsou et al., 2001; Erichsen et al., 2003; Limatola et al., 2005; Ragozzino et al., 2006; Lauro et al., 2010; Pabon et al., 2011). -Sheridan2014

Given the essential role played by the CX3CL1/CX3CR1 axis in neuron-microglia communication, the CX3CR1-GFP knock-in mouse line where the CX3CR1 gene has been replaced by a green fluorescent protein (GFP) reporter (Jung et al., 2000), represents one of the most important tools for studying microglial involvement in the healthy brain []. (Lauro et al., 2006; Paolicelli et al.,2011) // have been used extensively to study this cross-talk mechanism
Furthermore, fractalkine seems to play an essential role in a unique neuronal-glial interaction between neurons and CX3CR1-expressing microglia under normal and pathological states.

end -->


Post-synaptic modulation of GABA-A receptors has been reported for CX3CL1 onto serotoninergic neurons in the dorsal raphe and cortical neurons ( Heinisch and Kirby, 2009; Roseti et al., 2013 ). At Schaffer's collateral-CA1 pyramidal neurons CX3CL1 depresses AMPA-mediated currents with a mechanism that involves inhibition of forskolin-induced Ser-845 GluR1 phosphorylation ( Ragozzino et al., 2006 ), whereas it enhances NMDAmediated neurotransmission via adenosine A2A subtype activation and D-serine release by glial cells ( Maggi et al., 2009; Scianni et al., 2013 ). In the same area it has been reported that: i) CCL2 exerts pre-synaptic effects increasing the release of glutamate onto CA1 pyramidal neurons ( Zhou et al., 2011 ); ii) CXCL16 enhances both the release of glutamate and GABA, requiring adenosine type 3 receptor (A3R) and microglia activation ( Di Castro et al., 2016 ). <!-- Trettel 2020-->

CX3CL1 is a trans-membrane chemokine highly expressed by neurons and present in a soluble form upon cleavage by metalloproteases such as ADAM10, 17 ( Garton et al., 2001; Hundhausen et al., 2003 ), catepsin-S and γ -secretases ( Clark et al., 2007; Schulte et al., 2007; Fonovic et al., 2013 ). Both trans-membrane and soluble CX3CL1 forms bind a unique receptor CX3CR1, with possible differences in affinity and activity ( Biber et al., 2007 ). The discovery of the specific expression of CX3CR1 in microglial cells ( Cardona et al., 2006 ) opens to the perspective that CX3CL1 is implicated in neuron – microglia cross-talk and in the control of microglia activity ( Biber et al., 2007 ). 

In 2000, Zujovic et al. reported for the fi rst time that exogenous CX3CL1 restrained LPS-microglia activation in vitro, and that neutralization of endogenous CX3CL1 in hippocampal cultures increased the neurotoxic action on neuronal cells. Accordingly, in vivo neutralization of endogenous CX3CL1 potentiated LPS effects in the brain ( Zujovic et al., 2000 ). Later, Mizuno et al. (2003) reported the reduction of IL-6, NO and TNFα production by microglia stimulated with LPS upon CX3CL1 treatment, and a reduced neuronal cell death. Boehme et al. (2000) showed that CX3CL1 reduced FAS-mediated microglia cell death activating PI-3 kinase/PKB pathway, and modulating both the levels and the activation states of Bcl-2 family member proteins. In animal models, knocking down CX3CR1 signaling exacerbated microglia over-activation, increasing the release of IL-1 β and apoptotic neuronal cell death in mice injected with LPS, and increased neuronal cell loss in PD and ALS mouse models ( Cardona et al., 2006 ). In cx3cl1 − / − mice, the Adeno-Associated Virus (AAV)-mediated gene insertion of either soluble or membrane bound synthetic variant of CX3CL1 demonstrated that, in a MPTP- model of PD, only the soluble form rescued motor coordination, reduced neurodegeneration and microglia activation ( Morganti et al., 2012 ). A role for endogenous CX3CL1 in the attenuation of a pro-in fl ammatory phenotype was also reported in a mouse model of Tauopathy ( Lastres-Becker et al., 2014 ). Recent data show that only the over-expression of a speci fi c cleavage variant of the soluble CX3CL1 reduced Tau-pathology ( Finneran and Nash, 2019 ). 

 In hippocampal cultures, CX3CL1 reduced neuronal cell death due to gp120- or glutamate overexposure ( Meucci et al., 2000; Limatola et al., 2005 ). Microglial cells treated with CX3CL1 release soluble factors that promote neuroprotection in mixed hippocampal neuron – glia cultures. Among them adenosine modulates CX3CL1 neuroprotection through the activation of adenosine A1 receptor subtype (A1R) ( Lauro et al., 2008, 2010 ). Acting on microglia, CX3CL1 indirectly modulates the activity of glutamatetransporter 1 (GLT-1) on astrocytes, with higher glutamate removal from the extracellular space, and this effect requires the function of A1R ( Catalano et al., 2013 ). In a pMCAO rat model, i.c.v. injection of soluble CX3CL1, 30 min after ischemia, has long lasting protective effects, reducing lesion volume and neurological de fi cits, again with the involvement of active A1Rs ( Cipriani et al., 2011 ).
 
 CX3CL1-mediated neuroprotection and neuromodulation may also require the activity of adenosine-type 2 a receptors (A2ARs). Scianni et al. (2013) demonstrated that CX3CL1 modulates the NMDA glutamate receptor function and that this effect involves the release of D-serine from glial cells, and the activity of A2AR subtype. Altogether these data describe a mechanism by which CX3CL1, via A2AR and Dserine, and likely modulating synaptic NR2A/NMDARs, induced CREB phosphorylation, upregulation and release of BDNF, resulting in neuroprotection and neuromodulation ( Lauro et al., 2015). 
 
  However, its constitutive expression in different CNS cells ( Ludwig et al., 2005; Rosito et al., 2012 ) suggests additional roles in mediating cell-to-cell communication.
  
  

Fractalkine is the only member of the CX3C chemokine family and, unlike many other chemokines, shares a one-to-one  relationship  with  its  cognate  receptor, CX3CR1 [46,47]. CX3CR1 is a G protein-coupled receptor (GPCR) that signals through the Gq pathway, in turn  activating  PI-3  kinase  pathway  [48].  FKN  is expressed in neurons and peripheral endothelial and its receptor is produced by myeloid cells (including microglia), T cells, and natural killer cells [49,50]. FKN is a type I transmembrane protein with an N-terminal chemokine domain attached to a long, highly glycosylated mucin-like stalk with a short membrane-spanning domain and intracellular domain. FKN can be cleaved by a disintegrin and metalloprotease (ADAM) 10, ADAM 17, and cathepsin S to generate a soluble fragment [2–4] (Fig.1). Both the membrane-bound and soluble forms of FKN are capable of signaling through CX3CR1, although there may be differences in affinity and biological activity between these two ligands [1]. In the periphery, membrane-bound FKN can promote adhesion of monocytes to endothelial cells, and the soluble ligand can cause chemotaxis of monocytes, T cells, and natural killer cells [51,52]. Genetic ablation of FKN causes reduced monocyte survival and reduced ability of CX3CR1+macrophages to sense the gut lumen [53]. Expression of the chemokine domain of FKN was sufficient to rescue survival of certain populations of monocytes  

Generation of a reporter mouse, replacing endogenous Cx3cr1with a green fluorescent protein (GFP) reporter under control of theCx3cr1promoter, demonstrated  that  CX3CR1  expression  is  restricted  to microglia in the CNS [12,59]. This reporter line has been used extensively to investigate the impacts of disrupting FKN signaling from the developing to the aged brain. In development, CX3CR1 deficient mice were  observed  to  have  delayed  synaptic  pruning. Microglial number was transiently reduced inCx3cr1 −/−mice compared to wild-type controls while the number of dendritic spines was increased. This indicates that CX3CR1 deficiency may delay maturation of synapses by delaying engulfment during development [60]. In the adult brain, CX3CR1 has been identified as necessary for layer V cortical neuron survival [61]. These findings implicated FKN signaling in normal brain development and homeostasis but ablation of CX3CR1 also affects cognition.

Disruption of FKN signaling has deleterious effects on both neurogenesis and cognition.Cx3cr1−/−mice were found to have a significant reduction in neurogenesis, which could be reversed by IL-1 receptor antagonist administration [62]. When behaviorally assessed, these mice were found to have motor learning impairments, spatial recall impairments, and fear-associated recall impairments. These cognitive impairments were associated with reduced synaptic plasticity. Antagonism of IL-1β signaling successfully reversed hippocampal-dependent learning but not motor learning [63]. Disruption of FKN signaling has also been studied in the context of neurodegenerative disorders. In a seminal paper, Cardona et al. [12] described the impact of CX3CR1 knock out in several models of neurodegeneration. Broadly, they found that microglia lacking CX3CR1 are cytotoxic in models of systemic inflammation, amyotrophic lateral sclerosis (ALS), and Parkinson’s disease (PD). Mice lacking CX3CR1 were more susceptible to neuron loss upon systemic injection of LPS. Furthermore, adoptive transfer ofCx3cr1−/−microglia from LPS-challenged mice into wild-type mice also produced neurotoxicity in the area of the injection site. Interestingly, microglia lacking CX3CR1 did not migrate away from the injection site whereas microglia with intact CX3CR1 signaling migrated from the injection site. Inhibition of IL-1βsignaling blocked the neurotoxic effects of and restored the migratory capacity ofCx3cr1−/− microglia. Similarly, in the SODG93Amouse model of ALS, disruption of FKN signaling caused greater neuron loss, reduced hindlimb strength, and shortened lifespan. In a toxic model of PD, loss of FKN signaling by knocking out either the receptor or the ligand resulted in significantly greater neurotoxicity [12]. 

<!-- Finneran_2019-->

the CX3CL1 transmembrane form is cleaved by ADAM10 and ADAM17 proteases into its soluble variant (see: Figure 2A). <!-- Another fundamental finding was that upon stimulation, neurons from sensory pathways are able to cleave the membrane-attached CX3CL1 and release the soluble chemokine (Milligan et al. 2004).--><!-- These  findings indicate  that  the  cleavage  of  transmembrane  chemokines  into  their soluble  chemotactic  variants  may  have  an  important  role  in  the regulation of inflammation in human - CX3CL1 --><!-- The post-translational expression of CX3CL1 may be conditioned by the following factors: BBB and BSCB dysfunction, proteolytic cleavage by ADAM10 and ADAM17 proteases, rapid binding to CX3CR1, and penetrating between three compartments including the extracellular space, CSF, and circulating blood [156,197,198]. @poniatowski_2016--><!-- The regulation of the activation and functioning of the CX3CL1/CX3CR1 axis encompasses the control at the level  of transcription and also regulation during post-translational modifications.-->
It is thought that this dynamic proteolytic cleavage of CX3CL1 is a response to neurotoxic insult and serves anti-inflammatory functions [@chapman_2000]. <!-- dodać jeszcze jakieś inne jak znajdę --><!-- 
These  data  strongly  suggest  that  dynamic proteolytic cleavage of fractalkine from neuronal membranes in response to a neurotoxic insult, and subsequent chemoattraction of reactive immune cells, may represent an early event in the inflammatory response to neuronal injury. - @chapman_2000--><!-- These  data  strongly  suggest  that  dynamic proteolytic cleavage of fractalkine from neuronal membranes in response to a neurotoxic insult, and subsequent chemoattraction of reactive immune cells, may represent an early event in the inflammatory response to neuronal injury. - @chapman_2000-->

There is some evidence that different fragments of the FKN ligand may have different functional outcomes. Fractalkine signaling has been implicated in neuropathic pain in spinal injury models [77–79]. In these studies, neuropathic pain in injury models was alleviated by antibody antagonization of CX3CR1, and in non-injured rats neuropathic pain was induced by activation of CX3CR1 with intrathecal injections of exogenous fractalkine peptide comprising just the chemokine domain. Furthermore, Clark and Malcangio [15] show that infusion of this chemokine peptide of FKN (ckFKN, Fig.1) elicits mechanical allodynia, while infusion of sFKN (which contains the full mucin-like stalk, Fig.1) does not. They also demonstrate a difference in calcium mobilization upon binding between these two fragments. Interestingly, it has been identified that cathepsin S is necessary for the production of pain-inducing FKN in a spinal injury  model  [2,77].  In  silico  analysis  of  substrate [@finneran_2019]
preference of cathepsin S indicates membrane-bound FKN as a potential substrate [77,80–82] and a recent study published that cathepsin S cleaves membrane bound FKN to generate a soluble fragment that migrates at  a  lower  apparent  molecular  weight  than  the ADAM10/17 cleavage product [83]. These data suggest that removal of the mucin-like stalk (either partially or in whole) may alter the microglial response to FKN, which can elicit different effects and/or microglial phenotypes depending on the identity of the soluble ligand.
...
 These data may indicate that the form of the  soluble  fragment  (with  or  without  the  mucin stalk) affects how the  chemokine signals  in these
 neurodegenerative models and that proteolytic cleavage could be a mechanism for regulation of fractalkine  activity  in  vivo.  More  research  is  needed  to determine if there are differential effects of these soluble  FKN  variants  and  how  this  could  regulate neuroinflammation. 
 
 Consistent with its effect on CREB signaling, Ccr5 knockout resulted in enhanced long-term potentiation (LTP) in hippocampal CA1, and both Ccr5 knockout and knockdown enhance performance in contextual fear conditioning, Morris water maze, and social recognition paradigms (Frank et al., 2018; Kalkonde et al., 2011; Zhou et al., 2016). Similar to genetic ablation of Ccr5, pharmacological inhibition of CCR5 
 
CX3CL1  is  neuroprotective  against  Glu-induced  excitotoxicity, with  mechanisms  fully  dependent  on  A1 R  (Lauro  et  al.,  2008, 2010)  and  in  part  dependent  on  A 3 R  (Rosito  et  al.,  2014). CX3CL1  also  protects  neurons  against  NMDA-induced  death (Deiva  et  al.,  2004),  but  no  evidence  of  ARs  involvement  are reported   so   far. @lauro_2014

Adenosine is a metabolite that acts through different receptor subtypes (Jacobson and Gao, 2006); among them A 1 R (Lauro et al., 2008, 2010) and A 3 R (Rosito et al., 2014) are involved in CX3CL1 neuroprotection against Glu-induced toxicity. Moreover we  previously  demonstrated  that  CX3CL1  triggers  the  release of  adenosine  from  neuronal  and  microglial  cells  (Lauro  et  al., 2008,  2010). 