### CXCL12

CXCL12/SDF-1α belongs to the CXC group of chemokines. CXCL12/SDF-1α is the predominant and the smallest isoform (from all of six isoforms that are alternative spicing products of one common mRNA precursor molecule). It is also the smallest, at 89 amino acids, including a signaling peptide of 19 amino acids, which is cleaved to generate the mature protein. 

SDF-1α (CXCL12) is another chemokine which has recently attracted much attention due to its extensive distribution in the CNS as well as the fact that it can be produced not only by glial cells but also by neurons [@banisadr_2003, @heinisch_2010a, @stumm_2002]. This chemokine has been shown to play an essential role in brain plasticity during development but also in regulating the activity of various brain circuits in normal and pathological conditions [@merino_2014, @timotijevi_2012, @tiveron_2008a]. Furthermore, recent studies have shown that there are several cross-talks between the CXCL12 and with its receptor CXCR4 and other neurotransmitter systems in the brain (e.g. GABA, glutamate and endocannabinoids) [@heinisch_2010a, @heinisch_2011]. The neuromodulatory actions of CXCL12 have been observed in various neuronal populations, including the hippocampus [@kasiyanov_2008], cerebellum [@limatola_2000], MCH neurons of the lateral hypothalamus area [@guyon_2005] (LHA), vasopressinergic neurons of the hypothalamus [@callewaere_2006], dopaminergic neurons of the substantia nigra [@guyon_2006], the dorsal raphe nucleus [@heinisch_2010a] and recently the amygdala [@yang_2016]. What is particularly interesting, CXCL12 has often similar effects in these various circuits (increase in glutamate and/or GABA synaptic activity), however these effects occur via different mechanisms, even within one structure. For example, in the dorsal raphe nucleus CXCL12 increases the frequency of recorded spontaneous inhibitory post-synaptic currents (sIPSC) in serotonergic neurons through a pre-synaptic mechanism, but decreases sIPSC amplitude via a post-synaptic mechanism in non-serotonergic neurons [@heinisch_2010a]. Moreover, CXCL12 often appears to exert opposite effects on neuronal function depending on its concentration, e.g. in MCH-expressing neurons of the LHA, where the action potential discharge is different depending on the concentration [@guyon_2005]. Of particular interest is the observation that pro-inflammatory cytokine stimulation leads to elevated levels of CXCL12 and other chemokines by activation of glial or endothelial cells which in turn release chemokines [@guyon_2014]. The chemokines released bind to CXCR4 present on neurons and induce changes in excitability that could induce an adaptive response to inflammation, leading to “sickness behavior,” characterized by decreased mood, anorexia, and fatigue [@dantzer_2001, @dantzer_2007]. Sickness behavior is considered to be the physiological and psychological effect of immune activation during the course of infection, which is primarily mediated by the central action of peripherally released proinflammatory cytokines. Given the abundance of chemokines and their receptors in the CNS, it is not surprising that changes of cytokine/chemokine levels during inflammation are causing multiple physiological and behavioral perturbations. For example, effects of CXCL12 on dorsal raphe neurons could underlie depressive symptoms frequently observed with inflammation [@maes_1998], as dysfunction of the serotoninergic systems is implicated in depression. Similarly, the effects of CXCL12 on MCH neurons which are part of the feeding behavior and metabolism control circuit [@nahon_2006] could explain anorexia. These symptoms of sickness behavior are usually reversible when inflammation stops. Overall, this chemokine system is one of the key players in the neuro-immune interface that participates in shaping CNS responses to changes in the environment.

<!-- Unlike many chemokines whose expression is strongly up-regulated during inflammatory responses, the chemokine CXCL12 and its receptors CXCR4 and CXCR7 are constitutively and widely expressed in the developing and adult nervous system (Banisadr et al. 2002; Sanchez-Alcaniz et al. 2011; Schonemeier et al. 2008; Stumm et al. 2002; Stumm et al. 2003). -->

• CXCR7 is an interesting atypical chemokine receptor (Maksym et al., 2009). Together with CXCR4 and its ligand CXCL12, CXCR7 is conserved well across the vertebrate species including sea lamprey (Nomiyama et al., 2011). It binds CXCL11 and CXCL12. Importantly, CXCR7 can heterodimerize with CXCR4 and modulate the effect of CXCL12 on CXCR4. Furthermore, CXCR7 can also signal in some cell types although not by the classical G protein-coupled receptor pathways (Maksym et al., 2009). During embryogenesis, CXCR7 is necessary for proper migration of primordial germ cells to CXCL12 via CXCR4 by acting as a sink for CXCL12 (Boldajipour et al., 2008). CXCR7 is also involved in cardiac tissue development along with CXCR4 and CXCL12 (Sierro et al., 2007). Although poorly expressed in normal adult tissues, CXCR7 is widely expressed in a variety of tumors and tumor-associated vessels and appears to promote tumor growth and neoangiogenesis partly by signaling via mitogen activated protein kinase (MAPK) cascades (Maksym et al., 2009).
• Hematopoietic stem cells (HSCs) are known to reside in the bone marrow. Broxmeyer et al. (2005) reported that the CXCR4 inhibitor AMD3100 induced release of HSCs from the bone marrow, indicating that the CXCR4-CXCL12 axis is a key signal maintaining HSCs in the bone marrow. This observation had potential clinical utility, because certain cancer patients are candidates for whole-body irradiation followed by reconstitution of the hematopoietic compartment via HSCs. Thus, the ability of the CXCR4 antagonist AMD3100 to release HSCs from the bone marrow meant that these ‘‘mobilized’’ HSCs could be isolated from the blood of the patient in sufficient numbers to permit repopulation with autologous HSCs (Uy et al., 2008). Interestingly, AMD3100 synergizes with granulocyte colony stimulating factor to mobilize HSCs, improving the effectiveness of the approach and allowing the isolation of enough cells for autologous cell transplantation. This combined approach has been used in patients with non-Hodgkin’s lymphoma and with multiple myeloma (Pusic and DiPersio, 2010). Other CXCR4- based therapeutics have been reviewed recently (Peled et al., 2012).
• These developments underscore the important roles that CXCR4 plays in development. Other studies have documented that the CXCL12-CXCR4 axis plays pivotal roles in homing of various stem cells to particular places of the embryo during development. One of the most useful experimental models to understand these mechanisms has been the zebrafish, where CXCR4 is the signal that guides stem cells that give rise to the gonads of the developing fish embryo (Doitsidou et al., 2002; Knaut et al., 2003). More recent studies have documented the coordinated roles of CXCR4, CXCL12, and CXCR7 in the development of the central nervous system in the zebrafish (Diotel et al., 2010; Tiveron and Cremer, 2008). Thus, certain homeostatic chemokine receptors play key roles in the homing of various stem cells. The ability of the CXCR4-CXCL12 axis in directing stem cell homing is probably related to its prominent role in directing the metastatic destination of tumor cells as well (Zlotnik et al., 2011)


 In the developing and mature brain, virtually all types of CNS cells such as neural progenitors, neurons, microglial cells, and astrocytes as well as endothelial cells of brain blood vessels are targets for SDF-1 (Li and Ransohoff, 2008). Developmental aspects controlled by SDF-1 in the CNS include cell proliferation, migration, and (neuronal) cell survival (Li and Ransohoff, 2008). A recognized function of SDF-1 in the mature CNS is the control of intercellular communication between brain cells (Bezzi et al., 2001; Rostene et al., 2007). In the injured CNS, SDF-1 regulates inflammatory processes (Cartier et al., 2005; Li and Ransohoff, 2008) and promotes tissue regeneration by recruiting neural progenitor cells to the site of injury (Tran et al., 2007).
 CXCR7 shows a roughly 10 times higher binding affinity for SDF-1 as compared with CXCR4 (Balabanian et al., 2005; Crump et al., 1997) and additionally binds interferon-inducible T-cell a chemoattractant (I-TAC, CXCL11) as a second ligand (Burns et al., 2006). receptor. Similar to the atypical chemokine receptors, D6 and CCX-CKR (Graham, 2009), CXCR7 contains a modified DRYLAIV motif; this motif is assumed to be essential for G protein binding (Thelen and Thelen, 2008)
 Moreover, several studies failed to demonstrate CXCR7-dependent activation of G proteins and subsequent Ca2 1-induced chemotaxis (Burns et al., 2006; Levoye et al., 2009; Rajagopal et al., 2010b; Sierro et al., 2007). Studies on the migration of primordial germ  cells  further  revealed  that  CXCR7  controls CXCR4-mediated cell migration by sequestering extracellular SDF-1 and, hence, shaping the extracellular chemokine  gradient  (Boldajipour  et  al.,  2008).  More recently, this scavenger function was additionally highlighted by the demonstration of a constant cycling of CXCR7 between the plasma membrane and intracellular compartments as well as a nonsaturating binding of SDF-1 to CXCR7 (Naumann et al., 2010).  Intriguingly, despite this atypical function, CXCR7 induces cell signaling in various types of tumor cells and controls their growth,  adhesion,  and  transendothelial  migration (Burns et al., 2006; Grymula et al., 2010; Miao et al., 2007; Wang et al., 2008; Zabel et al., 2009). In addition, CXCR7-mediated cell signaling occurs in primary interneurons (Wang et al., 2011) Along the same line, we recently demonstrated that in primary astrocytes, SDF1-dependent activation of several signaling molecules/ pathways including Erk, Akt, and PKC  is entirely mediated by CXCR7 ( € Odemis et al., 2010). Since CXCR7 associates b -arrestin, it has been suggested that CXCR7 would affect cell function through a b -arrestin-dependent mechanism (Luker et al., 2009; Kalatskaya et al., 2009; Rajagopal et al., 2010a; Zabel et al., 2009). We now provide evidence that in primary rodent astrocytes and human astrocytoma cell lines, CXCR7 induces cell signaling and controls cell proliferation and migration through pertussis toxin-sensitive Gi/oproteins. 
Along the same line, we observed that SDF1-induced increases in [Ca2 1]i are sensitive to the CXCR7 antagonist, CCX771 (Zabel et al., 2009), but not to the CXCR4 antagonist, AMD31000 (Hatse et al., 2002).
The  previously  reported  failure  of  SDF-1-bound CXCR7 to activate G proteins in nonastroglial cells has been primarily attributed to the fact that CXCR7 contains a modified DRYLAIV motif (Thelen and Thelen, 2008). This motif represents a highly conserved region within the second intracellular loop of GPCRs and is assumed to be essential for G protein binding and their subsequent activation. Indeed, several established atypical chemokine receptors such as D6, DARC, and CCXCKR either lack the DRYLAIV motif or exhibit a modified motif (Graham, 2009). However, other chemokine receptors such as lymphotactin receptors and CXCR6, also showing modifications of the DRYLAIV motif, still signal through G proteins (Thelen and Thelen, 2008). These discrepancies are currently regarded as an indication that at least in case of some GPCRs the DRYLAIV motif is  not sufficient for  G protein  coupling and requires  additional  sequences  (Thelen  and  Thelen, 2008). Consequently, modifications  of  the DRYLAIV motif, as exhibited by CXCR7, may not per se represent a reliable indicator for the lack of G protein coupling.

**BIASED SIGNALLING**
Agonist binding to GPCR typically results in balanced G protein- and arrestin-mediated cell signaling (Rajagopal et al., 2010b). Biased signaling, through only one of these pathways, is either caused by a biased ligand or a biased receptor. While until now biased receptor function  has  only  been  observed  with  experimentally mutated  GPCRs,  a  recent  work  demonstrated  that CXCR7 acts as a biased receptor in HEK-293 cells and signals exclusively through b -arrestin (Rajagopal et al., 2010a). Notably, in astrocytes signaling of SDF-1-bound CXCR7 was sensitive to PTX, but was not affected by depletion of b -arrestin1 or b -arrestin2. Vice  versa , signaling of the alternative CXCR7 ligand, I-TAC (Burns et al., 2006), was unaffected by PTX, but was abolished following depletion of b -arrestin2. These findings are consistent with the view that CXCR7 functions as a ligandbiased receptor in astrocytes. Mechanistically, receptoror ligand-biased signaling of CXCR7 might be determined by whether or not SDF-1-bound CXCR7 couples to G proteins in a given cell type. 
 
 
 SDF-1 has been shown to act in the brain as a neurotransmitter  (Banisadr et al., 2005) and to be released with GABA from  inhibitory neurons (Bhattacharyya et al., 2008). 
 SDF-1 via CXCR4 coupled to G  i/o  has been shown to regulate  neuronal signaling through inhibition of voltage dependent  calcium (Ca  2+  ) currents (Oh et al., 2002), in particular the N-  type channel (Simen et al., 2001).
 However, SDF-1 also  activates GIRK channels (Guyon et al., 2005; Guyon and  Nahon, 2007) which GnRH neurons express (Hu et al., 2006;  Klenke et al., 2010). 
 
 Taken together, these data suggest that the small molecule and cyclic peptide block ligand binding by acting as orthosteric competitors of the CXCL12 N-terminal signaling trigger, providing strong support for the two-site model of binding. Along these lines, a recent NMR study showed that the CXCR4 antagonist AMD3100 could displace the CXCL12 N terminus from the receptor without displacing the chemokine core domain (58
 
 
  CXCR    has  been  localized  in  different  subsets2 of neurons of the central nervous system including cerebellar nerve cells  Horuk et al., 1997 , pointing to the cerebellum as a target for chemokine action in the brain.
  
  CXCR    signals  through  a  pertussis  toxin-sensitive  G2  protein-coupled  phospholipase  C b PLC b Wu  et  al., .. 1993 , raising inositol   1,4,5   trisphosphate   InsP   -depen-3 2 q. dent cytosolic Ca      level   Murphy and Tiffany, 1991 . In cerebellum,  the  activation  of  this  signalling  pathway  by neurotransmitters  is  known  to  play  a  crucial  role  both  in synaptic  activity  and  plasticity  processes   Linden,  1994; . Chen  and  Tonegawa,  1997 . <!-- ANALOGICAL - in amygdala, this pathways .... -->
  
  
  Since  Ca2 qis  considered  the  main  neuromodulator  of . neurotransmitter release  Katz, 1969 , cerebellar slices were 
  
   CXCL12 induces the tumor necrosis factor a (TNF a )-mediated Glu release from astrocytes (Bezzi et al., 2001) and TNF a increases the surface expression of synaptic AMPARs (Beattie et al., 2002) . @lax_2002
   
   The association of AMPAR subunits with PDZ (PSD-95/Dlg/ZO-1)
   
   Banisadr 2016: CXCR7 in the brain (Schönemeier et al. 2008a , b ; Shimizu et al. 2011 ). Knowledge of the precise expression pattern and characterization of cells expressing CXCR7 is required to further explore the function of CXCR7 in the brain. It is well established that SDF-1/CXCL12 is constitutively expressed by endothelial and neuronal cells in various regions of the adult rat brain (Tham et al. 2001 ; Stumm et al. 2002 ; Banisadr et al. 2003 ) and the expression patterns of SDF-1/CXCL12 and CXCR4 have been well established in structures associated with various functions such as their role in adult neurogenesis and neuroinflammation among other functions (Banisadr et al. 2002 ; Stumm et al. 2002 ; Tissir et al. 2004 ;Tranetal. 2007 ).
   
   
   CXCL12 is stored in vesicle like structures within neurons which seem to be neurotransmitter storage vesicles (Bhattacharyya et al. 2008).
   It has been shown that the development of adult DG neural stem cells is regulated by the release of GABA from neurons of this type (Ge et al. 2007; Bhattacharyya et al. 2008). Release of CXCL12 within the DG neural stem cell niche is able to enhance GABAergic transmission to neural stem cells (Ge et al. 2007; Bhattacharyya et al. 2008). We observed that CXCL14 had essentially the opposite effect and could inhibit GABAergic inputs to these cells. The GABAergic input to DG neural stem cells takes the form of both tonic and phasic transmission. Interestingly, both tonic and phasic effects of synaptically released GABA were inhibited by CXCL14. We also observed that some cells responded to both CXCL12, which enhanced, and CXCL14, which decreased GABAergic transmission to nestin-expressing cells. Hence, it seems likely that CXCL12 and CXCL14 represent ‘up’ and ‘down’ volume controls that can regulate GABA inputs to neural stem cells in a reciprocal fashion. The fact that CXCL14 and CXCL12 are also both contained in DG GABAergic interneurons (Bhatta- charyya et al. 2008) increases the probability of a meaningful connection between the effects of these three molecules in the control of DG neuron development in the adult. By comparison neither CXCL14 nor CXCL12 altered GABAergic transmission to mature granule cells in the DG (Figure S3 and Bhattacharyya et al. 2008).
   
In our previous studies, we concluded that the effects of CXCL12 on DG neural stem cells were likely to be mediated  post-synaptically  (Bhattacharyya et al. 2008). Indeed, CXCR4 receptors are clearly expressed by these cells (Tran et al. 2007; Bhattacharyya et al. 2008). It is also clear from our experiments that adult neural stem cells express the receptor (or at least ‘a receptor’) for CXCL14. Thus, CXCL14 increased [Ca2+]iin these cells, one of the cardinal signs of chemokine receptor signaling. Given the fact that neural progenitor cells express the receptor for CXCL14 and the observation that the chemokine reduces the amplitude of GABAergic PSCs recorded from these cells one might conclude that the effect of CXCL14 is at least partly mediated post-synaptically. However, it is quite possible that a pre-synaptic effect is also involved. Precise identification of the mechanism by which CXCL14 produces its effect will have to await further studies on identifying its receptor and its location in the DG.

Guyon_2006
SDF-1 a increased glutamate release in SN slices, as previously described in other brain structures such as cerebellum (Ragozzino et al . 1998) or hypothalamus (Guyon et al . 2005b). This current was not blocked by TTX, suggesting that it did not involve action potential-dependent release through the glutamate terminals. Glutamatergic terminals on DA neurones arise from the output of the subthalamic nucleus or prefrontal cortex, which are absent from our slices. Increased calcium permeability in terminals might raise the probability of spontaneous release of glutamate or uptake of glutamate might be inhibited at the axon terminal exposed to SDF-1 a . However, sEPSCs recorded in 10 lM bicuculline were unaffected by SDF-1 a . It is therefore likely that SDF-1 a induces glutamate release from glial cells present in the slice.

It is well established that SDF-1 a mobilizes cytosolic calcium following stimulation of CXCR4 in astrocytes and microglia (Tanabe et al . 1997), and that an increased calcium concentration in these cells may cause a massive release of glutamate (Araque et al . 2001). Interestingly, in the SN, the SDF-1 a effect was independent of CXCR4 as it was not blocked by AMD (1 lM) (Fig. 6), consistent with the lack of CXCR4 on astrocytes revealed by immunostaining. The mechanism of action of SDF-1 a on glutamate release thus needs further investigation.


in particular, CXCL12/CXCR4 pair modulates cerebral cortex ( Bagri et al., 2002; Lu et al., 2002; Stumm et al., 2003; Stumm and Höllt, 2007 ) and cerebellar ( Ma et al., 1998; Zou et al., 1998 ) development. In adult brain, high expression of CXCR4 has been reported in neuronal progenitor cells in the subventricular region and in the subgranular zone of the hippocampus, the two major niches of neuronal stem cells in the adult brain ( Stumm et al., 2002; Berger et al., 2007 ). The expression of CXCL12 in the hippocampal granular layer regulates the generation and the positioning of new granule neurons ( Abe et al., 2018 ), as well as axonal elongation and sprouting ( Pujol et al., 2005; Lysko et al., 2011; Su et al., 2012 ). According to its role in neurogenesis, the upregulation of CXCL12 upon stroke ( Wang et al., 2012 ), or demyelination ( Carbajal et al., 2011; Patel et al., 2012; Williams et al., 2014 ) contributes to generate new cells and to restore normal CNS functions. Postnatal development of neurons in the cortical layer V depends on CX3CL1 signaling, which regulates the release of insulin-like growth factor (IGF1) by microglia, important for survival of these neurons ( Ueno et al., 2013 ).

am  D 3100 is available from   a   nor   m   ed, and its effects on brain functions  have already been tested, although it does  not seem to cross the blood–brain barrier.  <!-- Rostene 2007-->

several compounds that  have been developed for human chemokine  receptors do not bind to their rodent counterparts and, furthermore, might have different receptor selectivity in different   species, reducing the possibility for developing relevant pharmacological animal models. <!-- Rostene 2007-->

@britton_2020

Historically the chemokine receptor CXCR4 and its canonical ligand CXCL12 are  associated with the bone marrow niche and hematopoiesis. 
However, CXCL12 exhibits broad tissue expression including brain, thymus, heart, lung, liver, kidney,  spleen, and bone marrow. 
CXCR4 can be considered as a node which is integrating  and transducing inputs from a range of ligand-receptor interactions into a responsive  and divergent network of intracellular signaling pathways that impact multiple cellular processes such as proliferation, migration, and stress resistance.

### cxcr4

CXCR4 is a G protein-coupled receptor (GPCR), originally  termed Fusin due to its role in cell-cell fusion12 and its expression was first described in peripheral blood leukocytes and  subsequently in hematopoietic stem cells, B-lymphocytes,  epithelial, endothelial, stromal fibroblasts, and cancer cells.13

CXCL12 is the canonical ligand for CXCR4, along with several other endogenous ligands including migration inhibitory factor (MIF),7 extracellular ubiquitin,14,15 and  human beta defensins (HBD) 2 and 315 as well as exogenous ligand, including viral macrophage inflammatory protein 2  (vMIP-II)16 and the HIV envelope glycoprotein GP12017  (discussed in detail in section viral ligands). CXCR4 ligand  binding induces a two-stage conformational change which  first enhances receptor-ligand binding and subsequently triggers GDP-GTP exchange and dissociation of the G proteins.6  Gαi and Gβγ activate several intracellular signaling cascades which, through increased intracellular calcium, modification  of cellular proteins, and altered transcription factor binding  and gene expression, lead to chemotaxis, cell growth and  proliferation, and cell survival.18 Following CXCR4 activation, phosphorylation of the intracellular C-terminal domain  results in β-arrestin recruitment, which sterically hinders  further G-protein engagement. Association with β-arrestin  promotes clathrin-mediated endocytosis of CXCR4, further modulating signaling and results in either recycling or  degradation.19 

### INTRACELLULAR PATHWAYS

When CXCL12 binds CXCR4, different downstream intracellular pathways effect different cellular phenotypes.  High affinity binding to CXCL12 requires the extracellular  N-terminal domain of CXCR4 which must be post-translationally modified by tyrosine sulfation.20 CXCL12 rapidly induces clathrin-mediated endocytosis of CXCR4, leading  to receptor downregulation and trafficking to endosomal  compartments.19 Following ligand binding of CXCR4, GDP exchanges for GTP and the trimeric Gi-protein dissociates into its constituent parts, Gαi and βγ.18 CXCR4 is typically associated with the Gαi type of G-protein, which activates phosphatidylinositol-3-OH kinase (PI3K) and Phospholipase  C (PLC), while the βγ subunit activates PLC, PI3K, and integrins.21 PLC hydrolyses phospholipid phosphatidylinositol 4,5-bisphosphate (PIP2) into diacyl glycerol (DAG) and  inositol 1,4,5-trisphosphate (IP3). IP3 increases the intracellular calcium from the endoplasmic reticulum22 while DAG activates protein kinase C (PKC).23 Both intracellular free calcium and PKC activate mitogen-activated protein kinase  (MAPK) pathways, leading to cell migration, growth, and  proliferation.22 The αi subunit both inhibits adenylate cyclase, decreasing cyclic adenosine monophosphate (cAMP),  and activating the Ras-MEK1/2-ERK1/2 pathway resulting  in cell cycle entry and proliferation.24 Both Gαi and Gβγ increase flux through the phosphoinositide 3-kinase (PI3K)Akt pathway.25 Akt promotes cell survival via inactivation of the Bcl-2-associated death promoter protein and activation of  mTor26,27 and through GSK-3 inactivation (thus preventing cyclin D1 degradation and promoting G1-S phase cell cycle  progression28) increases NF-kB-associated gene transcription and also stabilizes β-catenin which increases the transcription of genes linked to cell proliferation.

CXCR4 also binds to Gα12/13 and Gαq29 with both interactions promoting CXCL12-induced chemotaxis. However,  the mechanisms of signaling leading to migration varies according to the G protein involved: Gαq through Rac and PLC  and Gα12/13 through Rho.30 It is not known which ligands bias Gα12/13 and Gαq above the canonical Gαi activation.β-arrestin engagement with CXCR4 can be similarly in-tricate; distinct receptor conformations differentially drive  signal induction, desensitization, and endocytosis. Structural  studies reveal two distinct conformations: one in which β-arrestin docks with the phosphorylated C-terminal domain of  CXCR4 and a second in which β-arrestin is also coupled to the  core transmembrane region. Studies using CXCR4 mutants  reveal that association of β-arrestin with the phosphorylated  GPCR C-terminal tail drives β-arrestin signaling and receptor internalization though not desensitization. Dissociation of  β-arrestin from the internalized G-protein facilitates CXCR4  recycling back to the plasma membrane.31 Tuning of CXCR4 signaling is achieved through the expression of two distinct  isoforms of the receptor.

CXCR4 signaling is modulated through the expression of  multiple isoforms and by posttranslational modifications.  Two CXCR4 isoforms, CXCR4-A and CXCR4-B, produced  by alternative splicing have been shown to bind to CXCL12  and induce chemotaxis in both mice and humans. CXCR4-B  but not CXCR4-A mediates efficient HIV-1 X4 binding and  infection, although the chemotactic activity affected through  each isoform was the same.32,33 

Posttranslational modifications can also modulate CXCR4 activity, sulfation of Tyr,7  Tyr,12 and Tyr20 has been shown to increase binding to a subset of ligands.35 In particular, sulfation of Tyr20 increases CXCL12 binding and dimerization.36,37 Phosphorylation of CXCR4 following CXCL12 binding similarly influences the  downstream signaling based upon the site phosphorylated.  Increased ERK1/2 activation follows CXCR4 engagement  with G-protein kinases 3 and 6 along with β-arrestin-2, while  reduced intracellular calcium is linked modification by G  protein-coupled receptor kinases (GRK) 2 and 6 and arrestin-3 binding.38 Furthermore, phosphorylation of C-terminal residues is associated with increased β-arrestin recruitment  and clathrin-mediated endocytosis.38 The functionally different CXCR4 isoforms may provide a mechanism to extend the  capacity of CXCR4 to mediate varied effects under different  conditions or in different cell types. Thus, continued investigation of the mechanistic guidelines for the processes will  be invaluable to enabling improved therapeutic control of the  CXCR4 network. 

Multiple mechanisms may terminate CXCR4 signaling: desensitization, internalization, and degradation, each of which  act to guard against inappropriately sustained signaling.Desensitization of CXCR4 and other GPCRs can be ei-ther acute or sustained: short-term desensitization spans  minutes and results from β-arrestin-mediated steric hinderance of G-protein engagement. Longer term desensitization  occurs over hours to days and results from persistent internalization, degradation, and transcriptional downregulation.  Following ligand binding, CXCR4 phosphorylation, and G  protein recruitment, β-arrestin is recruited to sterically hinder  G-protein engagement with the receptor (desensitization).

Control over receptor internalization is exerted at the level of  ligand binding. Recent studies demonstrate that inverse agonists (TAK779) of CXCR4 stimulate a higher rate of receptor internalization compared to partial agonists (Met-CCL5),  suggesting an actively driven internalization process.39  Following internalization, CXCR4 signaling can continue.  For example, CXCL12 mediates human neural progenitor  cell survival by binding CXCR4 localized to the endosome.40  CXCR4 also localizes to the endosome for degradation  which is controlled at several levels

Cytoskeletal activity  can link CXCR4 internalization to endosomal degradation.  Rho and Gα13 mediate the actin polymerization necessary  for trafficking CXCR4 into the endosomal compartment.41  Furthermore, adaptor proteins are necessary for endocytosis:  a complex interplay between CXCR4, β-arrestin, and adaptor protein, AP2, is necessary to mediate CXCR4 endocytosis—mechanistic insight is lacking.42 Adaptor proteins are also necessary for CXCR4 recycling, for example, IQGAP1  regulates endosome interactions with microtubules during  CXCR4 trafficking back to the cell membrane.43 Following 

Whether a receptor is recycled or degraded is largely a function of the overall number of receptors internalized,42 competing cargo for CXCR4-binding motifs42 and the cytoskeleton.43 A network of CXCR4-binding proteins and cytoskeletal processes control CXCR4 signal  termination—finer mechanistic insight will provide potential  for therapeutic modulation.

Interaction of CXCR4 and CXCL12 was first understood as  a non-promiscuous signaling network. However, the discovery of multiple CXCR4 receptor isoforms then led to the observation that CXCR4 monomers combine to form a variety  signaling units which influence signal termination. FRET and  crystallization studies suggest CXCR4 constitutively forms  both monomers and dimers45 and CXCL12 binding shifts the equilibrium in favor of dimer formation.46 Allosteric ligands bind to the CXCR4 receptor at a different site to the  one at which agonists, antagonists, and inverse agonists bind.  Such ligands might be intra- or extra-cellular molecules or,  indeed, another G-protein receptor.

It has been demonstrated that dimers of CXCR4 are preferentially internalized as compared to monomers when  stimulated with either CXCL12 or phorbol ester.48 CXCR4 homodimerization can promote activation of the JAK/STAT  pathway, leading to cellular polarization and chemotaxis.49,50  CXCR4 receptors can also form heterodimers. When heterodimers of CXCR4 and CXCR5 form, binding of a cognate  ligand to either of these receptors inhibits chemokine binding  to the other via a mechanism known as allosteric trans-inhibition.51

Many of the details regarding the mechanisms of CXCR4  signaling have been elucidated with its canonical ligand,  CXCL12α. Here, we emphasize a need to expand our focus  from a one receptor-one ligand model to include multiple isoforms and oligomers of CXCL12, as well as MIF, extracellular ubiquitin, Human Beta Defensins-2 and −3, and viral  ligands. These ligands differentially impact the signaling  pathways downstream of CXCR4 and, therefore, therapeutic  intervention at the level of CXCR4 ligands might provide opportunity for finer tuning compared to CXCR4 antagonism.


### cxcr7

Additionally, CXCR4 and CXCR7 can form heterodimers, which results in impaired activation of Gαi and  increased binding of β-arrestin, leading to potentiation of the  ERK1/2, p38, MAPK, and SAPK pathways and enhanced  chemotactic response to CXCL12, as compared to CXCR4  activation alone.54 CXCR7-knockout mice have atrial and ventricular septal defects and impaired semi-lunar valve remodeling.55 CXCL12 was shown to be the ligand for CXCR7, only inducing signaling when CXCR7 forms a functional  heterodimer with CXCR4. The results of this study demonstrate a distinct developmental role for CXCR7-CXCR4  heterodimers.

### cxcl12

The canonical ligand for CXCR4 is the C-X-C chemokine  12 (CXCL12), originally known as stromal cell-derived factor-1 (SDF-1). CXCL12 is comprised of a three-stranded  β-sheet held in close apposition to an α-helix56; the two most N-terminal residues are essential for activation of  CXCR4.57,58 In particular, Lys1 at the CXCL12 N-terminus forms a strong polar interaction with Glu32 in the CXCR4  extracellular domain; this interaction leads to the movement of TM5 and TM6, facilitating G-protein binding and concomitant intracellular signal transduction.59 It is expressed by alternative splicing as in humans, alternative splicing of  transcripts yields the expression of six different isoforms (α,  β, δ, γ, ε, φ) ranging in size from 10 to 16 kDa.60 The α isoform is the smallest and most abundant; however, other isoforms likely play a key role in physiologic and pathological  processes.CXCL12 can also bind atypical chemokine receptor 3 (CXCR7), previously termed CXCR7. Originally CXCR7  was thought to provide only scavenging function, sequestering extracellular CXCL12, and decreasing signaling capacity through CXCR4.61 Subsequent worked suggested that CXCR7 can act to preserve CXCL12 gradients and CXCR4  sensitivity to CXCL1262 as well as to enable tighter control of such gradients and of cell migration, for example,  for guidance of interneurons in the cortex and of B cells  in diffuse large B-cell lymphoma.63-65 CXCL12-mediated CXCR7 signaling was initially described to require β-arrestin.66 However, this has since been challenged by find-ings in human astrocytes that activation of CXCR7 by  CXCL12 can be G-protein mediated.6

It should be noted that CXCR7 has a number of other ligands (CXCL11, MIF,  Adrenomedullin, Bovine Adrenal Medulla 22) not reviewed  here, rather the reader is directed toward reviews by Wang  et al68 and Chatterjee et al69 Interestingly, CXCL12 activation of CXCR4/CXCR7 heterodimers results in constitutive β-arrestin recruitment and decreased Gαι signaling, thereby enhancing signaling through ERK1/2, p38, MAPK,  and SAPK, resulting in increased cell migration compared  to homodimers.70

CXCL12 is proteolytically cleaved and inactivated by ma-trix metalloproteinases-2 and −9, cleaving at position 4-5,  and dipeptidyl peptidase 4 (DPP4), cleaving at position 2-3,  and controlling concentration gradients of the chemokine.71  The relative contributions of these enzymes in maintaining  the concentration gradient of CXCL12 remains uncertain.  


Inhibition of DPP4 by Diprotin A or Val-Pyr maintains the CXCL12 concentration at the site of ischemic  injury, promoting stem cell migration, and engraftment potential of ischemic tissue.72 Maintaining concentration gradients of CXCL12 by DPP4 inhibition has the potential to  enhance stem cell repopulation in an array of stem cell therapies, recent work looks at its ability to promote hippocampal  neurogenesis in Alzheimer's disease.73 

The CXCL12 isoforms differentially regulate CXCR4  signaling, which can impact both physiological and pathophysiological consequences.57 Humans express six different isoforms of CXCL12 (α,  β, δ, γ, ε, φ) produced through alternative splicing.60,74

CXCL12 can exist in monomeric, dimeric, and oligomeric  forms80; each of which can have differential effects on sign-aling and cellular processes. CXCL12 hetero-dimerization  has functional consequence, particularly in the setting of  inflammation. Following tissue damage, inflammatory cells  migrate into the tissue and release cytokines such as high mobility group box 1 (HMGB1). Recruitment of mononuclear  cells to sites of damage depends upon CXCL12-HMGB1 heterodimerization and binding to CXCR4, promoting different  conformational changes in CXCR4 as compared to CXCL12  binding alone.81

Furthermore, CXCL12 synergizes with CXCL14 in the induction of primary human lymphoid cell  chemotaxis. The maximal chemotactic response achieved  with CXCL12 stimulation alone can be exceeded by combination with CXCL14.82 Additional examples of synergy with CXCL12, including CCL3, CCL21, and CXCL-8, to induce  chemotaxis have been reported.

CXCL12 isoform and stoichiometry exert a regulatory effect over activation of CXCR4 signaling pathways. Constitutively  homodimeric CXCL12, bridged by the N-terminal of CXCR4 peptides, results in calcium influx and inhibition of chemotaxis,  whereas monomeric CXCL12 remains chemotactic.83

In summary, CXCR4 is a G protein-coupled receptor that impacts cellular survival, growth, proliferation, and migration. A signaling network underlying such a range of fundamental cellular processes must be finely modulated and  this is achieved at multiple levels: receptor isoforms and  cross talk, termination of signaling, and ligand diversity. The  regulatory complexity of this signaling network is necessary to achieve homeostatic control of fundamental cellular  processes across a broad range of tissue types. The potential  success of therapeutic modulation lies in engaging with this  complexity, rather than taking a reductionist approach to targeting, thereby enabling fine tuning of the intricate signaling  network.

CXCR4 activation is implicated in many physiological systems, from CXCL12-induced signaling in homing of hematopoietic stem and progenitor cells to the bone marrow108  to neovascularization,109 angiogenesis,110 neurogenesis,111  and adaptive immune responses.112 Dysregulation of the CXCR4 network is evident in multiple pathologies including viral infection,113 malignancy,114 ischemic disease,7  inflammatory disease,115 autoimmune conditions,116 and immunodeficiency in the Warts, Hypogammaglobulinemia,  Immunodeficiency, and Myelokathexis syndrome (WHIM)  disorder.117 Therefore, CXCR4 represents a potential therapeutic target for multiple diseases. However, while the nuanced biology of CXCR4 offers a finely tuneable system  influencing core physiology, therapeutic intervention should  consider the effects on the target tissue in context of its perturbation of other physiological processes, in order to maximize therapeutic benefit and minimize off-target effects.  Hence, we briefly review the role of CXCR4 in physiological  processes.

Interneurons are guided to the correct cortical layer via CXCL12 gradients while  CXCR7 acts as a sink to collect excess CXCL12.63 

 CXCL12/CXCR4 pair modulates cerebral cortex ( Bagri et al., 2002; Lu et al., 2002; Stumm et al., 2003; Stumm and Höllt, 2007 ) and cerebellar ( Ma et al., 1998; Zou et al., 1998 ) development. In adult brain, high expression of CXCR4 has been reported in neuronal progenitor cells in the subventricular region and in the subgranular zone of the hippocampus, the two major niches of neuronal stem cells in the adult brain ( Stumm et al., 2002; Berger et al., 2007 ). The expression of CXCL12 in the hippocampal granular layer regulates the generation and the positioning of new granule neurons ( Abe et al., 2018 ), as well as axonal elongation and sprouting ( Pujol et al., 2005; Lysko et al., 2011; Su et al., 2012 ). According to its role in neurogenesis, the upregulation of CXCL12 upon stroke ( Wang et al., 2012 ), or demyelination ( Carbajal et al., 2011; Patel et al., 2012; Williams et al., 2014 ) contributes to generate new cells and to restore normal CNS functions <!-- tRETTEL2020-->
 
 Pioneer experiments demonstrated that IL8 and CXCL1 potentiate the spontaneous and evoked excitatory transmission in cerebellar neurons by increasing the cytosolic Ca2+levels, whereas CXCL12 depresses the evoked input of the parallel fi bers to Purkinje neurons ( Giovannelli et al., 1998; Ragozzino et al., 1998, 2002 ). CXCL12 also induces a presynaptic increase of both glutamatergic and GABAergic neurotransmission onto serotoninergic neurons in the dorsal raphe, onto cortical immature neurons upon transient MCAO and onto dopaminergic neurons of substantia nigra (SN) ( Guyon et al., 2006; Heinisch and Kirby, 2010; Ardelt et al., 2013 ). <!-- trettel-->
 
 The fi rst evidence that CXCL12 has effects on neurons and promotes neuroprotection were given by Meucci et al. (1998) when, for the fi rst time, the authors demonstrated that CXCL12 reduced the apoptotic death of hippocampal neurons induced by gp120 or by glia deprivation. Following glia deprivation, neuroprotection was promoted by administration of CXCL12 speci fi cally to neurons highlighting a direct activity of the chemokine on these cells. Further, stimulation of hippocampal neurons with CXCL12 was able to induce Akt phosphorylation and p65NF-kB nuclear translocation, both signaling implicated in pro-survival cell fate ( Khan et al., 2004 ).Accordingly, in primary cortical neurons, CXCL12 promotes Rb function increasing its expression, nuclear localization, and transcriptional activity and reducing the excitotoxic cell death due to NMDA receptors over-activation ( Khan et al., 2008 ). 
 
 CXCL12 neuroprotection is also sustained by an increase in the pro-survival signaling of synaptic NMDA receptor, and in the down-regulation of the extrasynaptic NR2B-NMDA receptor subunit (whose activity is known to mediate neurotoxicity) ( Nicolai et al., 2010 ). Since all the experiments presented in the above cited papers were performed using neuronal cultures with a separate astrocytes layer, it cannot be excluded that the neuroprotective effects might be also mediated by glial cells. Indeed, CXCL12 stimulates astrocytes promoting Akt phosphorylation ( Khan et al., 2004 ), G-protein-PI-3Kinase-ERK1/2 signaling cascade leading to cell proliferation ( Bajetto et al., 2001b ), NF-Kb activation with consequent TNFα (Han, 2001) and glutamate
 
 Recently it has been reported that gliptin (Dipeptidyl-peptidase 4 DPP-4 inhibitor) improves motor functions and reduces tissue damage upon MCAO, increasing the cerebral level of CXCL12 ( Chiazza et al., 2018 ). Since CXCR4 antagonist reduced gliptin induced functional recovery ( Chiazza et al., 2018 ), it was speculated that CXCL12 represents  an  endogenous  modulator  counteracting  brain damage. The upregulation and the release of CXCL12 from astrocytes was also observed in the ischemic penumbra ( Stumm et al., 2002; Hill et al., 2004; Miller et al., 2005 ). In vitro, ischemia alters the expression of miRNAs associated with CXCL12 regulation, leading to increased CXCL12 expression and release from astrocytes ( Shin et al., 2014 ). In addition, acting on microglial cells, CXCL12 activates signaling pathways that trigger the release of IL-6 ( Lu et al., 2009 ), which has neuroprotective properties in ischemia ( Loddick et al., 1998; Ali et al., 2000; Ohtaki et al., 2006 ). Another novel neuroprotective activity of CXCL12/CXCR4 signaling has been identi fi ed in its ability to increase dendritic spine numbers ( Pitcher et al., 2014 ). In particular authors found that, in opiate abuser and in neuroAIDS patients, deregulation of CXCL12/CXCR4 is determinant to cognitive dysfunction associated with dendritic spine loss. The authors also demonstrated that CXCL12/CXCR4 regulates dendritic spine density both in vitro, in pure neuronal cultures, and in vivo, in a rat model of opiate abuse. CXCL12-CXCR4 signaling plays a role in neuroprotection also in Alzheimer disease: CXCL12 protected neurons from A β -induced apoptosis through the activation of Akt, ERK1/2 and the maintenance of metalloproteinase ADAM17 and, in vivo, counteracted the oxidative damage and the loss of spine density in the hippocampus ( Raman et al., 2011 ). Furthermore, a decreased expression of CXCL12 was observed in the brain of Tg2576 and in 3XTg AD animal models at the stage of cognitive decline, as well as in brain tissue from AD patients ( Parachikova and Cotman, 2007 ).
 
 CXCR7 is an interesting atypical chemokine receptor (Maksym et al., 2009). 
Together with CXCR4 and its ligand CXCL12, CXCR7 is conserved well across the vertebrate species including sea lamprey (Nomiyama et al., 2011). 
It binds CXCL11 and CXCL12. 
Importantly, CXCR7 can heterodimerize with CXCR4 and modulate the effect of CXCL12 on CXCR4. 
Furthermore, CXCR7 can also signal in some cell types although not by the classical G protein-coupled receptor pathways (Maksym et al., 2009). 
During embryogenesis, CXCR7 is necessary for proper migration of primordial germ cells to CXCL12 via CXCR4 by acting as a sink for CXCL12 (Boldajipour et al., 2008). 
CXCR7 is also involved in cardiac tissue development along with CXCR4 and CXCL12 (Sierro et al., 2007). 
Although poorly expressed in normal adult tissues, CXCR7 is widely expressed in a variety of tumors and tumor-associated vessels and appears to promote tumor growth and neoangiogenesis partly by signaling via mitogen activated protein kinase (MAPK) cascades (Maksym et al., 2009).

 @collins_2017 alone. CXCL14 did not activate CXCR4-expressing cells (i.e.,failed to trigger chemotaxis and Ca2+ mobilization, as well as signalingviaERK1/2 and the small GTPase Rac1); however, CXCL14 bound to CXCR4 withhigh affinity, induced redistribution of cell-surface CXCR4, and enhanced HIV-1 infection by>3-fold. We postulatethat CXCL14 is a positive allosteric modulator of CXCR4 that enhances the potency of CXCR4 ligands
 
 Receptor dimerization has been shown to modify ligand binding properties [155,170] and receptor signaling [153,167,171,172] as well as intracellular trafficking [158] .  However, so far there is no in vivo data reporting the existence of CKR dimers and therefore their biological relevance remains controversial [152,173] -->
<!-- This phenomenon is thought to be required for the functionality and signaling properties of chemokine receptors. The dimerization of CXCR4 and CCR2 receptors has been shown to be required for the functionality and signaling properties of these molecules, for example /// All of these processes are reported as critical for the triggering of biological responses ( Mellado et al., 2001; Vila-Coro et al., 2000, 1999 ). /// Several chemokine receptors have also been reported to undergo dimerization (heterodimerization, homodimerization) and oligomerization process after interaction with chemokines, these processes being critical for the triggering of biological responses ( Mellado et al., 2001; Vila-Coro et al., 2000, 1999 ). --><!-- Additionally, heterodimerization has been identified as a major mechanism that underlies the positive or negative cooperation between chemokine-receptor pairs [@collins_2017].--><!-- Positive cooperation takes place when both chemokines, each at concentration unable to activate receptor, induce signaling cascade as a 
Consistent with this idea, it was shown that the combination of CCL2 and CCL5 able to induce adhesion 
The combination of CCL2 and CCL5, each at much lower doses inefficient to trigger calcium responses, showed strong effects (synergy) in an adhesion assay, indicating a gain-of-function for the mixture [30] 
  Of note, negative cooperation between chemokines was reported recently. CXCL12 and its antagonist AMD3100 can inhibit CCL2 binding only in cells co-expressing CCR2 and CXCR4, but not CCR2 alone, suggesting that binding of CXCL12 to CXCR4 in the heterodimer trans-inhibited the binding of CCL2 to its receptor CCR2 in the receptor heterodimer.--><!-- zmienić bardziej (51, 52)- Collins2017 - --><!-- The biological relevance of chemokine dimerization is still a matter of debate and its impact on receptor binding, stoichiometry and biased signaling remains to be unraveled [128,132,150,151] . --><!-- The dimerization of CXCR4 and CCR2 receptors has been shown to be required for the functionality and signaling properties of these molecules, for example ( Rodriguez-Frade et al., 1999; Vila-Coro et al., 1999 ). 
For instance, CXCR4 has a propensity to form hetero- and homooligomers (14,15), and such oligomerization could play a role in the allosteric regulation of CXCR4 signaling (16)
CXCR4 has been reported to dimerize with CCR2 and CCR5, and both complexes show negative binding cooperativity with their ligands, not only in vitro but also in vivo (37,39), an observation that may have implications for drug efficacy.
The specific nature of the interactions may facilitate the ability of CXCR4 to heterodimerize with other chemokine receptors (37,39,48), as well as GPCRs outside of the chemokine family (49), although one cannot discount the possibility that many modes of oligomerization may exist.
Hetero-dimerization may allow for enhanced or specific functions of receptors and may be essential for receptor activity. --><!-- For instance, in cells co-expressing CCR2 and CCR4, but not CCR2 alone, CXCL12 can inhibit CCL2 binding [] --><!-- in cells co
However, negative cooperation between chemokines was reported recently. CXCL12 and its antagonist AMD3100 can inhibit CCL2 binding only in cells co-expressing CCR2 and CXCR4, but not CCR2 alone, suggesting that binding of CXCL12 to CXCR4 in the heterodimer trans-inhibited the binding of CCL2 to its receptor CCR2 in the receptor heterodimer. --><!--   heterodimerization:
  Like other GPCRs, chemokine receptors may also form heterodimers. 
  However, it is not clear that native CCR5 can directly bind CXCR4 and one study reported only weak binding of CCR5 and CXCR4 by BRET assay [26] . Other examples of constitutive heterodimers include studies showing CXCR1 and CXCR2 interact as well as forming respective homodimers. 
  The mixture of CCL2 and CCL5 at a dose less than the effective dose of each in inducing adhesion showed strong effects (synergy) in an adhesion assay, indicating a gain-of-function for the mixture [30] 
  Of note, negative cooperation between chemokines was reported recently. CXCL12 and its antagonist AMD3100 can inhibit CCL2 binding only in cells co-expressing CCR2 and CXCR4, but not CCR2 alone, suggesting that binding of CXCL12 to CXCR4 in the heterodimer trans-inhibited the binding of CCL2 to its receptor CCR2 in the receptor heterodimer. --><!-- Additionally, some chemokines have been observed to form higher-order oligomers [@kleist_2016]. --><!-- tetramers ( e.g. CCL2, CCL5, CCL27, CXCL4, and CX3CL1) or higher-order oligomers  [130,135–139].--><!-- CKRs from all four subfamilies (C, CC, CXC, CX3C) have now been described to form homo- or heterodimers in vitro [154,164–166] and some of them, including CXCR4 and CCR5, were shown to interact with other families of GPCRs such as thea1A/B-adrenergic receptors [167] , opioid receptors [168] or non-GPCR membrane proteins that modulate the activity of the receptor or act as coreceptor for certain nonconventional ligands ( Fig. 4 A) [169] . -->
  
  However, chemokine oligomers, including CXCL12, appear to be functional and to induce alternative signaling responses, such as cellular activation or signals to halt migration (55,60,61), which suggests the concept that these complexes dynamically change their stoichiometries and structures as part of their functional regulation.

cooperativity. Extending this concept to chemokine receptor heterodimers, CXCR4 has been reported to dimerize with CCR2 and CCR5, and both complexes show negative binding cooperativity with their ligands, not only in vitro but also in vivo (37,39), an observation that may have implications for drug efficacy.

The specific nature of the interactions may facilitate the ability of CXCR4 to heterodimerize with other chemokine receptors (37,39,48), as well as GPCRs outside of the chemokine family (49), although one cannot discount the possibility that many modes of oligomerization may exist.

A diverse set of CXCR4 ligands bind multiple isoforms and homo/heterodimers of CXCR4, differentially impacting a divergent set of downstream pathways. The complexity of the  molecular pathway and its regulation underpins diverse and  dynamic cellular function.

Thus, continued investigation of the mechanistic guidelines for the processes will  be invaluable to enabling improved therapeutic control of the  CXCR4 network.

In summary, CXCR4 is a G protein-coupled receptor that impacts cellular survival, growth, proliferation, and migration. A signaling network underlying such a range of fundamental cellular processes must be finely modulated and  this is achieved at multiple levels: receptor isoforms and  cross talk, termination of signaling, and ligand diversity. The  regulatory complexity of this signaling network is necessary to achieve homeostatic control of fundamental cellular  processes across a broad range of tissue types. The potential  success of therapeutic modulation lies in engaging with this  complexity, rather than taking a reductionist approach to targeting, thereby enabling fine tuning of the intricate signaling  network.

CXCR4 activation is implicated in many physiological systems, from CXCL12-induced signaling in homing of hematopoietic stem and progenitor cells to the bone marrow108  to neovascularization,109 angiogenesis,110 neurogenesis,111  and adaptive immune responses.112 Dysregulation of the CXCR4 network is evident in multiple pathologies including viral infection,113 malignancy,114 ischemic disease,7  inflammatory disease,115 autoimmune conditions,116 and immunodeficiency in the Warts, Hypogammaglobulinemia,  Immunodeficiency, and Myelokathexis syndrome (WHIM)  disorder.117 Therefore, CXCR4 represents a potential therapeutic target for multiple diseases. However, while the nuanced biology of CXCR4 offers a finely tuneable system  influencing core physiology, therapeutic intervention should  consider the effects on the target tissue in context of its perturbation of other physiological processes, in order to maximize therapeutic benefit and minimize off-target effects.  Hence, we briefly review the role of CXCR4 in physiological  processes.

The role of CXCR4/CXCL12 pathway in homeostasis, development, and immune response to disease requires that the  components of the pathway are highly responsive to contextual cues, simultaneously integrating, and impacting multiple  processes. Similarly, strategies for treatment with inhibitors  of CXCR4/CXCL12 signaling should contemplate the context and dynamics when determining an intervention strategy

The chemokine receptors CCR2, CCR3, CCR5, CXCR2, CXCR4 and ACKR3 bind endogenous or virus-encoded ligands other than chemokines. These unconventional ligands vary widely in size, ranging from large proteins ( e.g. >100 kDa) to peptides, and often have no sequence or structural similarities with chemokines [15,169,208,209] . Despite their structural dissimilarities, nonchemokine CKR ligands can trigger signaling pathways similar to those induced by endogenous chemokines, although in some cases they initiate unconventional signaling responses [15,169,208– 212] . 

In addition to CXCL12, CXCR4 also binds extracellular ubiquitin (eUb, 8.6 kDa). The eUb-CXCR4 interaction was proposed to follow a two-site binding model, leading to G protein signaling similar to that induced by CXCL12 [15] . Other endogenous non-chemokine ligands such as human b 3-defensin (HDB-3) (5.1 kDa) [223] and EPI-X4 (1.8 kDa), a 16-amino acid peptide derived from human albumin [224] , also interact with CXCR4 but fail to induce intracellular signaling


SDF-1, a chemokine, is  involved in primordial germ cell migration (Blaser et al., 2005),  migration of neural progenitors (via its receptor CXCR4) and axon  growth and branching during development of the nervous system  (Tran and Miller, 2003; Pujol et al., 2005). Recent work has shown  that GABA and SDF-1 may act synergistically to alter cell  movement (Seidel et al., 2007; Bhattacharyya et al., 2008). [@casoni_2012]

SDF-1 has been shown to act in the brain as a neurotransmitter  (Banisadr et al., 2005) and to be released with GABA from  inhibitory neurons (Bhattacharyya et al., 2008). However, [@casoni_2012]

SDF-1 induced changes in saltatory GnRH movement  were shown to occur through a GIRK dependent mechanism.  GIRK channels open via a signal transduction cascade triggered  by the G  bc  dimeric protein released by activated G protein-  coupled receptors (Dascal, 1997; Yamada et al., 1998). Opening  of the GIRK channel results in permeability to potassium ions  and hyperpolarization of the cell. To date, only melanin-  concentrating hormone neurons (involved in feeding behavior  regulation) have been shown to respond to SDF-1 directly  through GIRK current activation and in these cells, SDF-1  influenced neuronal activity (Guyon et al., 2005). [@casoni_2012]

 SDF-1α/CXCR4 interaction activated AKT,   extracellular signal-regulated kinases (ERK), and P38 mitogen-activated protein kinase (MAPK) signaling pathways but  not the c-Jun N-terminal kinase (JNK) pathway.Conclusions—SDF-1α promoted neurogenesis and angiogenesis during the postacute phase of ischemia without eliciting an inflammatory response. AAV-SDF-1α expression represents a promising avenue for ischemic stroke therapy with a  wider treatment window.  