### Chemokines actions in the CNS

Over the past two decades, mounting evidence have been illustrating that beyond their well-known immunological role, chemokines are also important players in the CNS during neurodevelopment and in the adult brain. <!-- -->
Accordingly, the neuroanatomical distributions of several chemokines and their corresponding receptors overlap in many regions in the healthy CNS, suggesting their involvement in local communication, including the described above CX3CL1/CX3CR1 and CXCL12/CXCR4/ACKR3 axes.
Consistently, chemokines and their receptors are emerging as a key mediators of homeostatic crosstalk between neurons and glia. 

#### Neuron-glial communication 

Recently, in the light of the "glial revolution", our long-held views of the functions of these cells were completely challenged.
Astrocytes, previously considered supporting and nourishing neurons, are now known as the highly heterogeneous group of active players in complex brain functions, such as synaptic transmission, synaptic plasticity, network oscillations, and behavior [@perea_2009; @mederos_2019]. 
Being organized into microdomains and coupled into multicellular astrocytic networks *via* gap junctions, they are highly specialized cells (for a review: @khakh_2015). 
Furthermore, astrocytes tightly enwrap neuronal cell bodies, axons, dendrites, and synapses.<!-- citations-->
For example, it is estimated that a single cortical astrocyte makes contact from 20,000 to 120,000 synapses in rodents and up to 2,000,000 synapses in humans [@oberheim_2009], suggesting bidirectional communication. 
Indeed, they are endowed with a great variety of ion channels and receptors [@olsen_2015; @seifert_2018; @kofuji_2021] to react to a changing microenvironment, while they can release a substantial set of gliotransmitters [@araque_2014; @savtchouk_2018; @covelo_2018]. 
Ca^2+^ levels are particularly relevant in astrocyte signaling, as their elevated Ca^2+^ levels are thought to induce gliotransmission and facilitate synaptic transmission. 
Thus, astrocytic intracellular Ca^2+^ elevations are of specific spatial and temporal properties, and this topic has been extensively discussed in several excellent reviews [@araque_2014; @guerragomes_2017; @bazargani_2016].

Microglia are the resident immune cells of the CNS, constituting about 5–12% of total CNS cells in the healthy brain and the spinal cord [@szepesi_2018].
They are derived from the myeloid precursor cells and colonize the immature brain during early embryonic development (for a review, see: @prinz_2011).
Finally, these glial cells are broadly distributed throughout the CNS, albeit their density and functions may differ based on spices and specific brain regions (for a review, see: @szepesi_2018).
Although microglia have long been recognized as "guardians of the brain", regulating inflammatory responses in the CNS, it is becoming increasingly evident that their functions are much more diverse, particularly in the healthy brain during both development and adulthood.
Being equipped highly motile processes, microglia are dynamic and plastic cells that constantly monitor the microenvironment to sense local perturbation. 
Moreover, similar to astrocytes, microglia also express numerous cell surface ion channels and receptors of neurotransmitters and neuromodulators, as well as signaling molecules.

Hence, both astrocytes and microglia are emerging as highly dynamics and heterogeneous cells.
Notably, those rich repertoire of expressed surface and signaling molecules includes set of chemokines and their receptors. <!-- Moreover, their ability to form direct contact and release the soluble factors, such as chemokines, enables bidirectional interaction with other cell types in the CNS. -->
Thus, glial cells can both react to and release the set of chemokines (for example: @dorf_2000, @mckimmie_2010; @sowa_2017).<!-- cytowania dotyczące microglia-->
Given glial constant monitoring of brain parenchyma, these immune molecules might orchestrate neuron-glia actions, linking the influence of the environment to brain function and behavior.
Therefore, dissecting mechanisms of neuron-glial communications in the brain is of high importance, as identifying molecular targets may be used to counteract brain damage and preserve brain homeostasis.
Consistent with this notion, accumulating data indicate mediation and possible coordination of glial cells and chemokine system.
What is more<!--this is true especially in case of CX3CL1-->, in the CX3CR1-GFP knock-in mouse line, the CX3CR1 receptor gene has been replaced by a green fluorescent protein (GFP) reporter [@jung_2000].
Considering CX3CL1 and CX3CR1 expression, this genetic strain is one of the essential tools for studying the consequences of neuron-microglia communication following CX3CL1-CX3CR1 axis dysregulation [@paolicelli_2014].
Thus, this model resulted in an extensive body of evidence, highlighting the key role of CX3CL1 signaling in regulating a broad spectrum of aspects of microglia functions, as discussed below. <!--EWENTUALNIE TO POTEM SKRÓCIĆ-->

#### Neuroprotection

The first evidence regarding CX3CL1 and CXCL12 non-inflammatory roles were the discoveries of their influence on reduction of neurotoxicity, mainly by activating neuroprotective pathways, such as Akt phosporylation or activation of MAP kineses (p-38, ERK1/2; [@maciejewskilenoir_1999; @meucci_2000]. <!--Another aspect regulated by CXCL12 is its implication in neuroprotective actions, mainly by activating neuroprotective pathways., such as Akt and ERK`r knitr::asis_output("\U00BD")` [@vauzour_2007].inne, poprawić....--><!-- for example the activation of the Ca^2+^ and cAMP-dependent transcription factor CREB [@meucci_1998] It can also act post-synaptically by activating aG protein activated inward rectifier K+(GIRK), a voltage-gated K channel Kv2.1 associated to neuronal survival, and by increasing high voltage-activated Ca2+currents. [@casoni_2012] ( Casoni et al., 2012 )., JAK/STAT przykłady cytowania // activation of pro-survival and anti-apoptotic pathways through phosphorylation of molecules such as Akt, as well as activation of MAP kinases such as p-38 and Erk1/2 (p44/42; Maciejewski-Lenoir et al., 1999;Meucci et al., 2000;Cambienet al., 2001;Deiva et al., 2004; Klosowska et al., 2009;Lyons et al.,2009). to dotyczy CX3CL1...--> 
Specifically, CXCL12 [@meucci_1998] and then CX3CL1 [@meucci_2000] were reported to reduce the apoptotic death of hippocampal neurons induced by gp120 or glia deprivation, further indicating their direct neuronal actions.
Later, more studies further documented that both CX3CL1 and CXCL12 are neuroprotective against glutamate-induced and NMDA-induced neurotoxicity in neuronal cultures from either rodents or humans [@deiva_2004; @limatola_2005; @nicolai_2010].

Moreover, the binding of CX3CL1 to microglial CX3CR1 was shown to restrain LPS-induced microglia activation (@mizuno_2003; @zujovic_2000, for a review: @biber_2007), leading to initial presumption that CX3CL1 maintains microglia in a ‘‘resting” or ‘‘off” state.
However, further studies illustrated that microglia activation is not an all or none event, but rather a continuum of progressive stages depending on the balance between pro-inflammatory and anti-inflammatory cues in the local environment, which, in turn, change their phenotype and functional activity (@crain_2013; @lively_2013; for a review: @masuda_2020 and @tan_2020). <!-- Accordingly, CX3CR1 signaling has been reported to impact microglial function under both physiological and pathological conditions, which is discussed throughout this dissertation.może też że nei tylko neuroprotective? -->

Nevertheless, following CX3CL1 application, microglia was reported to release soluble factors that promote neuroprotection, including adenosine [@lauro_2008; @lauro_2010]. 
It is an endogenous modulator of brain functions, with increasingly evident actions on synaptic transmission [@ribeiro_2010] or glia [@boison_2010], which acts by binding to its GPCR presynaptic receptor subtypes  (adenosine A1 receptor, adenosine A2A receptor,  adenosine A~2C~ receptor, and adenosine A~3~ receptor - A~1~R, A~2A~R, A~2C~, and A~3~R, respectively). 
It was shown that adenosine modulates CX3CL1 neuroprotection *via* A~1~R [@lauro_2008; @lauro_2010].
This receptor, expressed on microglia, was also reported to be required for CX3CL1 increase in glutamate transporter 1 (GLT-1) activity in astrocytes, resulting in higher glutamate removal from the extracellular space, and thereby neuroprotective action [@catalano_2013].
Thus, these data nicely illustrate the CX3CL1-regulated local communication between microglia, astrocytes, and neurons.<!-- A neuroprotective aspect of CX3CL1 was also studied in the context of neurodegeneration. Specifically, it was shown that deletion of CX3CR1 in microglia led to increased release of IL-1 and neuronal death in such models as systemic inflammation, amyotrophic lateral sclerosis (ALS), and Parkinson’s disease (PD) [@cardona_2006].Notably, gene insertion of the only soluble variant of CX3CL1, not the membrane-anchored version, was shown to rescue motor coordination and reduce neurodegeneration in the PD model [@morganti_2012].Similarly, only upregulation of soluble CX3CL1 was reported to reduce Tau-pathology [@finneran_2019]. On the other hand, in the ischemic model, the CX3CL1 intracerebroventricular injection was shown to induce neuroprotective effects (e.g., a reduction of a lesion volume and neurological deficits) [@cipriani_2011].Again, the involvement of A~1~Rs was associated with those effects. --> 

#### Neurodevelopment 

Next milestone in neuroimmunology was the evidence that CX3CL1 and CXCL12 with their corresponding receptors exhibit highest expression during neurodevelopment, indicating their crucial functions during this period. 
Indeed, it has became increasingly evident that both CX3CL1/CX3CR1 and CXCL12/CXCR4/ACKR3 axes are crucial players during neurodevelopment<!--synonym??-->, controlling cell proliferation, migration, and survival. <!-- citations?--> 
For instance, CX3CR1^-/-^ deficient microglia during hippocampal development showed impaired migration [@pagani_2015; @paolicelli_2011].
This observation was associated with their delayed synaptic pruning, reflected as a transient reduction of synaptic density and excitatory synaptic transmission in neurons compared to their wild-type littermates, indicating immature synaptic properties [@paolicelli_2011].
Precisely, these changes were observed during the early postnatal stage (P8-P28) and then returned to baseline.<!--, highlighting CX3CR1 impact on synaptic pruning during neurodevelopment.-->
Importantly, these mice were also tested in similar experimental settings in their adulthood (P40) [@zhan_2014]. 
Although dendritic spine density remained unchanged, neurons from CX3CR1^-/-^ mice still displayed a lower frequency of mEPSCs and sEPSCs than their wild-type littermates, illustrating that a transient reduction in microglial synaptic pruning during development is sufficient to induce the long-term deficit in synaptic transmission despite unchanged the number of excitatory synapses [@zhan_2014]. <!--These data support the idea of a critical window during which microglia-mediated synaptic pruning is crucial for proper circuit maturation. -->

#### Chemokines function in the adult brain

On the other hand, those neurodevelopmental processes regulated by CX3CL1 and CXCL12 (e.i., proliferation, migration, and survival) are also present in the adult brain. 
Accordingly, CX3CL1 and CXCL12 are associated not only with developmental neurogenesis [@lysko_2011; @pujol_2005; @tran_2004], but also adult neurogenesis. <!-- Accordingly, CXC12 is found to be a key player in neurogenesis during the development of, among others, the cerebral cortex and hippocampus .// CXCL12 was also reported to guide neural progenitors [@bhattacharyya_2008; @casoni_2012; @tran_2003].-->
For example, both CXCR4 and CX3CR1 receptors are expressed on neural stem cells [@ji_2004].
The adult brain neurogenesis is restricted to two neurogenic regions, e.i., the subventricular zone (SVZ) lining the lateral ventricles and the subgranular zone (SGZ) near the dentate gyrus of the hippocampus. 
It is well established that CXCL12 is responsible for the generation and positioning of new neurons within these niches, as well as their axonal and dendritic outgrowth and branching [@abe_2015; @abe_2018; @zhu_2017].

Moreover, similar to what was observed during the neurodevelopment, in CX3CR1^-/-^ knockout mice adult-born granule neurons in the DG also displayed a reduced number of dendritic spines with additionally observed morphological changes, such as enlargement and shortening [@bols_2018]. 
Besides being ultrastructurally enlarged, synapses at both afferent and efferent levels were depleted of synaptic vesicles, suggesting impaired functionality. <!-- lepiej, ale upewnić się -->

Similarly, in addition to mentioned in previous section microglial regulation of the elimination and maturation of synapses, these cells prune synapses at both presynaptic and postsynaptic sides, thereby regulating synaptic innervation [@paolicelli_2011; @schafer_2012]. 

In addition, 

In addition, CXCL12 was shown to enhance GABAergic transmission within the DG neurogenic niche, which, in turn, is implicated in the maturation of adult neural stem cells within this structure [@bhattacharyya_2008].




Indeed, For example, in the hippocampus, CX3CL1 was demonstrated to reduce spontaneous glutamate release and the postsynaptic glutamate currents [@lauro_2008; @limatola_2005; @meucci_1998; @ragozzino_2006]. 
These effects are probably a result of PKA-related phosphorylation of GluR1 Ser845 [@ragozzino_2006].
Further investigations revealed that CX3CL1 might not exclusively act on postsynaptic neurons but also activated microglia, which in turn, released adenosine. 
Of note, sole adenosine was demonstrated to decrease the glutamatergic synaptic transmission in the hippocampus, even despite the absence of CX3CL1, suggesting adenosine tonic activity in this structure [@piccinin_2010]. 
Similar to studies concerning the neuroprotective action of CX3CL1 described above, this CX3CL1-induced adenosine action on the glutamatergic transmission was revealed to be mediated by A~3~R and, to the lesser extent, A~1~R [@lauro_2008; @lauro_2010; @piccinin_2010]. 
Further evidence indicates that the activation of A~1~R and A~3~R results in a decrease in synaptic transmission, whereas A~2A~R exerts the opposite effect, manifested as CX3CL1-induced increase of evoked EPSC (eEPSC) observed when the A~1~ and A~3~ receptors are blocked [@piccinin_2010]. 
Moreover, the A~2A~ receptor, together with D-serine release from glial cells, is also required for CX3CL1 regulation of NMDA receptor function [@scianni_2013].
Overall, several lines of evidence described above indicate a predominantly inhibitory role for CX3CL1, possibly as a component of neuroprotective synaptic scaling mechanisms, required for hippocampal memory-associated synaptic plasticity processes [@bertollini_2006; @piccinin_2010]. 

Indeed, previously described reduction of postsynaptic glutamate currents *via* dephosphorylation of GluR1 AMPA in acute brain slices is associated with long-term potentiation (LTP) and mimics long-term depression (LTD) [@bertollini_2006; @ragozzino_2006]. 
Accordingly, LTD is enhanced in CX3CR1^-/-^ mice at P13 [@paolicelli_2011], suggesting that CX3CL1 has the highest relevance during early postnatal age.
However, similar electrophysiological studies indicated either a complete lack of LTP in knockout mice [@rogers_2011] or a more pronounced LTP than in wild-type counterparts when LTP was induced by a weak stimulation protocol [@maggi_2011]. 
Interestingly, when mice were housed in an enriched environment compared to wild-type mice, they had enhanced plasticity [@maggi_2009].
These results suggest that the absence of microglia-driven CX3CR1 signaling impedes enrichment effects, possibly due to some shared mechanisms that warrant further investigation. 
However, at the network level, microglial interactions with synapses were shown to be important in regulating the maturation of neural circuits and shaping their connectivity in an activity- and experience-dependent manner, altering synaptic plasticity [@paolicelli_2011; @parkhurst_2013; @schafer_2012; @tremblay_2010; @wake_2009].

As synaptic plasticity is widely known as a molecular model of learning, the changes in synaptic plasticity correlates should results in modulation in learning and memory. 
In line with this hypothesis, behavioral studies on the CX3CL1/CX3CR1 axis in the regulation of learning and memory were giving contradictory results, reflecting changes in synaptic plasticity in the studies described above.
Briefly, CX3CR^-/-^ mice have shown impaired [@rogers_2011], improved [@maggi_2011; @reshef_2017], or unaltered [@serchov_2015] cognitive functions. 
Those discrepancies may result from differences in housing conditions, animal gender, age, or behavioral test protocols between laboratories.
However, this issue warrants further clarifications. 
It should be noted that adult neurogenesis, especially near SGZ, is linked to memory and both CX3CL1/CX3CR1 and CXCL12/CXCR4 axes were reported to be upregulated following learning [@su_2012]. <!-- dodać cytowanie z ... Consistently, after learning, the CXCR4 level was documented to be increased in CA3 .// Importantly, as adult neurogenesis is known to be an important player in memory, CXCL12 was also shown to be upregulated after learning [@su_2012]. -->
//////
Moreover, adult neurogenesis, especially in the DG, is also believed to affect memory and learning, and CX3CL1 is suggested to be implicated in those processes. <!-- lepiej to napisać --> 
Accordingly, disruption of CX3CL1/CX3CR1 signaling has harmful effects on both neurogenesis and cognition. 
Increasing studies implicated both exogenous or exercise-induced CX3CL1 in promoting neurogenesis and NSC/NPC activity in a microglia-dependent manner, whereas depletion of CX3CR1 resulted in a decreased number of newly generated neurons [@vukovic_2012; @bachstetter_2011; @rogers_2011].
In addition to microglial mediation, CX3CR1^-/-^ knockout mice were shown to significantly reduce neurogenesis, which could be reversed by IL-1`r knitr::asis_output("\U03B2")` receptor antagonist administration [@bachstetter_2011].
When behaviorally assessed, these mice displayed impaired motor learning, spatial recognition, and fear-conditioning. 
Interestingly, blocking IL-1`r knitr::asis_output("\U03B2")` signaling reversed hippocampal-dependent learning, whereas motor learning was still impaired [@rogers_2011]. 



Another aspect in relation to CX3CL1 involvement in synaptic plasticity concerns the activity of interneurons.
Importantly, CX3CL1 was shown to decrease the LTP at synapses in the DG; however, when GABA~A~ receptors were blocked, the magnitude of the LTP was enhanced [@sheridan_2014].
These results might highlight the possible modulation of CX3CL1 in regulating the balance between excitation and inhibition on the network level. 
In line with this hypothesis, CX3CL1 is also able to modulate inhibitory synaptic transmission. 
For example, beyond the hippocampus, CX3CL1 was documented to increase the amplitude of sIPSCs and eIPSC without affecting PPR, increasing the sensitivity of serotoninergic neurons to GABA inputs and consequently inhibiting 5-HT neurotransmission [@heinisch_2009; @heinisch_2011]. 
In addition, by using human tissue from epileptic patients, which is usually less responsive to the repeated activation of GABA~A~ receptors than those from healthy tissue [@ragozzino_2005], it was shown that CX3CL1 reduced this desensitization of GABA~A~ currents in cortical pyramidal neurons [@roseti_2013].

Of note, not only CX3CL1 modulates local communication and networks within a structure, but also some initial evidence implicates this chemokine in coupling between brain regions. 
Neuronal populations are thought to couple between structures, reflecting information processing, which can be quantified using coherence as a measure (for a review: @schnitzler_2005). 
In particular, by measuring connections between hippocampus and prefrontal cortex, mice with deletion of CX3CR1 revealed a decrease in the coherence between those two structures, compared to their wild-type littermates [@zhan_2014].<!-- , see Fig 4D-->
Thus, this finding suggests that the CX3CR1 knockdown leads to a decrease in hippocampal–prefrontal connectivity, which may have behavioral consequences, such as anxiety or cognitive impairments [@zhan_2014].
Moreover, knockout mice showed reduced frontal cortex oscillatory driving to the hippocampus than their wild-type littermates at baseline conditions [@zhan_2015]. 
It is speculative whether it is the consequence of morphological modifications of microglia depleted of CX3CR1 [@piirainen_2021], but scanty evidence is available so far. <!-- tutaj może poprawić tę drugą część zdania...-->

CX3CL1 regulation of synaptic plasticity is not restricted to the hippocampus. 
Briefly, this signaling molecule was shown to induce synaptic depression of evoked parallel fibers inputs onto Purkinje neurons [@giovannelli_1998], and mice with CX3CR1^-/-^ receptor deletion were characterized by the LTP in the spinal cord [@bian_2015].
These findings may be associated with CX3CL1-mediated behavioral consequences regarding motor coordination and pain [@rogers_2011; @verge_2004].

#### Behavior

Besides mentioned above behavioral phenotypes, CX3CR1^-/-^ knockout mice have been gaining attention in relation to chronic stress. 
Briefly, in comparison to wild-type littermates, CX3CR1 is essential for controlling social behavior and social dominance [@zhan_2014; @piirainen_2021]. 
However, there are many inconsistencies. 
Regarding anxiety, most studies did not show any differences between genotypes [@rogers_2011; @hellwig_2016; @schubert_2018]. 
Nonetheless, there is one study that suggests anxiolytic effects of CX3CR1 depletion [@bols_2018], whereas the other study indicates the opposite [@schubert_2018].
A similar situation was described regarding depressive-like behavior: one study indicates knockout is more depressive measured by Forced Swim Test and/or Tail Suspension Test, whereas the other reported the opposite conclusion.
It seems like the main difference between those experiments was the gender between animals.
Specifically, CX3CR1^-/-^ females are more depressive and anxiolytic than wild-type littermates, whereas the depletion of the same receptor in males elicits the opposite reaction. 
However, as this hypothesis is based only on two studies, further investigation is needed.



# CXCL12

Thus, the abovementioned findings strongly indicate that CXCL12 could modulate glutamatergic and GABAergic synaptic transmission. 
Consistently, in the cerebellum, CXCR4 activation results in a decrease in NMDAR function, and thus, leads to synaptic depression [@ragozzino_2002].<!-- , probably by CXCL12-induced reduction in NR2B expression subunit of NMDAR [@nicolai_2010]. na ile to prawda? nie bardziej aktywacja NR2B przyczynia się do LTD? sprawdzić -->
Moreover, CXCR4 receptors were shown to be presynaptically located in hippocampal noradrenergic and glutamatergic nerve endings.
They were connected with presynaptic NMDA receptors, suggesting that CXCR4-NMDAR interactions can regulate both noradrenaline and glutamate exocytosis [@diprisco_2016]. 
In addition, CXCL12 was shown to increase glutamate and GABA release in the substantia nigra (SN), the cerebellum, the hypothalamus, and the DRN [@guyon_2005; @guyon_2006; @heinisch_2010; @ragozzino_1998].
<!--CXCR4 is also widely expressed on microglia, and thus being able to react to astrocytic glutamate. najlepiej rozbudować -->
By acting on the presynaptic site, CXCL12 affects the activity of serotoninergic, dopaminergic, and melanin-concentrating hormone (MCH)-containing neurons, thereby modulating the release of neuroactive molecules [@guyon_2005; @guyon_2006; @heinisch_2010]. 
Moreover, CXCL12 is packed in small dense vesicles in the nerve terminals of these neurons, which are then released from neuronal cell bodies and terminal nerve endings in a calcium-dependent manner (for example: @bhattacharyya_2008).
However, as CXCL12 and/or CXCR4 are often co-localized with neurons releasing these signaling molecules (e.g., vasopressin, MCH, and DA<!-- dodać inne + cytowania-->), <!--together with ...., -->postsynaptic mechanisms are also suggested to be involved in this phenomenon. 
For instance, in MCH neurons, CXCR4 was described to directly modulate several voltage-dependent channels, including Na^+^ and K^+^ channels of the action potential [@guyon_2005], or tetrodotoxin-sensitive sodium currents [@guyon_2005a].

Considering that the hypothalamus, a brain region comprised of different nuclei and several neuronal populations producing neuropeptides, is critically involved in regulating major neuroendocrine functions, including water/food intake, metabolism, and stress, one could speculate that CXCL12 signaling may be involved in these functions.
In line with this notion, CXCL12/CXCR4/ACKR3 signaling dysfunctions are associated with feeding disorders, such as anorexia.
Not only a high-fat diet was reported to increase the expression of CXCL12, its receptors, and neuropeptides (e.g., enkephalin, galanin, orexin, and MCH) in the PVN and perifornical lateral hypothalamus, but also an intracerebroventricular injection of CXCL12 was shown to mimic the effects of the high-fat diet in the hypothalamus [@poon_2016]. 
These findings point to a vital role of the CXCL12/CXCR4/ACKR3 axis in feeding behavior. <!-- Both SDF-1 and GABA have been shown to regulate the rate of GnRH neuronal migration by accelerating and slowing migration, respectively. As such, this system was used to explore the mechanism by which these molecules act to produce coordinated cell movement during development. In the present study, GABA and SDF-1 are shown to exert opposite effects on the speed of cell movement by activating depolarizing or hyperpolarizing signaling pathways, GABA via changes in chloride, and SDF-1 via changes in potassium. GABA and SDF-1 were also found to act synergistically to promote linear rather than random movement. The simultaneous activation of these signaling pathways, therefore, results in tight control of cellular speed and improved directionality along the migratory pathway of GnRH neurons. -->
Importantly, depending on the concentration, CXCL12 is thought to exert opposite effects on the action potential discharge in MCH neurons [@guyon_2005], which may have functional consequences on the activity of neuroendocrine functions.
Precisely, CXCR4 was reported to be tonically active at low physiological concentrations, constantly exerting its action on MCH neurons.<!-- whereas its activation lead to ... -->
Consistently, under basal conditions, those cells showed more hyperpolarized membrane potential than orexin neurons, which do not express CXCR4 [@eggermann_2003]. 

The dopaminergic neurons in the SN are also the target of both pre- and post-synaptic actions of CXCL12. 
CXCL12 was reported to enhance the frequency of sIPSCs and mIPSCs in this region, indicating presynaptic mechanisms, which is in line with the documented presence of CXCR4 on the GABAergic neurons [@guyon_2006].
In addition, it was demonstrated that CXCL12 could act directly as a neuromodulator of dopaminergic neuronal electrical activity through the modulation of HVA currents [@guyon_2008a].
Consistent with this data, by using unilateral intranigral or intracerebroventricular injections of CXCL12, a further study has illustrated that this chemokine triggered contralateral turns in circling behavior  [@skrzydelski_2007]. 
Of note, considering that both CXCL12 and CXCR4 are co-expressed in dopamine neurons<!-- citations -->, it is tempting to speculate that this chemokine may act in an autocrine manner [@guyon_2008a].
<!--For instance, electrophysiological recordings of supraoptic neurons have demonstrated that CXCL12 decreases the electrical activity of AVP neurons *via* CXCR4, resulting in reduced AVP release [@callewaere_2006].
Importantly, These findings also elucidate that CXCL12 cognate receptor, CXCL12, may be implicated in the autocrine regulation of these neurons. -->

Interestingly, following the CXCL12 application, SN dopaminergic neurons have shown an increase in an inward current [@guyon_2006].
This effect was independent of the CXCR4 receptor, action potential-dependent sodium channel, and GABA~A~ receptors [@guyon_2006], suggesting that this chemokine may induce glutamate release from astrocytes.
Consistently, immunohistological analyses revealed that astrocytes in this structure lacked CXCR4, further supporting the possibility of astrocytic mediation [@guyon_2006]. 
Considering the abovementioned expression of another ACKR3 receptor in astrocytes, this receptor may be responsible for this CXCL12-induced increase in glutamate. 
Alternatively, it may also be mediated on CXCR4-expressing microglial cells. 
However, the exact mechanism of action of CXCL12 on glutamate release still warrants further investigation.

Unlike in the SN, astrocytes cultured from the cerebral cortex presented the high expression of CXCR4 [@cal_2008].
Upon CXCL12-induced stimulation of CXCR4 in astrocytes, (i) the Ca^2+^-dependent release of glutamate, regulated by exocytosis on a millisecond time scale [@cal_2008; @cal_2010], and (ii) the release of prostaglandins and TNF`r knitr::asis_output("\U03B1")` [@bezzi_2001].
It is widely accepted that TNF`r knitr::asis_output("\U03B1")` mediates synaptic scaling, a form of homeostatic plasticity leading to the adjustment of synaptic strength [@stellwagen_2006], and mainly astrocytes, have been identified as the main source of the TNF`r knitr::asis_output("\U03B1")` in the CNS.
Therefore, by modulating TNF`r knitr::asis_output("\U03B1")` levels, CXCL12/CXCR4 axis, by acting on glia, may participate in homeostatic activity-dependent regulation of synaptic plasticity [@stellwagen_2006].

Convincing evidence illustrates that opioid receptors and CKRs are often co-expressed in the same neuron and can directly interact, thus each influencing the function of the other. 
In this regard, the most studied mechanism is the heterologous desensitization, where the activation of one type of GPCR receptor leads to the inactivation of another GPCR receptor present in the same cell.
Consistent with this idea, following CXCL12 exposure, the heterologous desensitization of opioid receptors has been linked to functional outcomes at the cellular (e.g., reduced chemotaxis [@szabo_2002]) and electrophysiological (e.g., decreased morphine-induced hyperpolarization in PAG neurons in the presence of CXCL12 [@heinisch_2011]) levels. 
In addition, a recent study has provided extensive<!--novel?new?--> evidence that ACKR3 is a chemokine receptor with the ability to bind opioid peptides; however, opioid binding did not trigger downstream signaling through this receptor [@meyrath_2020].
Thus, it is suggested that ACKR3 serves scavenger functions for many opioids, especially enkephalins and dynorphins, by reducing their availability for their classical opioid receptors [@meyrath_2020]. 
Consistent with this idea, ACKR3 was reported to bind intermediate opioid peptides, specifically BAM22 and peptide E, which results in enhancement of circadian glucocorticoid oscillation in the adrenal glands, and, therefore, anxiolytic-like behavior [@ikeda_2013]. <!-- może poprawic albo wrocić do innej wersji? -->
BAM22 and peptide E were shown to be released under a condition named subcapsular cell hyperplasia (SCH) [@ikeda_2013], which is a pathohistological change of adrenal tissue.
SCH cells lack prohormone convertase, an enzyme required for processing these proteins to mature enkephalins [@ikeda_2013].
Therefore, this study highlights the functional relevance of chemokine and opioid systems interactions.

Finally, it is also worth noting that the profile of CXCL12-induced actions is similar to “sickness behavior”.
It is a physiological and psychological state characterized by decreased mood, anorexia, and fatigue, due to immune activation during infection, primarily mediated by peripherally released proinflammatory cytokines [@dantzer_2001; @dantzer_2007]. 
Considering that CXCL12 was shown to modulate the release of 5-HT in the DRN as well as neuropeptides in the hypothalamus, it could affect mood-related and feeding behavior, observed in depression [@maes_1998].
Thus, the effect of CXCL12 on serotonergic neurons in the DRN could underlie depressive symptoms, as dysfunction of the serotoninergic systems is implicated in depression.
<!-- Moreover, amygdala --> 

Thus, given our evolving understanding of how CXCL12/CXCR4 or CXCL12/ACKR3 are involved in the control of intercellular communication between brain cells, as well as in synaptic transmission, plasticity, and behavior, further mechanistic and theoretical understanding of their actions will undoubtedly be of great basic and translational benefit. <!-- napisać lepsze podsumowanie.... Overall, this chemokine system is one of the key players in the neuro-immune interface that shapes CNS responses to changes in the environment. While much effort has been made to investigate the mechanisms underlying CXCL12/CXCR4 or CXCL12/ACKR3-mediated regulation of synaptic transmission and plasticity and their specific properties in certain synapses and brain regions, their impact on network function and animal behavior have only been initially explored. Taken together, the relevance of the actions mentioned above of CXCL12/CXCR4/ACKR3 signaling to mechanisms implicated in many neurobiological disorders is suggestive of -->
