### Chemokine expression in the CNS cells

<!-- po signalling inny sub-chapter? -->
Interestingly, the neuroanatomical distributions of a chemokine and its receptor <!--(see below and FIG. 1)inne odwołania do figur i nie wiem czy uznawać -->overlap in many regions in the normal adult brain. 
This suggests that these chemokines, through the action on specific GPCRs, might be involved in local neuronal communication.

The effects of chemokines in the brain may be due to their ability to activate chemokine receptors localized on neurons and/or glia, thus leading to changes in neuronal membrane properties and/or synaptic transmission. 
Specifically, chemokines may alter synaptic transmitter release [@limatola_2000, @ragozzino_2002], modulate the functional properties of ionic channels [@lax_2002, @oh_2002] and promote the release of glutamate from astrocytes [@lax_2002]. 
In addition, the chemokine system can alter the actions of neuronally active pharmacological agents such as opioids and the cannabinoid system [@heinisch_2011]. 
Moreover, chemokine receptor knockout mice (CCR6, CCR7, CXCR5) have recently been shown to exhibit behavioral and neurobiological phenotypes of relevance to psychiatric disorders, which suggests their essential role in physiological conditions [@harrison_2014, @jaehne_2014, @stuart_2014].

In this thesis, CXCL12 and CX3CL1 and their receptors (CXCR4, CXCR7, CX3CR1) have been investigated, as they are both expressed constitutively, even in physiological conditions, throughout the CNS [@banisadr_2002a, @hesselgesser_1999, @schonemeier_2008].<!-- ładne przejście do kolejnych subchapterów? -->


```{r chemoexpression, results = 'asis', echo = FALSE, message= FALSE, warning=FALSE}
library(gt)
library(tidyverse)
library(gtsummary)
library(flextable)
cell_table <- read_csv("D:\\OneDrive\\articles\\Review_PharmaReports\\cell_type_table.csv")
cell_table <- cell_table %>% dplyr::rename("not_present"  = "NOT PRESENT")
cell_table <- cell_table %>% dplyr::select("Cell Type", "Chemokine Production","Chemokine Family", "Chemokine Receptor Expression", "not_present")
cell_table <- cell_table %>% dplyr::filter(is.na(not_present))
cell_table <- cell_table %>% dplyr::select(- "not_present")
cell_table <- cell_table %>% dplyr::select("Cell Type", "Chemokine Production", "Chemokine Receptor Expression", "Chemokine Family")
cell_table <- cell_table  %>% tidyr::unite("Ligand", "Chemokine Production":"Chemokine Receptor Expression", na.rm = TRUE, remove = FALSE)
cell_table <- cell_table %>% dplyr::select("Cell Type", "Ligand")
cell_table <- dplyr::arrange(cell_table, cell_table$`Cell Type`)

cell_merged <- cell_table %>%
  dplyr::group_by(`Cell Type`) %>%
  dplyr::summarise(Ligand = paste(Ligand, collapse = ", "))



if (knitr::is_latex_output()) {
  
  cell_merged  %>%
    gt(caption = "Summary of chemokine and chemokine receptor expression by different types of brain cells") %>%
#  tab_header(title="Summary of chemokine and chemokine receptor expression by different types of brain cells", label = 'tab:tab1') %>%
    opt_row_striping() %>%
   tab_source_note(source_note = md("* depicts inconsistent results <br> Based on:")) %>% # add citations
   as_latex()
  
} else {

   x <- cell_merged  %>%
    gt(caption = "Summary of chemokine and chemokine receptor expression by different types of brain cells") %>%
    opt_row_striping() %>%
   tab_source_note(source_note = md("* depicts inconsistent results <br> Based on:")) %>%
    as_raw_html()
    print(x)



} 
# else if(knitr::is_html_output()) {
# 
#    x <- cell_merged  %>%
#     gt(caption = "Summary of chemokine and chemokine receptor expression by different types of brain cells") %>%
#     opt_row_striping() %>%
#    tab_source_note(source_note = "* depicts inconsistent results <br> Based on:") # add citations
#    
#   x %>%
#   gtsummary::as_flex_table() #as_hux_table(tbl) %>% huxtable::to_latex()
#    
# }

```




Several chemokines are widely expressed throughout the CNS during development and throughout life where they have been shown to play diverse roles in cell migration and differentiation (Lu et al., 2002), regulation of cellular communication in the adult brain (Tran and Miller, 2003) and neuroprotection (Araujo and Cotman, 1993; Meucci et al., 1998; Robinson et al., 1998; Bruno et al., 2000; Limatola et al., 2000; Hatori et al., 2002; Deiva et al., 2004; Krathwohl and Kaiser, 2004; Limatola et al., 2005; Catalano et al., 2013; Shepherd et al., 2013). - Sheridan2014 <!--They have been shown functional relevance of chemokine system.-->

#### CX3CL1/CX3CR1

Moreover, unlike most chemokines, CX3CL1 is constitutively expressed in the CNS with particularly high levels in forebrain structures, including hippocampus, amygdala, cerebral cortex, globus pallidus, striatum, and thalamus (Harrison et al., 1998; Tarozzo et al., 2003). <!-- In the brainstem, a few scattered cells immunoreactive for fractalkine were initially depicted by Tarozzo and colleagues, while significant expression of the protein was subsequently observed in situ (Heinisch and Kirby, 2009; Ruchaya et al., 2012).CX3CL1 is highly expressed on hippocampal neurons in the post-natal and adult rat and declines in old age which has been linked to cognitive decline in rodents (Lyons et al., 2009).///The high basal level of CX3CL1 mRNA and protein expression in the hippocampus is suggestive of a physiological, non- inflammatory function.///Fractalkine is constitutively expressed at high levels by neurons, mostly in forebrain structures such as the hippocampus, amygdala, cerebral cortex, globus pallidus, striatum and thalamus, but also in the olfactory bulb, with almost no expression in the cerebellum, at the mRNA and protein levels in adult mouse in situ (Tarozzo et al., 2003).--> 
Besides neuronal expression of CX3CL1, few studies also detected its transcript and protein level in astrocytes, albeit at lower levels (Hulshof et al., 2003; Sunnemark et al., 2005) <!--Besides this neuronal expression, **fractalkine mRNA and protein was also shown to be constitutively expressed by astrocytes, albeit at lower levels, in adult mouse, rat and human brain in situ (Hulshof et al., 2003; Sunnemark et al., 2005). -->
Another unique feature of this chemokine is that, to date, it appears to be the only ligand of CX3CR1 receptor (Allen et al., 2007).


CX3CL1, also named fractalkine, is produced almost exclusively by neurons under physiological conditions (Paolicelli et al., 2011; Rogers et al., 2011).


In the periphery, CX3CR1 iS expressed by monocytes, dendritic cells, and natural killer cells (Imai et al., 1997; Combadiere et al., 1998; Harrison et al., 1998; Jung et al., 2000). <!-- ZMIENIĆ SCX3CR1 is ubiquitously expressed by monocytes, dendritic cells, and natural killer cells throughout the body (Imai et al., 1997; Combadiere et al., 1998; Harrison et al., 1998; Jung et al., 2000). Since these cells rarely infiltrate the brain parenchyma during normal physiological conditions, resident microglia are considered the only source of CX3CR1 expression and thus the only recipient of fractalkine signaling in the healthy brain (Jung et al., 2000; Mizutani et al., 2012).-->
However, the cell type expression pattern of CX3CR1 in the CNS remains controversial: some reports confine the localization of CX3CR1 microglia [@tarozzo_2003; @cardona_2006 <!--(Bachstetter et al., 2011; Zhan et al., 2014)-->], whereas several studies report CX3CR1 expression on neurons in vitro as well as in brain regions, including the hippocampus, raphe nucleus, nucleus of the solitary tract (NTS) and paraventricular nucleus (PVN) of the hypothalamus, amygdala, cerebral cortex, globus pallidus, striatum and thalamus (Meucci et al., 1998, 2000; Maciejewski- Lenoir et al., 1999; Hatori et al., 2002; Hughes et al., 2002; Tarozzo et al., 2003; Verge et al., 2004; Limatola et al., 2005; Zhuang et al., 2007; Heinisch and Kirby, 2009; Ruchaya et al., 2012, 2014).  <!-- zmienić drugą część zdania -->

**CX3CR1 KO**

The CX3CR1-GFP knock-in mouse line, where the CX3CR1 gene has been replaced by a green fluorescent protein (GFP) reporter (Jung et al., 2000), is one of the most common tools for studying neuron-microglia interaction under physiological conditions ((Lauro et al., 2006; Paolicelli et al.,2011)) see also: \@ref(micro_inter)). @cardona_2006, @jurgens_2012
The reasong for it is that in this model all microglial cells abundantly express GFP, resulting in an exceptional fluorescent labeling of their complex arborization, from cell body to distal processes (Tremblay et al., 2010). <!--zmienić!!!!-->
Since the CX3CR1-GFP homozygous mice (CX3CR1KO/KO) are completely devoid of microglial CX3CR1, and therefore of fractalkine signaling, comparing the heterozygous (CX3CR1KO/+) used for imaging with the homozygous mice also provides a strategy for dissecting the molecular determinants of neuron-microglia communication in a non-invasive manner (Tremblay, 2011; Wolf et al., 2013).  <!--zmienić!!!!-->
The CX3CR1-GFP heterozygous mice may be partially deficient in fractalkine signaling. <!--zmienić!!!!-->
Nevertheless, microglial morphology, dynamic surveillance (Nimmerjahn et al., 2005; Wake et al., 2009), dendritic spine turnover (Parkhurst et al., 2013), and microglial interactions with synaptic elements (Wake et al., 2009; Tremblay et al., 2010) were comparable in vivo between these CX3CR1-GFP heterozygous mice and the Iba1-GFP mice from Hirasawa and colleagues where CX3CR1 is not deleted (Hirasawa et al., 2005). - Paolicelli2014 <!--zmienić!!!!-->

### CXCL12/CXCR4/ACKR3

The first evidence that CXCL12 has effects on neurons and promotes neuroprotection were given by Meucci et al. (1998) when, for the first time, the authors demonstrated that CXCL12 reduced the apoptotic death of hippocampal neurons induced by gp120 or by glia deprivation. 
Following glia deprivation, neuroprotection was promoted by administration of CXCL12 specifically to neurons highlighting a direct activity of the chemokine on these cells. 
Further, stimulation of hippocampal neurons with CXCL12 was able to induce Akt phosphorylation and p65NF-kB nuclear translocation, both signaling implicated in pro-survival cell fate ( Khan et al., 2004 ).
Accordingly, in primary cortical neurons, CXCL12 promotes Rb function increasing its expression, nuclear localization, and transcriptional activity and reducing the excitotoxic cell death due to NMDA receptors over-activation ( Khan et al., 2008 ). 
 
CXCL12 neuroprotection is also sustained by an increase in the pro-survival signaling of synaptic NMDA receptor, and in the down-regulation of the extrasynaptic NR2B-NMDA receptor subunit (whose activity is known to mediate neurotoxicity) ( Nicolai et al., 2010 ). 
Since all the experiments presented in the above cited papers were performed using neuronal cultures with a separate astrocytes layer, it cannot be excluded that the neuroprotective effects might be also mediated by glial cells. 
Indeed, CXCL12 stimulates astrocytes promoting Akt phosphorylation ( Khan et al., 2004 ), G-protein-PI-3Kinase-ERK1/2 signaling cascade leading to cell proliferation ( Bajetto et al., 2001b ), NF-Kb activation with consequent TNFα (Han, 2001) and glutamate
 
Recently it has been reported that gliptin (Dipeptidyl-peptidase 4 DPP-4 inhibitor) improves motor functions and reduces tissue damage upon MCAO, increasing the cerebral level of CXCL12 ( Chiazza et al., 2018 ). 
Since CXCR4 antagonist reduced gliptin induced functional recovery ( Chiazza et al., 2018 ), it was speculated that CXCL12 represents  an  endogenous  modulator  counteracting  brain damage. 
The upregulation and the release of CXCL12 from astrocytes was also observed in the ischemic penumbra ( Stumm et al., 2002; Hill et al., 2004; Miller et al., 2005 ). 
In vitro, ischemia alters the expression of miRNAs associated with CXCL12 regulation, leading to increased CXCL12 expression and release from astrocytes ( Shin et al., 2014 ). 
In addition, acting on microglial cells, CXCL12 activates signaling pathways that trigger the release of IL-6 ( Lu et al., 2009 ), which has neuroprotective properties in ischemia ( Loddick et al., 1998; Ali et al., 2000; Ohtaki et al., 2006 ). 
Another novel neuroprotective activity of CXCL12/CXCR4 signaling has been identified in its ability to increase dendritic spine numbers ( Pitcher et al., 2014 ). 
In particular authors found that, in opiate abuser and in neuroAIDS patients, deregulation of CXCL12/CXCR4 is determinant to cognitive dysfunction associated with dendritic spine loss. The authors also demonstrated that CXCL12/CXCR4 regulates dendritic spine density both in vitro, in pure neuronal cultures, and in vivo, in a rat model of opiate abuse. 
CXCL12-CXCR4 signaling plays a role in neuroprotection also in Alzheimer disease: CXCL12 protected neurons from A β -induced apoptosis through the activation of Akt, ERK1/2 and the maintenance of metalloproteinase ADAM17 and, in vivo, counteracted the oxidative damage and the loss of spine density in the hippocampus (Raman et al., 2011 ). 
Furthermore, a decreased expression of CXCL12 was observed in the brain of Tg2576 and in 3XTg AD animal models at the stage of cognitive decline, as well as in brain tissue from AD patients ( Parachikova and Cotman, 2007).

CXCL12, along with their receptors CXCR4 and ACKR3, is constitutively expressed in the CNS, both during neurodevelopment and adulthood. 
These molecules are present in nearly all CNS cell types, including endothelial, glial, and notably neuronal cells (see: Fig.2).
They are widely distributed across the CNS.
Specifically, both CXCL12 and CXCR4 are co-localized with many neuropeptides, for example, in  dopaminergic neurons in the substantia nigra (SN) and the ventral tegmental area (VTA) [@guyon_2006].
Additionally, they are often co-expressed with opioid receptors in neurons and astrocytes, frequently forming heterodimers [@burbassi_2010], which implies interactions between those two systems (see Section: \@ref(opio), for review: @mlikparsadaniantz_2015). 
Likewise, recent evidence has begun to implicate ACKR3 in chemokine-opioid interactions,leading to behavioral manifestations (see: \@ref(behavior), @ikeda_2013; @meyrath_2020).



Moreover, ACKR3 and CXCR4 are co-expressed in the same neuronal [@shimizu_2011] and astrocytic populations [@odemis_2010]. 
In neurons, prominent cytoplasmic expression of ACKR3 was demonstrated, whereas CXCR4 was found on the cell membrane [@shimizu_2011], suggesting that ACKR3 may affect CXCR4 trafficking and/or coupling to other proteins [@shimizu_2011].
Consistently, ACKR3 up-regulation was shown to enhance heterodimer formation with CXCR4, which further resulted in its internalization and degeneration [@utokonomi_2013].

 In adult brain, high expression of CXCR4 has been reported in neuronal progenitor cells in the subventricular region and in the subgranular zone of the hippocampus, the two major niches of neuronal stem cells in the adult brain ( Stumm et al., 2002; Berger et al., 2007 ). The expression of CXCL12 in the hippocampal granular layer regulates the generation and the positioning of new granule neurons ( Abe et al., 2018 ), as well as axonal elongation and sprouting ( Pujol et al., 2005; Lysko et al., 2011; Su et al., 2012 ). According to its role in neurogenesis, the upregulation of CXCL12 upon stroke ( Wang et al., 2012 ), or demyelination ( Carbajal et al., 2011; Patel et al., 2012; Williams et al., 2014 ) contributes to generate new cells and to restore normal CNS functions. Postnatal development of neurons in the cortical layer V depends on CX3CL1 signaling, which regulates the release of insulin-like growth factor (IGF1) by microglia, important for survival of these neurons ( Ueno et al., 2013 ).
 
However, CXCL12 exhibits broad tissue expression including brain, thymus, heart, lung, liver, kidney,  spleen, and bone marrow. 
CXCR4 can be considered as a node which is integrating  and transducing inputs from a range of ligand-receptor interactions into a responsive  and divergent network of intracellular signaling pathways that impact multiple cellular processes such as proliferation, migration, and stress resistance.

CXCR4 is a G protein-coupled receptor (GPCR), originally  termed Fusin due to its role in cell-cell fusion12 and its expression was first described in peripheral blood leukocytes and  subsequently in hematopoietic stem cells, B-lymphocytes,  epithelial, endothelial, stromal fibroblasts, and cancer cells.13

@fumagalli_2020 - ACKR3 expressed in HEK293T cells recruits the gap junction protein Connexin 43 (Cx43). <!-- zmienić -->
Cx43 and ACKR3 are co-expressed in mouse brain astrocytes and human glioblastoma cells and form a complex in embryonic mouse brain. <!-- zmienić -->
Functional in vitro studies show enhanced ACKR3 interaction with Cx43 upon ACKR3 agonist stimulation. <!-- zmienić -->
Furthermore, ACKR3 activation promotes β-arrestin2- and dynamin-dependent Cx43 internalization to inhibit gap junctional intercellular communication in primary astrocytes. <!-- zmienić -->
These results demonstrate a functional link between ACKR3 and gap junctions that might be of pathophysiological relevance. <!-- zmienić -->

CXCL12 is another chemokine which has recently attracted much attention due to its extensive distribution in the CNS as well as the fact that it can be produced not only by glial cells but also by neurons [@banisadr_2003, @heinisch_2010a, @stumm_2002].

<!-- Unlike many chemokines whose expression is strongly up-regulated during inflammatory responses, the chemokine CXCL12 and its receptors CXCR4 and CXCR7 are constitutively and widely expressed in the developing and adult nervous system (Banisadr et al. 2002; Sanchez-Alcaniz et al. 2011; Schonemeier et al. 2008; Stumm et al. 2002; Stumm et al. 2003). -->

During embryogenesis, ACKR3 is necessary for proper migration of primordial germ cells to CXCL12 *via* CXCR4 by acting as a sink for CXCL12 <!-- (Boldajipour et al., 2008)., zmienić, in agreement with the scavenger role ...., choć nie wiem czy nie odchodzimy za bardzo od CNS--> 
<!-- another tissue development and tumors
ACKR3 is also involved in cardiac tissue development along with CXCR4 and CXCL12 (Sierro et al., 2007).
Although poorly expressed in normal adult tissues, ACKR3 is widely expressed in a variety of tumors and tumor-associated vessels and appears to promote tumor growth and neoangiogenesis partly by signaling *via* mitogen activated protein kinase (MAPK) cascades (Maksym et al., 2009). /// The ability of the CXCR4-CXCL12 axis in directing stem cell homing is probably related to its prominent role in directing the metastatic destination of tumor cells as well (Zlotnik et al., 2011) ///  -->

<!-- CXCR4 ane neurodevelopment -->
These developments underscore the important roles that CXCR4 plays in development. <!-- zmienić -->
Other studies have documented that the CXCL12-CXCR4 axis plays pivotal roles in homing of various stem cells to particular places of the embryo during development. <!-- zmienić -->
In zebrafish, a cannonical model of the developmental studies, ... More recent studies have documented the coordinated roles of CXCR4, CXCL12, and ACKR3 in the development of the central nervous system in the zebrafish (Diotel et al., 2010; Tiveron and Cremer, 2008). <!-- zmienić -->
Thus, certain homeostatic chemokine receptors play key roles in the homing of various stem cells. <!-- zmienić -->
In the developing and mature brain, virtually all types of CNS cells such as neural progenitors, neurons, microglial cells, and astrocytes as well as endothelial cells of brain blood vessels are targets for CXCL12 (Li and Ransohoff, 2008). <!-- ŁADNE ZDANIE ALE TROCHĘ ZMIENIĆ -->
Developmental aspects controlled by CXCL12 in the CNS include cell proliferation, migration, and (neuronal) cell survival (Li and Ransohoff, 2008). <!-- zmienić -->

<!--cxcl12 functions-->
A recognized function of CXCL12 in the mature CNS is the control of intercellular communication between brain cells (Bezzi et al., 2001; Rostene et al., 2007). 
In the injured CNS, CXCL12 regulates inflammatory processes (Cartier et al., 2005; Li and Ransohoff, 2008) and promotes tissue regeneration by recruiting neural progenitor cells to the site of injury (Tran et al., 2007).


   Banisadr 2016: ACKR3 in the brain (Schönemeier et al. 2008a , b ; Shimizu et al. 2011 ). Knowledge of the precise expression pattern and characterization of cells expressing ACKR3 is required to further explore the function of ACKR3 in the brain. It is well established that CXCL12/CXCL12 is constitutively expressed by endothelial and neuronal cells in various regions of the adult rat brain (Tham et al. 2001 ; Stumm et al. 2002 ; Banisadr et al. 2003 ) and the expression patterns of CXCL12/CXCL12 and CXCR4 have been well established in structures associated with various functions such as their role in adult neurogenesis and neuroinflammation among other functions (Banisadr et al. 2002 ; Stumm et al. 2002 ; Tissir et al. 2004 ;Tranetal. 2007 ).
   
   Subsequent worked suggested that ACKR3 can act to preserve CXCL12 gradients and CXCR4  sensitivity to CXCL12 62 as well as to enable tighter control of such gradients and of cell migration, for example,  for guidance of interneurons in the cortex and of B cells  in diffuse large B-cell lymphoma.63-65 
   
   CXCL12, a chemokine, is  involved in primordial germ cell migration (Blaser et al., 2005),  migration of neural progenitors (via its receptor CXCR4) and axon  growth and branching during development of the nervous system  (Tran and Miller, 2003; Pujol et al., 2005). 
Recent work has shown  that GABA and CXCL12 may act synergistically to alter cell  movement (Seidel et al., 2007; Bhattacharyya et al., 2008). [@casoni_2012]

CXCL12 has been shown to act in the brain as a neurotransmitter  (Banisadr et al., 2005) and to be released with GABA from  inhibitory neurons (Bhattacharyya et al., 2008). However, [@casoni_2012]

CXCL12 induced changes in saltatory GnRH movement  were shown to occur through a GIRK dependent mechanism.  GIRK channels open via a signal transduction cascade triggered  by the G  bc  dimeric protein released by activated G protein-  coupled receptors (Dascal, 1997; Yamada et al., 1998). Opening  of the GIRK channel results in permeability to potassium ions  and hyperpolarization of the cell. To date, only melanin-  concentrating hormone neurons (involved in feeding behavior  regulation) have been shown to respond to CXCL12 directly  through GIRK current activation and in these cells, CXCL12  influenced neuronal activity (Guyon et al., 2005). [@casoni_2012]

Finally, we addressed the striking mismatch between intense CXCR4 mRNA expression (Stumm et al., 2002, 2003; Tissir et al., 2004; Tran et al., 2007) and weak CXCR4 protein expression in the SGL (Stumm et al., 2002).
Studies in non-neuronal cell lines showed that CXCR4 is sequestered from the cell surface (internalized), sorted to lysosomes, and degraded after agonist stimulation (Orsini et al., 1999; Marchese and Benovic, 2001). Therefore, the mismatch between CXCR4 mRNA and CXCR4 protein in the SGL may reflect tonic activation and turnover of CXCR4 by endogenous CXCL12
   

#### Functions in the CNS

##### Neurodevelopment
In physiological conditions, CX3CL1/CX3CR1 signaling is involved in different neural functions both in development (participation in functional maturation of neuronal circuits driving cell positioning) and adulthood (regulation of synaptic plasticity and cognitive functions) [@lauro_2015]. <!-- zmienić -->

##### Adult 



###### Electrophysiological effects

Indeed, there is mounting evidence which implicates both CX3CL1 and its receptor, CX3CR1, in synaptic plasticity and neuromodulation (Bertollini et al., 2006; Ragozzino et al., 2006; Piccinin et al., 2010; Maggi et al., 2011; Rogers et al., 2011; Roseti et al.,2013; Scianni et al.,2013). <!-- zmienić // In fact, CX3CL1 is a confirmed inhibitor of basal glutamate synaptic activity in the hippocampus [@Bertollini2006]. -->

Regarding electrophysiological effects of CX3CL1 action, hippocampus is the most documented structure, as it has most-known network // a golden structure for electrophysiologist, with high basal levels of CX3CL1 transcript and protein expression. <!-- zmienić The high basal level of CX3CL1 mRNA and protein expression in the hippocampus is suggestive of a physiological, non-inflammatory function. -->
For example, CX3CL1 has been shown to reduce post-synaptic glutamate currents (Meucci et al., 1998; Limatola et al., 2005), involving an increased intracellular calcium and dephosphorylation of the GluR1 AMPA receptor subunit on serine 845 (Ragozzino et al., 2006). <!-- zmienić jeszcze trochę -- SPRAWDZIĆ spontaneous glutamate release and-->
The latter mechanism has been linked to ability of CX3CL1 to inhibit LTP and mimocs long-term depression (LTD) at the CA3–CA1 synapses in acute hippocampal slices (Bertollini et al., 2006; Ragozzino et al., 2006; Maggi et al., 2009).  <!-- zmienić CX3CL1-mediated regulation of glutamate transmission has been shown to be due to its post-synaptic effects on neurons and involves the dephosphorylation of the GluR1 AMPA receptor subunit on serine 845, a mechanism reminiscent of LTD (Ragozzino et al., 2006). //Previous studies have shown that CX3CL1 inhibits LTP and mimics long-term depression (LTD) at the CA3–CA1 synapses in acute hippocampal slices (Bertollini et al., 2006; Ragozzino et al., 2006; Maggi et al., 2009). -->
LTD can play vital roles in the context of memory-associated synaptic plasticity including synaptic scaling and enhanced signal-to-noise ratio mechanisms <!-- CITATION, ZMIENIĆ -->
These synaptic effects are consistent with a direct action of CX3CL1 on neurons most likely exerted through the CX3CR1 receptor, which is reportedly expressed on the dendrites of hippocampal neurons (Meucci et al., 2000; Limatola et al., 2005). <!-- zmienić -->
The ability of CX3CL1 to inhibit glutamate function is thought to be responsible for some of its neuroprotective actions, and provides further support for the chemokine-neuromodulatory role in the CNS [@adler_2005, @callewaere_2007, @guyon_2007]. <!-- not sure if it is my sentence Overall, previous studies indicate a predominantly inhibitory role for CX3CL1, perhaps as a component of neuroprotective synaptic scaling mechanisms necessary for hippocampal memory-associated synaptic plasticity processes (Bertollini et al., 2006; Turrigiano, 2008; Piccinin et al., 2010).-->
Consistent with this hypothesis, neuroprotective ADAM17-mediated increase in in soluble CX3CL1 is observed in multiple settings of glutamatergic neurotransmission where the chemokine is suggested to performa neuroprotective function (Chapman et al., 2000; Tsou et al., 2001; Erichsen et al., 2003; Limatola et al., 2005; Ragozzino et al., 2006; Lauro et al., 2010; Pabon et al., 2011). <!-- zmienić-->

Beyond the hippocampus, CX3CL1 is also documented to reduce the activity of serotonergic neurons in the raphe nucleus through enhanced GABA~A~ receptor-mediated inhibition (Heinisch and Kirby, 2009).<!-- zmienić trochę drugą część -->



LTP-inducing TBS resulted in an up-regulation in CX3CL1 expression after 2 h on the stimulated DG blade compared to the upper unstimulated blade. - Sheridan2014

**DOSE**
At levels reached during inflammatory conditions, CX3CL1 signaling has previously been associated with activation of pro-survival and anti-apoptotic pathways through phosphorylation of molecules such as Akt, as well as activation of MAP kinases such as p-38 and Erk1/2 (p44/42; Maciejewski-Lenoir et al., 1999; Meucci et al., 2000; Cambien et al., 2001; Deiva et al., 2004; Klosowska et al., 2009; Lyons et al., 2009)

While previous studies have shown that CX3CL1 causes an increase in intracellular calcium in neurons and other cell types (Oh et al., 2002; Deiva et al., 2004; Ragozzino et al., 2006) this effect of CX3CL1 becomes apparent at concentrations of 25 nM and higher (Oh et al., 2002; Deiva et al., 2004), well above the levels we investigated here and we observed no such increase in intracellular calcium. At a concentration of 2 nM, in both neurons and non-neurons, CX3CL1 pre-incubation suppressed glutamate-mediated rises in intracellular calcium levels. These data are in good agreement with previous findings of a protective effect of inflammatory levels of CX3CL1 against glutamate excitotoxicity and glutamate NMDA receptor activation, in particular (Meucci et al., 1998; Deiva et al., 2004; Limatola et al., 2005), although, unlike the current work, the latter effect was linked to increased intracellular calcium (Ragozzino et al., 2006). Calcium oscillations in both neuronal and non-neuronal cells are important for cellular growth, migration and synaptic structural refinement (Katz and Shatz, 1996; Komuro and Rakic, 1998; Spitzer et al., 2000). Thus, the dampening of such signaling by CX3CL1 is suggestive of a role in stability of network connectivity and activity. Overall, the current data along with information in the published literature reveal that a role for CX3CL1 in control of glutamate-mediated excitatory neurotransmission during excitotoxic events can be extended to situations of synaptic plasticity required for normal functions such as memory formation.

CX3CL1 has been reportedly up-regulated in several settings of augmented glutamatergic transmission where the chemokine is clearly protective against excitotoxic cell death (Tong et al., 2000; Tarozzo et al., 2002; Limatola et al., 2005; Cipriani et al., 2011; Briones et al., 2014). Moreover, both CX3CL1 and its receptor, CX3CR1, have been shown to be up-regulated in hippocampal neurons after pilocarpine-induced status epilepticus (Yeo et al., 2011), a condition characterized by excessive glutamatergic excitation. Overall, the abundance and expression pattern of CX3CL1 make the chemokine ideally suited for sensing hippocampal glutamate tone. Our data supports a possible role for CX3CL1 in homeostatic mechanisms of synaptic scaling during memory-associated synaptic plasticity.-Sheridan2014

**GABA A**
The GABA~A~ receptor/chloride channel blocker, picrotoxin, used in the current studies would decrease GABAergic inhibitory transmission promoting depolarization in some cells with corresponding increases in intracellular calcium (Antonucci et al., 2012). Thus, the current work suggests GABA~A~ receptor/chloride channel activity within the hippocampal neuronal network must be intact for CX3CL1 to attenuate glutamatergic neurotransmission or LTP. 
This situation is remarkably similar to that described for CX3CL1 inhibition of serotonergic neurons of the Raphe nucleus (Heinisch and Kirby, 2009). While this effect may relate to basal inhibitory tone, CX3CL1 could actually be enhancing GABAA receptor function. For example, CX3CL1 enhances phosphorylation and activation of Akt in neurons and this serine/threonine kinase has been associated with phosphorylation of the GABAA beta2 receptor subunit, a modification that enhances activity of the receptor (Meucci et al., 2000; Wang et al., 2003). Moreover, several signaling systems can enhance GABAmediated inhibition through promotion of rapid insertion of GABA~A~ receptors into the post-synaptic plasma membrane (Wan et al., 1997; Nusser et al., 1998; Mizoguchi et al., 2003; Jovanovic et al., 2004) - Sheridan2014



####### Microglia
it is believed that the binding of soluble CX3CL1 to its receptor CX3CR1 maintains microglia in a ‘‘resting” or ‘‘off” state (Bachstetter et al., 2011; Valero et al., 2016), although chemoattractant properties have been demonstrated for the membrane-bound form of CX3CL1 (Lauro et al., 2006; Song et al., 2013).Accordingly, microglia of CX3CR1-/- mice show impaired migration during development (Pagani et al., 2015; Paolicelli et al., 2011), together with a partially activated phenotype during adulthood (Reshef et al., 2014). -Bolos2018

Recently it has been established in vitro and in vivo, that the acute activation of dorsal horn microglia by inflammaory insult or sciatic nerve impairments result in a release of CatS from microglia, which liberates FKN from dorsal horn of spinal cord neurons (Clark and Malcangio, 2012; Clark et al., 2010, 2009). 

###### Behaviour
Of note, there is great controversy regarding the behavioral phenotype of *CX3CR1-/-* mice in the literature (Paolicelli et al., 2014). For instance, reports of impairment (Rogers et al., 2011), improvement (Maggi et al., 2011; Reshef et al., 2014) or no changes (Serchov et al., 2015) in hippocampal-dependent learning have been reported. In each study involving behavioral studies with these animals, the relevance of housing conditions, animal gender and age, feeding and behavioral test protocols is brought to light (Gemma and Bachstetter, 2013). Regarding the regulation of emotional behavior, previous evidence shows that the connectivity of brain regions involved in the regulation of mood disorders is impaired in CX3CR1-/- animals (Squarzoni et al., 2014). Although other authors detected no depressive-like phenotype of these mice in the sucrose preference (Milior et al., 2016) or in the TST (Hellwig et al., 2016), male and female animals were grouped and tested together. Here we report that 4-month- old female CX3CR1-/- mice show a hyperactive, anxiolytic-like and depressive-like phenotype, in agreement with previous data indicating altered social behavior in these mice (Zhan et al., 2014). Interestingly, although stress resilience has been described in CX3CR1-/- mice (Rimmerman et al., 2017; Yirmiya et al., 2015), other authors found that these animals show greater depressive- like behavior in response to inflammation compared to WT coun- terparts (Corona et al., 2013). - Bolos2018

Several behavioral comorbidities, such as anxiety, depression, and other mood disorders, commonly occur in mice with CX3CR1 deletion.

<!-- unused sentences:
The full-length molecule is also larger than most other chemokines, containing approximately 373 amino acid residues compared to the more common 70–80 amino acid size. // The 95 kDa full-length protein is a type I transmembrane protein consisting of  N-terminal chemokine domain, a 241-amino acid glycosylated mucin-like stalk, an 18-amino acid transmembrane region and an intracellular C- terminal domain.
It is converted to a soluble form on cleavage from the plasma membrane, through the action of metalloproteinases  (ADAM 10 and ADAM17 on leukocytes) (Hundhausen et al., 2003) or  cysteine protease Cathepsin S (CatS) which is expressed and released by microglial cells in the spinal cord (Clark et al., 2007; Meucci et al., 2000; Ransohoff, 2002).
The approximately 70 kDa soluble N-terminal chemokine domain can be released from the full-length protein via the action of several metalloproteinases such as cathepsin S, ADAM10, and ADAM17 (TACE: TNF-α-converting enzyme) in both the periphery and CNS (Garton et al., 2001; Hundhausen et al., 2003; Clark et al., 2007; Cook et al., 2010; Jones et al., 2013). 


The high basal level of CX3CL1 mRNA and protein expression in the hippocampus is suggestive of a physiological, non-inflammatory function. Indeed, there is mounting evidence which implicates both CX3CL1 and its receptor, CX3CR1, in synaptic plasticity and neuromodulation (Bertollini et al., 2006; Ragozzino et al., 2006; Piccinin et al., 2010; Maggi et al., 2011; Rogers et al., 2011; Roseti et al.,2013; Scianni et al.,2013). For example, CX3CL1 has been shown to reduce spontaneous glutamate release and post-synaptic glutamate currents (Meucci et al., 1998; Limatola et al., 2005). The latter effect has been linked to increased intracellular calcium and dephosphorylation of the GluR1 AMPA receptor subunit (Ragozzino et al., 2006). These synaptic effects are consistent with a direct action of CX3CL1 on neurons most likely exerted through the CX3CR1 receptor, which is reportedly expressed on the dendrites of hippocampal neurons (Meucci et al., 2000; Limatola et al., 2005). Overall, previous studies indicate a predominantly inhibitory role for CX3CL1, perhaps as a component of neuroprotective synaptic scaling mechanisms necessary for hippocampal memory-associated synaptic plasticity processes (Bertollini et al., 2006; Turrigiano, 2008; Piccinin et al., 2010). Consistent with this hypothesis, neuroprotective ADAM17-mediated increase in in soluble CX3CL1 is observed in multiple settings of glutamatergic neurotransmission where the chemokine is suggested to performa neuroprotective function (Chapman et al., 2000; Tsou et al., 2001; Erichsen et al., 2003; Limatola et al., 2005; Ragozzino et al., 2006; Lauro et al., 2010; Pabon et al., 2011). -Sheridan2014

Given the essential role played by the CX3CL1/CX3CR1 axis in neuron-microglia communication, the CX3CR1-GFP knock-in mouse line where the CX3CR1 gene has been replaced by a green fluorescent protein (GFP) reporter (Jung et al., 2000), represents one of the most important tools for studying microglial involvement in the healthy brain []. (Lauro et al., 2006; Paolicelli et al.,2011) // have been used extensively to study this cross-talk mechanism
Furthermore, fractalkine seems to play an essential role in a unique neuronal-glial interaction between neurons and CX3CR1-expressing microglia under normal and pathological states.

end -->


Post-synaptic modulation of GABA-A receptors has been reported for CX3CL1 onto serotoninergic neurons in the dorsal raphe and cortical neurons ( Heinisch and Kirby, 2009; Roseti et al., 2013 ). At Schaffer's collateral-CA1 pyramidal neurons CX3CL1 depresses AMPA-mediated currents with a mechanism that involves inhibition of forskolin-induced Ser-845 GluR1 phosphorylation ( Ragozzino et al., 2006 ), whereas it enhances NMDAmediated neurotransmission via adenosine A2A subtype activation and D-serine release by glial cells ( Maggi et al., 2009; Scianni et al., 2013 ). In the same area it has been reported that: i) CCL2 exerts pre-synaptic effects increasing the release of glutamate onto CA1 pyramidal neurons ( Zhou et al., 2011 ); ii) CXCL16 enhances both the release of glutamate and GABA, requiring adenosine type 3 receptor (A3R) and microglia activation ( Di Castro et al., 2016 ). <!-- Trettel 2020-->

CX3CL1 is a trans-membrane chemokine highly expressed by neurons and present in a soluble form upon cleavage by metalloproteases such as ADAM10, 17 ( Garton et al., 2001; Hundhausen et al., 2003 ), catepsin-S and γ -secretases ( Clark et al., 2007; Schulte et al., 2007; Fonovic et al., 2013 ). Both trans-membrane and soluble CX3CL1 forms bind a unique receptor CX3CR1, with possible differences in affinity and activity ( Biber et al., 2007 ). The discovery of the specific expression of CX3CR1 in microglial cells ( Cardona et al., 2006 ) opens to the perspective that CX3CL1 is implicated in neuron – microglia cross-talk and in the control of microglia activity ( Biber et al., 2007 ). 

In 2000, Zujovic et al. reported for the fi rst time that exogenous CX3CL1 restrained LPS-microglia activation in vitro, and that neutralization of endogenous CX3CL1 in hippocampal cultures increased the neurotoxic action on neuronal cells. Accordingly, in vivo neutralization of endogenous CX3CL1 potentiated LPS effects in the brain ( Zujovic et al., 2000 ). Later, Mizuno et al. (2003) reported the reduction of IL-6, NO and TNFα production by microglia stimulated with LPS upon CX3CL1 treatment, and a reduced neuronal cell death. Boehme et al. (2000) showed that CX3CL1 reduced FAS-mediated microglia cell death activating PI-3 kinase/PKB pathway, and modulating both the levels and the activation states of Bcl-2 family member proteins. In animal models, knocking down CX3CR1 signaling exacerbated microglia over-activation, increasing the release of IL-1 β and apoptotic neuronal cell death in mice injected with LPS, and increased neuronal cell loss in PD and ALS mouse models ( Cardona et al., 2006 ). In cx3cl1 − / − mice, the Adeno-Associated Virus (AAV)-mediated gene insertion of either soluble or membrane bound synthetic variant of CX3CL1 demonstrated that, in a MPTP- model of PD, only the soluble form rescued motor coordination, reduced neurodegeneration and microglia activation ( Morganti et al., 2012 ). A role for endogenous CX3CL1 in the attenuation of a pro-in fl ammatory phenotype was also reported in a mouse model of Tauopathy ( Lastres-Becker et al., 2014 ). Recent data show that only the over-expression of a speci fi c cleavage variant of the soluble CX3CL1 reduced Tau-pathology ( Finneran and Nash, 2019 ). 

 In hippocampal cultures, CX3CL1 reduced neuronal cell death due to gp120- or glutamate overexposure ( Meucci et al., 2000; Limatola et al., 2005 ). Microglial cells treated with CX3CL1 release soluble factors that promote neuroprotection in mixed hippocampal neuron – glia cultures. Among them adenosine modulates CX3CL1 neuroprotection through the activation of adenosine A1 receptor subtype (A1R) ( Lauro et al., 2008, 2010 ). Acting on microglia, CX3CL1 indirectly modulates the activity of glutamatetransporter 1 (GLT-1) on astrocytes, with higher glutamate removal from the extracellular space, and this effect requires the function of A1R ( Catalano et al., 2013 ). In a pMCAO rat model, i.c.v. injection of soluble CX3CL1, 30 min after ischemia, has long lasting protective effects, reducing lesion volume and neurological de fi cits, again with the involvement of active A1Rs ( Cipriani et al., 2011 ).
 
 CX3CL1-mediated neuroprotection and neuromodulation may also require the activity of adenosine-type 2 a receptors (A2ARs). Scianni et al. (2013) demonstrated that CX3CL1 modulates the NMDA glutamate receptor function and that this effect involves the release of D-serine from glial cells, and the activity of A2AR subtype. Altogether these data describe a mechanism by which CX3CL1, via A2AR and Dserine, and likely modulating synaptic NR2A/NMDARs, induced CREB phosphorylation, upregulation and release of BDNF, resulting in neuroprotection and neuromodulation ( Lauro et al., 2015). 
 
  However, its constitutive expression in different CNS cells ( Ludwig et al., 2005; Rosito et al., 2012 ) suggests additional roles in mediating cell-to-cell communication.
  
  

Fractalkine is the only member of the CX3C chemokine family and, unlike many other chemokines, shares a one-to-one  relationship  with  its  cognate  receptor, CX3CR1 [46,47]. CX3CR1 is a G protein-coupled receptor (GPCR) that signals through the Gq pathway, in turn  activating  PI-3  kinase  pathway  [48].  FKN  is expressed in neurons and peripheral endothelial and its receptor is produced by myeloid cells (including microglia), T cells, and natural killer cells [49,50]. FKN is a type I transmembrane protein with an N-terminal chemokine domain attached to a long, highly glycosylated mucin-like stalk with a short membrane-spanning domain and intracellular domain. FKN can be cleaved by a disintegrin and metalloprotease (ADAM) 10, ADAM 17, and cathepsin S to generate a soluble fragment [2–4] (Fig.1). Both the membrane-bound and soluble forms of FKN are capable of signaling through CX3CR1, although there may be differences in affinity and biological activity between these two ligands [1]. In the periphery, membrane-bound FKN can promote adhesion of monocytes to endothelial cells, and the soluble ligand can cause chemotaxis of monocytes, T cells, and natural killer cells [51,52]. Genetic ablation of FKN causes reduced monocyte survival and reduced ability of CX3CR1+macrophages to sense the gut lumen [53]. Expression of the chemokine domain of FKN was sufficient to rescue survival of certain populations of monocytes  

Generation of a reporter mouse, replacing endogenous Cx3cr1with a green fluorescent protein (GFP) reporter under control of theCx3cr1promoter, demonstrated  that  CX3CR1  expression  is  restricted  to microglia in the CNS [12,59]. This reporter line has been used extensively to investigate the impacts of disrupting FKN signaling from the developing to the aged brain. In development, CX3CR1 deficient mice were  observed  to  have  delayed  synaptic  pruning. Microglial number was transiently reduced inCx3cr1 −/−mice compared to wild-type controls while the number of dendritic spines was increased. This indicates that CX3CR1 deficiency may delay maturation of synapses by delaying engulfment during development [60]. In the adult brain, CX3CR1 has been identified as necessary for layer V cortical neuron survival [61]. These findings implicated FKN signaling in normal brain development and homeostasis but ablation of CX3CR1 also affects cognition.

Disruption of FKN signaling has deleterious effects on both neurogenesis and cognition.Cx3cr1−/−mice were found to have a significant reduction in neurogenesis, which could be reversed by IL-1 receptor antagonist administration [62]. When behaviorally assessed, these mice were found to have motor learning impairments, spatial recall impairments, and fear-associated recall impairments. These cognitive impairments were associated with reduced synaptic plasticity. Antagonism of IL-1β signaling successfully reversed hippocampal-dependent learning but not motor learning [63]. Disruption of FKN signaling has also been studied in the context of neurodegenerative disorders. In a seminal paper, Cardona et al. [12] described the impact of CX3CR1 knock out in several models of neurodegeneration. Broadly, they found that microglia lacking CX3CR1 are cytotoxic in models of systemic inflammation, amyotrophic lateral sclerosis (ALS), and Parkinson’s disease (PD). Mice lacking CX3CR1 were more susceptible to neuron loss upon systemic injection of LPS. Furthermore, adoptive transfer ofCx3cr1−/−microglia from LPS-challenged mice into wild-type mice also produced neurotoxicity in the area of the injection site. Interestingly, microglia lacking CX3CR1 did not migrate away from the injection site whereas microglia with intact CX3CR1 signaling migrated from the injection site. Inhibition of IL-1βsignaling blocked the neurotoxic effects of and restored the migratory capacity ofCx3cr1−/− microglia. Similarly, in the SODG93Amouse model of ALS, disruption of FKN signaling caused greater neuron loss, reduced hindlimb strength, and shortened lifespan. In a toxic model of PD, loss of FKN signaling by knocking out either the receptor or the ligand resulted in significantly greater neurotoxicity [12]. 

<!-- Finneran_2019-->

the CX3CL1 transmembrane form is cleaved by ADAM10 and ADAM17 proteases into its soluble variant (see: Figure 2A). <!-- Another fundamental finding was that upon stimulation, neurons from sensory pathways are able to cleave the membrane-attached CX3CL1 and release the soluble chemokine (Milligan et al. 2004).--><!-- These  findings indicate  that  the  cleavage  of  transmembrane  chemokines  into  their soluble  chemotactic  variants  may  have  an  important  role  in  the regulation of inflammation in human - CX3CL1 --><!-- The post-translational expression of CX3CL1 may be conditioned by the following factors: BBB and BSCB dysfunction, proteolytic cleavage by ADAM10 and ADAM17 proteases, rapid binding to CX3CR1, and penetrating between three compartments including the extracellular space, CSF, and circulating blood [156,197,198]. @poniatowski_2016--><!-- The regulation of the activation and functioning of the CX3CL1/CX3CR1 axis encompasses the control at the level  of transcription and also regulation during post-translational modifications.-->
It is thought that this dynamic proteolytic cleavage of CX3CL1 is a response to neurotoxic insult and serves anti-inflammatory functions [@chapman_2000]. <!-- dodać jeszcze jakieś inne jak znajdę --><!-- 
These  data  strongly  suggest  that  dynamic proteolytic cleavage of fractalkine from neuronal membranes in response to a neurotoxic insult, and subsequent chemoattraction of reactive immune cells, may represent an early event in the inflammatory response to neuronal injury. - @chapman_2000--><!-- These  data  strongly  suggest  that  dynamic proteolytic cleavage of fractalkine from neuronal membranes in response to a neurotoxic insult, and subsequent chemoattraction of reactive immune cells, may represent an early event in the inflammatory response to neuronal injury. - @chapman_2000-->

There is some evidence that different fragments of the FKN ligand may have different functional outcomes. Fractalkine signaling has been implicated in neuropathic pain in spinal injury models [77–79]. In these studies, neuropathic pain in injury models was alleviated by antibody antagonization of CX3CR1, and in non-injured rats neuropathic pain was induced by activation of CX3CR1 with intrathecal injections of exogenous fractalkine peptide comprising just the chemokine domain. Furthermore, Clark and Malcangio [15] show that infusion of this chemokine peptide of FKN (ckFKN, Fig.1) elicits mechanical allodynia, while infusion of sFKN (which contains the full mucin-like stalk, Fig.1) does not. They also demonstrate a difference in calcium mobilization upon binding between these two fragments. Interestingly, it has been identified that cathepsin S is necessary for the production of pain-inducing FKN in a spinal injury  model  [2,77].  In  silico  analysis  of  substrate [@finneran_2019]
preference of cathepsin S indicates membrane-bound FKN as a potential substrate [77,80–82] and a recent study published that cathepsin S cleaves membrane bound FKN to generate a soluble fragment that migrates at  a  lower  apparent  molecular  weight  than  the ADAM10/17 cleavage product [83]. These data suggest that removal of the mucin-like stalk (either partially or in whole) may alter the microglial response to FKN, which can elicit different effects and/or microglial phenotypes depending on the identity of the soluble ligand.
...
 These data may indicate that the form of the  soluble  fragment  (with  or  without  the  mucin stalk) affects how the  chemokine signals  in these
 neurodegenerative models and that proteolytic cleavage could be a mechanism for regulation of fractalkine  activity  in  vivo.  More  research  is  needed  to determine if there are differential effects of these soluble  FKN  variants  and  how  this  could  regulate neuroinflammation. 
 
 Consistent with its effect on CREB signaling, Ccr5 knockout resulted in enhanced long-term potentiation (LTP) in hippocampal CA1, and both Ccr5 knockout and knockdown enhance performance in contextual fear conditioning, Morris water maze, and social recognition paradigms (Frank et al., 2018; Kalkonde et al., 2011; Zhou et al., 2016). Similar to genetic ablation of Ccr5, pharmacological inhibition of CCR5 
 
CX3CL1  is  neuroprotective  against  Glu-induced  excitotoxicity, with  mechanisms  fully  dependent  on  A1 R  (Lauro  et  al.,  2008, 2010)  and  in  part  dependent  on  A 3 R  (Rosito  et  al.,  2014). CX3CL1  also  protects  neurons  against  NMDA-induced  death (Deiva  et  al.,  2004),  but  no  evidence  of  ARs  involvement  are reported   so   far. @lauro_2014

Adenosine is a metabolite that acts through different receptor subtypes (Jacobson and Gao, 2006); among them A 1 R (Lauro et al., 2008, 2010) and A 3 R (Rosito et al., 2014) are involved in CX3CL1 neuroprotection against Glu-induced toxicity. Moreover we  previously  demonstrated  that  CX3CL1  triggers  the  release of  adenosine  from  neuronal  and  microglial  cells  (Lauro  et  al., 2008,  2010). 

CX3CL1 is a trans-membrane chemokine highly expressed by neurons and present in a soluble form upon cleavage by metalloproteases such as ADAM10, 17 ( Garton et al., 2001; Hundhausen et al., 2003 ), catepsin-S and γ -secretases ( Clark et al., 2007; Schulte et al., 2007; Fonovic et al., 2013 ). Both trans-membrane and soluble CX3CL1 forms bind a unique receptor CX3CR1, with possible differences in affinity and activity ( Biber et al., 2007 ). The discovery of the specific expression of CX3CR1 in microglial cells ( Cardona et al., 2006 ) opens to the perspective that CX3CL1 is implicated in neuron – microglia cross-talk and in the control of microglia activity ( Biber et al., 2007 ). 


### Chemokines modulate neuron-glia cross-talk

## Neuro-glial interactions  {#glia_inter} 

Chemokines are key molecules in neuron-microglia communication in the developing and mature brain under both physiological and pathological conditions (de Jong et al., 2005). Fractalkine is an important neuron-microglia chemokine signal. - Pagani2015

A fundamental property of the mammalian brain is its ability to modify its function based on experience, and thereby to alter subsequent behavior. By changing the strength of transmission at preexisting synapses, transient experiences can be incorporated into the neuronal circuits as persistent memory traces during both development and adulthood. As such, synaptic plasticity is a fundamental mechanism that supports brain function (Buzsáki and Chrobak, 2005). Among the different factors that regulate synaptic plasticity, glial cells have been found to be key players in maintenance of synapse homeostasis (Eroglu and Barres, 2010). The biggest challenge when studying the effects of glial cells on brain activity is isolating the different cell-type components, i.e., neurons vs. glia. Recent research advances using various strategies, such as pharmacological or genetic manipulation and gene expression from viral vectors (Nimmerjahn and Bergles, 2015; Oliveira et al., 2015; Ben Haim and Rowitch, 2017), have allowed researchers to elucidate the role of glial cells in several aspects of brain function, and such knowledge may lead to the development of new therapies and biomarkers for many types of neurological dysfunction (Almad and Maragakis, 2018). [@mederos_2018]<!-- use all of the review -->

Functional and molecular analysis of glial voltage- and ligand-gated ion channels underwent tremendous boost over the last 15 years. The traditional image of the glial cell as a passive, structural element of the nervous system was transformed into the concept of a plastic cell,  capable  of  expressing  a  large  variety  of  ion  channels  and  neurotransmitter receptors.  These  molecules  might  enable  glial  cells  to sense neuronal activity and to integrate it within glial networks, e.g., by means of spreading

Among the many strategies used by cells to communicate one with another, the repertoire of chemokines constitutes one of the most tightly regulated systems. <!--zmienić -->
Often, a particular cell type is uniquely expressing the ligand for a receptor that is selectively found on another cell type, thereby conferring a high degree of specificity to the ensuing signaling [@allen_2007; @rossi_2000; @zlotnik_2000; @zlotnik_2012]. <!--zmienić -->
Recently, in the light of the "glial revolution", our long-held views of the functions of both of these cells were completely challenged. 
<!--Accordingly, another layer of complexity to neuronal information processing is added by astrocyte and microglia actions at synapses. 
 Recently, there was substantial "glial revolution" which completely challenged our view on both of these cells. -->

Since, as reported in this review, all the cited chemokines can trigger different mechanisms o f neuroprotection, limiting apoptotic and excitotoxic cell death as well as inflammatory conditions, it can be speculated that upon noxious insult endogenous protective programs, such as the chemokine induced-chemokine release, might orchestrate neurons-microglia-astrocytes action to preserve and limit brain damage.

It has been shown that in neurons CXCL12 triggers intracellular pathways ( Khan et al., 2005, 2008 ) that can upregulate the transcription of cx3cl1 gene such as NF-Kb and p53 ( Shiraishi et al., 2000 ). Cook et al. (2010) showed that CXCL12 increases the shedding of neuronal CX3CL1, likely via up-regulation of neuronal ADAM17, suggesting that, in addition to the direct neuroprotective activity of CXCL12, its ability to induce CX3CL1 release may further facilitate neuronal recovery after excitotoxic insults. CX3CL1, in turn, can elicit the release of soluble CXCL16 from astrocytes and microglia, and A3R and CCL2, mediators of CXCL16 neuroprotective activity, represent active player in CX3CL1 protection against excitotoxic-insult ( Rosito et al., 2012 ). In line with these data, the neuroprotection induced by CX3CL1 against ischemic insult is significantly reduced in mice that lack CXCL16 signaling ( Rosito et al., 2014 ). The above mentioned findings strongly corroborate the concept that, in the CNS, chemokines could represent key endogenous modulators of the cross-talk between neurons and glia cells aimed at preserve brain functioning ( Fig. 1 ). 



### Neuron-astrocyte signaling  {#astro_inter} 

Astrocytes, after oligodendrocytes, constitute the major glial cell population in the mammalian brain (Herculano-Houzel et al., 2015). Since the tripartite synapse concept emerged in 1999 (Araque et al., 1999), data from numerous studies have supported the notion that astrocytes are involved 


....
....

Astrocytes tightly enwrap neuronal cell bodies, axons, dendrites and synapses (Montagnese et al., 1988; Ventura and Harris, 1999; Khan et al., 2001; Witcher et al., 2010), and their endfoot processes associate with vascular endothelial cells and pericytes (Liebner et al., 2018), being ideally positioned to monitor and regulate both synaptic activity and blood brain barrier. The close association between astrocytes and neuronal synapses is a critical factor required for the maintenance of brain homeostasis (Perea et al., 2009).

Astrocytes, which were considered as supporting and nourishing neurons, are now known as the highly heterogeneous group of active players in complex brain functions, such as synaptic transmission and synaptic plasticity, network oscillations [@perea_2009, @mederos_2019].
To react to changing microenvironment, they are endowed with a great variety of voltage and ligand-operated ion  channels [@olsen_2015, @seifert_2018, @kofuji_2021] as well as they can release a substantial set of gliotransmitters [@araque_2014, @savtchouk_2018, @covelo_2018].
Ca^2+^ levels are particularly relevant in astrocyte signaling, as their elevated Ca^2+^ levels are thought to induce gliotransmission and facilitate synaptic transmission. <!-- nie podoba mi się to zdanie -->
Thus, astrocytic intracellular Ca^2+^ elevations are of specific spatial and temporal properties, and this topic  has been extensively discussed in several excellent reviews [@araque_2014, @guerragomes_2017, @bazargani_2016].

Astrocytes are integral elements of synapses in developing rodent and human cerebral cortices [ 30 – 32 ]. 
A single cortical astrocyte is estimated to contact 20,000 to 120,000 synapses in  rodents and up to 2,000,000 synapses in humans [ 30 ]. 
Several lines of evidence suggest that,  through this close association with neurons, astrocytes alter synaptic functions. 
Astrocytes have been shown to modulate synaptic transmission [ 33 , 34 ], long-term potentiation [ 34 – 40 ],  and long-term depression [ 15 ] in several brain areas, as well as provide a developmental switch  of synaptic transmission from LTD to LTP in hippocampus [ 41 ]. 
More and more details about  astrocytic cellular and subcellular mechanisms have recently been presented [ 40 , 42 – 49 ]. 
It is  of interest to understand how these subcellular mechanisms in astrocytes and their processes are linked with synaptic transmission and plasticity in neocortex [ 13 , 15 , 42 , 50 , 51 ]. [@manninen_2020]

They are prominently found in proximity of nerve terminals, sensing neural activity and being activated during synaptic transmission.
 
Astrocytes can also modulate synaptic transmission by releasing transmitters

In agreement with this hypothesis is the observation that astrocyte stimulation in mice’s primary sensory areas increases neural firing beyond stimulation (Perea et al., 2014; Poskanzer et al., 2016).

Astrocytes are specialized cells, organized in non-overlapping domains within the CNS parenchyma and coupled into multicellular networks via gap junctions ( Sofroniew and Vinters, 2010 ). Astrocytes are essential for brain homeostasis affecting: i) the blood – brainbarrier (BBB) integrity; ii) the cerebral blood fl ow, fl uid, ion, pH and transmitter homeostasis; iii) the synaptic function, being components of the (tripartite) synapsis and releasing gliotransmitters; iv) the CNS metabolism regulating energy supply to neurons ( Sofroniew and Vinters, 2010 ). Upon acute brain insults or chronic brain diseases (such as neurodegenerative disease, brain tumor, epilepsy) astrocytes become reactive and undergo morphological, transcriptional and functional changes that can be either bene fi cial or detrimental ( Sofroniew and Vinters, 2010; Liddelow and Barres, 2017 ). <!--Trettel2020-->

A1 astrocytes lose the ability to promote synapses formation, are defective in phagocytosis, and release soluble factors that induce apoptosis of neurons and oligodendrocytes ( Zamanian et al., 2012; Liddelow et al., 2017 ). A2 reactive astrocytes might have protective/reparative functions, since they upregulate neurotrophic factors and thrombospondins (which promote synapses repair) ( Liddelow and Barres, 2017 ). These and other evidence support the notion that the interplay among neurons, microglia and astrocytes orchestrates the endogenous response to limit brain damage upon toxic insult. <!--Trettel2020-->

Chemokines are small pro-in fl ammatory cytokines with chemoattractant and regulatory activities ( Baggiolini, 1998 ). Chemokines are important regulators of both the peripheral and central immune response, which largely explains how they contribute to controlling in fl ammatory processes in the brain. Indeed, in pathological processes, chemokines represent important neuro-in fl ammatory mediators that drive leukocytes traf fi cking and activation into the CNS, facilitating the immune responses, targeting cells of the innate and adaptive immune system ( Williams et al., 2014 ). However, chemokine expression in the CNS is not only related to pathological conditions. Constitutive brain expression of chemokines and their receptors on endothelial cells, neurons and glia, suggests a role for such molecules in mediating homeostatic cross-talk between cells of the brain parenchyma ( Williams et al., 2014 ). The cross-talk among neurons and glia is determinant to establish and maintain a normal brain function.

Observational studies from postmortem human tissues have revealed that human astrocytes are much larger and more complex than their murine counterparts (Oberheim et al., 2006, Oberheim et al., 2009). More recently, transplantation of human glial progenitors into mouse brains has been shown to improve learning and memory (Han et al., 2013). These observations raise questions about how murine astrocyte physiology and function might extend to humans. Are there distinct properties of human astrocytes that contribute to human intelligence and cognition? Can we extend findings about astrocyte pathology in neurological disorders from mouse and rat studies to develop effective therapeutic approaches in humans?

Interestingly, the GABA transporters (GATs) GAT-1 and GAT-3 show particular cellular and sub-cellular distributions throughout the brain (Ribak et al., 1996; Boisvert et al., 2018). GAT-3 is the most abundant GAT in astrocytes and is localized in astrocytic processes that are adjacent to synapses and cell bodies, but are also close to basal and apical dendrites (Boddum et al., 2016), while GAT-1 can be found in distal astrocytic processes and is more abundant in neurons (Borden, 1996; Scimemi, 2014). 

Glial cells continuously monitor the neural parenchyma and any disturbance or loss of CNS homeostasis (e.g. infection, trauma, ischaemia, neurodegenerative diseases or altered neuronal activity) evokes morphological changes and alterations in the gene expression pattern of microglia, a process called microglial activation [16]
Glial cells are crucial for the maintenance of correct neuronal functionality in a physiological state and intervene to restore the equilibrium when environmental or pathological conditions challenge central nervous system homeostasis.

#### Pharmacological blockade of astrocytes - fluorocitrate

Moreover, pretreatment of brain slices with fluorocitrate (100 lM for 30 min) increased sIPSC duration in ventrobasal nucleus neurons or decreased sIPSC duration in the thalamic reticular nucleus neurons (Christian and Huguenard, 2013). - Peng2016

### Neuron-microglia signaling   {#micro_inter} 

Microglia constantly survey the local microenvironment and express a unique sensome that dynamically and heterogeneously regulates synaptic connectivity and remodeling in both developing and mature brains (Hong et al., 2016; Masuda et al., 2020; Smolders et al., 2019; Tan et al., 2020; Tay et al., 2017). [@piirainen_2020]

How and what kind of microglia modulate synapses in the adult brain are still poorly known, particularly in adult animals, although previous studies have revealed evidences on synaptic phagocytosis or nibbling by neonate and adolescent microglia (Paolicelli [@piirainen_2020]

Although CX3CR1 is widely acknowledged as pivotal for brain development and function, evidence on how it regulates microglial differentiation under psychosocial stress is limited (Bollinger et al., 2016; Bollinger et al., 2017; Trojan et al., 2017). We hereby provide evidence that CX3CR1 expression was dampened in both CRS animals and schizophrenia patients, and CX3CR1 gene had less interactions with other brain genes in schizophrenia; this receptor was further found to be important for CD206+microglial subtype differentiation and morphological process arborization, and its deficiency resulted in social dominancy impairment.

Modification of local brain microenvironment can be sensed by microglia cells, which respond to preserve brain homeostasis, or to exacerbate brain damage. Understanding the mechanisms of microglia communication in the brain is important to identify molecular players that can be used as targets to counteract brain damage and preserve brain homeostasis. Within the brain, microglia are plastic cells that constantly monitor brain parenchyma to sense local perturbation and, depending on specific environmental cues, can change their phenotype and functional activity promoting inflammatory or anti-inflammatory conditions (  1  ,  2  ). <!-- Lepore 2019 -->

Following acute brain damages, microglia cells at the site of injury produce anti-inflammatory cytokines,  scavenger  receptors,  and  trophic  factors  thus promoting restorative processes. However, later on, microglia acquire  a  pro-inflammatory  phenotype  releasing  proinflammatory  cytokines,  chemokines,  and  inducible  nitric oxide synthase, all involved in the exacerbation of brain damage (  37  ,  38  ). <!-- Lepore 2019 -->

The same microglia phenotype triggers different effects on brain homeostasis, in a context-dependent way.

Microglia are the immune system resident cells in the CNS. <!--ZMIENIĆ -->
Their roles include, but are not limited to, a continuous surveillance, elimination of pathogens, phagocytosis of apoptotic cells and cellular debris, and synapse remodeling and elimination, thereby contributing to maintaining tissue homeostasis under both  physiological and pathophysiological conditions (Paolicelli et al., 2014; Reshef et al., 2014; Sierra et al., 2010). <!--ZMIENIĆ synonimy funkcji jeszcze trochę. They play a play a continuous surveillance role, thereby contributing to maintaining tissue homeostasis under both pathological and physiological conditions. // Microglial roles include, but are not limited to, continuous surveillance, elimination of pathogens, phagocytosis of apoptotic cells and cellular debris, and synapse remodeling and elimination  -->
In this regard, the actions exerted by microglia on neurons have often been referred to as dual or even multifaceted (Sierra et al., 2013), given that both neuroprotective and detrimental actions have been reported. <!--ZMIENIĆ -->
Microglia show an extraordinary degree of plasticity, which allows them to rapidly switch between activation phenotypes and to adapt to everchanging neuron and environmental requirements. <!--ZMIENIĆ --> 
In this regard, a plethora of soluble and membrane-bound cytokines execute the orders of bi-directionally orchestrated neuron-microglia communication. <!--ZMIENIĆ -->
This bidirectional cross-talk governs the delicate equilibrium between the neuroprotective and detrimental actions of microglia on neurons. <!--ZMIENIĆ -->
Cellular distribution of CX3CL1/CX3CR1 axis as well as a model of CX3CR1^GFP^/^GFP^ mice led to many reports on fractalkine-microglia cross-talk in healthy conditions. <!--spróbować napisać to lepiej In this regard, neurons regulate microglial function through the CX3CL1/CX3CR1 axis (Rogers et al., 2011).-->

<!--a chemokine which signals directly from the producing neurons to their effector microglia, the only cells expressing its cognate receptor CX3CR1 in the healthy brain (Nishiyori et al., 1998; Schwaeble et al., 1998; Maciejewski-Lenoir et al., 1999; Hughes et al., 2002). Paolicelli2014-->

Growing evidence suggests a delicate balance between the protective and detrimental influence of microglial activation on neuron functionality (Sierra et al., 2013). Bolos2018

In this regard, the impaired cross-talk between neurons and microglia is thought to be the underlying mechanism of other anatomical alterations found in CX3CR1-/- mice (Paolicelli et al., 2014; Zhan et al., 2014). <!--zmienić,Bolos2018-->
The first evidence of this phenomenon was provided by an elegant study by Paolicelli et al. (2011). <!--zmienić,Bolos2018-->
These authors showed that CX3CR1-/- mice exhibit impairments in the positioning of microglia in the CA1 region during embryonic development. <!--zmienić,Bolos2018-->
Thus, as a consequence of deficient synaptic pruning, CA1 pyramidal neurons show a postnatal transient increase in the number of synaptic spines (Paolicelli et al., 2011). <!--zmienić,Bolos2018-->
This is a beautiful example of the bi-directional manner in which the system is regulated. <!--zmienić,Bolos2018-->
The data obtained in the present work support the notion that microglia are key regulators of granule neuron connectivity during adulthood. <!--zmienić,Bolos2018--> 
In this regard, we and others have demonstrated that chronic inflammation negatively regulates the connectivity and functional maturation of newborn granule neurons (Ekdahl et al., 2003; Llorens-Martin et al., 2014) and that several of the pro-inflammatory cytokines that are increased in CX3CR1-/- mice (such as IL-6, TNF$\alpha$ and Eotaxin, among others) impair the generation of newborn neurons (Villeda et al., 2011). <!--zmienić,Bolos2018-->

Microglia, traditionally known as resident immune cells in the central nervous system (CNS), play essential roles in brain circuit maturation during development, participating in the precise refinement of synaptic connections (Tremblay et al., 2010; Paolicelli et al., 2011; Schafer et al., 2012; Zhan et al., 2014). <!--zmienić, Pagani2015-->
Microglial cells derive from myeloid lineage and colonize the immature brain during development, progressively acquiring a ramified morphology, commonly associated to surveying activity (Prinz and Mildner, 2011; Walker et al., 2014). <!--zmienić, Pagani2015-->
Ramified microglia lie very close to each other and have highly motile filopodia-like protrusions of variable shape, defining rarely overlapping niches of competency (Raivich, 2005). <!--zmienić, Pagani2015-->
Microglial processes continuously sample the extracellular space and contact preand post-synaptic elements (Davalos et al., 2005; Nimmerjahn et al., 2005; Wake et al., 2009; Tremblay et al., 2010). <!--zmienić, Pagani2015-->
Among the functional consequences of this active and continuous surveillance of the developing brain appear to be the shaping neuronal circuits by phagocytosis (Paolicelli et al., 2011) and favoring synaptic maturation (Hoshiko et al., 2012). <!--zmienić, Pagani2015-->
In damaged brain, microglial processes rapidly rearrange toward the site of injury (Nimmerjahn et al., 2005; Lee et al., 2008). <!--zmienić, Pagani2015-->
Among soluble factors activating microglial cells, ATP regulates microglial processes extention and ramification in both physiological and pathological conditions (Davalos et al., 2005; Inoue et al., 2007). <!--zmienić, Pagani2015--> 
To reach the site of activating stimuli, microglia retract their cellular processes and rearrange them in a directional manner toward the lesion. <!--zmienić, Pagani2015-->
In addition, a marked change in ionic channel expression has been observed (Boucsein et al., 2000). Indeed, in acute brain slices non-activatedmicroglia frequently display a small linear conductance, while following nerve lesion (Boucsein et al., 2000) or status epilepticus (Avignone et al., 2008) they transiently express inward and outward rectifier potassium (K+) currents (Menteyne et al., 2009; Kettenmann et al., 2011). <!--zmienić, Pagani2015-->
Ion channels have been involved in many microglial functional properties (Eder, 2005), such as cell volume regulation (Schlichter et al., 1996; Eder et al., 1998), proliferation (Kotecha and Schlichter, 1999), migration (Rappert et al., 2002; Schilling et al., 2004) and cell process extension and retraction (Eder et al., 1998). <!--zmienić, Pagani2015-->
However, microglia activation is no longer considered an all or none event, but rather a sequence of progressive stages (Ponomarev et al., 2007; Olah et al., 2012; Crain et al., 2013) depending on the balance between pro-inflammatory and anti-inflammatory signals in the surrounding environment (Biber et al., 2007; Lively and Schlichter, 2013).<!--zmienić, Pagani2015-->

CX3CR1 signaling has been shown to influence microglial function under both normal and pathological conditions (Limatola and Ransohoff, 2014; Paolicelli et al., 2014).
For example, a transient reduction of microglial density during hippocampal development has been reported in Cx3cr1 knockout mice (Paolicelli et al., 2011). 
However, previous studies examining microglia ramification did not evidentiate morphological differences (Liang et al., 2009; Hoshiko et al., 2012), 

Microglia are ramified cells that exhibit highly motile processes, which continuously survey the brain parenchyma and react to any insult to the CNS homeostasis. <!--Szepesi2018-->
Although microglia have long been recognized as a crucial player in generating and maintaining inflammatory responses in the CNS, now it has become clear, that their function are much more diverse, particularly in the healthy brain. <!--Szepesi2018-->
The innate immune response and phagocytosis represent only a little segment of microglia functional repertoire that also includes maintenance of biochemical homeostasis, neuronal circuit maturation during development and experience-dependent remodeling of neuronal circuits in the adult brain. <!--Szepesi2018-->
Being equipped by numerous receptors and cell surface molecules microglia can perform bidirectional interactions with other cell types in the CNS. <!--Szepesi2018--> 
There is accumulating evidence showing that neurons inform microglia about their status and thus are capable of controlling microglial activation and motility while microglia also modulate neuronal activities. <!--Szepesi2018-->

Microglia are the resident immune cells of the central nervous system, which represent about 5– 12% of total CNS cells in the healthy brain and the spinal cord. <!--Szepesi2018-->
Microglia are derived from the myeloid precursors cells in the embryonic yolk sac and they travel to the area of the developing CNS during early embryogenesis (Schulz et al., 2012; Ginhoux et al., 2013; Kierdorf and Prinz, 2013; Ginhoux and Prinz, 2015;Wieghofer and Prinz, 2016; Hoeffel and Ginhoux, 2018). <!--Szepesi2018-->
Microglial progenitors are already present around the neural tube at embryonic day 9 in mice, and from the fifth gestational week in humans. <!--Szepesi2018-->
After neural entry, microglia progenitors migrate through the developing nerve tissue and undergo massive proliferation before they reach their final density (Ginhoux et al., 2010; Verney et al., 2010). <!--Szepesi2018-->
Embryonic microglia develop into highly ramified mature microglia via regulatory factors such as Pu.1, IL-34, and CSF-1 (Schulz et al., 2012; Kierdorf et al., 2013). <!--Szepesi2018-->
Microglia are broadly distributed throughout the CNS although quantity and location among species varies (Lawson et al., 1990; Mittelbronn et al., 2001). <!--Szepesi2018--> 
Despite their broad distribution, microglia represent a rather heterogeneous community with different subpopulation based on specific brain regions. <!--Szepesi2018-->
Each microglia subpopulation develop unique features and they can be distinguished by capacities and functions (Gertig and Hanisch, 2014; Neiva et al., 2014; Doorn et al., 2015; Grabert et al., 2016; De Biase et al., 2017). <!--Szepesi2018-->
Microglia are considered to be the resident macrophages in the CNS and are long-lived, self-renewing cells, autonomous from peripheral monocytes that normally do not enter the brain. <!--Szepesi2018-->

Neural circuits are constantly monitored and supported by the surrounding microglial cells, using finely tuned mechanisms which include both direct contact and release of soluble factors. <!--Paolicelli2014-->
These bidirectional interactions are not only triggered by pathological conditions as a S.O.S. response to noxious stimuli, but they rather represent an established repertoire of dynamic communication for ensuring continuous immune surveillance and homeostasis in the healthy brain. <!--Paolicelli2014-->
In addition, recent studies are revealing key tasks for microglial interactions with neurons during normal physiological conditions, especially in regulating the maturation of neural circuits and shaping their connectivity in an activityand experience-dependent manner. <!--Paolicelli2014-->
Chemokines, a family of soluble and membrane-bound cytokines, play an essential role in mediating neuron-microglia crosstalk in the developing and mature brain. <!--Paolicelli2014-->

In recent years, microglia were demonstrated to originate from yolk-sac derived progenitors infiltrating the brain during early embryonic development, with no subsequent contribution to their renewal from bone-marrow derived myeloid cells (Ginhoux et al., 2010; Mizutani et al., 2012; Kierdorf et al., 2013). <!--Paolicelli2014-->
Microglia were also shown to be extremely dynamic in their once presumed “resting” state, continuously surveying the brain parenchyma and contacting preand post-synaptic elements with their highly motile processes (Davalos et al., 2005; Nimmerjahn et al., 2005; Wake et al., 2009; Tremblay et al., 2010). <!--Paolicelli2014-->
Their physiological roles discovered so far comprise the elimination of supernumerary neurons and the maturation of synapses in the developing brain (Hoshiko et al., 2012; Cunningham et al., 2013; Lenz et al., 2013; Ueno et al., 2013), the regulation of neuronal and synaptic activity (Li et al., 2012; Pascual et al., 2012), the elimination of apoptotic newborn neurons generated in excess during adult hippocampal neurogenesis (Sierra et al., 2010), and the activityand experience-dependent remodeling of neuronal circuits. <!--Paolicelli2014-->
Neuronal circuit plasticity is required for learning and memory processes in the developing and mature brain, where microglia contribute to both the formation and elimination of synapses (Tremblay et al., 2010, 2012; Paolicelli et al., 2011; Schafer et al., 2012; Parkhurst et al., 2013). <!--Paolicelli2014-->

Usually de  fi  ned as cells of the  “  innate-immunity  ”  that protect  the CNS from pathogens, microglia senses signals of danger,  such as PAMPs (pathogen-associated molecular patterns  molecules) and DAMPs (damaged-associated molecular pat-  terns molecules) and react to modulate an in  fl  ammatory  response. Despite their myeloid origin, highly differentiated  microglia interact with neurons to regulate homeostatic plas-  ticity (  Masgrau et al., 2017  ). In recent years, it became evi-  dent that the so called  “  resting  ”  microglia are fully active  cells that participate to brain functions controlling pruning,  elimination and maturation of synapses (  Paolicelli et al.,  2011; Schafer et al., 2012  ). Microglial cells play a role during  development promoting programmed cell death and remov-  ing apoptotic neurons and glia (  Marín-Teva et al., 2004; Wakselman et al., 2008 ). In adult brain, microglia contribute to neurogenesis promoting neural precursor proliferation, neuroblast migration, and neuronal differentiation via the secretion of trophic factors ( Choi et al., 2008; Yan et al., 2009; Ribeiro Xavier et al., 2015 ).<!-- Trettel 2020-->

 Considering the key role of microglia in sensing neuronal microenvironment ( Davalos et al., 2005 ), it was not surprising to discover that some of the effects of CXCL16 are also mediated by these cells. <!-- Trettel 2020 -->
 
 Usually defined as cells of the  “innate-immunity”  that protect  the CNS from pathogens, microglia senses signals of danger,  such as PAMPs (pathogen-associated molecular patterns  molecules) and DAMPs (damaged-associated molecular patterns molecules) and react to modulate an inflammatory  response. 
Despite their myeloid origin, highly differentiated  microglia interact with neurons to regulate homeostatic plasticity (  Masgrau et al., 2017  ). 
In recent years, it became evident that the so called  “resting”  microglia are fully active  cells that participate to brain functions controlling pruning,  elimination and maturation of synapses (  Paolicelli et al.,  2011; Schafer et al., 2012  ). 
Microglial cells play a role during  development promoting programmed cell death and removing apoptotic neurons and glia (  Marín-Teva et al., 2004;


A handful of studies have utilized CX3CR1-deficient mice to explore the role of this receptor in chronic stress, regarding its regulation by stress (Bollinger et al., 2016; Bollinger et al., 2017; Trojan et al., 2017), its importance for microglial morphological ramification and phagocytosis (Hellwig et al., 2016; Milior et al., 2016; Rimmerman et al., 2017), and its beneficial versus detrimental role in brain and behavioral responses to physio-pathological (Gunner et al., 2019; Lowery et al., 2017; Schecter et al., 2017) or psychosocial stressors (Hellwig et al., 2016; Milior et al., 2016; Winkler et al., 2017; Wohleb et al., 2013). Among these, studies have showed that CX3CR1 rescued chronic stress-induced increase in microglial phagocytosis (Milior et al., 2016) and decrease in hippocampal long-term potentiation (Milior et al., 2016), while improving neurogenesis and short-term memory (Rimmerman et al., 2017); CX3CR1-deficiency caused social withdrawal and increased repetitive behavior (Zhan et al., 2014), as well as increased fear acquisition and reinstatement (Schubert et al., 2018), implicating a beneficial function of CX3CR1 for  the  stressed  brain.  However, other  studies  showed that CX3CR1-deficient mice were resistant to chronic stress-induced depressive-like and anxiety behaviors (Hellwig et al., 2016; Milior et al., 2016; Rimmerman et al., 2017; Wohleb et al., 2017), jointly implying a detrimental role of CX3CR1 in psychiatric disorders. [@paiirainen_2021]

We previously found that microglia from mice with high-anxiety traits were prone to polarization from a CD206+to an MHCII+phenotype (Li et al., 2014), and identified candidate innate immune genes involved in synaptic plasticity (Ma et al., 2015). We also observed the regional heterogeneity of microglia and its potential importance for neurological diseases and psychiatric disorders (Li et al., 2016; Tan et al., 2020; Xuan et al., 2019). [@paiirainen_2021]

In cx3cl1 − / − mice, the Adeno-Associated Virus (AAV)-mediated gene insertion of either soluble or membrane bound synthetic variant of CX3CL1 demonstrated that, in a MPTP- model of PD, only the soluble form rescued motor coordination, reduced neurodegeneration and microglia activation ( Morganti et al., 2012 ).

#### Minocycline

**NEUROGENESIS**
Unlike other regions of the adult brain, the DG has a unique feature, namely it continuously generates new neurons throughout life – a process known as adult hippocampal neurogenesis (AHN) (Bayer and Altman, 1975; Gould et al., 1990). This property confers the entire hippocampal circuit with an extraordinary degree of plasticity and allows the participation of newly generated neurons in the fine tuning of hippocampal-related behavior (Nakashiba et al., 2012; Sahay et al., 2011).The incorporation of new synaptic elements to the hippocampal trisynaptic circuit as a consequence of AHN triggers a substantial remodeling of the pre-existing synaptic contacts (McAvoy et al., 2016; Toni et al., 2008; Toni et al., 2007). Bolos2018
This process is **positively modulated by the activation of inhibitory interneurons (Alvarez et al., 2016), which is, in turn, regulated by a specialized structure of the extracellular matrix (EM) called the perineuronal net (PN) (Yamadaand Jinno, 2017). This structure controls neuroplasticity through a variety of mechanisms (Miyata and Kitagawa, 2016, 2017).** In addition, the PN is thought to orchestrate the intercommunication between glial cells and neurons (Iozzo and Schaefer, 2015).  In this regard, it is known that microglia play a key role in synapse remodeling (Paolicelli et al., 2011; Valero et al., 2016). In addition, they exert a tight regulation of the whole process by regulating the number of newborn neurons that survive in the neurogenic niche (Sierra et al., 2010).Bolos2018

**Modulatory action of fractalkine**




Microglia are considered the innate immune cells in the brain, and maintain central nervous system (CNS) homeostasis in response to changes in their microenvironment such as immune challenge and stress. Microglia are extremely plastic and microglial activation has been associated with specific morphologic changes; during activation, microglia retract their processes, resulting in decreased occupied area and increased soma size.9 - Yuan2020

Microglia are the resident myeloid cells ofthe brain (Sierra et
al., 2014) and are thought to mediate the first response to inflam- matory signals. In addition, microglial interactions with synapses are important in maintenance ofneuronal connections and affect neuronal plasticity (Wake et al., 2009; Tremblay et al., 2010a). In healthy and developing brains, microglia prune synapses at both presynaptic and postsynaptic sides and thus regulate synaptic innervation (Paolicelli et al., 2011; Schafer et al., 2012). Recently, a crucial role for microglial autophagy in synaptic pruning has been demonstrated (Kim et al., 2017). The molecular cues that guide microglia to the synapses destined for engulfment remain to be identified, as do the specific mechanisms that are recruited. However, it is thought that the complement factors C1 and C3 ‘tag’ such synapses and thus direct the microglia to them for phagocytosis (Schafer et al., 2012; Bialas and Stevens, 2013). In addition, synaptic stripping, which is the physical separation of presynaptic and postsynaptic elements by intervening microglial processes, is well documented upon injury (Kettenmann et al., 2013). - Acharjee2018b

Given the role of microglia in regulating synapse number (Tremblay et al., 2011; Stephan et al., 2012; Schafer et al., 2013; Wuet al.,2013, 2015), we explored a possible role for microglia in the BLA during early EAE. Microglial morphology reflects their functional activation state (Zanier et al., 2015). In the unchallenged state, surveillant microglia present a ramified morphology, highly motile processes that interact with synapses, whereas upon “activation,” their processes typically retract as the cell body becomes hypertrophied (Tremblay et al., 2010a). “Activated” microglia are also well known to display an increased expression of IBA-1 in various contexts of injury and disease (Norden et al., 2016; Wang et al., 2017). We have previously shown that electron microscopy (EM) can reveal the functional state ofmicroglia in a highly sensitive manner (Tremblay et al., 2010a). Based on that work, we quantified microglial ultrastructural features in pre-onset EAE by transmission EM using an immunoperoxidase staining against IBA-1. ;;

* **Microglial processes constantly survey the brain parenchyma,transiently contact neuronal elements, and can also engulf cellular debris and eliminate synapses**. Using immunocytochemical EM against IBA-1, we found direct contacts between microglial process and neuronal perikarya, as well as presynaptic elements, postsynaptic elements, and synaptic clefts. Synaptic elements showing signs of autophagy were also frequently contacted by microglia in both CFA and EAE. **Microglial inclusions, sometimes containing recognizable synaptic elements that probably resulted from phagocytosis, were occasionally encountered in both conditions**. **In addition, features associated with extracellular digestion or “exophagy” (Haka et al., 2016), such as microglial processes in association with extracellular space pockets that contained partially to completely disrupted cellular membranes, as well as synaptic elements, were observed**. **These features are suggestive of ongoing extracellular digestion, either mediated by microglial remodeling of the extracellular matrix or release of lysosomal proteins.** The prevalence of extracellular digestion was significantly reduced in EAE. **Accordingly, the expression of CD68 in IBA-1-labeled cells, a lysosome-associated protein often used as a marker of microglial “activation” or “phagocytosis” was significantly reduced** in the BLA of EAE mice compared with CFA controls.;;

* **However, we acknowledge that minocycline, in addition to impairing microglial proinflammatory and phagocytic activity, has many other unrelated effects; however, our use of ICV injection at least eliminated the peripheral effects of minocycline (Brundula et al., 2002; Giuliani et al., 2005)** Thus, to determine further whether microglia specifically control synaptic transmission in the BLA, we injected Saporin toxin conjugated to macrophage antigen complex-1 (Mac-1, integrin CD11b/ CD18 receptor localized to microglia) directly into the BLA of 8-week-old C57BL/6N females to transiently deplete microglia. IgG-Saporin, which does not bind to any specific receptor, was used as a control.;;

*  Microglia can react rapidly to infection, trauma, and other danger signals, by retracting their processes and enlarging their cell body. However, microglial phenotypes vary depending on the type of stimulus and by brain region (Morrison and Filosa, 2013; Abiega et al., 2016). Genome-wide analyses of microglia of different CNS regions showed that cerebellar and hippocampal microglia exist in a more vigilant state than do microglia in other brain areas (Grabert et al., 2016). Even within the hippocampus, the microglia of area CA3 are more sensitive to LPS compared with those of CA1 or dentate gyrus (Madore et al., 2013). Thus, it is not surprising that we saw different effects in BLA compared with what another group reported in the striatum.;;

* In contrast, a recent study with microglial gene profiling using microarray analysis revealed suppression of microglial genes during the early stages of EAE development; specifically, the genes related to their phagocytic functions and cytoskeleton organization were suppressed (Yamasaki et al., 2014). This suppression could have multiple effects, such as reduced phagocytosis, cytokine, chemokine, and metalloproteinase production (Shemer et al., 2015).;;

* Reduced extracellular spaces between the neuron and microglia were also observed in the EAE amygdala. These spaces generally contained material undergoing digestion in the CFA controls (synaptic elements that could be identified or membranes in a more advanced state of digestion), suggesting a reduced pruning of synaptic materials in EAE (Haka et al., 2009; Singh et al., 2016).;;

* It seems that glial cells can affect neural function and reward-related process by releasing certain cytokines and chemokines (Narita et al. 2006; Niwa et al. 2007a). - Arezoomandan2018



#### Pharmacological blockade of microglia - minocycline

Minocycline, a second-generation tetracycline, is well known for its antibiotic, anti-inflammatory, and antinoci- ceptive effects. Modulation ofsynaptic transmission is one of the analgesic mechanisms of minocycline. Although it has been reported that minocycline may suppress excitatory glu- tamatergic synaptic transmission, it remains unclear whether it could affect inhibitory synaptic transmission, which also plays a key role in modulating pain signaling. - Peng2016

minocycline has been recognized as playing two mainly independent roles: it is a microglial inhibitor as well as a second- generation tetracycline. Since microglia is an upstream partner of astrocytes in response to stimuli (Pascual et al., 2012), we next examined whether astrocyte activa- tion will affect sIPSCs - Peng

Minocycline, a semisynthetic tetracycline, is well
known for its functions, such as neuroprotection or antihypernociception, that have been identified in the last decade, and it typically acts by blocking microglial activation and reducing proinflammatory cytokine
production (Yong et al., 2004). - Peng

Moreover, the effect of minocycline may differ on different types of neurons. For example, minocycline (50 nM) had no effect on basal exci- tatory synaptic transmission in CA1 (Pascual et al., 2012). or SG neurons (Berta et al., 2014); however, 100 lM minocycline may inhibit dorsal root entry zone stimulation-elicited EPSCs in SG neurons (Cho et al., 2006) or may decrease sEPSC frequency and amplitude in hippocampal neurons (Gonzalez et al., 2007). At a con- centration of 200 lM, minocycline may decrease C-fiber evoked field potentials in the spinal dorsal horn, indicating an inhibition of excitatory synaptic transmission (Zhong et al., 2010). In addition, minocycline at 500 lM abolished the mustard oil-induced glutamatergic-dependent central sensitization in medullary dorsal horn nociceptive neurons (Itoh et al., 2011). The above observations suggest that minocycline may decrease neuronal excitability in a concentration- and cell-type-dependent manner by decreasing glutamatergic transmission. In addition to excitatory input, neurons also receive inhibitory synaptic transmission. If minocycline could modulate inhibitory synaptic transmission, then IPSC frequency or amplitude must be influenced by minocycline. In

Minocycline, a second-generation, broad spectrum, semi-
synthetic tetracycline antibiotic is of particular interest as an analgesic, in addition to its anti-microbial effect. Minocycline effectively crosses the blood-brain barrier (Aronson, 1980) and has a proven safety record in humans (Thomas and Le, 2004).Minocycline mediated inhibition of microglial activation has been reported to reduce nociception in inflammation-evoked pain (Hua et al., 2005), spinal cord contusion injury (Hains and Waxman, 2006) and spinal nerve ligation (Lin et al., 2007). While the majority of these studies attribute the analgesic effect of minocy- cline to inhibition of microglial activation (Tikka et al., 2001; Garrido-Mesa et al., 2013), some studies have also reported on its action on other targets like astrocytes (Zhang et al., 2012) and neurons (González et al., 2007). While reports indicate that minocycline has no direct effect on
the neurons, González et al. (2007) have reported that minocycline is associated with the mitigation of neuronal excitability, gluta- mate release, and Ca2þ overloading in hippocampal neurons. - Kannampalli2014

Recent reports suggests that minocycline inhibits Na+ channels in the primary afferent neurons (Kim et al., 2011) and also inhibits phosphorylated extracellular signal-regulated kinase (p-ERK) expression in the spinal cord (Cho et al., 2012), supporting a neuronal target for minocycline. Therefore, it is possible that the observed analgesic effect of minocycline in this study might not be exclusively through glial inhibition, but rather a combined effect on glial cells and neuronal targets. However, further experiments are warranted to identify these targets - Kannampalli2014

Minocycline affects dopamine (Hashimoto et al. 2007) and glutamate transmission and depresses Ca2+ signaling in hippocam- pal neurons (González et al. 2007). Furthermore, there is enough evidence that a cross talk exists between neu- rons and glial cells. Microglia secrete proinflammatory mediators such as prostaglandins, proteases, cytokines (tumor necrosis factor-α, interleukin-1β, interleukin-6) and excitatory amino acids, which can affect neural activity as well as neuronal circuit involved in drug addiction (Coull et al. 2005; Niwa et al. 2007b; Yirmiya & Goshen 2011). Minocycline can affect expression of these factors. It has been shown that minocycline is able to upregulate the expression of brain-derived neurotrophic factor and tumor necrosis factor-α (Chen et al. 2012b).
- Arezoomandan2018


Importantly, neither of these phenotypes was altered by transgenic expression of the soluble CX3CL1 isoform, suggesting that it is the membrane-anchored version of CX3CL1 that regulates microglial phagocytosis of Aand neuronal MAPT phosphorylation. Analysis of transcript levels in purified microglia isolated from APPPS1 mice with the various CX3CL1/CX3CR1 genotypes revealed increased expression of inflammatory cytokines and phagocytic markers, which was associated with activation of p38 mitogen-activated protein kinase and Ainternalization within microglia. Together, these studies challenge the “frustrated phagocytosis” concept and suggest that neuronal–microglial communication link the two central AD pathologies. [Lee_2014]

The unique transmembrane structure of CX3CL1 raises the possibility of additionalfunctional regulation by altering its abundance at the cell surface. This could be accomplished in principle by changes in traffic between subcellular compartments. To analyze this possibility we examined the subcellular distribution of CX3CL1 in human ECV-304 cells stablyexpressing  untagged  or  green  fluorescent  proteintagged forms of the chemokine. CX3CL1 was present intwo distinct compartments, diffusely on the plasma membrane and in a punctate juxtanuclear compartment. The latter shared some features with, yet was distinct from the conventional endocytic pathway and may represent a specialized recycling subcompartment. Accordingly, surface CX3CL1 was found to be in dynamic equilibrium with the juxtanuclear vesicular compartment. Intracellular CX3CL1 co-localized with theSNARE (solubleN-ethylmaleimide factor attachmentprotein receptor) proteins syntaxin-13 and VAMP-3. Cleavage of VAMP-3 by tetanus toxin or impairment of syntaxin-13 function by expression of a dominant-negative allele inhibited the ability of internalized CX3CL1 totraffic back to the plasma membrane. These data demonstrate the existence of a dynamic, SNARE-mediated recycling of CX3CL1 from the cell surface to and from anendomembrane storage compartment. The intracellular storage depot may serve as a source of the chemokine that could be rapidly mobilized by stimuli. [@liu_2005]


Under those conditions, many chemokines are synthesized in activated astrocytes and microglial cells, suggesting their involvement in CNS defense mechanisms (Biber et al. 2007, Harrison and Lukacs 2007, Meucci 2010, Ransohoff et al. 1993) as well as in monocyte recruitment and migration into the CNS (Ransohoff 2009), (Semple et al. 2010) 
Chemokines are involved in virtually all pathologies that present an inflammatory component including nervous system disorders, such as neurodegenerative or neuroinflammatory diseases. 
Under such conditions, a large number of chemokines and chemokine receptors are induced in activated astrocytes and microglia, suggesting their involvement in the activation of the CNS defense mechanisms [23,60,84,109]. <!-- może w rozdziele glia nie tylko że chemokines and glia były związane z zapaleniem, ale teraz okazuje się, że to potężne dzieło w synaptic plasticity etc etc. -->