


#### CXC12 actions in the brain {#CXCL12inthebrain}

Considering that virtually all types of brain cells express either CXCL12 and/or one of its receptors, this chemokine serves a wide array of functions in both the developing and mature brain.
Indeed, several lines of evidence illustrate that CXCL12 is involved in neurodevelopment, mainly by controlling cell proliferation, migration, and survival. 
For instance, CXCL12 is associated with both developmental and adult neurogenesis. 
Indeed, the expression of CXCL12 and its receptors is relatively high in embryonic and adult neural progenitor cells [@tran_2004].
Accordingly, CXC12 is found to be a key player in neurogenesis during the development of, among others, the cerebral cortex and hippocampus [@lysko_2011; @pujol_2005].
On the other hand, the adult brain neurogenesis is restricted to two neurogenic regions, e.i., the subventricular zone (SVZ) lining the lateral ventricles and the subgranular zone (SGZ) near the dentate gyrus of the hippocampus. <!-- better written, citations --> 
It is well established that CXCL12 is responsible for the generation and positioning of new neurons within these niches, as well as their axonal and dendritic outgrowth and branching [@abe_2015; @abe_2018; @zhu_2017].
Adult neurogenesis, especially near SGZ, is linked to memory.
Consistently, after learning, the CXCR4 level was documented to be increased in CA3 [@su_2012]. 

CXCL12 was also reported to guide neural progenitors [@bhattacharyya_2008; @casoni_2012; @tran_2003].
Importantly, as interneurons are guided to the correct destination by CXCL12 gradient, ACKR3, acting as a "sink" to collect excess CXCL12, is also implicated in this phenomenon [@snchezalcaiz_2011].
Moreover, a recent study further demonstrated that ACKR3-mediated scavenging and endocytosis of CXCL12 was dependent on receptor phosphorylation rather than `r knitr::asis_output("\U03B2")`-arrestin signaling [@saaber_2019]. 
Thus, certain homeostatic chemokine receptors play critical roles in the homing of various stem cells. 
In addition, CXCL12 was shown to enhance GABAergic transmission within the DG neurogenic niche, which, in turn, is implicated in the maturation of adult neural stem cells within this structure [@bhattacharyya_2008].
CXCL12-induced modulation of GABAergic neurotransmission is also present during adulthood and will be described later in this section. <!-- + GABAergic transmission-->
Importantly, as adult neurogenesis is known to be an important player in memory, CXCL12 was also shown to be upregulated after learning [@su_2012]. <!-- ładniej napisać to zdanie... -->

Another aspect regulated by CXCL12 is its implication in neuroprotective actions, mainly by activating neuroprotective pathways.<!--, such as Akt and ERK`r knitr::asis_output("\U00BD")` [@vauzour_2007].inne, poprawić....--><!-- for example the activation of the Ca^2+^ and cAMP-dependent transcription factor CREB [@meucci_1998] It can also act post-synaptically by activating aG protein activated inward rectifier K+(GIRK), a voltage-gated K channel Kv2.1 associated to neuronal survival, and by increasing high voltage-activated Ca2+currents. [@casoni_2012] ( Casoni et al., 2012 )., JAK/STAT przykłady cytowania // activation of pro-survival and anti-apoptotic pathways through phosphorylation of molecules such as Akt, as well as activation of MAP kinases such as p-38 and Erk1/2 (p44/42; Maciejewski-Lenoir et al., 1999;Meucci et al., 2000;Cambienet al., 2001;Deiva et al., 2004; Klosowska et al., 2009;Lyons et al.,2009). to dotyczy CX3CL1...--> 
The first evidence was the observation that CXCL12 reduces the apoptotic death of hippocampal neurons induced by gp120 or glia deprivation [@meucci_1998].
Moreover, this chemokine was shown to inhibit NR2B [@nicolai_2010], an NMDA receptor subunit predominantly located extrasynaptically [@ivanov_2006; @lveill_2008]. 
Their activation due to excessive glutamate is thought to be neurotoxic.
Thus, CXCL12 is believed to reduce NMDA-induced calcium responses associated with decreased neuronal death [@nicolai_2010].

Thus, the abovementioned findings strongly indicate that CXCL12 could modulate glutamatergic and GABAergic synaptic transmission. 
Consistently, in the cerebellum, CXCR4 activation results in a decrease in NMDAR function, and thus, leads to synaptic depression [@ragozzino_2002].<!-- , probably by CXCL12-induced reduction in NR2B expression subunit of NMDAR [@nicolai_2010]. na ile to prawda? nie bardziej aktywacja NR2B przyczynia się do LTD? sprawdzić -->
Moreover, CXCR4 receptors were shown to be presynaptically located in hippocampal noradrenergic and glutamatergic nerve endings.
They were connected with presynaptic NMDA receptors, suggesting that CXCR4-NMDAR interactions can regulate both noradrenaline and glutamate exocytosis [@diprisco_2016]. 
In addition, CXCL12 was shown to increase glutamate and GABA release in the substantia nigra (SN), the cerebellum, the hypothalamus, and the DRN [@guyon_2005; @guyon_2006; @heinisch_2010; @ragozzino_1998].
<!--CXCR4 is also widely expressed on microglia, and thus being able to react to astrocytic glutamate. najlepiej rozbudować -->
By acting on the presynaptic site, CXCL12 affects the activity of serotoninergic, dopaminergic, and melanin-concentrating hormone (MCH)-containing neurons, thereby modulating the release of neuroactive molecules [@guyon_2005; @guyon_2006; @heinisch_2010]. 
Moreover, CXCL12 is packed in small dense vesicles in the nerve terminals of these neurons, which are then released from neuronal cell bodies and terminal nerve endings in a calcium-dependent manner (for example: @bhattacharyya_2008).
However, as CXCL12 and/or CXCR4 are often co-localized with neurons releasing these signaling molecules (e.g., vasopressin, MCH, and DA<!-- dodać inne + cytowania-->), <!--together with ...., -->postsynaptic mechanisms are also suggested to be involved in this phenomenon. 
For instance, in MCH neurons, CXCR4 was described to directly modulate several voltage-dependent channels, including Na^+^ and K^+^ channels of the action potential [@guyon_2005], or tetrodotoxin-sensitive sodium currents [@guyon_2005a].

Considering that the hypothalamus, a brain region comprised of different nuclei and several neuronal populations producing neuropeptides, is critically involved in regulating major neuroendocrine functions, including water/food intake, metabolism, and stress, one could speculate that CXCL12 signaling may be involved in these functions.
In line with this notion, CXCL12/CXCR4/ACKR3 signaling dysfunctions are associated with feeding disorders, such as anorexia.
Not only a high-fat diet was reported to increase the expression of CXCL12, its receptors, and neuropeptides (e.g., enkephalin, galanin, orexin, and MCH) in the PVN and perifornical lateral hypothalamus, but also an intracerebroventricular injection of CXCL12 was shown to mimic the effects of the high-fat diet in the hypothalamus [@poon_2016]. 
These findings point to a vital role of the CXCL12/CXCR4/ACKR3 axis in feeding behavior. <!-- Both SDF-1 and GABA have been shown to regulate the rate of GnRH neuronal migration by accelerating and slowing migration, respectively. As such, this system was used to explore the mechanism by which these molecules act to produce coordinated cell movement during development. In the present study, GABA and SDF-1 are shown to exert opposite effects on the speed of cell movement by activating depolarizing or hyperpolarizing signaling pathways, GABA via changes in chloride, and SDF-1 via changes in potassium. GABA and SDF-1 were also found to act synergistically to promote linear rather than random movement. The simultaneous activation of these signaling pathways, therefore, results in tight control of cellular speed and improved directionality along the migratory pathway of GnRH neurons. -->
Importantly, depending on the concentration, CXCL12 is thought to exert opposite effects on the action potential discharge in MCH neurons [@guyon_2005], which may have functional consequences on the activity of neuroendocrine functions.
Precisely, CXCR4 was reported to be tonically active at low physiological concentrations, constantly exerting its action on MCH neurons.<!-- whereas its activation lead to ... -->
Consistently, under basal conditions, those cells showed more hyperpolarized membrane potential than orexin neurons, which do not express CXCR4 [@eggermann_2003]. 

The dopaminergic neurons in the SN are also the target of both pre- and post-synaptic actions of CXCL12. 
CXCL12 was reported to enhance the frequency of sIPSCs and mIPSCs in this region, indicating presynaptic mechanisms, which is in line with the documented presence of CXCR4 on the GABAergic neurons [@guyon_2006].
In addition, it was demonstrated that CXCL12 could act directly as a neuromodulator of dopaminergic neuronal electrical activity through the modulation of HVA currents [@guyon_2008a].
Consistent with this data, by using unilateral intranigral or intracerebroventricular injections of CXCL12, a further study has illustrated that this chemokine triggered contralateral turns in circling behavior  [@skrzydelski_2007]. 
Of note, considering that both CXCL12 and CXCR4 are co-expressed in dopamine neurons<!-- citations -->, it is tempting to speculate that this chemokine may act in an autocrine manner [@guyon_2008a].
<!--For instance, electrophysiological recordings of supraoptic neurons have demonstrated that CXCL12 decreases the electrical activity of AVP neurons *via* CXCR4, resulting in reduced AVP release [@callewaere_2006].
Importantly, These findings also elucidate that CXCL12 cognate receptor, CXCL12, may be implicated in the autocrine regulation of these neurons. -->

Interestingly, following the CXCL12 application, SN dopaminergic neurons have shown an increase in an inward current [@guyon_2006].
This effect was independent of the CXCR4 receptor, action potential-dependent sodium channel, and GABA~A~ receptors [@guyon_2006], suggesting that this chemokine may induce glutamate release from astrocytes.
Consistently, immunohistological analyses revealed that astrocytes in this structure lacked CXCR4, further supporting the possibility of astrocytic mediation [@guyon_2006]. 
Considering the abovementioned expression of another ACKR3 receptor in astrocytes, this receptor may be responsible for this CXCL12-induced increase in glutamate. 
Alternatively, it may also be mediated on CXCR4-expressing microglial cells. 
However, the exact mechanism of action of CXCL12 on glutamate release still warrants further investigation.

Unlike in the SN, astrocytes cultured from the cerebral cortex presented the high expression of CXCR4 [@cal_2008].
Upon CXCL12-induced stimulation of CXCR4 in astrocytes, (i) the Ca^2+^-dependent release of glutamate, regulated by exocytosis on a millisecond time scale [@cal_2008; @cal_2010], and (ii) the release of prostaglandins and TNF`r knitr::asis_output("\U03B1")` [@bezzi_2001].
It is widely accepted that TNF`r knitr::asis_output("\U03B1")` mediates synaptic scaling, a form of homeostatic plasticity leading to the adjustment of synaptic strength [@stellwagen_2006], and mainly astrocytes, have been identified as the main source of the TNF`r knitr::asis_output("\U03B1")` in the CNS.
Therefore, by modulating TNF`r knitr::asis_output("\U03B1")` levels, CXCL12/CXCR4 axis, by acting on glia, may participate in homeostatic activity-dependent regulation of synaptic plasticity [@stellwagen_2006].

Convincing evidence illustrates that opioid receptors and CKRs are often co-expressed in the same neuron and can directly interact, thus each influencing the function of the other. 
In this regard, the most studied mechanism is the heterologous desensitization, where the activation of one type of GPCR receptor leads to the inactivation of another GPCR receptor present in the same cell.
Consistent with this idea, following CXCL12 exposure, the heterologous desensitization of opioid receptors has been linked to functional outcomes at the cellular (e.g., reduced chemotaxis [@szabo_2002]) and electrophysiological (e.g., decreased morphine-induced hyperpolarization in PAG neurons in the presence of CXCL12 [@heinisch_2011]) levels. 
In addition, a recent study has provided extensive<!--novel?new?--> evidence that ACKR3 is a chemokine receptor with the ability to bind opioid peptides; however, opioid binding did not trigger downstream signaling through this receptor [@meyrath_2020].
Thus, it is suggested that ACKR3 serves scavenger functions for many opioids, especially enkephalins and dynorphins, by reducing their availability for their classical opioid receptors [@meyrath_2020]. 
Consistent with this idea, ACKR3 was reported to bind intermediate opioid peptides, specifically BAM22 and peptide E, which results in enhancement of circadian glucocorticoid oscillation in the adrenal glands, and, therefore, anxiolytic-like behavior [@ikeda_2013]. <!-- może poprawic albo wrocić do innej wersji? -->
BAM22 and peptide E were shown to be released under a condition named subcapsular cell hyperplasia (SCH) [@ikeda_2013], which is a pathohistological change of adrenal tissue.
SCH cells lack prohormone convertase, an enzyme required for processing these proteins to mature enkephalins [@ikeda_2013].
Therefore, this study highlights the functional relevance of chemokine and opioid systems interactions.

Finally, it is also worth noting that the profile of CXCL12-induced actions is similar to “sickness behavior”.
It is a physiological and psychological state characterized by decreased mood, anorexia, and fatigue, due to immune activation during infection, primarily mediated by peripherally released proinflammatory cytokines [@dantzer_2001; @dantzer_2007]. 
Considering that CXCL12 was shown to modulate the release of 5-HT in the DRN as well as neuropeptides in the hypothalamus, it could affect mood-related and feeding behavior, observed in depression [@maes_1998].
Thus, the effect of CXCL12 on serotonergic neurons in the DRN could underlie depressive symptoms, as dysfunction of the serotoninergic systems is implicated in depression.
<!-- Moreover, amygdala --> 

Thus, given our evolving understanding of how CXCL12/CXCR4 or CXCL12/ACKR3 are involved in the control of intercellular communication between brain cells, as well as in synaptic transmission, plasticity, and behavior, further mechanistic and theoretical understanding of their actions will undoubtedly be of great basic and translational benefit. <!-- napisać lepsze podsumowanie.... Overall, this chemokine system is one of the key players in the neuro-immune interface that shapes CNS responses to changes in the environment. While much effort has been made to investigate the mechanisms underlying CXCL12/CXCR4 or CXCL12/ACKR3-mediated regulation of synaptic transmission and plasticity and their specific properties in certain synapses and brain regions, their impact on network function and animal behavior have only been initially explored. Taken together, the relevance of the actions mentioned above of CXCL12/CXCR4/ACKR3 signaling to mechanisms implicated in many neurobiological disorders is suggestive of -->