## Neuro-glial interactions  {#glia_inter}  

Among the many strategies used by cells to communicate one with another, the repertoire of chemokines constitutes one of the most tightly regulated systems. <!--zmienić -->
Often, a particular cell type is uniquely expressing the ligand for a receptor that is selectively found on another cell type, thereby conferring a high degree of specificity to the ensuing signaling (Rossi and Zlotnik, 2000; Zlotnik and Yoshie, 2000; Allen et al., 2007). <!--zmienić -->


### Neuron-astrocyte signaling  {#astro_inter} 

Moreover, pretreatment of brain slices with fluorocitrate (100 lM for 30 min) increased sIPSC duration in ventrobasal nucleus neurons or decreased sIPSC duration in the thalamic reticular nucleus neurons (Christian and Huguenard, 2013). - Peng2016


Astrocytes are integral elements of synapses in developing rodent and human cerebral cortices [ 30 – 32 ]. A single cortical astrocyte is estimated to contact 20,000 to 120,000 synapses in  rodents and up to 2,000,000 synapses in humans [ 30 ]. Several lines of evidence suggest that,  through this close association with neurons, astrocytes alter synaptic functions. Astrocytes have been shown to modulate synaptic transmission [ 33 , 34 ], long-term potentiation [ 34 – 40 ],  and long-term depression [ 15 ] in several brain areas, as well as provide a developmental switch  of synaptic transmission from LTD to LTP in hippocampus [ 41 ]. More and more details about  astrocytic cellular and subcellular mechanisms have recently been presented [ 40 , 42 – 49 ]. It is  of interest to understand how these subcellular mechanisms in astrocytes and their processes are linked with synaptic transmission and plasticity in neocortex [ 13 , 15 , 42 , 50 , 51 ]. [@manninen_2020]

### Neuron-microglia signaling   {#micro_inter}  

Microglia are the immune system resident cells in the CNS. <!--ZMIENIĆ -->
Their roles include, but are not limited to, a continuous surveillance, elimination of pathogens, phagocytosis of apoptotic cells and cellular debris, and synapse remodeling and elimination, thereby contributing to maintaining tissue homeostasis under both  physiological and pathophysiological conditions (Paolicelli et al., 2014; Reshef et al., 2014; Sierra et al., 2010). <!--ZMIENIĆ synonimy funkcji jeszcze trochę. They play a play a continuous surveillance role, thereby contributing to maintaining tissue homeostasis under both pathological and physiological conditions. // Microglial roles include, but are not limited to, continuous surveillance, elimination of pathogens, phagocytosis of apoptotic cells and cellular debris, and synapse remodeling and elimination  -->
In this regard, the actions exerted by microglia on neurons have often been referred to as dual or even multifaceted (Sierra et al., 2013), given that both neuroprotective and detrimental actions have been reported. <!--ZMIENIĆ -->
Microglia show an extraordinary degree of plasticity, which allows them to rapidly switch between activation phenotypes and to adapt to everchanging neuron and environmental requirements. <!--ZMIENIĆ --> 
In this regard, a plethora of soluble and membrane-bound cytokines execute the orders of bi-directionally orchestrated neuron-microglia communication. <!--ZMIENIĆ -->
This bidirectional cross-talk governs the delicate equilibrium between the neuroprotective and detrimental actions of microglia on neurons. <!--ZMIENIĆ -->
Cellular distribution of CX3CL1/CX3CR1 axis as well as a model of CX3CR1^GFP^/^GFP^ mice led to many reports on fractalkine-microglia cross-talk in healthy conditions. <!--spróbować napisać to lepiej In this regard, neurons regulate microglial function through the CX3CL1/CX3CR1 axis (Rogers et al., 2011).-->

<!--a chemokine which signals directly from the producing neurons to their effector microglia, the only cells expressing its cognate receptor CX3CR1 in the healthy brain (Nishiyori et al., 1998; Schwaeble et al., 1998; Maciejewski-Lenoir et al., 1999; Hughes et al., 2002). Paolicelli2014-->

Growing evidence suggests a delicate balance between the protective and detrimental influence of microglial activation on neuron functionality (Sierra et al., 2013). Bolos2018

In this regard, the impaired cross-talk between neurons and microglia is thought to be the underlying mechanism of other anatomical alterations found in CX3CR1-/- mice (Paolicelli et al., 2014; Zhan et al., 2014). <!--zmienić,Bolos2018-->
The first evidence of this phenomenon was provided by an elegant study by Paolicelli et al. (2011). <!--zmienić,Bolos2018-->
These authors showed that CX3CR1-/- mice exhibit impairments in the positioning of microglia in the CA1 region during embryonic development. <!--zmienić,Bolos2018-->
Thus, as a consequence of deficient synaptic pruning, CA1 pyramidal neurons show a postnatal transient increase in the number of synaptic spines (Paolicelli et al., 2011). <!--zmienić,Bolos2018-->
This is a beautiful example of the bi-directional manner in which the system is regulated. <!--zmienić,Bolos2018-->
The data obtained in the present work support the notion that microglia are key regulators of granule neuron connectivity during adulthood. <!--zmienić,Bolos2018--> 
In this regard, we and others have demonstrated that chronic inflammation negatively regulates the connectivity and functional maturation of newborn granule neurons (Ekdahl et al., 2003; Llorens-Martin et al., 2014) and that several of the pro-inflammatory cytokines that are increased in CX3CR1-/- mice (such as IL-6, TNF$\alpha$ and Eotaxin, among others) impair the generation of newborn neurons (Villeda et al., 2011). <!--zmienić,Bolos2018-->

Microglia, traditionally known as resident immune cells in the central nervous system (CNS), play essential roles in brain circuit maturation during development, participating in the precise refinement of synaptic connections (Tremblay et al., 2010; Paolicelli et al., 2011; Schafer et al., 2012; Zhan et al., 2014). <!--zmienić, Pagani2015-->
Microglial cells derive from myeloid lineage and colonize the immature brain during development, progressively acquiring a ramified morphology, commonly associated to surveying activity (Prinz and Mildner, 2011; Walker et al., 2014). <!--zmienić, Pagani2015-->
Ramified microglia lie very close to each other and have highly motile filopodia-like protrusions of variable shape, defining rarely overlapping niches of competency (Raivich, 2005). <!--zmienić, Pagani2015-->
Microglial processes continuously sample the extracellular space and contact preand post-synaptic elements (Davalos et al., 2005; Nimmerjahn et al., 2005; Wake et al., 2009; Tremblay et al., 2010). <!--zmienić, Pagani2015-->
Among the functional consequences of this active and continuous surveillance of the developing brain appear to be the shaping neuronal circuits by phagocytosis (Paolicelli et al., 2011) and favoring synaptic maturation (Hoshiko et al., 2012). <!--zmienić, Pagani2015-->
In damaged brain, microglial processes rapidly rearrange toward the site of injury (Nimmerjahn et al., 2005; Lee et al., 2008). <!--zmienić, Pagani2015-->
Among soluble factors activating microglial cells, ATP regulates microglial processes extention and ramification in both physiological and pathological conditions (Davalos et al., 2005; Inoue et al., 2007). <!--zmienić, Pagani2015--> 
To reach the site of activating stimuli, microglia retract their cellular processes and rearrange them in a directional manner toward the lesion. <!--zmienić, Pagani2015-->
In addition, a marked change in ionic channel expression has been observed (Boucsein et al., 2000). Indeed, in acute brain slices non-activatedmicroglia frequently display a small linear conductance, while following nerve lesion (Boucsein et al., 2000) or status epilepticus (Avignone et al., 2008) they transiently express inward and outward rectifier potassium (K+) currents (Menteyne et al., 2009; Kettenmann et al., 2011). <!--zmienić, Pagani2015-->
Ion channels have been involved in many microglial functional properties (Eder, 2005), such as cell volume regulation (Schlichter et al., 1996; Eder et al., 1998), proliferation (Kotecha and Schlichter, 1999), migration (Rappert et al., 2002; Schilling et al., 2004) and cell process extension and retraction (Eder et al., 1998). <!--zmienić, Pagani2015-->
However, microglia activation is no longer considered an all or none event, but rather a sequence of progressive stages (Ponomarev et al., 2007; Olah et al., 2012; Crain et al., 2013) depending on the balance between pro-inflammatory and anti-inflammatory signals in the surrounding environment (Biber et al., 2007; Lively and Schlichter, 2013).<!--zmienić, Pagani2015-->

CX3CR1 signaling has been shown to influence microglial function under both normal and pathological conditions (Limatola and Ransohoff, 2014; Paolicelli et al., 2014).
For example, a transient reduction of microglial density during hippocampal development has been reported in Cx3cr1 knockout mice (Paolicelli et al., 2011). 
However, previous studies examining microglia ramification did not evidentiate morphological differences (Liang et al., 2009; Hoshiko et al., 2012), 

Microglia are ramified cells that exhibit highly motile processes, which continuously survey the brain parenchyma and react to any insult to the CNS homeostasis. <!--Szepesi2018-->
Although microglia have long been recognized as a crucial player in generating and maintaining inflammatory responses in the CNS, now it has become clear, that their function are much more diverse, particularly in the healthy brain. <!--Szepesi2018-->
The innate immune response and phagocytosis represent only a little segment of microglia functional repertoire that also includes maintenance of biochemical homeostasis, neuronal circuit maturation during development and experience-dependent remodeling of neuronal circuits in the adult brain. <!--Szepesi2018-->
Being equipped by numerous receptors and cell surface molecules microglia can perform bidirectional interactions with other cell types in the CNS. <!--Szepesi2018--> 
There is accumulating evidence showing that neurons inform microglia about their status and thus are capable of controlling microglial activation and motility while microglia also modulate neuronal activities. <!--Szepesi2018-->

Microglia are the resident immune cells of the central nervous system, which represent about 5– 12% of total CNS cells in the healthy brain and the spinal cord. <!--Szepesi2018-->
Microglia are derived from the myeloid precursors cells in the embryonic yolk sac and they travel to the area of the developing CNS during early embryogenesis (Schulz et al., 2012; Ginhoux et al., 2013; Kierdorf and Prinz, 2013; Ginhoux and Prinz, 2015;Wieghofer and Prinz, 2016; Hoeffel and Ginhoux, 2018). <!--Szepesi2018-->
Microglial progenitors are already present around the neural tube at embryonic day 9 in mice, and from the fifth gestational week in humans. <!--Szepesi2018-->
After neural entry, microglia progenitors migrate through the developing nerve tissue and undergo massive proliferation before they reach their final density (Ginhoux et al., 2010; Verney et al., 2010). <!--Szepesi2018-->
Embryonic microglia develop into highly ramified mature microglia via regulatory factors such as Pu.1, IL-34, and CSF-1 (Schulz et al., 2012; Kierdorf et al., 2013). <!--Szepesi2018-->
Microglia are broadly distributed throughout the CNS although quantity and location among species varies (Lawson et al., 1990; Mittelbronn et al., 2001). <!--Szepesi2018--> 
Despite their broad distribution, microglia represent a rather heterogeneous community with different subpopulation based on specific brain regions. <!--Szepesi2018-->
Each microglia subpopulation develop unique features and they can be distinguished by capacities and functions (Gertig and Hanisch, 2014; Neiva et al., 2014; Doorn et al., 2015; Grabert et al., 2016; De Biase et al., 2017). <!--Szepesi2018-->
Microglia are considered to be the resident macrophages in the CNS and are long-lived, self-renewing cells, autonomous from peripheral monocytes that normally do not enter the brain. <!--Szepesi2018-->

Neural circuits are constantly monitored and supported by the surrounding microglial cells, using finely tuned mechanisms which include both direct contact and release of soluble factors. <!--Paolicelli2014-->
These bidirectional interactions are not only triggered by pathological conditions as a S.O.S. response to noxious stimuli, but they rather represent an established repertoire of dynamic communication for ensuring continuous immune surveillance and homeostasis in the healthy brain. <!--Paolicelli2014-->
In addition, recent studies are revealing key tasks for microglial interactions with neurons during normal physiological conditions, especially in regulating the maturation of neural circuits and shaping their connectivity in an activityand experience-dependent manner. <!--Paolicelli2014-->
Chemokines, a family of soluble and membrane-bound cytokines, play an essential role in mediating neuron-microglia crosstalk in the developing and mature brain. <!--Paolicelli2014-->

In recent years, microglia were demonstrated to originate from yolk-sac derived progenitors infiltrating the brain during early embryonic development, with no subsequent contribution to their renewal from bone-marrow derived myeloid cells (Ginhoux et al., 2010; Mizutani et al., 2012; Kierdorf et al., 2013). <!--Paolicelli2014-->
Microglia were also shown to be extremely dynamic in their once presumed “resting” state, continuously surveying the brain parenchyma and contacting preand post-synaptic elements with their highly motile processes (Davalos et al., 2005; Nimmerjahn et al., 2005; Wake et al., 2009; Tremblay et al., 2010). <!--Paolicelli2014-->
Their physiological roles discovered so far comprise the elimination of supernumerary neurons and the maturation of synapses in the developing brain (Hoshiko et al., 2012; Cunningham et al., 2013; Lenz et al., 2013; Ueno et al., 2013), the regulation of neuronal and synaptic activity (Li et al., 2012; Pascual et al., 2012), the elimination of apoptotic newborn neurons generated in excess during adult hippocampal neurogenesis (Sierra et al., 2010), and the activityand experience-dependent remodeling of neuronal circuits. <!--Paolicelli2014-->
Neuronal circuit plasticity is required for learning and memory processes in the developing and mature brain, where microglia contribute to both the formation and elimination of synapses (Tremblay et al., 2010, 2012; Paolicelli et al., 2011; Schafer et al., 2012; Parkhurst et al., 2013). <!--Paolicelli2014-->



**NEUROGENESIS**
Unlike other regions of the adult brain, the DG has a unique feature, namely it continuously generates new neurons throughout life – a process known as adult hippocampal neurogenesis (AHN) (Bayer and Altman, 1975; Gould et al., 1990). This property confers the entire hippocampal circuit with an extraordinary degree of plasticity and allows the participation of newly generated neurons in the fine tuning of hippocampal-related behavior (Nakashiba et al., 2012; Sahay et al., 2011).The incorporation of new synaptic elements to the hippocampal trisynaptic circuit as a consequence of AHN triggers a substantial remodeling of the pre-existing synaptic contacts (McAvoy et al., 2016; Toni et al., 2008; Toni et al., 2007). Bolos2018
This process is **positively modulated by the activation of inhibitory interneurons (Alvarez et al., 2016), which is, in turn, regulated by a specialized structure of the extracellular matrix (EM) called the perineuronal net (PN) (Yamadaand Jinno, 2017). This structure controls neuroplasticity through a variety of mechanisms (Miyata and Kitagawa, 2016, 2017).** In addition, the PN is thought to orchestrate the intercommunication between glial cells and neurons (Iozzo and Schaefer, 2015).  In this regard, it is known that microglia play a key role in synapse remodeling (Paolicelli et al., 2011; Valero et al., 2016). In addition, they exert a tight regulation of the whole process by regulating the number of newborn neurons that survive in the neurogenic niche (Sierra et al., 2010).Bolos2018

**Modulatory action of fractalkine**


**Minocycline**
Minocycline, a second-generation tetracycline, is well known for its antibiotic, anti-inflammatory, and antinoci- ceptive effects. Modulation ofsynaptic transmission is one of the analgesic mechanisms of minocycline. Although it has been reported that minocycline may suppress excitatory glu- tamatergic synaptic transmission, it remains unclear whether it could affect inhibitory synaptic transmission, which also plays a key role in modulating pain signaling. - Peng2016

minocycline has been recognized as playing two mainly independent roles: it is a microglial inhibitor as well as a second- generation tetracycline. Since microglia is an upstream partner of astrocytes in response to stimuli (Pascual et al., 2012), we next examined whether astrocyte activa- tion will affect sIPSCs - Peng

Minocycline, a semisynthetic tetracycline, is well
known for its functions, such as neuroprotection or antihypernociception, that have been identified in the last decade, and it typically acts by blocking microglial activation and reducing proinflammatory cytokine
production (Yong et al., 2004). - Peng

Moreover, the effect of minocycline may differ on different types of neurons. For example, minocycline (50 nM) had no effect on basal exci- tatory synaptic transmission in CA1 (Pascual et al., 2012). or SG neurons (Berta et al., 2014); however, 100 lM minocycline may inhibit dorsal root entry zone stimulation-elicited EPSCs in SG neurons (Cho et al., 2006) or may decrease sEPSC frequency and amplitude in hippocampal neurons (Gonzalez et al., 2007). At a con- centration of 200 lM, minocycline may decrease C-fiber evoked field potentials in the spinal dorsal horn, indicating an inhibition of excitatory synaptic transmission (Zhong et al., 2010). In addition, minocycline at 500 lM abolished the mustard oil-induced glutamatergic-dependent central sensitization in medullary dorsal horn nociceptive neurons (Itoh et al., 2011). The above observations suggest that minocycline may decrease neuronal excitability in a concentration- and cell-type-dependent manner by decreasing glutamatergic transmission. In addition to excitatory input, neurons also receive inhibitory synaptic transmission. If minocycline could modulate inhibitory synaptic transmission, then IPSC frequency or amplitude must be influenced by minocycline. In

Minocycline, a second-generation, broad spectrum, semi-
synthetic tetracycline antibiotic is of particular interest as an analgesic, in addition to its anti-microbial effect. Minocycline effectively crosses the blood-brain barrier (Aronson, 1980) and has a proven safety record in humans (Thomas and Le, 2004).Minocycline mediated inhibition of microglial activation has been reported to reduce nociception in inflammation-evoked pain (Hua et al., 2005), spinal cord contusion injury (Hains and Waxman, 2006) and spinal nerve ligation (Lin et al., 2007). While the majority of these studies attribute the analgesic effect of minocy- cline to inhibition of microglial activation (Tikka et al., 2001; Garrido-Mesa et al., 2013), some studies have also reported on its action on other targets like astrocytes (Zhang et al., 2012) and neurons (González et al., 2007). While reports indicate that minocycline has no direct effect on
the neurons, González et al. (2007) have reported that minocycline is associated with the mitigation of neuronal excitability, gluta- mate release, and Ca2þ overloading in hippocampal neurons. - Kannampalli2014

Recent reports suggests that minocycline inhibits Na+ channels in the primary afferent neurons (Kim et al., 2011) and also inhibits phosphorylated extracellular signal-regulated kinase (p-ERK) expression in the spinal cord (Cho et al., 2012), supporting a neuronal target for minocycline. Therefore, it is possible that the observed analgesic effect of minocycline in this study might not be exclusively through glial inhibition, but rather a combined effect on glial cells and neuronal targets. However, further experiments are warranted to identify these targets - Kannampalli2014

Microglia are considered the innate immune cells in the brain, and maintain central nervous system (CNS) homeostasis in response to changes in their microenvironment such as immune challenge and stress. Microglia are extremely plastic and microglial activation has been associated with specific morphologic changes; during activation, microglia retract their processes, resulting in decreased occupied area and increased soma size.9 - Yuan2020

Microglia are the resident myeloid cells ofthe brain (Sierra et
al., 2014) and are thought to mediate the first response to inflam- matory signals. In addition, microglial interactions with synapses are important in maintenance ofneuronal connections and affect neuronal plasticity (Wake et al., 2009; Tremblay et al., 2010a). In healthy and developing brains, microglia prune synapses at both presynaptic and postsynaptic sides and thus regulate synaptic innervation (Paolicelli et al., 2011; Schafer et al., 2012). Recently, a crucial role for microglial autophagy in synaptic pruning has been demonstrated (Kim et al., 2017). The molecular cues that guide microglia to the synapses destined for engulfment remain to be identified, as do the specific mechanisms that are recruited. However, it is thought that the complement factors C1 and C3 ‘tag’ such synapses and thus direct the microglia to them for phagocytosis (Schafer et al., 2012; Bialas and Stevens, 2013). In addition, synaptic stripping, which is the physical separation of presynaptic and postsynaptic elements by intervening microglial processes, is well documented upon injury (Kettenmann et al., 2013). - Acharjee2018b

Given the role of microglia in regulating synapse number (Tremblay et al., 2011; Stephan et al., 2012; Schafer et al., 2013; Wuet al.,2013, 2015), we explored a possible role for microglia in the BLA during early EAE. Microglial morphology reflects their functional activation state (Zanier et al., 2015). In the unchallenged state, surveillant microglia present a ramified morphology, highly motile processes that interact with synapses, whereas upon “activation,” their processes typically retract as the cell body becomes hypertrophied (Tremblay et al., 2010a). “Activated” microglia are also well known to display an increased expression of IBA-1 in various contexts of injury and disease (Norden et al., 2016; Wang et al., 2017). We have previously shown that electron microscopy (EM) can reveal the functional state ofmicroglia in a highly sensitive manner (Tremblay et al., 2010a). Based on that work, we quantified microglial ultrastructural features in pre-onset EAE by transmission EM using an immunoperoxidase staining against IBA-1. ;;

* **Microglial processes constantly survey the brain parenchyma,transiently contact neuronal elements, and can also engulf cellular debris and eliminate synapses**. Using immunocytochemical EM against IBA-1, we found direct contacts between microglial process and neuronal perikarya, as well as presynaptic elements, postsynaptic elements, and synaptic clefts. Synaptic elements showing signs of autophagy were also frequently contacted by microglia in both CFA and EAE. **Microglial inclusions, sometimes containing recognizable synaptic elements that probably resulted from phagocytosis, were occasionally encountered in both conditions**. **In addition, features associated with extracellular digestion or “exophagy” (Haka et al., 2016), such as microglial processes in association with extracellular space pockets that contained partially to completely disrupted cellular membranes, as well as synaptic elements, were observed**. **These features are suggestive of ongoing extracellular digestion, either mediated by microglial remodeling of the extracellular matrix or release of lysosomal proteins.** The prevalence of extracellular digestion was significantly reduced in EAE. **Accordingly, the expression of CD68 in IBA-1-labeled cells, a lysosome-associated protein often used as a marker of microglial “activation” or “phagocytosis” was significantly reduced** in the BLA of EAE mice compared with CFA controls.;;

* **However, we acknowledge that minocycline, in addition to impairing microglial proinflammatory and phagocytic activity, has many other unrelated effects; however, our use of ICV injection at least eliminated the peripheral effects of minocycline (Brundula et al., 2002; Giuliani et al., 2005)** Thus, to determine further whether microglia specifically control synaptic transmission in the BLA, we injected Saporin toxin conjugated to macrophage antigen complex-1 (Mac-1, integrin CD11b/ CD18 receptor localized to microglia) directly into the BLA of 8-week-old C57BL/6N females to transiently deplete microglia. IgG-Saporin, which does not bind to any specific receptor, was used as a control.;;

*  Microglia can react rapidly to infection, trauma, and other danger signals, by retracting their processes and enlarging their cell body. However, microglial phenotypes vary depending on the type of stimulus and by brain region (Morrison and Filosa, 2013; Abiega et al., 2016). Genome-wide analyses of microglia of different CNS regions showed that cerebellar and hippocampal microglia exist in a more vigilant state than do microglia in other brain areas (Grabert et al., 2016). Even within the hippocampus, the microglia of area CA3 are more sensitive to LPS compared with those of CA1 or dentate gyrus (Madore et al., 2013). Thus, it is not surprising that we saw different effects in BLA compared with what another group reported in the striatum.;;

* In contrast, a recent study with microglial gene profiling using microarray analysis revealed suppression of microglial genes during the early stages of EAE development; specifically, the genes related to their phagocytic functions and cytoskeleton organization were suppressed (Yamasaki et al., 2014). This suppression could have multiple effects, such as reduced phagocytosis, cytokine, chemokine, and metalloproteinase production (Shemer et al., 2015).;;

* Reduced extracellular spaces between the neuron and microglia were also observed in the EAE amygdala. These spaces generally contained material undergoing digestion in the CFA controls (synaptic elements that could be identified or membranes in a more advanced state of digestion), suggesting a reduced pruning of synaptic materials in EAE (Haka et al., 2009; Singh et al., 2016).;;

* It seems that glial cells can affect neural function and reward-related process by releasing certain cytokines and chemokines (Narita et al. 2006; Niwa et al. 2007a). - Arezoomandan2018

Minocycline affects dopamine (Hashimoto et al. 2007) and glutamate transmission and depresses Ca2+ signaling in hippocam- pal neurons (González et al. 2007). Furthermore, there is enough evidence that a cross talk exists between neu- rons and glial cells. Microglia secrete proinflammatory mediators such as prostaglandins, proteases, cytokines (tumor necrosis factor-α, interleukin-1β, interleukin-6) and excitatory amino acids, which can affect neural activity as well as neuronal circuit involved in drug addiction (Coull et al. 2005; Niwa et al. 2007b; Yirmiya & Goshen 2011). Minocycline can affect expression of these factors. It has been shown that minocycline is able to upregulate the expression of brain-derived neurotrophic factor and tumor necrosis factor-α (Chen et al. 2012b).
- Arezoomandan2018