## Amygdala       

The amygdala, a complex comprised of heterogenous collection of nuclei, is located in the medial temporal lobe. 
These nulei can be distinguished based on their different connectivity, immunohistochemical and cytoarchitectural profiles.
Unfortunately, due to the complexity of this structure, there is no standardization in naming the amygdaloid nuclei. Historically, amygdala nuclei are divided into three groups: (1) the deep or basolateral group, which includes the lateral nucleus, the basal nucleus, and accessory basal nucleus; (2) the superficial or cortical-like group, which includes the cortical nuclei and nucleus of the lateral olfactory tract; and 3) the centromedial group composed of the medial and central nuclei and listed separately nuclei that do not easily fall into any of these three groups - intercalated cell masses and the amygdalohippocampal area [@mcdonald_1998; @sah_2003]. 
However, since then many excellent papers mainly focused on three domains due to their contribution in fear-conditioning: the basolateral complex of the amygdala (BLA), the central amygdala (CeA) and intercalated cell masses (ICM) [@bocchio_2016; @duvarci_2014; @ehrlich_2009; @pape_2010; @spampanato_2011] and here this classification will be used <!--{ref. figure classification}-->.

This limbic region is involved in mood regulation, fear-conditioning/associative learning, and modulation of cognitive functions [@ehrlich_2009; @herry_2010; @ledoux_2000; @roozendaal_2009].
Amygdala is also involved in an integration of autonomic responses to homeostatic challenges, including from the peripheral immune system [@pachecolpez_2005]. <!--więcej cytowań-->
Importantly, the circuitry and function of this structure is well-conserved across evolution and even non-mammalian species, including reptiles, birds and fish, have an amygdala-like brain region, which serves similar functions to the mammalian amygdala [@jarvis_2005]. <!-- bardziej zmienić? //// The amygdala is a brain region that is important for emotional processing, the circuitry and function of which has been well-conserved across evolution (Fig. 1), although species differences do exist1. Even non-mammalian species such as reptiles, birds and fish have an amygdala-like brain region with similar circuits and functions to the amygdala in mammals2–5 ///// -->

### Structure

#### The basolateral complex of the amygdala (BLA)

The basolateral complex consist of the lateral nucleus (LA), the basal nucleus (B), which is sometimes called the basolateral nucleus (BLA), and the basomedial nucleus (BMA), which is also known as accessory basal nucleus [@krettek_1978]. 
In order to avoid misunderstanding, I will refer to the basolateral complex as BLA and basal/basolateral nucleus as B. 
The BLA is considered to be the main point of entry for cortical and subcortical sensory inputs into the amygdala [@duvarci_2014]. 
This nuclei developmentally and structurally is a cortical-like structure [@waclaw_2010]. 
Within this nuclei approximately 80% of all neurons are glutamatergic pyramidal-like principal cells and the remaining 20% belong to a heterogeneous group of interneurons [@duvarci_2014; @mcdonald_1993; @spampanato_2011].

##### Principal cells

Principal cells show many morphological and electrophysiological characteristics similar to their cortical and hippocampal pyramidal counterparts, including spiny complex dendritic trees and prominent spike frequency adaptation in response to current injections [@faber_2001; @par_1995]. 
However, these cells are heterogenous regarding their morphological profile as well as their spike frequency adaptation degree varies forming continuum: at one end cells fire two to three spikes only and show marked spike frequency accommodation, whereas at the other end cells fire repetitively throughout the current injection with little accommodation [@faber_2001; @funahashi_2000]. <!-- może jakiś figure? see Fig. in methods?-->
Moreover, no correlation was found between the cells’ firing properties and their morphology [@faber_2001; @funahashi_2000]. 


Interestingly, neurons with prominent spike frequency adaptation were shown to have larger afterhyperpolarization (AHP) than those that fire repetitively [@faber_2002; @sah_1996]. 
As a rich repertoire of ion channels shape the firing pattern of mammalian central neurons (for example: @bean_2007), it is suggested that principal cells have differential distribution of calcium-activated potassium channels responsible for AHP, which leads to difference in their repetitive firing properties [@faber_2001; @faber_2002].
Additionally, another electrophysiological characteristics of principal neurons in BLA are: relatively wide  action potentials (half-width = 1.2 ms), <!--....., .....-->. 
Interestingly, some of them display bursting activity or a delay in firing when depolarized from more negative membrane potentials, which is thought to be due to the presence of low-treshold, slowly inactivating potassium current  [@washburn_1992].

##### Interneurons

Interneurons, in contrast to BLA principal cells, have aspine, smooth dendrites and their axon collaterals are restricted to the basolateral nuclei [@mcdonald_2001; @mcdonald_2002; @mcdonald_2004].
However, it is difficult to identify different types of interneurons based on their immunohistochemical, morphological, and electrophysiological characteristics [@spampanato_2011].
Morphologically they could be subdivided into multipolar, bitufted, and bipolar cells according to their dendritic trees [@mcdonald_1982]. 
Moreover, similar to the neocortex and the hippocampus, interneurons in the BLA can be characterized by their expression of similar<!--?--> neurochemical markers. 
Although there may be differences in relative ratios of interneuron types regarding brain region, in the BLA the main two non-overlapping groups are those that express calbindin (around 50% of neurons in the BLA) and calretinin (around 20% of neurons in the BLA) [@kemppainen_2000; @mcdonald_2001; @mcdonald_2002].
Each of these groups can be further sub-divided based on their expression of somatostatin (SOM+), vasoactive intestinal peptide  (VIP+), cholecystokinin (CCK+), and parvalbumin (PV+) (for review: @spampanato_2011). 

Regarding the electrophysiological profile of BLA interneurons, contrary to principal cells, they show no apparent spike frequency adaptation in response to a prolonged depolarizing current injection, their action potentials have shorter duration (half-width 0.7 ms), and they fire spontaneously *in vivo* at high frequencies (10-15 Hz)  [@spampanato_2011; @pare_1995]. 
Consistent with the notion that the BLA is a cortical-like structure, these firing properties are similar to those found in cortical interneurons [@petillainterneuronnomenclaturegroup_2008], but different from those of GABAergic neurons in the CeA [@dumont_2002; @lopezdearmentia_2004]. 
Specifically, electrophysiological analyses have identified at least six distinct types of firing properties [@jasnow_2009; @mahanty_1998; @sosulina_2010; @woodruff_2007]. 
There is no correlation between neurochemical markers and electrophysiological profile. <!--usunąć?//zminić-->
For example, four electrophysiologically separable types of cells were found to express PV in combination with either CCK or CB [@sosulina_2010]. 
The roles of these neurons with different firing properties are not currently understood, but it speculated that cells with disparate electrophysiological properties will involve different local circuits and have distinct afferent/efferent connections. <!-- cytowanie?-->

#### Central amygdala 

Central amygdala (CeA) is comprised of capsular (CeC), lateral (CeL), medial (CeM) and intermediate (CeI) divisions [@jolkkonen_1998; @mcdonald_1982a; @sah_2003]; however the classification of these areas is inconsistent. <!-- inne cytowanie? problem z nim bo takiego nie ma  [@Cassell1986].-->
Significantly, the capsular region of the CeA appears to overlap with intercalated cell clusters (ITC) [@mcdonald_1982a; @pape_2010] and latter term will be used in this dissertation.
Additionally, CeA is commonly divided into the CeL and CeM divisions and there is a sparse number of investigations regarding CeI and CeL as a functionally and anatomically distinct subdivisions [@ciocchi_2010; @duvarci_2014; @haubensak_2010]. 
Therefore, in this dissertation, the latter classification will be used. 
In some papers, CeA is also considered to be a part of extended amygdala, together with the bed nucleus of stra terminalis (BNST), as they have similar cell types and they are densely inter-connected and share similar connectivity patterns with other brain regions [@fox_2015; @sah_2003]. 
However, BDST is out of the scope of this dissertation. 

Contrary to the BLA, CeA is considered as a main output nuclei [@ciocchi_2010; @haubensak_2010; @hou_2016].
Its neurons are GABAergic, morphologically reminiscent of striatal medium spiny neurons [@mcdonald_1993; @sun_1993].  
This is consistent with different developmental origins of the BLA and the CeA [@medina_2004; @waclaw_2010]. 
Precisely, CeL neurons mainly have similar medium spiny neurons-like morphology with relatively small soma and multiple primary dendrites with numerous branches with high density of spines. <!-- bardziej porównanie BLA i CeA a nie CeA i CeM-->
In contrast, CeM neurons have a large soma, dendrites with few branches with low density of dendritic spines [@cassell_1989; @mcdonald_1982a]. <!--[@Marina1999; @Hall1972-->
Similarly to neurons in striatum, neuronal cells in CeA also express wide selection of neuropeptides and markers, including protein kinase C`r knitr::asis_output("\U03B4")` (PKC`r knitr::asis_output("\U03B4")`), somatostatin (SOM), corticotropin-releasing factor (CRF), oxytoxin receptors (OR), enkephalin and others [@cassell_1989; @haubensak_2010]. 
Of these, PKC`r knitr::asis_output("\U03B4")` and SOM are the two most highly expressed and largely non-overlapping neurochemical markers [@haubensak_2010; @hunt_2017; @li_2013].

Based on their electrophysiological profiles<!--response to current injections-->, two major types have been described in the CeA: (1) late-firing neurons (LF), which display a pronounced delay before onset of the first action potential (100-200 ms) mediated by K~v1~-dependent slowly inactivated D-type K^+^ currents [@hou_2016; @martina_1999] and (2) regular-spiking neurons (RS), which fire spikes repetitively  [@dumont_2002; @lopezdearmentia_2004].
Two further types of neurons were described in the CeA, however they are very rare (each does not exceed more than 10% of whole CeA neuronal population): (3) fast-spiking cells and (4) low-treshold bursting cells [@marina_1999].

Fast-spiking cells have a high membrane resistance and a high action potential frequency (>40 Hz), showing no accommodation, similarly to subtype of interneurons present in cortex, hippocampus or BLA. 
Their action potentials are significantly briefer with a half-width of around 0.6 ms compared with more than 1 ms in other cell types in CeA. 
They have also higher frequency of spontaneous synaptic events (sEPSP). 
CeA neurons display aspiny morphology. 
These neurons likely correspond to local-circuit cells. 
Low-treshold bursting cells are endowed with a T-type calcium current, giving rise to spike bursts. 
They also show display rebound spikes after hyperpolarizing current step [@dumont_2002; @hou_2016]. 

Considering expression of immunohistochemical markers, electrophysiological properties, and synaptic connections, two groups of CeA neurons have emerged: PKC`r knitr::asis_output("\U03B4")`-expressing  (PKC`r knitr::asis_output("\U03B4")`+) and SOM-expressing (SOM+) neurons. 
PKC`r knitr::asis_output("\U03B4")` marker is specific to CeA. 
PKC`r knitr::asis_output("\U03B4")`+ neurons are relatively homogeneous group: they are mainly late-firing cells (~85%) and display reduction of activity following fear conditioning protocol (CeL~off~ cells). 
In contrary, most of the PKC`r knitr::asis_output("\U03B4")`- cells are SOM+ display heterogeneous intrinsic excitability with both late-firing (40%) or regular-spiking types (60%). 
Moreover, these neurons respond to the fear conditioning with an increase in activity, and have therefore been called CeL~ON~ neurons [@ciocchi_2010; @haubensak_2010; @hou_2016; @li_2013]. 
Therefore, it seems that these distinct populations have been associated with different functional roles.

#### Intercalated masses

Intercalated (ITC) neurons do not form a compact nucleus but form numerous small densely packed cell clusters distributed in the main fiber bundles found in and around the amygdala. <!-- figure -->
In particular, these fiber bundles are the external capsule that borders the BLA laterally as well as the intermediate capsule, the fiber bundle separating the BLA from the CeA. 
ITC clusters located in the external and intermediate capsules called lateral (ITC~L~) and medial (ITC~M~), respectively.
Intercalated neurons are GABAergic cells [@McDonald1993; @Nitecka1987] with small (10–15 `r knitr::asis_output("\U00B5")`m) ovoid cell bodies. Their dendritic trees are spiny, flattened, long and mostly remains within border of the fiber bundle where their soma is located [@Millhouse1986]. 
Regarding their electrophysiological features, ITC cells have higher membrane resistance and firing frequency compared with BLA and CeA interneurons [@duvarci_2014; @royer_2000]. 
Their high intrinsic firing frequency could be explained by their ability to express afterhyperpolarization (AHP) after action potential, which is explained by slowly-inactivating K+ currents (I~SD~) [@royer_2000].
ITC neurons express the highest density of `r knitr::asis_output("\U00B5")`-opioid and dopamine type-1 receptor (D1) in whole amygdala [@jacobsen_2006; @palomarescastillo_2012; @pape_2010], that indicates the possibility of modulation of amygdala activity by opioid and dopaminergic systems. 
As the intercalated cells inhibit neurons in the CeA, therefore modulation of the activity of these neurons will have an impact on the output of this structure.
Additionally, these neurons are surrounded by a small subset of larger (>50 `r knitr::asis_output("\U00B5")`m) cells with long thick dendrites. 
Still, little is known about these larger neurons within ITC masses. 
Previously, they were regarded as cholinergic neurons [@nitecka_1989]; however recent a report demonstrated that they are also GABAergic, and in addition display strong expression of metabotropic glutamate receptor 1`r knitr::asis_output("\U03B1")` (mGluR1`r knitr::asis_output("\U03B1")`) and GABA~A~ receptor `r knitr::asis_output("\U03B1")`1 subunit, and parvalbumin (PV) [@bienvenu_2015].


#### Other nuclei

Here, I will briefly describe the remaining amygdala nuclei, as they are beyond of scope of this dissertation. They include <!--the cell types and connectivity of--> the medial nucleus of the amygdala (MeA), the anterior amygdala area (AAA), and the amygdalo-hippocampal area (AHA).

##### Medial nucleus

The MeA consists of two types of morphologically distinct neurons: multipolar bitufted and spiny stellet neurons [@rasiafilho_2004]. 
Physiologically, MeA neurons are either regular-spiking neurons, adapting neurons, or fully accommodating neurons [@niimi_2012]. 
Interestingly, MeA is fuctionally different from other amygdala nuclei due to its key role in the reproductive, defensive, maternal and social behaviors and its involvement in pheromone and olfactory signaling [@bian_2013; @ferguson_2001].

##### AAA

<!-- czyli rozumiem, że mam uzupełnić? -->

##### AHA

The cell types observed in the nucleus of the lateral olfactory tract, the amygdalohippocampal area, and the cortical nuclei are similar to those in the basolateral complex. 
The majority of the cells are pyramidal-like with smaller stellate cells (which resemble the local circuit neurons), spiny stellate cells, and neurogliaform cells also present to lesser degrees <!--później dodać cytowanie--> [MCDONALD AJ. Cytoarchitecture of the nucleus of the lateral olfac- tory tract: a Golgi study in the rat. Brain Res Bull 10: 497–503, 1983.]. <!-- uzupełnić cytowanie-->
Orientation of neurons in the olfactory areas is more cortical-like with apical dendrites oriented parallel to each other. 
To the best of my knowledge, there have been no detailed studies of the electrophysiological properties of neurons in these other nuclei. 

### Amygdala functional circuits

The amygdala is documented to have widespread connections with a variety of other structures, from the prefrontal cortex to the brainstem (for reviews: @duvarci_2014; @pape_2010; @sah_2003. 
The oversimplified model of the amygdala circuit is as follows: it receives many distinct inputs.
Then, it computes the information *via* complex connections of intra-connected nuclei with many levels of modulation.
Finally, it sends output to various brain regions, which suggests that the amygdala could influence other parts of the brain as well as behaviors mediated by those regions. <!--  It serves as a hub .-->

Indeed, several lines of evidende indicate that amygdala is involved in very distinct behaviour related with learning, fear, anxiety, reward and addiction. <!-- citations? --> 
At first glimpse, this variety of functions could be surprising, but most of them are related to associative learning, e.g fear conditioning and its malfunctions. 
In order to survive, when confronted with particular events, animals must discriminate and learn specific environmental stimuli that predict potentially life-threatening or sustaining events, so that they can mobilize adaptive responses to those stimuli in the future. 
This form of learning is termed Pavlovian conditioning. 
For example, during fear conditioning, an neutral stimulus, such as an acoustic tone (i.e., the conditioned stimulus [CS]), that predicts an aversive outcome, such as a footshock (i.e., the unconditioned stimulus [US]), results in defensive responses, such as freezing behavior [@janak_2015; @ledoux_2000].
Therefore, amygdala has been conserved throught evolution and even non-mammalian species such as reptiles, birds and fishes have a counterpart with similar circuits and functions to the amygdala in mammals [@janak_2015]. <!-- już to chyba wcześniej pisałam, jak tak to wywalić wcześniej-->
Recent technological advances and approaches, including optogenetic and pharmacogenetic, in conjunction with genetic targeting of specified cells, battery of behavioural tests and electrophysiology, enable determining how neuronal activity within the amygdala could contribute to each of these distinct processes.
It can provide new insights into behavioural functions of amygdala neuronal activity, revealing a complex picture of amygdalar control of behaviour.

#### Amygdala afferents

As amygdala is involved in complex processes crucial for learning adaptive responses for survival, it indicates that there must be a diversity of neuronal responses in the BLA. <!-- really? it must? -->
BLA complex is regarded as the main input nuclei of the amygdala, because pyramidal-like cells receives glutamatergic projections from all sensory modalities, mainly *via* cerebral cortex: olfactory, somatosensory, gustatory and visceral, auditory, and visual (for review: @pape_2010; @sah_2003). 
The majority are ipsilateral connections that enter the amygdala *via* the external capsule [@mascagni_1993; @sah_2003].
The prefrontal cortex is a major source of cortical projections to the amygdaloid complex in all species [@duvarci_2014; @mcdonald_1996; @pape_2010; @sah_2003]. 
Especially its medial part (mPFC) serves as a major input to the BLA, regulating fear extinction and expression [@burgosrobles_2009; @milad_2002; @sotresbayon_2010].
A large body of evidence, including fMRI studies in humans [@labar_1998], highlight the BLA involvement, its lateral part, in acqusition of fear conditioning [@ledoux_1990] @Blanchard1972]. <!-- nie podoba mi sie to its lateral part, dodać cytowanie, chociaż ona jest ... -->
Principal cells in the LA are thought to simultaneously receive initially weak afferent carrying sensory information about the CS and a strong afferent carrying US information when these experiences are paired. 
This leads to LTP-mediated enhanced strength of the excitatory synapses carrying CS information [@kim_2017], which enables CS alone to activate LA neurons and induce the freezing behaviour. 
Importantly, optogenetic stimulation of principal cells in LA, paired with a neutral tone (CS; without footshock) produced an increase in freezing both during training and in a later retention test [@johansen_2010]. 
Similarly, photoactivation of LA axonal terminals from the auditory thalamus (the medial geniculate nucleus, MGN) and the auditory cortex (AC) when applying footshock (without a neutral tone) leads to conditioned freezing and synaptic potentiation [@nabavi_2014]. 
Intriguingly, optical stimulation of a subset of principal neurons, which express Thy1 promoter, did not affect freezing behaviour during acoustic fear conditioning [@jasnow_2013]. <!-- DODAĆ CYTOWANIE, JUŻ ŚCIĄGNIĘTE -->
However, stimulation of these neurons enhanced the retention of the extinction learning [@jasnow_2013]. <!-- DODAĆ CYTOWANIE, JUŻ ŚCIĄGNIĘTE -->
Therefore, as suggested @lalumiere_2014<!-- dodać cytowanie, ściągnięte -->, optical activation of this neuronal subpopulation had no effect on the acute expression of fear but rather appeared to influence consolidation specifically for memories that oppose fear conditioning. 
Above-mentioned notion that BLA neurons contribute to consolidation of learning is further supported by several lines of evidence. 
Firstly, the BLA complex has strong reciprocal connections with structures involved in long-term declerative memory, including the perirhinal cortex, the entorhinal cortex, the parahippocampal cortex, and the hippocampus [@McDonald2000; <!--cognitive review i brak tego artykułu...-->]. 
Moreover, the consolidation in the BLA is thought to be mediated by synchronized oscillations at theta and gamma frequencies in local ensembles of projection neurons [@bauer_2007; @pelletier_2004]. 
Recent work by @huff_2013 shows that optical stimulation of BLA pyramidal cells with bursts of light pulses in gamma frequency (40 Hz) for 15 min, right after inhibitory avoidance training, enhanced retention 2 days later. 
Importantly, other frequencies did not change retention. 
Conversly, inhibition of these neuron for 15 minutes impaired retention of the learning [@huff_2013].

Just as BLA neurons develop excitatory responses to a CS paired with aversive stimuli, the same scenario takes place when CS is paired with rewarding stimuli, such as sweet liquid or food pellets [@schoenbaum_1998; @tye_2007; @tye_2008]. 
Thus, not only fear conditioning, but also reward cue responses develop through long-lasting enhancement of glutamatergic inputs from sensory thalamus onto principal neurons in the LA 78. 
Moreover, the acquisition of conditioned responding to both fear and reward cues requires an NMDA-receptor-dependent increase in AMPA-receptor function in LA neurons44,46,78. The end result of this synaptic potentiation is that the cue is able to drive spiking in LA neurons, which in turn activates neuronal populations in downstream regions that contribute to the cue-triggered behaviour. Clearly, learning about environmental stimuli that predict the occurrence of food and other rewards is adaptive, as is learning about potential aversive outcomes. Thus, learning across a valence continuum of positive (rewarding) to negative (punishing or aversive) outcomes engages the amygdala.

Principal cells in the BLA complex are not the only cell types that receives projection from other structures. Some reports indicates that interneurons in the BLA also receives excitatory inputs from cortical and thalamic sources [@Szinyei2000]. Moreover, @Chu2012 demonstrated that activation of D2 receptor in parvalbumin-expressing interneurons in LA reduced GABAergic transmission only to principal cells, but not to other interneurons. Therefore, different stimuli could influence only a subset of cell population in BLA. Moreover, dopamine, released by axons originated in midbrain [@Asan1997], has crucial role in modulating BLA actiity. Some studies also show actions of this neuromodulatior on intercalated cells, especially the medial cluster, but in D1 receptor-dependent manner [@Marowsky2005]. These cells receive sensory input as well, participating in fear conditioning [].<!--Thus, multiple plastic systems, and especially those integrating GABAergic neurons, could act in concert to encode aspects of stimulus associations in the amygdala.-->

Importantly, CeA, which is regarded as main output nuclei, also receive substantial inputs . Moreover, CeL receives oxytonergic innervation from hypothalamus and release of oxytocin from their axon terminals results in increase in neuronal activity in this region [@Knobloch2012]. Additionally, a stimulation of oxytogenic terminals during fear conditioning leads to attenuation of freezing behavior [@Knobloch2012]. Stimulation of axons from another CeL input, parabrachial nucleus, leads to suppresion of appetite [@Carter2013], which suggests that CeL has many paralel circuits. <!--CeA receives projections from BNST [@Gungor2015]-->

In addition to excitatory, oxygenic and dopaminergic innervations, nuclei in amygdala are also strongly modulated by acetylocholine [@Washburn1992a], norepinephire [@Faber2002], serotonin, and opioids <!-- more citations -->. 

Thus, each nuclei receives multiple inputs from yet distinct brain regions //unique set of inputs, which 
On a larger level, these findings contribute to our understanding of how specific inputs, and even genetically distinct inputs, to the amygdala regulate both behavior and local circuit activity

This picture is more complex when added a role of neuromodulators. Neurons in CeL and CeM express many neuropeptides (Gray and Magnuson 1987, 1992; Woodhams et al. 1983) that likely modulate fast inhibitory and excitatory neurotransmission (Kash et al. 2015; McElligott and Winder 2009). 

#### Intrinsic amygdala connections

In the BLA, principal cells prefer to form local synapses with proximal interneurons [@Szineyi2000] and longer distance collaterals send onto other principal cells. The latter connections seems to be formed with preferential lateromedial directionality: LA principal neurons send many projections onto neurons in basal nuclei (B) [@Krettek1978; @Pitkanen1997; @Duvarci2014]. 
On the other hand, interneurons in the BLA form synaptic connections, creating local circuit networks [@Lang1998]. Consistent with this idea, their axon branch several times creating many axon collaterals and terminals near the cell body [Millhouse1983]. 
-----------
Activation of these cells in the basolateral complex generates inhibitory synaptic potentials that have GABA~A~ receptor dependent fast and GABA~B~ receptor dependent slow components (108, 218, 284) (135, 218, 284).  Measurements of spontaneously occurring miniature inhibitory synaptic currents have suggested that different interneurons in the basolateral complex are responsible for generating the GABAA and GABAB receptor-mediated component of inhibitory synaptic current (263).  In contrast to most other cells, the slow component of the inhibitory synaptic potential in LA pyramidal neurons is in part generated by a calcium-activated potassium conductance that is activated by calcium influx via NMDA receptors (39, 108). This observation raises the possibility that NMDA receptors in lateral amygdala neurons might be coupled to calcium-activated potassium channels.
However, it is possible that the excitatory inputs to interneurons are due to activation of axon collaterals of pyramidal cells, which indicates a feedback role for interneurons. Tract tracing studies in the cat and monkey found that cortical afferents form few if any synapses with parvalbumin positive neurons, while local afferents do make synapses onto them (262). In contrast, a similar study in the rat has described thalamic inputs to interneurons in the LA (295). These findings are consistent with the proposal that different populations of interneurons can have a feed-forward and/or a feedback role in the basolateral complex.
Interestingly, glutamatergic input of BLA interneurons, partly from local principal cells, have unusual properties: their synapses contain AMPA receptors with low GluR2 subunit in the postsynaptic membrane and no NMDA receptors [@McDonald1996; @Mahanty1998]. Generally, including principal BLA or interneurons from other brain areas, their glutamatergic input contain both NMDA- and AMPA- receptors. Moreover,
AMPA receptor are heterodimers with 4 possible subunits: mGluR1-4. It was documented that AMPA receptors with few or no mGluR2 component results in strong inward rectification and calcium permeability [@Washburn1997].
------------
Additionally, principal cells in LA, BL and BM innervate the CeA, either directly by forming glutamatergic synapses [@DeArmentiaMikelLopezSah2004; @Krettek1978] or via GABAergic ITC~m~ neurons, leading to feed-forward inhibition [@Jungling2008; @Royer1999]. In particular, whereas LA exclusively projects to CeL, the BA nuclei also make synapses onto CeM neurons [@Krettek1978]. Moreover, neurons in LA preferentially make synapses onto ITC cluster located dorsally (ITC~DM~); whereas ventral medial cluster (ITC~VM~) receives input from BL and BM principal cells [@Royer2000]. The study conducted by @Tye2011 nicely showed that optogenetic stimulation of BLA terminals <!-- or cell body --> in CeL reduced anxiety-related behaviour in freely moving mice, whereas inhibition of these terminals increased this behavioural phenotype. Importantly, this fear-related behaviour was dependent on feed-forward inhibition of the CeM [@Pare2004; @Ciocchi2010; @Tye2011] <!-- BLA-cell-body activation decreased time spent by mice in the open arms of an elevated plus maze (EPM), indicating an increase in anxiety-like behaviour --> Thus, a glutamatergic BLA projection to the CeA can promote anxiolysis.

/// CeL:PKCδ+ neurons to allow their direct photoactivation, increased time in the open arms of the EPM was observed58. These data support the notion that a population of BLA neurons preferentially excites CeL:PKCδ+ neurons that lead to reduced anxiety, perhaps through the projection from CeL:PKCδ+ to CeM output neurons. Alternatively, the CeL:PKCδ+ neuronal projection to the BNST, also implicated in anxiety59,60, could mediate anxiolysis. These studies show that the BLA–CeA pathway does not universally promote aversive states.
////////////


Indirect connection via ITC clusters 
Additionally, within each ITC cluster, intercalated neurons form GABAergic reciprocal synapses onto other intercalated cell [@Geracitano2012; @Royer2000] and between clusters, at least dorsal and ventral medial clusters []. Simiarly to BLA connections' pattern, neurons in ITC cluster located dorsolaterally (ICMMD) send more projections to the CeM than CeL, whereas opposite relation was observed in dorsally located ITC mass[@Royer1999; @Pare1993].
However, little is known about the intercalated cell cluster in the external capsule. It was documented that these cells form synapses with BLA neurons and does not project to CeA [@Marowsky2005]. It is tempting to speculate that similar to their medial counterparts, these intercalated neurons modulate cortical inputs to the BLA. 


/////////////////////
• The PV+ interneurons receive strong excitatory inputs from BLA principal cells but weak inputs from the cerebral cortex [@Smith2000] suggesting a main role in feedback inhibition. On the other hand, large inhibitory synaptic events underlie spontaneous and cortically-evoked membrane potential fluctuations of BLA pyramidal-like cells [@Lang1997; @Popescu2011]. Since BLA interneurons fire robustly during oscillatory activity, inhibition of principal cells may also originate from feed-forward action of local GABAergic neurons [@Lang1998]. An interesting recent study sheds light on this issue showing that CB+ interneurons mediate cortically-evoked feedforward inhibition in the BLA [@Unal2014]. Selective feed-forward and feed- back inhibition onto principal cells has been suggested to be mediated by different types of PV+ interneurons of BLA [@Woodruff2007]
• Limited quantitative information is available on the relative innervation by BLA interneurons of excitatory or inhibitory cells [7]. It is clear from both functional and anatomical data that PV expressing cells powerfully inhi- bit both principal cells as well as other interneurons [@Woodruff2007, @Muller2005]. A recent study demonstrates an interesting target-specific effect induced by dopamine acting at PV expressing-P- cells or PV-expressing-interneuron synapses [@Chu2012]. Specifically, dopamine selectively inhibits the release of GABA from PV+ interneurons to principal cells, but not to other interneurons. This target-specific neurochemical modulation enables a sharp disinhibition of principal cells not accompanied by a concomitant alteration of the inhibitory inputs. Such a decrease of the inhibitory tone on BLA P- cells by dopamine may facilitate the induction of long- term potentiation at sensory afferents [@Bissieere2003] and the for- mation of fear memories [@Fadok2009].



<!-- their functional
properties depend on the subunit composition-->
<!--These receptors have been called GABAC-like receptors due to their pharmacological similarity to retinal GABAC receptors (89, 217). Bicuculline-insensitive receptors have also been shown to be present in the medial subdivision (239), indicating these receptors are present throughout the central nucleus. Although bicuculline-insensitive ionotropic GABA receptors have been described in other regions of the central nervous system (90), the presence of these receptors at synapses has not been shown outside the central amygdala. The two GABA receptor types appear to be localized to different GABAergic inputs onto CeL neurons. Thus inputs from the intercalated neurons that form synapses onto the dendrites of CeL neurons express both GABAA- and GABAC-like receptors. These results suggest that the different GABA receptors may play distinct roles in the local circuitry of the central amygdala (47).-->

 <!--In contrast, unusual receptor, GABA~C-like~, has been demonstrated to be present at GABAergic synapses between ITC and CeL neurons, together with common GABA~A~ receptor []. GABA~C-like~ receptor is insensite to bicuculline --> 

Within CeA, neurons form GABAergic synapses with each other. Recent study using optogenetic approach with whole-cell patch-clamp recordings nicely showed that neurons in the CeL are extensively interconnected, with local connections apparent between all types of neurons, but strongest between like neurons (SOM+ $\rightarrow$ SOM+ and PKC$\delta$+ $\rightarrow$ PKC$\delta$+)[@Hunt2017]. Both tracing studies and optogenetical techniques with electrophysiology demonstrated that both types of CeL neurons mainly unidirectionally project to CeM [@Petrovich1997; @Jolkkonen1998; @Haubensak2010; @Li2013; @Cocchi2010]. ///// /////The CeA network then receives signals from the BLA and computes the inhibitory GABAergic output to various brain areas.
Taken together, these combinations of connections between BLA and CeA, including the feedforward inhibition generated by intercalated neurons, enables to increase or decrease the amplitude of the CeA responses depending on which set of amygdala nuclei are activated and in what sequence. Thus, the CeA output depends not only on the nature and intensity of received inputs, but also on their timing and origin.
//// Although both subtypes of CeL neurons inhibit one another and both project to the CeM52,53 , CeLON neurons respond to a fear CS at a shorter latency than CeLOFF
52, suggesting that conditioned fear responses occur following activation of CeLON neurons that inhibit CeLOFF neurons projecting to CeM output neurons53 , thereby .promoting freezing through disinhibition52,53. Neurons that inhibit CeLOFF neurons projecting to CeM output neurons53 , thereby promoting freezing through disinhibition52,53
The LA was shown to form functional excitatory synapses on SOM+ and PKCδ− cells in the CeL (CeL:SOM+), and the excitatory strength of these synapses greatly increased as a result of fear conditioning (Li 2013). The presence of experience-dependent potentiation in the CeL indicates that this region is also important for acquisition of the CS–US association, as suggested by earlier studies17,40,52, rather than merely serving as a relay of information from the LA
///CeL — in both acquiring and expressing conditioned freezing in response to a fear cue, as well as multiple neural projections from the CeL that may regulate this behavioural response

New findings continue to enlarge our conceptions of CeA circuitry in non-fear behaviour. In a
/// • In a recent study on feeding suppression, genetic targeting of CeL:PKCδ+ neurons was used to selectively express hM4Di to allow for reversible neuronal inhibition. In mice, reducing the activity of CeL:PKCδ+ neurons was found to block decreased feeding stimulated by sickness or unpalatable tastes 58. Conversely, optogenetic excitation of CeL:PKCδ+ neurons dramatically decreased feeding in both hungry and sated mice, and this was not a confound of reduced activity or increased anxiety. These results indicate that CeL:PKCδ+ neurons suppress feeding in response to anorexigenic stimuli58.  multiple inputs to CeL:PKCδ+ neurons that are activated by anorexigenic signals, including the BLA, the parabrachial nucleus (PBN) and the insula (IN)58

<!-- 5-HT3 receptors in this nucleus have been proposed to be present presynaptically on interneuron terminals (103, 104).Sah 2003-->
<!--neurons in both the CeM and CeL receive glutamatergic inputs from the lateral and basal nucleus which activate both AMPA and NMDA receptors [(Royer and M de A 2004)]]. Excitatory inputs to CeL neurons also express presynaptic metabotropic glutamate receptors (186). As in many other regions of the central nervous system (Debanne2011), activation of these receptors leads to depression of the synaptic input. The activity of these receptors is modulated following kindling and chronic cocaine treatment (Neugebauer2000). These findings suggest that alterations in synaptic efficacy at inputs to the CeA may be involved in the changes seen in epilepsy and behavioral sensitization to cocaine.-->
 
#### Amygdala projections
//////////////////////Efferent projections from the amygdala are also widespread and include both cortical and subcortical regions (208).
/// Although many cortical regions are contacted by BLA axons, this review will only consider the medial prefrontal cortex (mPFC), because it plays a critical role in regulating condi- tioned fear (Sotres-Bayon and Quirk, 2010). Other amygdala outputs thought to contribute to conditioned fear include projec- tions to BNST (Dong et al., 2001) and various hypothalamic nuclei (Pitkanen, 2000).
//// Finally, the amygdala can also indirectly influence the excitability of the entire prosencephalon via its projections to neuromodulatory cell groups (releasing acetylcholine, noradrenaline [NA], and dopamine [DA]) of the basal forebrain and brainstem (Steriade and Pare, 2007).
On the output side, the targets of the amygdala are extremely diverse, however the CeM is widely accepted to be the main output nuclei.
Indeed, nearly all brainstem projections of the amygdala are sent from CeM (Hopkins and Holstege 1978; Petrovich and Swanson 1997; Veening et al. 1984). Specificly, CeM is the sole source of amygdala projections to the periaqueductal gray, which generates freezing (LeDoux et al. 1988), the most common index of conditioned fear. Moreover, CeM neurons fire at high rates during fear-inducing conditioned stimuli (Ciocchi et al. 2010; Duvarci et al. 2011), and optogenetic activation or inactivation of CeM triggers or impairs freezing, respectively (Ciocchi et al. 2010).
Indeed, CeA supplies most amygdala projections to the brainstem nuclei that generate the behavioral and visceral correlates of conditioned fear, including the PAG, parabrachial nuclei, solitary nucleus, and DVC (Hopkins and Holstege, 1978). Those outputs seems to be segregated as to the ... and ... and seems to be sent from distinct cell populations - 
More recently, it was found that distinct subtypes of CeL neurons contact CeM cells projecting to different brainstem sites. In particular, CeM cells that project to the periaqueductal gray (PAG) are contacted by CeL neurons expressing oxytocin receptors (OR+), whereas CeM cells projecting to the dorsal vagal complex (DVC) receive inputs from OR- CeL neurons (Viviani et al., 2011). It should be noted that many of the OR+ CeL neurons also express PKC$\delta$ but not SOM and conversely for OR- CeL neurons (Haubensak et al., 2010; Li et al., 2013).
Neurons from parabranchial area (PB) receives inputs from CeA [@Bester1995]
//////Li et al. (2012) have investigated the role ofkappa opioid receptor signaling in the bed nucleus of the stria terminalis (BNST). Patch-clamp record- ings in the BNST provided evidence that activation of kappa opioid receptors inhibits GABAergic transmission via presynaptic mechanisms. As the CEA provides an important GABAergic input to the BNST, one that has been implicated as a critical pathway in the central stress system (Jasnow et al., 2004; Walker and Davis, 2008), the authors used optogenetics to target and control activity in this pathway. The results indicated that kappa opioid recep- tor activation inhibited GABAergic transmission in this pathway specificall

Finally, as with the majority of cells in the striatum, projections from the central nuclei are predominantly GABAergic while the basolateral nuclei have glutamatergic projections (42, 244, 269).
/// -> cortical connections //// sensory association areas1; in primates, these reciprocal connections extend to primary sensory areas21 Hence, the BLA transmits information widely throughout cortical regions, but its neuronal processing is greatly affected by excitatory projections from these regions. Predominantly unidirectional outputs of the BLA include the striatum, especially the nucleus accumbens (NAc), and the bed nucleus of the stria terminalis (BNST) and the CeA. In turn, the striatum, BNST and CeA have been considered to mediate the translation of BLA signals to behavioural output. Of note, there are exceptions to this serial model of information flow; the BA and CeA also receive sensory inputs, and the CeA contributes to some behavioural processes independently from the BLA23,24

In contrast to CeA GABAergic projections, BLA forms glutamatergic synapses, usually onto neurons in different brain regions. <!--[@Pitkanen,2000]-->
contributes most amygdala projections to the striatum, thalamus, and cerebral cortex. Many cortical regions are contacted by BLA axons, this review will only consider the medial prefrontal cortex (mPFC), because it plays a critical role in regulating conditioned fear (Sotres-Bayon and Quirk, 2010). 
/////////// Luna and Morozov (2012) contrasted the microcircuitry of BLA inputs vs. anterior piriform inputs to the posterior piriform cortex. Although both structures were found to innervate deep pyramidal cells of the posterior piriform, the BLA and anterior piriform connected with different kinds of interneurons. Specifically, the BLA produced strong connections with fast-spiking interneu- rons, whereas the anterior piriform had its strongest synapses on irregular-spiking interneurons. As these different classes of interneurons synapse on different regions of the pyramidal cells (somatic vs. distal dendritic), the feedforward inhibition from BLA vs. anterior piriform inputs would be expected to have profoundly different effects on the likelihood of spiking in the principal cells of the posterior piriform.
///////////// connections between the BLA and the mPFC. The reciprocal connections between these regions appear to be involved in a wide variety of behavioral and higher cognitive functions. Yet, the mPFC receives inputs from many other structures and the distinctions among the connections formed by these inputs have not been clear. Therefore, Little and Carter (2012) investigated how BLA, ventral hippocampal, midline thalamus, and contralateral mPFC inputs to the layer two pyramidal neurons of the mPFC make synaptic connections. The authors used optogenetics to target specific pathways by transducing the efferent structures with ChR2 and providing illumination to their axonal terminals in the mPFC. Moreover, they combined their optogenetic manipulations with two-photon microscopy in order to determine the functional con- nections on a subcellular level. The results from this study indicate that the different regions do, in fact, make different subcellular connections. The BLA appears to make synaptic connections much closer to the soma, relative to other regions, especially the thalamic inputs. Additionally, the BLA inputs target spines of an “intermediate” size, along with ventral hippocampal inputs, in contrast to the thalamic inputs to the large spines and the contralateral mPFC inputs to the small spines. As both the size of the spine and the distance from the soma govern the relative strengths of the inputs, these findings shed light on how different regions influence local circuit activity in other regions. In a follow-up study, Little and Carter (2013) extended their findings, again using optogenetics combined with two-photon microscopy. In this case, their findings indicated that BLA inputs to the mPFC were considerably stronger on mPFC neurons that innervated the BLA, compared to mPFC neurons that provide inputs to the contralateral mPFC. Together, these findings have contributed to a deeper understanding for how the BLA and mPFC inter-act and, critically, provide a foundation for understanding how BLA inputs to the mPFC may regulate PFC activity and PFC- dependent functions.
///////////BLA projects to the ventral hippocampus, structure which is also involved in axiety (Pitkänen et al., 1995, 2000; Bannerman et al., 2003). Felix-Ortiz et al. found that inhibi- tion of BLA afferents to the ventral hippocampus, via activation of halorhodopsin, decreased anxiety-related behaviors. Similarly, stimulation of such afferents, using 20 Hz light pulses to activate ChR2, increased anxiety-related behaviors. Moreover, electrophysiology analysis suggested that the effects of stimu- lating BLA inputs to the ventral hippocampus were mediated through local circuit mechanisms involving both direct activation of principal cells in the hippocampus and indirect recruitment of inhibitory neurons. 
//// In other work, Felix-Ortiz and Tye (2014) social behaviour - timulation of these terminals, using 20 Hz light pulses, reduced social interactions of the resident, whereas inhibition of these terminals increased such interactions, suggesting that activation of this pathway increased anxiety in the animals whereas silencing ofthis pathway produced the opposite effect. The effects with stimulation were blocked with microinjections of glutamate receptor antagonists into the ventral hippocampus, indicating that the results were due to stimulation of BLA axon terminals and the concomitant release ofglutamate from those terminals.
///////// neurons within the basal nucleus of the BLA that are responsive to cues associated with footshocks and other neurons that are responsive to cues previously associated with footshocks that have been extinguished. Senn et al. (2014) investigated whether such neurons also show distinct projection patterns to the medial prefrontal cortex (mPFC). To perform a functional investigation of these subpopulations of neurons, retrogradely transported viruses containing Cre-recombinase were injected into either the prelimbic (PL) or infralimbic (IL) cortex while a conditional viral vector expressing the opsins in a Cre-dependent manner was injected into the BLA. As a result, the opsins were selectively expressed in the IL-projecting neurons or the PL- projecting neurons, enabling illumination of the entire BLA to only stimulate or inhibit the specific subpopulation of neurons. Consistent with previous work suggesting a dichotomy between the dorsal regions of the mPFC (PL) and the ventral regions (IL) with regard to fear conditioning (Peters et al., 2009), the authors demonstrated that BLA neurons projecting to the PL are activated by unextinguished cues whereas those projecting to the IL are activated by extinguished cues. Moreover, inhibition of IL-projecting neurons during cue extinction training produced a significant impairment in the retention ofthe extinction learning, compared to stimulating such neurons. Conversely, inhibition of the PL-projecting neurons during such training enhanced the retention ofthe extinction learning, compared to stimulating such neurons. While much previous research has focused on the mPFC inputs to the BLA in regulating fear extinction and expression, these findings provide evidence that BLA inputs to distinct mPFC regions also differentially influence such behaviors.
Moreover, some set of projections are sent from both BLA and CeA. This connections are sent to BNST (Dong et al., 2001) and various hypothalamic nuclei (Pitkanen, 2000). Finally, the amygdala can also indirectly influence the excitability of the entire prosencephalon via its projections to neuromodulatory cell groups (releasing acetylcholine, noradrenaline [NA], and dopamine [DA]) of the basal forebrain and brainstem (Steriade and Pare, 2007).
////// As part of under- standing the precise role played by the BLA in such behaviors, Stuber et al. (2011) examined the pathway from the BLA to the nucleus accumbens (NA) core in modulating and driving reinforcement of operant behavior. Although previous evidence had suggested that the BLA could directly influence dopamine release in the NA (Howland et al., 2002), a key mechanism for reinforcement, it was not clear whether activity in the BLA inputs to the NAcore could actually reinforce operant behavior or was necessary for reward seeking. Stuber et al. found that mice engaged in an operant behavior (nose pokes) in order to receive optical stimulation (burst of 20 Hz light pulses) of the BLA axon terminals in the NAcore. Similarly, optical inhibition, via activation of halorhodopsin, of the BLA terminals decreased responding for a sucrose reward. Strikingly, optical stimulation of mPFC inputs to the NAcore did not produce the same effects. Other work has shown that optical stimulation of BLA inputs to the NAshell are also reinforcing (Britt et al., 2012), though, in contrast to the mPFC inputs to the NAcore, stimulation of mPFC inputs or ventral hippocampal inputs to the NAshell was also found to be reinforcing. Together, these findings illustrate not only the increasing evidence for a role for BLA glutamatergic inputs to the NA in regulating reinforcement and reward but also that, depending on the part of the NA targeted, other glutamatergic inputs do not necessarily produce identical results
//////BLA is a key part of the neural circuit that drives drug-seeking behavior triggered by drug-associated cues (See et al., 2003). However, as the BLA projects to both the PL and the NAcore, both of which are considered critical components of a general drug-seeking circuit (McFarland and Kalivas, 2001; McFarland et al., 2004; LaLumiere and Kalivas, 2008), it has not been clear which pathway is responsible for driving cue-induced drug-seeking. Recent work by Stefanik and Kalivas (2013) has used optogenetics to investigate this issue. The BLA was transduced with ArchT. Inhibition of BLA terminals in either the PL or NAcore reduced cue-induced reinstatement of cocaine-seeking, indicating that activity in both pathways is obligatory for associative cue-driven cocaine-seeking.
///// originate in the BLA that have since been implicated in bidirectional regulation of anxiety. Optically driving BLA projections to the ventral HPC (vHPC) is anxiogenic61 , whereas photostimulation of BLA inputs in the anterodorsal BNST (adBNST) is anxiolytic62. Photostimulation of the BLA–Vhpc pathway also decreases social interaction63, an effect perhaps related to the increase in anxiety that is seen following BLA–vHPC activation64


<!--The central amygdala is particularly sensitive to a kindling stimulus (123a) and has been implicated in the reinforcing ability of repeated cocaine exposure (170). These findings suggest that alterations in synaptic efficacy at inputs to the CeA may be involved in the changes seen in epilepsy and behavioral sensitization to cocaine. Sah2003-->

### Amygdala functions
#### Fear/ Anxiety

The fear circuitry orchestrates defense mechanisms in response to environmental threats. This circuitry is evolutionarily crucial for survival, but its dysregulation is thought to play a major role in the pathophysiology of psychiatric conditions in humans.

Although many brain regions have been found to participate in anxiety regulation it is commonly accepted that among them the amygdala plays a prominent role (Canteras et al., 2010; Davis and Whalen, 2001; Ehrlich et al., 2009; Engin and Treit, 2008; Everitt et al., 2003; Herry et al., 2010; LeDoux, 2000, 2007; McNally et al., 2011; Pape and Paré, 2010; Paré et al., 2004; Pérez de la Mora et al., 2008, 2010; Roozendaal et al., 2009).


#### Amygdala and neuroinflammation
Amygdala is considered to be an essential component of the brain circuitry that forms the neural response to systemic immune activation [@Gaykema2007] and it is involved in sickness behavior [@Dantzer2008, @Goehler2007, @Roozendaal2009].
Regarding neuroinflammation circuit, pro-inflammatory cytokines signal the brain mainly through the activation of vagal afferent fibers projecting to the nucleus of the solitary tract (NTS) and then to amygdala [@Goehler2000, @Quan2008]. Therefore, it is important to get better insights into brain activity during acute and chronic immune responses.
Evidence from many animal studies indicates that LPS significantly increases c-fos expression in the central nucleus of the amygdala (CeA) and, to a lesser extent, in the basolateral nucleus of the amygdala (BLA) [@Engler2011, @Frenois2007, @Vitkovic2000]. Moreover, functional and neuroanatomical studies indicate that peripheral immune activation may also affect amygdala function in humans. For example, depressive-like symptoms and anxiety can be transiently elicited in healthy human subjects by peripheral administration of LPS [@Grigoleit2011, @Harrison2009, @Wright2005]. These findings suggest that in humans, similar to rodents, the amygdala is involved in the integration of behavioral and immune responses.
A recent study documented that LPS-induced anxiety in mice as well as a pronounced increase in sEPSC frequency resulting in the hyperexcitability of BLA neurons were mediated through the CXCL12/CXCR4 interaction [@Yang2016]. This suggests that alterations of CXCL12 signaling in this area play critical roles in the development of anxiety induced by systemic inflammation, and that CXCR4 may be a potential therapeutic target for inflammation-induced anxiety, a key component of a sickness behavior. Several studies have indicated the relative abundance of CX3CL1 receptors within the amygdala complex, including the BLA and the CeA [@Nishiyori1998, @Tarrozo2003], suggesting a possible influence on amygdala function. Although CX3CL1 also modulate synaptic activity and has been shown to modulate glutamate and GABA release in the hippocampus [@Ragozzino2006] and dorsal raphe nucleus [@Heinisch2009a], its neuromodulatory role in other brain centers remains unknown. Surprisingly, so far there have been no neurophysiological studies of CX3CL1 effects in the amygdala.

In summary, recent studies have demonstrated that the BLA–CeA
circuitry is involved in a diverse array of behaviours in addition to those related to fear. The key to understanding the production of these differ- ent behaviours is in the functional anatomy.

The CeA is a GABAergic nucleus (McDonald and Au- gustine, 1993; Sun and Cassell, 1993) that is anatomically divided into the lateral sector of the CeA (CeL) and the medial sector of the CeA (CeM), with substantial unidirec- tional connections between the CeL and the CeM (Mc- Donald, 1982; Grove, 1988; Jolkkonen and Pitkänen, 1998). Neurons in both regions also make extensive local connections (McDonald, 1982; Sun and Cassell, 1993; Jolkkonen and Pitkänen, 1998), with local glutamate ex- citation of CeL neurons evoking IPSCs in neighboring neurons (Lopez de Armentia and Sah, 2004). Recent stud- ies have divided CeL neurons into distinct populations based on the expression of immunohistochemical mark- ers, electrophysiological properties, and synaptic connec- tions (Ciocchi et al., 2010; Haubensak et al., 2010; Li et al., 2013). Of these, one population expresses protein kinase C␦ [PKC␦(⫹)], and these neurons are predominantly de- scribed as late-firing (LF) neurons, exhibiting a substantial delay to action potential (AP) initiation in response to depolarizing somatic current injections. Following fear conditioning, these neurons respond to the CS with a reduction in activity and have therefore been called Ce- LOFF cells (Ciocchi et al., 2010; Haubensak et al., 2010). A second population of CeL neurons, which is largely sep- arate from the PKC␦(⫹) population, expresses soma- tostatin [somatostatin-positive (SOM⫹); Li et al., 2013]. These neurons receive direct synaptic input from the lateral amygdala, which is potentiated following auditory fear conditioning (Li et al., 2013). Electrophysiologically, PKC␦(⫺) neurons which are predominantly SOM(⫹), have been described as either LF or regular spiking (RS). Fol- lowing fear conditioning, PKC␦(⫺) neurons respond to the CS with an increase in activity, and have therefore been called CeLON neurons (Ciocchi et al., 2010; Haubensak et al., 2010), which likely also correspond to SOM(⫹) neurons (Yu et al., 2016). PKC␦(⫺) neurons inhibit PKC␦(⫹) neurons, which in turn project to the CeM (Hau- bensak et al., 2010).- Hunt2017

The physiologic role, if any, of SOM and PKC&delta; are not known; however, they clearly label separate populations of neurons in the CeL. Developmentally, the CeL has a striatal origin (Medina et al., 2011), and **SOM and PKC&delta;, rather than specifying different populations that mediated different functional roles, should be thought of as lineage markers**. We suggest that PKC&delta;-expressing and SOM- expressing neurons form heterogeneous populations of neurons, with different populations contributing to different behavioral outcomes. **Understanding the flow of information through the CeA and its outputs, in a behaviorally specific and relevant manner, will be a challenge for future experiments**. - Hunt2017

The CeA is generally considered to be the main output nucleus of the amygdalar complex and is divided into the lateral and medial sectors. It contains GABAergic neurons that have been divided into several distinct populations using immunohistochemical and electrophysiological markers. These - Hunt2017

The physiologic role, if any, of SOM and PKC␦ are not known; however, they clearly label separate populations of neurons in the CeL. Developmentally, the CeL has a striatal origin (Medina et al., 2011), and SOM and PKC␦, rather than specifying different populations that mediated different functional roles, should be thought of as lineage markers. We suggest that PKC␦-expressing and SOM- expressing neurons form heterogeneous populations of neurons, with different populations contributing to different behavioral outcomes. Understanding the flow of information through the CeA and its outputs, in a behaviorally specific and relevant manner, will be a challenge for future experiments. Similarly, - Hunt2017