## CX3CL1/CX3CR1 in the CeA

The main target of the BLA is CeA.<!-- ładniej napisać// bardziej rozbudować -->
However, the basolateral and central complexes of the amygdala participate in different extended circuitries <!--citations--> and hence, the CX3CL1 may differentially regulate these networks. 
Thus, to gain insight into the CX3CL1-mediated regulation of the CeA circuitry, we examined cellular localization of CX3CL1 and CX3CR1 and the functional characteristics of CeA neurons.<!-- zmienić drugą część zdania... --> 
<!--the next step was to asses the cellular localization of CX3CL1 and its receptor, as well as their  electrophysiological effects. /// to gain insight into the CX3CL1-mediated regulation of the CeA circuitry, we examined the functional characteristic of the IPSCs in DG granule cells (Figure 1) and CA3 pyramidal neurons (Figure 2) in the dorsal and ventral hippocampus.  zmienić oczywiście...// they have different connectivity patterns -->


### Cellular distribution of CX3CL1 and CX3CR1 in the rat CeA

To gain greater insights about the cellular localization of CXCL12 and CXCR4, their expression was studied in rat brain slices by immunocytochemistry and fluorescence microscopy.

Molecular identification and characterization of fear controlling circuitries is a promising path towards developing targeted treatments of fear-related disorders.

### Electrophysiological classification of CeA neurons 

### CX3CL1/CX3CR1 modulation of the electrical properties in CeA neurons

#### Modulation of intrinsic membrane properties of CeL neurons by CX3CL1 in the cell-type specific manner

```{r CX3CL1CeAexcitabilitystats, include = FALSE}
# getting the table of statistics for all CeA df (LF + RS) condition of one experiment
CX3CL1_CeA_stat_all <- stat_table_exp_membr_extended((CeA_df_final))
CX3CL1_CeA_stat_2nM_all <- stat_table_exp_membr_extended(CeA_df_final %>% filter(Experiment == 'CX3CL1(2nM)'))
CX3CL1_CeA_stat_azdfrak2nM_all <- stat_table_exp_membr_extended(CeA_df_final %>% filter(Experiment == 'AZD8797 + \nCX3CL1(2nM)'))
CX3CL1_CeA_stat_minofrak2nM_all <- stat_table_exp_membr_extended(CeA_df_final %>% filter(Experiment == 'minocycline + \nCX3CL1(2nM)'))
# selecting a stat_row so it prints nicely in text
CX3CL1_CeA_stat_all_gain <- as.data.frame(CX3CL1_CeA_stat_all %>% dplyr::filter(Variable == 'gain') %>% dplyr::select(Statistics))
CX3CL1_CeA_stat_frak2nM_gain <- CX3CL1_CeA_stat_all_gain$Statistics[1]
CX3CL1_CeA_stat_azdfrak_gain <- CX3CL1_CeA_stat_all_gain$Statistics[2]
CX3CL1_CeA_stat_azd_gain <- CX3CL1_CeA_stat_all_gain$Statistics[3]
CX3CL1_CeA_stat_minofrak_gain <- CX3CL1_CeA_stat_all_gain$Statistics[4]
CX3CL1_CeA_stat_mino_gain <- CX3CL1_CeA_stat_all_gain$Statistics[5]

CX3CL1_CeA_stat_all_Rm <- as.data.frame(CX3CL1_CeA_stat_all %>% dplyr::filter(Variable == 'Input_resistance') %>% dplyr::select(Statistics)) 
CX3CL1_CeA_stat_frak2nM_Rm <- CX3CL1_CeA_stat_all_Rm$Statistics[1]
CX3CL1_CeA_stat_azdfrak_Rm <- CX3CL1_CeA_stat_all_Rm$Statistics[2]
CX3CL1_CeA_stat_azd_Rm <- CX3CL1_CeA_stat_all_Rm$Statistics[3]
CX3CL1_CeA_stat_minofrak_Rm <- CX3CL1_CeA_stat_all_Rm$Statistics[4]
CX3CL1_CeA_stat_mino_Rm <- CX3CL1_CeA_stat_all_Rm$Statistics[5]

CX3CL1_CeA_stat_all_tau <- as.data.frame(CX3CL1_CeA_stat_all %>% dplyr::filter(Variable == 'tau') %>% dplyr::select(Statistics))
CX3CL1_CeA_stat_frak2nM_tau <- CX3CL1_CeA_stat_all_tau$Statistics[1]
CX3CL1_CeA_stat_azdfrak_tau <- CX3CL1_CeA_stat_all_tau$Statistics[2]
CX3CL1_CeA_stat_azd_tau <- CX3CL1_CeA_stat_all_tau$Statistics[3]
CX3CL1_CeA_stat_minofrak_tau <- CX3CL1_CeA_stat_all_tau$Statistics[4]
CX3CL1_CeA_stat_mino_tau <- CX3CL1_CeA_stat_all_tau$Statistics[5]

CX3CL1_CeA_stat_all_Vm <- as.data.frame(CX3CL1_CeA_stat_all %>% dplyr::filter(Variable == 'Vm') %>% dplyr::select(Statistics))
CX3CL1_CeA_stat_frak2nM_Vm <- CX3CL1_CeA_stat_all_Vm$Statistics[1]
CX3CL1_CeA_stat_azdfrak_Vm <- CX3CL1_CeA_stat_all_Vm$Statistics[2]
CX3CL1_CeA_stat_azd_Vm <- CX3CL1_CeA_stat_all_Vm$Statistics[3]
CX3CL1_CeA_stat_minofrak_Vm <- CX3CL1_CeA_stat_all_Vm$Statistics[4]
CX3CL1_CeA_stat_mino_Vm <- CX3CL1_CeA_stat_all_Vm$Statistics[5]

#### RS
CX3CL1_CeA_stat_RS <- stat_table_exp_membr_extended((CeA_df_final_RS))

# selecting a stat_row so it prints nicely in text
CX3CL1_CeA_stat_RS_all_gain <- as.data.frame(CX3CL1_CeA_stat_RS %>% dplyr::filter(Variable == 'gain') %>% dplyr::select(Statistics))
CX3CL1_CeA_stat_frak2nM_RS_gain <- CX3CL1_CeA_stat_RS_all_gain$Statistics[1]
CX3CL1_CeA_stat_azdfrak_RS_gain <- CX3CL1_CeA_stat_RS_all_gain$Statistics[2]
CX3CL1_CeA_stat_azd_RS_gain <- CX3CL1_CeA_stat_RS_all_gain$Statistics[3]
CX3CL1_CeA_stat_minofrak_RS_gain <- CX3CL1_CeA_stat_RS_all_gain$Statistics[4]
CX3CL1_CeA_stat_mino_RS_gain <- CX3CL1_CeA_stat_RS_all_gain$Statistics[5]

CX3CL1_CeA_stat_RS_all_Rm <- as.data.frame(CX3CL1_CeA_stat_RS %>% dplyr::filter(Variable == 'Input_resistance') %>% dplyr::select(Statistics)) 
CX3CL1_CeA_stat_frak2nM_RS_Rm <- CX3CL1_CeA_stat_RS_all_Rm$Statistics[1]
CX3CL1_CeA_stat_azdfrak_RS_Rm <- CX3CL1_CeA_stat_RS_all_Rm$Statistics[2]
CX3CL1_CeA_stat_azd_RS_Rm <- CX3CL1_CeA_stat_RS_all_Rm$Statistics[3]
CX3CL1_CeA_stat_minofrak_RS_Rm <- CX3CL1_CeA_stat_RS_all_Rm$Statistics[4]
CX3CL1_CeA_stat_mino_RS_Rm <- CX3CL1_CeA_stat_RS_all_Rm$Statistics[5]

CX3CL1_CeA_stat_RS_all_tau <- as.data.frame(CX3CL1_CeA_stat_RS %>% dplyr::filter(Variable == 'tau') %>% dplyr::select(Statistics))
CX3CL1_CeA_stat_frak2nM_RS_tau <- CX3CL1_CeA_stat_RS_all_tau$Statistics[1]
CX3CL1_CeA_stat_azdfrak_RS_tau <- CX3CL1_CeA_stat_RS_all_tau$Statistics[2]
CX3CL1_CeA_stat_azd_RS_tau <- CX3CL1_CeA_stat_RS_all_tau$Statistics[3]
CX3CL1_CeA_stat_minofrak_RS_tau <- CX3CL1_CeA_stat_RS_all_tau$Statistics[4]
CX3CL1_CeA_stat_mino_RS_tau <- CX3CL1_CeA_stat_RS_all_tau$Statistics[5]

CX3CL1_CeA_stat_RS_all_Vm <- as.data.frame(CX3CL1_CeA_stat_RS %>% dplyr::filter(Variable == 'Vm') %>% dplyr::select(Statistics))
CX3CL1_CeA_stat_frak2nM_RS_Vm <- CX3CL1_CeA_stat_RS_all_Vm$Statistics[1]
CX3CL1_CeA_stat_azdfrak_RS_Vm <- CX3CL1_CeA_stat_RS_all_Vm$Statistics[2]
CX3CL1_CeA_stat_azd_RS_Vm <- CX3CL1_CeA_stat_RS_all_Vm$Statistics[3]
CX3CL1_CeA_stat_minofrak_RS_Vm <- CX3CL1_CeA_stat_RS_all_Vm$Statistics[4]
CX3CL1_CeA_stat_mino_RS_Vm <- CX3CL1_CeA_stat_RS_all_Vm$Statistics[5]


#### LF
CX3CL1_CeA_stat_LF <- stat_table_exp_membr_extended((CeA_df_final_LF))

# selecting a stat_row so it prints nicely in text
CX3CL1_CeA_stat_LF_all_gain <- as.data.frame(CX3CL1_CeA_stat_LF %>% dplyr::filter(Variable == 'gain') %>% dplyr::select(Statistics))
CX3CL1_CeA_stat_frak2nM_LF_gain <- CX3CL1_CeA_stat_LF_all_gain$Statistics[1]
CX3CL1_CeA_stat_azdfrak_LF_gain <- CX3CL1_CeA_stat_LF_all_gain$Statistics[2]
CX3CL1_CeA_stat_azd_LF_gain <- CX3CL1_CeA_stat_LF_all_gain$Statistics[3]
CX3CL1_CeA_stat_minofrak_LF_gain <- CX3CL1_CeA_stat_LF_all_gain$Statistics[4]
CX3CL1_CeA_stat_mino_LF_gain <- CX3CL1_CeA_stat_LF_all_gain$Statistics[5]

CX3CL1_CeA_stat_LF_all_Rm <- as.data.frame(CX3CL1_CeA_stat_LF %>% dplyr::filter(Variable == 'Input_resistance') %>% dplyr::select(Statistics)) 
CX3CL1_CeA_stat_frak2nM_LF_Rm <- CX3CL1_CeA_stat_LF_all_Rm$Statistics[1]
CX3CL1_CeA_stat_azdfrak_LF_Rm <- CX3CL1_CeA_stat_LF_all_Rm$Statistics[2]
CX3CL1_CeA_stat_azd_LF_Rm <- CX3CL1_CeA_stat_LF_all_Rm$Statistics[3]
CX3CL1_CeA_stat_minofrak_LF_Rm <- CX3CL1_CeA_stat_LF_all_Rm$Statistics[4]
CX3CL1_CeA_stat_mino_LF_Rm <- CX3CL1_CeA_stat_LF_all_Rm$Statistics[5]

CX3CL1_CeA_stat_LF_all_tau <- as.data.frame(CX3CL1_CeA_stat_LF %>% dplyr::filter(Variable == 'tau') %>% dplyr::select(Statistics))
CX3CL1_CeA_stat_frak2nM_LF_tau <- CX3CL1_CeA_stat_LF_all_tau$Statistics[1]
CX3CL1_CeA_stat_azdfrak_LF_tau <- CX3CL1_CeA_stat_LF_all_tau$Statistics[2]
CX3CL1_CeA_stat_azd_LF_tau <- CX3CL1_CeA_stat_LF_all_tau$Statistics[3]
CX3CL1_CeA_stat_minofrak_LF_tau <- CX3CL1_CeA_stat_LF_all_tau$Statistics[4]
CX3CL1_CeA_stat_mino_LF_tau <- CX3CL1_CeA_stat_LF_all_tau$Statistics[5]

CX3CL1_CeA_stat_LF_all_Vm <- as.data.frame(CX3CL1_CeA_stat_LF %>% dplyr::filter(Variable == 'Vm') %>% dplyr::select(Statistics))
CX3CL1_CeA_stat_frak2nM_LF_Vm <- CX3CL1_CeA_stat_LF_all_Vm$Statistics[1]
CX3CL1_CeA_stat_azdfrak_LF_Vm <- CX3CL1_CeA_stat_LF_all_Vm$Statistics[2]
CX3CL1_CeA_stat_azd_LF_Vm <- CX3CL1_CeA_stat_LF_all_Vm$Statistics[3]
CX3CL1_CeA_stat_minofrak_LF_Vm <- CX3CL1_CeA_stat_LF_all_Vm$Statistics[4]
CX3CL1_CeA_stat_mino_LF_Vm <- CX3CL1_CeA_stat_LF_all_Vm$Statistics[5]
```

The next step was to investigate whether reduced excitability of CX3CL1 in the BLA<!--,together with ....,--> would affect the membrane properties of their main target, i.e., GABAergic cells in the CeL.
<!-- razem z tym, że on sam też może mieć udział... --> 
To this end, among others, electrophysiological features such as the excitability, input resistance, membrane time constant, resting membrane potential, was measured (see: Methods \@ref(electroprotocols)). <!-- analogous to the neurons in the BLA./// recorded using a whole-cell patch-clamp approach, in a current-clamp configuration.-->

In general, these experiments revealed that several membrane properties in the CeL neurons were significantly modified by CX3CL1 (Fig. \@ref(fig:CX3CL1CeAintrinsic)). 
Specifically, similar to what was observed in the BLA, bath application of CX3CL1 (2nM) produced a <!--reversible--> decrease in the number of action potentials evoked by a given current step, manifested as a decrease in gain (baseline = `r round(CeA_df_final %>% filter(Experiment == 'CX3CL1(2nM)' & Condition == "baseline") %>% ungroup() %>% summarize(mean(gain)), digits = 2)` `r knitr::asis_output("\U00B1")` `r round(CeA_df_final %>% filter(Experiment == 'CX3CL1(2nM)' & Condition == "baseline") %>% ungroup() %>% dplyr::summarize(x = sd(gain), count = n()) %>% dplyr::summarize(x/sqrt(count)), digits = 3)`, CX3CL1(2nM) = `r round(CeA_df_final %>% filter(Experiment == 'CX3CL1(2nM)' & Condition == "CX3CL1") %>% ungroup() %>% summarize(mean(gain)), digits = 2)` `r knitr::asis_output("\U00B1")` `r round(CeA_df_final %>% filter(Experiment == 'CX3CL1(2nM)' & Condition == "CX3CL1") %>% ungroup() %>% dplyr::summarize(x = sd(gain), count = n()) %>% dplyr::summarize(x/sqrt(count)), digits = 3)`, `r CX3CL1_CeA_stat_frak2nM_gain`, see Fig. \@ref(fig:CX3CL1CeAintrinsic)<!--jaki?-->).<!-- który panel?--><!--  We injected a series of depolarizing current steps to assess the number of action potentials (Figure 4a – c). Repeated-measure ANOVA revealed that projection neurons fired significantly less after NF knockdown // Bath application of DA (0.05–30 μm) produced a reversible decrease in the number of action potentials evoked by a given current step-->
This effect was accompanied by decreased input resistance (`r CX3CL1_CeA_stat_frak2nM_Rm`)and membrane time constant (`r CX3CL1_CeA_stat_frak2nM_tau`) after CX3CL1 application (Fig. \@ref(fig:CX3CL1CeAintrinsic)<!--jaki?-->).
Moreover, resting membrane potentials of CeL neurons become more depolarized in response to bath-applied 2nM CX3CL1 (from `r round(CeA_df_final %>% filter(Experiment == 'CX3CL1(2nM)' & Condition == "baseline") %>% ungroup() %>% summarize(mean(RMS)), digits = 2)` `r knitr::asis_output("\U00B1")` `r round(CeA_df_final %>% filter(Experiment == 'CX3CL1(2nM)' & Condition == "baseline") %>% ungroup() %>% dplyr::summarize(x = sd(RMS), count = n()) %>% dplyr::summarize(x/sqrt(count)), digits = 3)` to `r round(CeA_df_final %>% filter(Experiment == 'CX3CL1(2nM)' & Condition == "CX3CL1") %>% ungroup() %>% summarize(mean(RMS)), digits = 2)` `r knitr::asis_output("\U00B1")` `r round(CeA_df_final %>% filter(Experiment == 'CX3CL1(2nM)' & Condition == "CX3CL1") %>% ungroup() %>% dplyr::summarize(x = sd(RMS), count = n()) %>% dplyr::summarize(x/sqrt(count)), digits = 3)`, `r CX3CL1_CeA_stat_frak2nM_Vm`) (Fig. \@ref(fig:CX3CL1CeAintrinsic)<!--jaki?-->).<!-- In response to bath-applied agonists, the depolarization is strong enough that it is capable of producing prolonged spiking ( Beierlein et al., 2000; Fanselow et al., 2008; Kawaguchi, 1997; Xu et al., 2013 ).-->

Given that CeL neurons demonstrate mainly two types of electrophysiological firing patterns, specifically Regular-Spiking and Late-Firing neurons (see Introduction, CeA subchapter \@ref(CeA) and Fig. \@ref(fig:methodsBLACeAIVrep)b),<!-- which was also confirmed by cluster analysis from recorded CeL cells as a part of this dissertation,comprises neurons of two main electrophysiological types // La  ter studies further characterized at least four main physiological types of neurons in the CeA, distinguished based on their responses to intracellular current injections.-->, previously measured intrinsic parameters were further analyzed<!--divided?--> by these neuronal subtypes.<!-- odnośnik do góry i lepiej napisać// segregated those neurons according to their types.-->
Intriguingly, majority of RS neurons were revealed to respond to CX3CL1, which was reflected as robust changes in intrinsic properties (Fig. \@ref(fig:CX3CL1CeAintrinsic)<!--part-->).
In contrast, under presented here experimental conditions, CX3CL1 seems not to affect LF cells' intrinstic membrane properties (see Fig. \@ref(fig:CX3CL1CeAintrinsic)<!--part-->), implying that much higher proportion of RS cells was reactive to CX3CL1.
All parameters and statistics are summarized in Table <!--?-->.


#### Excitatory synaptic transmission in the CeL and its effect by CX3CL12

Considering the observed reduction in RS cells' excitability, 


 Neurons in both regions also make extensive local connections (McDonald, 1982; Sun and Cassell, 1993; Jolkkonen and Pitkänen, 1998), with local glutamate excitation of CeL neurons evoking IPSCs in neighboring neurons (Lopez de Armentia and Sah, 2004).

#### Effects of CX3CL1 on the inhibitory synaptic transmission in the CeL

<!-- two major classes of CeL neurons with distinct firing patterns,-->