# Discussion

Chemokines are a class of small immune proteins emerging as neuromodulators and coordinators of neuron-glial communication.<!-- Chemokines (chemotaxic cytokines) are a family of small proteins which play a prominent role in the trafficking of immune cells and in the orchestration of inflammatory responses--><!-- Indeed, chemokines appear to play several important roles in neuronal development and in the function of the mature nervous system (Tran and Miller 2003).Chemokine receptors are expressed by diverse populations of neurons and glia.-->
Few of them, such as CX3CL1 and CXCL12, are particularly important in this regard, as they are constitutively and widely expressed in the CNS, where they were shown to act on cellular, synaptic, network, as well as the behavioral level [@sowa_2021; @trettel_2020].<!-- lepiej napisać-->
Moreover, dysregulation of CXCL12/CXCR4 and CX3CL1/CX3CR1 signaling are implicated in psychiatric diseases, including anxiety-related behaviors.
As they receptors, CXCR4 and CX3CR1, are relatively densely present in the amygdala, the critical region in the development of many neuropsychiatric disorders, the electrophysiological consequences of their activation were explored.
Moreover, since distinct nuclei of the amygdala play different roles in ...<!--lepiej napisać o różnicach-->, it is of interest to investigate whether CX3CL1 and CXCL12 trigger different electrophysiological responses in those regions.
To this end, in the presented PhD dissertation, by using a combination of electrophysiological, immunohistochemical, and pharmacological approaches, the actions of two chemokines (CX3CL1 and CXCL12) were determined in two nuclei of the amygdala - basolateral (BLA) and central (CeA).
Moreover, considering the pivotal role of chemokines in neuro-glial communication, the aim of experiments was also to explore the glial component of observed effects.<!--???-->
Performing all electrophysiological experiments using acute brain slices with microglial inhibitor and astrocytic toxin allowed also for dissecting local neuro-glial cross-talk in these nuclei of the amygdala.<!-- Since all the experiments presented in here were performed using acute brain slices, it cannot be excluded that observed effects might be also mediated by glial cells. analogous -->

## CX3CL1/CX3CR1 signaling in the basolateral amygdala

<!--Despite relatively high levels of CX3CL1 and CX3CR1 in the amygdala and the involvement of this chemokine in anxiety-related behavior, the precise role of the CX3CL1/CX3CR1 signaling pathway in the amygdala is still unknown. lepiej napisać -->
This dissertation provides evidence that the CX3CL1/CX3CR1 pair: (i) reduced the excitability of principal cells in the BLA by depolarizing their threshold current, (ii) significantly suppressed GABAergic transmission in this area, as well as (iii) impaired long-term potentiation at cortico-BLA synapses. 
These effects were mediated by the CX3CL1 only receptor, CX3CR1, and probably by microglia.
In addition, in primary neuronal cultures from the amygdala, incubation with CX3CL1 induced an immature-like phenotype of dendritic spines reflected as a decreased ratio of dendritic head to length.<!-- Application of CX3CL1 on acute brain slices led to the following electrophysiological effects: (1) depression of principal cell's excitability, (2) reduction of GABAergic transmission, manifested as a decreased median frequency of spontaneous inhibitory synaptic currents, (3) the impairment in the long-term potentiation.-->

Principal cells in the basolateral amygdala (BLA) are well-known to converge information about both conditional and unconditional stimuli.
Multiple pairings of those experiences lead to the LTP at excitatory synapses onto BLA neurons, enabling CS alone to induce the freezing behavior (for example, @nabavi_2014).
Moreover, by combining several approaches to label only those neurons involved in fear conditioning (CS+), @kim_2017 found that AMPA/NMDA ratios were explicitly increased in CS+ terminals, confirming an input-specific, postsynaptic nature of this phenomenon.
Accordingly, plasticity at synapses onto principal cells in this region is considered to be a candidate mechanism of neural plasticity mediating the acquisition and storage of new fear memories.
Hence, their activity is tightly regulated by a broad array of factors, including a GABAergic system or different types of neuromodulators.<!-- lepiej napisać /// external signals? External signals such as hormones and modulatory neurotransmitters that affect cellular excitability or signalling in biochemical pathways can exert a profound influence on the degree of synaptic plasticity induced by a particular stimulus protocol-->
 
Here, the reduced excitability was demonstrated after CX3CL1 treatment, manifested as an increased threshold current needed for eliciting action potentials.
Thus, the CX3CL1-mediated regulation of the principal cells' firing may have significant consequences on BLA physiology.<!--The CX3CL1–induced decrease in excitability of BLA principal cells manifested as an increase in threshold current, together with an broadening of action potentials,tutaj broadining statistically significant in 2nM, but only tendency in 5nM, w miarę blokowane, najsłabiej przez AZD8797... suggests that MCP-1 might reduce a K+ conductance. @sun_2006--><!--One of the main effects induced by CX3CL1 in the BLA is a decreased principal cell's excitability ( Figures \@ref(fig:)--><!--CX3CL1 did not significantly affect intrinsic excitability (Figures \@ref(fig:))--><!-- Both LPS injection and CCL2 perfusion onto hippocampal slices increased total neuronal excitability ( Figures 5 C, 5D, 5G, and 5H), which has contributions from excitatory and inhibitory synaptic inputs, as well as the neuron’s intrinsic electrical properties. Consistent with the observed increase in excitatory synaptic transmission and lack of change in inhibitory synaptic transmission ( Figures 5 E, 5F, S7 C, and S7D), the effects of CCL2 were blocked by the AMPA receptor inhibitor NBQX, but not the GABAAreceptor inhibitor gabazine ( Figures S7 E–S7H). CCL2 did not significantly affect intrinsic excitability ( Figures S7 I and S7J).--><!--An enhancement of neuronal excitability in the absence of membrane depolarization was previously described in dissociated DRG neurons during exposure to PGE2, which suppresses the sustained K^+^ current (Nicol et al. 1997)--><!--The MCP-1–induced reduction in rheobase, together with an increase in spike frequency and a broadening of action potentials, suggests that MCP-1 might reduce a K+ conductance. analogous-->
This effect was dependent on the CX3CL1 receptor, CX3CR1.<!--further verifying? confirming specificity? -->
To block this receptor, two approaches were used. 
Although pre-incubating slices with an antibody against CX3CL1 abolished the observed effect, a small portion of neurons still remained responsive to CX3CL1. 
This may be due to the limited tissue penetration of antibodies, estimated around 50`r knitr::asis_output("\U03BC")`m, while slices used for this study were 300`r knitr::asis_output("\U03BC")`m thick. 
Thus another approach was used by employing the pharmacological inhibitor of the CX3CR1 receptor, AZD8797.
The effectiveness of AZD8797 molecule in inhibiting actions of CX3CR1 was validated in cell cultures [@lannes_2019]<!--hamster, 10uM--> as well as *in vivo* administered both intracerebroventricularly (i.c.v) [@ho_2020a] and intraperitoneally (i.p) in neuropathic pain model [@chen_2020].
The concentration used in previous studies, i.e., 10`r knitr::asis_output("\U03BC")` [@baxter_2021; @ridderstadwollberg_2014], was also effective during the experiments presented here.
Moreover, when applied solely, AZD8797 did not affect any measured electrophysiological parameters.
Thus, in the remaining experiments, the  10`r knitr::asis_output("\U03BC")` was applied.<!--, since at this concentration electrophysiological effects triggered by CX3CL1 were efficiently prevented.-->
<!--However, this CX3CR1 inhibitor did not change the expression level of the CX3CR1 protein but enhanced the expression level of the CX3CL1 protein. AZD8797 is a non-competitive inhibitor for CX3CR1. The above result suggests that it has no influence on the CX3CR1 protein itself except for affecting the activation of its downstream signaling pathway. More intriguingly, AZD8797 increases the expression level of CX3CL1, indicating that there is a feedback loop, probably a compensatory effect after blocking the signaling pathway, which has been pointed out previously but is yet to be further defined [@cederblad_2016]. - [@chen_2020].-->

The presented CX3CL1-mediated impairment in the LTP is consistent with many previous studies showing CX3CL1-induced inhibition of LTP or mimicking LTD in the hippocampus [@bertollini_2006; @maggi_2009; @ragozzino_2006; @sheridan_2014], without affecting paired-pulse ratio [@bertollini_2006; @ragozzino_2006; @sheridan_2014].<!-- In PPF (at multiple synapses), the second pair of stimuli separated by a few tens of milliseconds produces a larger synaptic response than the first, owing to the transient elevation of Ca2^+^ in terminal boutons produced by the second stimulus summing with the residual Ca2^+^ produced by the first stimulus, and increasing the probability of transmitter release. Since probability of transmitter release cannot exceed 1, the PPF ratio tends to decrease as probability of release increases (Bliss & Collingridge, 2013). Therefore, in the LA the glutamate release in response to paired pulse stimulation seems to be reduced in TPH2− / −mice. Besides differences in release probability differences in PPF in the amygdala and the hippocampus, -->
PPR, a measure of short-term synaptic plasticity, is defined as the ratio of the amplitude of the second response to that of the first, which depends on the probability of vesicular release at the synapse.
Thus, the unaffected PPR suggests a similar release probability of glutamate and, therefore, a postsynaptic mechanism of CX3CL1 action.
Consistently, in this study, a CX3CL1-mediated increase in the threshold current was observed, leading to a reduction of principal cells' firing.

Many lines of evidence show neuroprotective and beneficial actions of CX3CL1/CX3CR1 signaling.
For instance, the expression of CX3CL1 is upregulated in several settings of augmented glutamatergic transmission, such as after pilocarpine-induced status epilepticus or ischemia, where it is consistently shown to reduce neurotoxicity [@cipriani_2011; @limatola_2005; @tarozzo_2002; @tong_2000; @yeo_2011].<!--CX3CL1 has been reportedly up-regulated in several settings of augmented glutamatergic transmission where the chemokine is clearly protective against excitotoxic cell death (Tong et al., 2000; Tarozzo et al., 2002; Limatola et al., 2005; Cipriani et al., 2011; Briones et al., 2014).Moreover, both CX3CL1 and its receptor, CX3CR1, have been shown to be up-regulated in hippocampal neurons after pilocarpine-induced status epilepticus (Yeo et al., 2011), a condition characterized by excessive glutamatergic excitation. // with reduction of glutamate-induced and NMDA-induced neurotoxicity [@deiva_2004; @limatola_2005]. // On the other hand, in the ischemic model, the CX3CL1 i.c.v. injection was shown, again with the involvement of A~1~Rs, to induce neuroprotective effects, such as the reduction of a lesion volume and neurological deficits [@cipriani_2011].-->
Its beneficial actions were also reported in neurodegenerative models, where it was shown to rescue motor coordination [@morganti_2012] or reduce Tau-pathology [@finneran_2019].<!-- A role for endogenous CX3CL1 in the attenuation of a pro-inflammatory phenotype was also reported in a mouse model of Tauopathy ( Lastres-Becker et al., 2014 ).Recent data show that only the over-expression of a specific cleavage variant of the soluble CX3CL1 reduced Tau-pathology ( Finneran and Nash, 2019 ). -->
<!-- In a pMCAO rat model, i.c.v. injection of soluble CX3CL1, 30 min after ischemia, has long lasting protective effects, reducing lesion volume and neurological deficits, again with the involvement of active A1Rs ( Cipriani et al., 2011).-->
Moreover, in the hippocampus, CX3CL1 was demonstrated to reduce spontaneous glutamate release and the postsynaptic glutamate currents with a mechanism that involves increased intracellular calcium and dephosphorylation of the GluR1 AMPA receptor subunit [@lauro_2008; @limatola_2005; @meucci_1998; @ragozzino_2006], a hallmark of the long-term depression (LTD).<!-- For example, CX3CL1 has been shown to reduce spontaneous glutamate release and post-synaptic glutamate currents (Meucci et al., 1998; Limatola et al., 2005).-Sheridan2014 // These effects are probably a result of a PKA-related phosphorylation of GluR1 Ser845 [@ragozzino_2006]. -->
Thus, this predominantly inhibitory role is suggested<!--może po prostu suggested?--> to be a component of neuroprotective synaptic scaling mechanisms necessary for hippocampal memory-associated synaptic plasticity processes [@bertollini_2006; @piccinin_2010; @sheridan_2014].<!--zmienić bardziej /// Overall, previous studies indicate apredominantly inhibitory role for CX3CL1, perhaps as a compo-nent of neuroprotective synaptic scaling mechanisms necessary for hippocampal memory-associated synaptic plasticity processes (Bertollini et al., 2006;Turrigiano, 2008; Piccinin et al., 2010). -->
Importantly, in the BLA, many disorders are linked with the increased excitability of pyramidal-like cells along with the elevated magnitude of LTP.<!--citations-->
Indeed, blocking LTP with NMDA receptor antagonists, calcium channel blockers, and protein synthesis inhibitors was reported to disrupt the extinction of conditioned fear, whereas promoting LTP was shown to facilitate extinction ((Falls et al, 1992; Vianna et al, 2001; Santini et al, 2004; Sotres-Bayon et al, 2007, (Walker and Davis, 2002; Yang and Lu, 2005)).<!--citations i może bardziej zmienić--><!--For example, long-term potentiation (LTP) is considered to be a candidate mechanism of neural plasticity that mediates the acquisition and storage of new fear memories, particularly in the lateral nuclei of the amygdala. Treatments that block LTP, such as NMDA receptor antagonists, calcium channel blockers, and protein synthesis inhibitors, disrupt the extinction of conditioned fear (Falls et al, 1992; Vianna et al, 2001; Santini et al, 2004; Sotres-Bayon et al, 2007). Conversely, drugs that promote LTP can facilitate extinction (Walker and Davis, 2002; Yang and Lu, 2005). // Moreover, and adult-like LTP of amygdala afferents emerges during infancy when the amygdala begins to contribute to fear learning (Thompson et al. 2008).-->
<!-- więcej zaburzeń -->
Therefore, considering its well-documented neuroprotective role in other brain structures, the reduced activity of PCs along with impaired LTP in the BLA may suggest the anxiolytic actions of CX3CL1. 

<!--Consistently, CX3CL1 application did not significantly affect the frequency of excitatory synaptic currents. 
However, contrary to studies and present LTP data, the amplitude of these events also remained unchanged following CX3CL1 application.
Further experimentation is required to clarify whether despite impaired synaptic plasticity and reduced frequency of neurons, changes in glutamatergic transmission are not detectible.
 wyjaśneinei? It is suggested that maybe due to regional differences  -->

Unlike what is observed in the hippocampus, this study did not find any effect on excitatory synaptic transmission in the BLA by CX3CL1.<!--jakoś lepiej to napisać?-->
<!-- First of all, in some studies a much higher dose was used than here (100nM vs. 2-5nM; @meucci_1998, @ragozzino_2006), reaching levels during inflammatory conditions. 
This raises the possibility that the postsynaptic CX3CL1/CX3CR1-dependent mechanism leading to activation of pro-survival pathways requires higher concentrations.At levels reached during inflammatory conditions, CX3CL1 signaling has previously been associated with activation of pro-survival and anti-apoptotic pathways through phosphorylation of molecules such as Akt, as well as activation of MAP kinases such as p-38 and Erk1/2 (p44/42; Maciejewski-Lenoir et al., 1999;Meucci et al., 2000;Cambienet al., 2001;Deiva et al., 2004; Klosowska et al., 2009;Lyons et al.,2009).// For example, CX3CR1 dose-dependently stimulates calcium mobilization in CX3CR1-expressing cells with an EC50 of 2 nM (Imai et al., 1997). CX3CL1 also dose-dependently reduces glutamate-induced excitotoxicity in hippocampal neurons with an EC50 of 0.7 nM (Limatola et al., 2005). Finally, CX3CL1 dose-dependently inhibits field excitatory postsynaptic potentials (Bertollini et al., 2006) and evoked excitatory postsynaptic current amplitude (Ragozzino et al., 2006) in hippocampal neurons with an EC50 of 0.7 and 1.0 nM, respectively.// At levels reached during inflammatory conditions, CX3CL1 signaling has previously been associated with activation of pro-survival and anti-apoptotic pathways through phosphorylation of molecules such as Akt, as well as activation of MAP kinases such as p-38 and Erk1/2 (p44/42; Maciejewski-Lenoir et al., 1999; Meucci et al., 2000; Cambien et al., 2001; Deiva et al., 2004; Klosowska et al., 2009; Lyons et al., 2009) While previous studies have shown that CX3CL1 causes an increase in intracellular calcium in neurons and other cell types (Oh et al., 2002; Deiva et al., 2004; Ragozzino et al., 2006) this effect of CX3CL1 becomes apparent at concentrations of 25 nM and higher (Oh et al., 2002; Deiva et al., 2004), well above the levels we investigated here and we observed no such increase in intracellular calcium. At a concentration of 2 nM, in both neurons and non-neurons, CX3CL1 pre-incubation suppressed glutamate-mediated rises in intracellular calcium levels. These data are in good agreement with previous findings of a protective effect of inflammatory levels of CX3CL1 against glutamate excitotoxicity and glutamate NMDA receptor activation, in particular (Meucci et al., 1998; Deiva et al., 2004; Limatola et al., 2005), although, unlike the current work, the latter effect was linked to increased intracellular calcium (Ragozzino et al., 2006). Calcium oscillations in both neuronal and non-neuronal cells are important for cellular growth, migration and synaptic structural refinement (Katz and Shatz, 1996; Komuro and Rakic, 1998; Spitzer et al., 2000). Thus, the dampening of such signaling by CX3CL1 is suggestive of a role in stability of network connectivity and activity. Overall, the current data along with information in the published literature reveal that a role for CX3CL1 in control of glutamate-mediated excitatory neurotransmission during excitotoxic events can be extended to situations of synaptic plasticity required for normal functions such as memory formation.--><!--This is unlikely, as the CX3CL1-induced reduction of neurotoxicity, field excitatory postsynaptic potentials or evoked excitatory postsynaptic current amplitude are dose-dependent with EC50 between 0.7-1 nM [@bertollini_2006; @limatola_2005; @ragozzino_2006].
On the other hand, while CX3CL1 at the dose of 25nM and higher was reported to increase intracellular calcium levels in neurons and other cell types [@deiva_2004; @oh_2002; @ragozzino_2006], both neuronal and non-neuronal cells reacted with suppression of intracellular calcium levels following the concentration of 2nM [@sheridan_2014]./// many studies using similar concentrations to those reported in this dissertation [@bertollini_2006; @lauro_2008; @maggi_2009; @maggi_2011; @piccinin_2010; @scianni_2013] demonstrated that CX3CL1 reduce glutamatergic transmission *via* the involvement of a glial component.-->
These regional differences between hippocampus and amygdala may be linked to the fact that CX3CL1 does not directly modulate glutamatergic transmission in the hippocampus, but rather its action is mediated by adenosine, released from microglia upon CX3CR1 receptor activation [@lauro_2008; @lauro_2010; @piccinin_2010].
Adenosine is a cellular metabolite that acts through four different G-protein-coupled receptor subtypes (A~1~R, A~2A~R, A~2B~R, and A~3~R; @verkhratsky_2009), behaving as a homeostatic modulator and also as a neuromodulator at the synaptic level [@boison_2010; @cunha_2001; @ribeiro_2010].<!-- Adenosine exerts two parallel modulatory roles in the CNS, acting as a homeostatic modulator and also as a neuromodulator at the synaptic level. [@cunha_2001]--><!-- In the brain, astrocytes represent the main cellular source of extracellular ADO and express all the four known types of adenosine receptors (ARs): A1R, A2AR, A2BR, A3R (Verkhratsky et al., 2009).-->
Notably, depending on the receptor activation, adenosine exerts opposing action and tonic activity on glutamatergic transmission in the hippocampus [@piccinin_2010].<!-- koniecznie lepiej napisać....// Among them, A 1 R (Lauro et al., 2008, 2010) and A 3 R (Rosito et al., 2014) are involved in CX3CL1 neuroprotection against Glu-induced toxicity. Moreover we previously demonstrated that CX3CL1 triggers the release of adenosine from neuronal and microglial cells (Lauro et al., 2008, 2010). This CX3CL1-induced adenosine action on the glutamatergic transmission was revealed to be mediated by A~3~R and, to the lesser extent, A~1~R, in the hippocampus [@lauro_2008; @lauro_2010; @piccinin_2010]. Further evidence indicates that the activation of A~1~R and A~3~R results in a decrease in synaptic transmission, whereas A~2A~R exerts the opposite effect, manifested as CX3CL1-induced increase of evoked EPSC (eEPSC) observed when the A~1~ and A~3~ receptors are blocked [@piccinin_2010]. // Of note, sole adenosine was demonstrated to decrease the glutamatergic synaptic transmission in the hippocampus, even despite the absence of CX3CL1, suggesting adenosine tonic activity in this structure . // Adenosine (ADO) is a cellular metabolite that is formed by the breakdown of intracellular and extracellular adenine nucleotides that are physiologically present at nanomolar concentration inside and outside the cells (Fredholm, 2007). It represents an endogenous modulator of brain functions acting to fine-tune inhibitory and excitatory synaptic transmission (Ribeiro et al., 2010), glial function (Boison et al., 2010), and blood flow (Kusano et al., 2010); moreover, in the nervous system, the level of extracellular ADO rises upon brain damage which follows stroke, ischemia, and epileptic seizures (Ribeiro et al., 2003). Acting through four different G-protein-coupled receptors (A1R, A2AR, A2BR, and A3R), extracellular ADO determines the outcome of different brain injuries, mediating neuroprotective or neurotoxic effects. In this regard, we have recently shown that ADO plays a significant role in mediating CX3CL1, BDNF, and erythropoietin-mediated neuroprotection through the activation of A1receptors (Lauro et al., 2008; 2010), and other reports describe that interleukin-6 (IL-6) and oncostatin M (OSM) require A1R functions to exert their neuroprotective effects (Biber et al., 2008; Moidunny et al., 2010). [@rosito_2012]-->
<!-- This notion is further supported by the fact that -- powiązać to jakoś z microglejem? --><!-- The concept that ADO acts as an endogenous modulator able to exert neuroprotective effects through to the control of glutamatergic transmission is well established (Fredholm et al., 2005). In addition, itsroleinmodulationofcellmetabolism(Cunha,2001),neuron-glia communication (Boison et al., 2010), and the tuning of growth factor signaling (Gomes et al., 2011) is becoming evident. Indeed, we and others have recently shown that the chemokine CX3CL1 and the cytokines IL-6 and OSM are able to drive neuroprotection only in the presence of functional A1R (Biber et al., 2008; Lauro et al., 2008, 2010; Moidunny et al., 2010; Cipriani et al., 2011). In particular, IL-6 and OSM potentiate the expression and the function of neuronal A1R and therefore the ADO effects on neurotransmission and neu roprotection (Moidunny et al., 2010); on the other hand, CX3CL1 neuroprotection is due to ADO release from microglia, activation of A1R, and, possibly, the subsequent release of glial-soluble factors that contribute to neuroprotection (Lauro et al., 2010). In contrast, in the present work we found that CXCL16 exerts neuroprotection against Glu insult only in the presence of functional A3R, the inactivation of all of the other ARs being unable to limit the CXCL16 effect. In rodents, among ARs, A3R has the lower affinity for ADO (Jacobson et al., 1995) and is expressed at low levels in the brain (Ji et al., 1994), including the hippocampus (Dunwiddie et al., 1997; Macek et al., 1998) and the cerebral cortex (Brand et al., 2001). The ability of A3R to contribute to neuroprotection is controversial: in vivo studies suggest that differences in timing of intraperitoneal A3R agonist admin istration may alter the outcome of ischemic brain injury (Von Lubitz et al., 1995, 2001). In vitro studies showed that, depending on brief or prolonged periods of ischemia, A3R mediates effects on neurotrans mission that can shift from protection to injury (Pugliese et al., 2007). In the present study we report data supporting the hypothesis that A3R drives neuroprotective effects, in agreement with the find ing that upon repeated episodes of hypoxia, A3R / mice have a wider neurodegeneration compared with wt (Fedorova et al., 2003), and that central administration of selective A3R agonist reduces isch emic brain injury in mice (Chen et al., 2006). -->
Specifically, further evidence indicated that CX3CL1-induced adenosine action *via* A~1~R and A~3~R receptor led to decreased glutamatergic transmission [@lauro_2008, @lauro_2010; @piccinin_2010], whereas A~2A~R exerts the opposite effect, manifested as CX3CL1-triggered increase of evoked EPSC (eEPSC), observed when the A~1~ and A~3~ receptors are blocked [@piccinin_2010]. <!--This CX3CL1-induced adenosine action on the glutamatergic transmission was revealed to be mediated by A~3~R, and to the lesser extend A~1~R  [@lauro_2008, @lauro_2010; @piccinin_2010]./// Further evidence indicates that the activation of A~1~R and A~3~R results in a decrease in synaptic transmission, -->
Moreover, @scianni_2013 demonstrated that CX3CL1 modulates the NMDA glutamate receptor function and that this effect involves the release of D-serine from glial cells and the activity of the A~2A~R subtype.<!-- CX3CL1-mediated neuroprotection and neuromodulation may also require the activity of adenosine-type 2 a receptors (A2ARs). --><!-- Scianni et al. (2013) demonstrated that CX3CL1 modulates the NMDA glutamate receptor function and that this effect involves the release of D-serine from glial cells, and the activity of A2AR subtype. // CX3CL1 was also shown to trigger D-serine, a NMDAR co-agonist, release from glial cells, and potentiate NMDAR function in an A~2A~- and D-serine-dependent manner, which was driven by microglial cells [@scianni_2013].// Altogether these data describe a mechanism by which CX3CL1, via A2AR and D-serine, and likely modulating synaptic NR2A/NMDARs, induced CREB phosphorylation, upregulation and release of BDNF, resulting in neuroprotection and neuromodulation ( Lauro et al., 2015). -->
<!--Therefore, the CX3CL1-induced adenosine release may affect glutamatergic neurotransmission by a mechanism involving a combination of three different AR subtypes and both glutamatergic receptors. Nevertheless, the opposite effects of CX3CL1 on AMPAR and NMDAR functions are nicely correlated with the difference between A~3~R/A~1~R and A~2A~R receptors.Moreover, the depressed glutamatergic transmission following CX3CL1 and adenosine application corresponds with results from studies of synaptic plasticity (see: Section \@ref(LTP)). -->
Thus, these studies raises the possibly that CX3CL1 similarly induce the release of adenosine, which in turn, is downstream modulate observed electrophysiological effects of CX3CL1 are mediated by adenosine

We speculate that the activation of A3Risan event downstream of the release of ADO from astrocytes upon CXCL16 treatment;

These findings are suggestive of the possible mediation of CX3CL1-induced effects by adenosine.
A1R activation inhibits spontaneous and evoked AMPA receptor-mediated synaptic transmission,13 while A2AR increase the firing rate of BLA pyramidal neurons14 and facilitate long-term synaptic potentiation (LTP) of LA population spikes, evoked by stimulating external mainly cortical afferents.15
Our results show that A1R inhibit evoked NMDA receptors-mediated responses in BLA pyramidal neurons, an effect that has been described for hippocampal NMDA currents in isolated rat neurons.18 A2AR do not exert tonic effects and do not control A1R-mediated decrease in NMDA-EPSC. Surprisingly, in contrast to the hippocampus where exogenous activation of A2AR increases the amplitude of NMDA currents,19–22,24 A2AR agonists decreased NMDA-EPSCs in the amygdala; however, this effect was not prevented by the selective A2AR antagonist SCH58261, calling into question the selectivity of CGS21680 and regadenoson for A2AR in the amygdala.

Alternatively, the high variability of the CX3CL1 application on excitatory synaptic transmission from cell to cell possibly<!--might?--> depends upon the relative contribution of both excitatory inputs from other pyramidal-like cells in the BLA and GABAergic synapses from local interneurons.<!--trochę bardziej zmienić?-->
Several microscopic analyses illustrated that principal neurons form complex dendritic arborizations, with distal dendrites receiving high levels of excitatory synaptic inputs from outside and within the BLA<!-- sprawdzić and (Brinley-Reed et al. 1995; Farb and Ledoux 1997, 1999) -->and proximal dendrites and soma being densely covered with GABAergic synapses.<!--citations-->
Mounting evidence shows that <!--in addition to their dendritic and somatic differences in morphology-->BLA interneuron subtypes display distinct somatic, dendritic, and axonal morphologies, including the specific subcellular domains targeted by their axons [@mcdonald_2001; @muller_2003; @muller_2005; @muller_2006; @muller_2007].
While axonal arborizations of PV- and CCK-expressing interneurons were shown to target perisomatic regions of principal cells, including their soma, proximal dendrites, and the axon initial segment (AIS; @mcdonald_2001, @muller_2005, @muller_2006), somatostatin-positive interneurons predominantly target distal dendrites and spines of these pyramidal-like neurons [@muller_2007].
Since these parts of dendrites are also a destination of extensive excitatory inputs, GABAergic synapses from SOM-expressing neurons influence how EPSPs travel along the dendritic arbor, summating and activating voltage-gated conductances.
<!--Therefore, inhibitory synapses from SOM-containing interneurons may influence such phenomena as a generation of calcium-dependent dendritic action potentialsdirectly blocks the initiation of dendritic calcium spikes in , dendritic integration, glutamatergic synaptic plasticity, and back-propagation of action potentials from somata to dendrites (for a comprehensive review, see: @tremblay_2016). -->
As whole-cell patch-clamp recordings in this study were made from the soma,  and the potassium-based intrapipette solution was used, excitatory synaptic currents originating from distal parts of dendrites needed to travel more distance and can be decreased by GABAergic synapses.
Hence, they might not be detected from baseline noise.<!--Given that the the glutamatergic synapses are located on the distal parts of principal cells' dendrites, it is likely that interneurons contacting synapses mainly on distal dendritic parts might decrease the excitatory inputs. -->
Noting that cesium blocks potassium currents, additional experiments using cesium-based intrapipette solution might resolve whether CX3CL1 mediate changes contributed by inputs to more distal dendrites [@williams_2008].<!-- Cesium reduces filtering of the synaptic currents arising from distal parts of the dendrite by blocking the potassium current, and changes in EPSC frequency seen only with cesium internal suggested that most of the changes were contributed by inputs to more distal dendrites.--><!-- the probability of neurotransmitter release was either increased, decreased or remained constant as a consequence of a differential presynaptic activity. In the connectivity context it is rather interesting that a presynaptic neuron responsible of a given synaptic strength forms synaptic connections with different neurons and, conversely that the same postsynaptic neuron was contacted by different types of synaptic connections formed by different presynaptic cells. Furthermore, this functional heterogeneity is further supported by the finding that presynaptic neurons forming synapses having a different synaptic weights display a different axonal pattern. bardziej o ITCs and CeA, ale ładne słownictwo-->
<!--However, this scenario is unlikely, as proportions of neuronal reactions were the same between CX3CL1(2nM) application and CX3CL1(2nM) application with additional inhibition of GABA~A~ and GABA~B~ channels (see Fig \@ref(fig:CX3CL1BLAsEPSCfigall) in Appendix \@ref(CX3CL1sEPSCappendix)).-->

<!--sheridan 500 pM (Ragozzino et al., 2006), the paired-pulse ratio of DG neuronresponses evoked by two successive stimuli (50 ms apart) was unaffected by CX3CL1 treatment either at baseline or followingTBS (Figure 4B). While not ruling out a presynaptic contribution, these data support a post-synaptic action for CX3CL1-mediated inhibition of fEPSP amplitude in the DG following TBS. -->
<!--CX3CL1 was also shown to trigger D-serine, a NMDAR co-agonist, release from glial cells, and potentiate NMDAR function in an A~2A~- and D-serine-dependent manner, which was driven by microglial cells [@scianni_2013].Altogether these data describe a mechanism by which CX3CL1, via A~2A~R and D-serine, and likely modulating synaptic NR2A/NMDARs, induced CREB phosphorylation, upregulation and release of BDNF, resulting in neuroprotection and neuromodulation ( Lauro et al., 2015).zmienić --><!--Overall, the abundance and expression pattern of CX3CL1 make the chemokine ideally suited for sensing hippocampal glutamate tone. 
Our data supports a possible role for CX3CL1 in homeostatic mechanisms of synaptic scaling during memory-associated synaptic plasticity.-Sheridan2014-->

In addition, the lack of changes in the paired-pulse ratio of field EPSP, together with inconclusive changes in the frequency of sEPSC, implies postsynaptic actions of CX3CL1.
Intriguingly, the suppression of principal cells' firing was not associated with any significant changes in passive membrane properties, such as input resistance (see Figure \@ref(fig:CX3CL1BLAexcitabilityfigall1) in Appendix \@ref(CX3CL1membraneappendix)).<!-- However, the input resistance and other passive membrane properties remained unchanged following CX3CL1 treatment, suggesting that this effect was rather presynaptic.-->
The action potentials result from a dynamic interplay between not only the intrinsic biophysical properties of the postsynaptic neuron, but also their excitatory and inhibitory synaptic inputs.<!--cytowanie jakiegos klasyka? // which may be a results of not only neuron’s intrinsic electrical properties, but also from excitatory and inhibitory synaptic inputs. --><!--Most action potentials that neurons emit during their lifetime are produced by a dynamic interplay between the synaptic inputs and the intrinsic biophysical properties of the postsynaptic neuron. Activity-dependent or neuromodulatory changes targeting these intrinsic properties effectively regulate intrinsic excitability of the neurons and how they integrate synaptic input into firing output.--><!-- ticular, pro-inflammatory cytokines such as interleukin (IL)-1, IL-6, and tumor necrosis factor alpha (TNF-α)haveallbeenimplicated in cardinal cellular and molecular processes of longterm hippocampal-dependent memory consolidation including synaptic plasticity, synaptic scaling and neurogenesis (Malenkaand Bear, 2004; Bruel-Jungerman et al., 2007a, b;Turrigiano, 2007; Baier et al., 2009; McAfoose and Baune, 2009;Bachstetter et al.,2011; Ben Menachem-Zidon et al., 2011;Yirmiya and Goshen,2011; del Rey et al., 2013;Gemma and Bachstetter, 2013).-->
<!-- increased intra-cellular calcium and dephosphorylation of the GluR1 AMPAreceptor subunit (Ragozzino et al., 2006). These synaptic effectsare consistent with a direct action of CX3CL1 on neurons mostlikely exerted through the CX3CR1 receptor, which is reportedlyexpressed on the dendrites of hippocampal neurons (Meucci et al.,2000; Limatola et al., 2005).-->
As present data reported significant changes neither in passive membrane properties of pyramidal-like BLA neurons nor onto their excitatory synaptic transmission, the remaining candidate of the observed CX3CL1-mediated reduction of pyramidal-like neurons' firing is the regulation by a GABAergic inhibitory system.
Fast inhibitory synaptic transmission within the CNS is mediated by the GABA~A~ receptor, a heteropentameric chloride permeable, GABA-gated member of ligand-gated ion channels, whereas slow inhibitory synaptic transmission is associated with GABA~B~ receptor.<!--więcej o nich-->
Indeed, in the presence of the GABA~A~ and GABA~B~ receptor blockers, picrotoxin and CGP52432, CX3CL1 failed to depolarize threshold current (Fig.\@ref(fig:CX3CL1BLAexcitabilityfrak)), illustrating that those receptors were involved in this effect.<!--Consistent with the observed decrease in inhibitory synaptic transmission and lack of change in excitatory synaptic transmission (Figures \@ref(fig:)), the effects of CX3CL1 were abolished by the GABA~A~ and GABA~B~ receptor blockers, picrotoxin and CGP52432 (Fig. \@ref(fig:))-->
However, one would expect that reduced principal cells' firing is a consequence of increased inhibition onto those cells.<!--lepiej napisać // -->
In contrast, CX3CL1 reduced the GABAergic transmission onto principal cells in the BLA (Figure \@ref(fig:CX3CL1BLAsIPSC), reflected as decreased median frequency and amplitude of sIPSCs.
Because spontaneous synaptic currents consist of a mixture of miniature (TTX insensitive) synaptic currents and those caused by presynaptic neuron firing (TTX sensitive) [@bellingham_1996; @doze_1991], sIPSC frequency reflects a combination of both basal presynaptic release probability and presynaptic activity.<!--zmienić!!!!!!/// klenowski_2015 , and both factors are limited by the number of inhibitory synapses-->
Moreover, a change in the amplitude of <!--m-->IPSCs reflects alterations in postsynaptic GABA~A~ receptors, whereas a change in the frequency of <!--m-->IPSCs implicates an altered probability of GABA release and/or changes in the number of active synapses [@dekoninck_1994; @otis_1994].<!--bardziej zmienić?-->
Thus, a reduction in median frequency and amplitude of sIPSCs after CX3CL1 application, which was abolished in the presence of TTX, suggests a CX3CL1-mediated inhibition of interneuronal spontaneous spiking and/or a decreased reactivity or number of GABA~A~ postsynaptic receptors.<!--decreased inputs onto BLA principal cells, probably due to--><!-- Thus, these results provide direct evidence that CX3CL1 impairs GABAergic transmission within the BLA by reducing spontaneous spiking of local interneurons.//Nevertheless, our results provide direct evidence that NF knockdown impairs GABAergic transmission within the BLA by reducing functional GABAAreceptors at the postsynaptic site.// Thus, consistent with our previous findings, it is likely that both presynaptic and postsynaptic mechanisms contribute to the fear conditioning-induced synaptic potentiation onto CeL neurons ( Li et al., 2013 ). -->
Nevertheless, these results provide direct evidence that CX3CL1 downregulated GABAergic transmission within the BLA, probably by both presynaptic and postsynaptic mechanisms.<!-- może silniej? direct evidence?-->
However, to the best of my knowledge, only a postsynaptic mechanism of CX3CL1-triggered modulation of GABAergic transmission was previously reported.
In the dorsal raphe nucleus, CX3CL1(10nM) enhanced postsynaptic GABA~A~ receptor number or sensitivity selectively on serotonergic neurons under conditions of both spontaneous and synaptically-evoked GABA release [@heinisch_2009].
Similar action was reported in another electrophysiological study using human tissue from epileptic patients. 
The epileptic tissue is characterized by more pronounced desensitization of GABA~A~ receptors  than healthy tissue, manifested as an increasing decrease in GABA~A~-mediated currents following repetitive GABA applications.<!--Desensitization is a general term that describes a decrease or loss of biological response following prolonged or repetitive stimulation //  to repetitive activation of GABA~A~ receptor//  Electrophysiology studies indicate aCX3CL1-mediated enhancement of spontaneous inhibitory postsynaptic current (sIPSC) amplitude and dose-dependent increase of evoked IPSC (eIPSC) amplitude without affecting eIPSC paired–pulse ratio, a finding observed selectively in 5-HT neurons.--><!-- Thus, CX3CL1 enhances postsynaptic GABA receptor number or sensitivity on 5-HT DRN neurons under conditions of both spontaneous and synaptically-evoked GABA release. // CX3CL1 may indirectly inhibit 5-HT neuro-transmission by increasing the sensitivity of 5-HT DRN neu-rons to GABA inputs. / GABA-mediated sIPSC recordings were isolated by additionof the non-N-methyl D-aspartate (NMDA) receptor antagonist 6,7-dinitroquinoxaline-2,3(1H, 4H)-dione (DNQX; 20M) and were recorded for 6 min. CX3CL1 (10 nM) was then added to the perfusion bath, -->
However, CX3CL1 was shown to reduce this rundown in pyramidal neurons from cortical slices of epileptic patients [@roseti_2013], illustrating that it might stabilize GABA~A~ receptor currents.<!-- It should be noted that epileptic tissue usually is less responsive to the repeated activation of GABA~A~ receptors (i.e., showing increased rundown after repetitive activation) than those from healthy tissue [@ragozzino_2005].-->
<!-- BOTH POST-SYNAPTIC EFFECTS, HERE PRESYNAPTIC ....and postsynaptic. different subunitis of GABA~A~? in the amygdala vs in the DRN? +SEROTNIN INPUTS TO AMYGDALA?--><!--use-dependent decrease (rundown) of the GABA-evoked currents// In particular, the repetitive activation of GABAA receptors produces a use-dependent decrease (rundown) of the evoked currents (IGABA), which is markedly enhanced in the hippocampus and cortex of drug-resistant mTLE patients.--><!-- GABAAreceptors from epileptic tissue (hippocampus and neo-cortex) become less responsive to repeated activation (as detected by current rundown) than those from healthy tissue (Palma et al.,2004, 2007a, b;Ragozzino et al.,2005).// -->
Hence, both studies reported CX3CL1-triggered modulation of postsynaptic GABA~A~ receptors, leading to increased sensitivity of postsynaptic neurons to GABA inputs.<!--These results suggest CX3CL1 reduces neuronal excitability by stabilizing GABA~A~ receptor currents. // These results are in line with previous report indicating that CX3CL1 reduce GABA~A~ receptor desensitization (i.e., rundown), as shown in oocytes transfected with human epileptic patients [@roseti_2013]. /// For example, fractalkine (CX3CL1) was shown to reduce GABA~A~ use-dependent receptor desensitization (i.e., rundown), as shown in oocytes transfected with human TLE membranes (Roseti et al., 2013), suggesting it reduces excitability by stabilizing receptor currents. ///zmienić -->
Importantly, one study also documented that inhibitory tone and GABA~A~ receptors mediated the effect of CX3CL1 on the LTP in the dentate gyrus [@sheridan_2014].<!--EFFECTS OF CX3CL1 ON LTP IN THE DENTATE GYRUS DEPENDS ONINHIBITORY TONE AND GABAARECEPTORS ///Interestingly, CX3CL1 did not prevent LTP in the presence of picrotoxin (Figure 4C). In fact, when picro-toxin was present, the magnitude of LTP was enhanced by CX3CL1 during the initial 20 min following the TBS (p<0.05). -->
While CX3CL1 reduced the magnitude of LTP in the DG, this phenomenon was more pronounced in the additional presence of a GABA~A~ blocker.
Hence, all these findings, including those presented in this dissertation, highlight that the actions of the chemokine CX3CL1 may vary depending on the balance between excitation and inhibition in the network. <!-- They suggest that neuronal responses to CX3CL1 can vary depending on the balance between excitation and inhibition in the hippocampal network.-->
Thus, at least in the hippocampus, the CX3CL1 neuroprotective inhibition of glutamatergic synaptic transmission is thought to be present during periods of enhanced excitatory activity and intact GABA~A~ receptor activity.<!--Therefore, during periods of enhanced excitatory activity in the hippocampus, CX3CL1 may act as a neuropro-tective dampener of excessive glutamatergic neurotransmission and this action appears to be dependent on GABA-mediated inhibition-->
<!-- in the hippocampus and here?-->
Whether other chemokines orchestrate the I/E balance and mechanisms underlying those effects are still unexplained.<!--+ WHETER DEPEND ON CELL TYPE ? -->


<!--jakieś różnice w GABA A amygdala vs hippocampus / cortex? -->
<!--This receptor, heteropentameric chloride permeable, GABA-gated member of ligand-gated ion channels, mediates fast inhibitory synaptic transmission within the CNS.Fast inhibitory synaptic transmission within the central nervous system is mediated by the GABA~A~ receptor, a heteropentameric chloride permeable, GABA-gated member of <!--the cys-loop superfamily of ligand-gated ion channels. GABAAreceptors are formed from limited combinations of subunits that have diverse structural and functional properties ( a 1–6, ß1–3, g 1–3, d , E , u , and p ; Olsen and Sieghart, 2009).-->
<!-- composition of GABA subunit in the amygdal...
The composition of GABAAreceptors has been found to be quite diverse because their subunit assembly makes their roles significantly different, depending on the timing of activation and subcellular localization (Pouille and Scanziani, 2001; Marowsky et al., 2004).
 The BLA of mature animals contains a 1 and a 2 subunits of the GABAAreceptor; a 1 subunit-containing GABAAreceptors are expressed primarily at the somal level of PV GABAergic interneurons but also exhibit coimmunoreactivity with the ß2/3 subunits (McDonald and Mascagni, 2004). Alternatively, GABAAreceptors on principal neurons contain primarily the a 2 subunit, which is predominantly responsible for the benzodiazepine allosteric potentiation of inhibitory currents (Marowsky et al., 2004). In addition, principal neurons in the BLA contain g 2 subunits, which likely contribute to the formation of a 2ßx g 2 pentameric GABAAreceptors, which contribute to fast inhibitory synaptic transmission (Esmaeili et al., 2009). Extrasynaptically, the GABAAreceptor in the BLA is made up primarily of the a 3 subunit, which strongly mediates tonic GABAergic currents (Marowsky et al., 2012). However, the a 5 subunit, which is diazepam sensitive and shapes the decay phase of the inhibitory postsynaptic currents (Marowsky et al., 2004), and the d subunit, both of which are hallmark subunits that contribute to tonic inhibition (Farrant and Nusser, 2005), are also expressed in the BLA, though not as strongly as the a 3 subunit (Marowsky et al., 2012).-->
<!-- development
In rat, the development of the mature GABAergic system in the BLA takes place between postnatal day (P) 14 and P30 with the emergence of PV interneurons (Berdel and Morys, 2000; Davila et al., 2008), an increase in the density of GABAergic fibers, and a decrease in the density of GABAergic cell bodies (Brummelte et al., 2007). 
Concurrently, GABAA receptor-mediated inhibitory postsynaptic currents (IPSCs) reach maturity between P21 and P28.
Simultaneously, the reversal potential of GABAAreceptors expressed in principal neurons shifts from –55 mV at P7 to –70 mV by P21. 
This increase in hyperpolarization - prager_2016 -->




<!--Besides the well-known fact that different regions of the brain may exhibit different electrophysiological reaction to the same substance, whether it is due to temporal and/or compositional difference in channels ... -->
<!-- Besides ... i tutaj co zazwyczaj jest związane z regional differences...// As we observed an increase in BLA dendritic spine number at d7 p.i., it is apparent that different regions of the brain may exhibit different morphological reactions to the insult. Whether this is due to temporal and/or compositional differences in cytokine profile in the different areas or whether local as contrasted with global changes are responsible, is yet unknown [@acharjee_2018]-->
Mounting evidence illustrates that a relatively small population of GABAergic inhibitory neurons are able to tightly control the spiking of pyramidal-like neurons in the BLA, especially those forming synapses at the perisomatic region or the axon initial segment of principal cells due to their critical role in the initiation and propagation of action potentials.<!--citations?--><!-- The activity of principal cells is well-documented to be tightly regulated by a relatively small population of GABAergic inhibitory neurons. // plays a central role in the regulation of amygdala excitability.--><!-- Importantly, GABAergic inputs were reported to be able to control spiking of pyramidal-like neurons in the BLA, especially when formed at the perisomatic region or the axon initial segment, a region critical for the initiation and propagation of action potentials. ///Indeed, it has been demonstrated that AACs can control action potential generation at the AIS of projection neurons via their GABAergic inputs, either through changing the action potential threshold, or by shifting the site of origin (Douglas and Martin, 1990; Somogyi et al , 1982; Wefelmeyer et al , 2015; Veres et al , 2014). Accordingly,-->
This was reported to happen either *via* changing the action potential threshold or by shifting the site of origin.<!-- zmienić i przeczytać cytowania? -->
The only subpopulation of interneurons presently known to innervate the AIS are chandelier cells, also known as AACs [@bazelot_2015].<!-- zmienić trochę // The only interneuron subtype presently described that innervates the AIS are AACs or chandelier cells (Bazelot et al , 2015).--><!--Importantly, due to its restriction to the AIS, CX3CL1 application and the associated reduction in inhibitory inputs may also affect the properties of evoked action potentials.citations!!!!--><!-- analogous // Moreover, due to its restriction to the AIS, knockdown of NF and the associated reduction in inhibitory inputs may also affect the properties of evoked action potentials. // Moreover, PV-expressing neurons can be further grouped into chandelier cells that were demonstrated to primarily innervate the AIS of principal cells [@bienvenu_2012] and basket cells, which form a continuum, varying proportions of perisomatic and distal dendritic synapses with principal neurons [@veres_2014].
Considering that the perisomatic region generates sodium-mediated action potentials, those strategically positioned inhibitory synapses are thought to strongly regulate PCs' spiking output and timing [@woodruff_2006].-->
Anatomically, these cells express parvalbumin (PV).<!--Anatomically, PV-INs with this characteristic feedback excitation are chandelier INs ( Woodruff et al., 2006 ; Spampanato et al., 2016 ; Szabadics et al., 2006 ).-->
Importantly, electrophysiological data illustrate that in some chandelier cells, action potential discharge can evoke a time-locked, feedback excitatory synaptic input [@spampanato_2016; @szabadics_2006; @woodruff_2006]. <!--Whole-cell recordings from PV-expressing INs in ex vivo slices have shown that in some INs, action potential discharge can evoke a time-locked, feedback excitatory synaptic input ( Spampanato et al., 2016 ; Woodruff et al., 2006 ).--> 
This feedback excitatory input is disynaptic with a latency of `r knitr::asis_output("\U223C")` 4 ms and shows a dual pharmacological sensitivity to AMPA and GABA~A~ receptor antagonists [@woodruff_2006], similar to synaptic bursts seen during oscillations [@perumal_2021].<!-- co to?--><!-- zmienić ... This feedback excitatory input is disynaptic with a latency of `r knitr::asis_output("\U223C")` 4 ms and shows a dual pharmacological sensitivity to AMPA and GABAA receptor antagonists ( Woodruff et al., 2006 ). // This dual pharmacological sensitivity of this feedback current is similar to the synaptic burst seen during SWs ( Figure 1 ). -->
Importantly, one elegant study conducted by @saha_2016 has shown that exclusive reduction of a pool of GABAergic synapses innervating the AIS of BLA projection neurons resulted in similar differences observed after acute CX3CL1 application.
Specifically, elimination of GABAergic inputs in the AIS led to a reduction in GABAergic transmission, decreased firing rate of principal cells, as well as impaired LTP.
What is more, the decreased excitability of principal cells was associated with depolarized threshold potential, while the input resistance was unaltered [@saha_2016; @zonta_2011].
In line with this notion, chandelier cells were reported to regulate action potential generation at the AIS of projection neurons through their GABAergic inputs, either through changing the action potential threshold or by shifting the site of origin (Douglas and Martin, 1990; Somogyi et al , 1982; Wefelmeyer et al , 2015; Veres et al , 2014).<!--zmienić bardziej!!!--><!-- Accordingly, similar differences in action potential properties as seen after acute CX3CL1 treatment arise by shifting the action potential initiation site to the first node of Ranvier (Clark et al , 2005).-->
Thus, it is tempting to speculate that CX3CL1 likely perturbed the signaling of this PV-positive specific set of interneurons onto BLA projection neurons, leading to the observed increased threshold current.<!-- CX3CL1 likely perturbed the signaling of this specific set of interneurons onto BLA projection neurons. --><!--Following CX3CL1 treatment, the firing rate was significantly reduced and the action potential half-width was increased, whereas the input resistance was unaltered. trochę zmienić i zobaczyć czy pisać o action potential hal-width...--><!--The reduced firing rate of neurons could be explained by their hyperpolarized resting membrane potential and a depolarized threshold potential, in accordance with Zonta et al (2011). zmienić i nie rozumiem jak to się ma do całości...--><!-- przeczytać to... // Accordingly, similar differences in action potential properties as seen after NF knockdown arise by shifting the action potential initiation site to the first node of Ranvier (Clark et al , 2005).--> 


<!-- Accordingly, the reduced firing rate of projection neurons could also contribute to the observed LTP impairment (Cohen et al , 1999). -->
At the network level, while impaired LTP in the external capsule–BLA pathway after CX3CL1 treatment in the BLA is consistent with CX3CL1-induced reduction in principal cells' excitability, its relation to suppressed GABAergic inhibition appears counterintuitive at first sight.<!-- While impaired LTP in the vSub – BLA pathway after NF knockdown in the BLA may result from reduced neural excitability, its relation to reduced GABAergic inhibition by NF knockdown appears counterintuitive on first sight. // Because a large majority of the inhibitory signaling within the BLA is provided by locally projecting interneurons, one would expect reductions in interneuron synaptic number and/or activity to have a profound effect on the excitatory output of this region. 
Inhibitory synaptic plasticity has previously been demonstrated within the BLA (Szinyei et al. 2007), and reduced GABAergic activity facilitates long-term potentiation of thalamic input to the lateral amygdala (Bissiere et al. 2003).--> 
However, mounting evidence indicates that different BLA projections target specific subpopulations of interneurons [@mcdonald_2011; @unal_2014], thus enabling input-specific modulation of BLA inhibitory networks, which in turn may affect the induction of LTP in this structure.<!-- ładne zdanie ale trochę zmienić /// Increasing evidence suggests that different BLA afferents target specific subpopulations of interneurons (Leitermann et al , 2016; McDonald et al , 2011; Unal et al , 2014), thus enabling input-specific modulation of BLA local networks, which in turn may affect induction of LTP in this structure-->
Similar to the cellular level, the chandelier PV-expressing interneuronal subpopulation is a good candidate for observed CX3CL1-mediated actions in the BLA.
For instance, it may be related to the fact that previous studies suggested rather excitatory network effects of chandelier interneurons onto pyramidal-like cells in the BLA [@woodruff_2010].<!--However, it may be related to the fact that previous studies suggested rather excitatory net effects of AACs onto BLA projection neurons (Woodruff et al , 2010)// zmienić bardziej --> 
Following this idea, CX3CL1 could inhibit those cells, leading to an observed reduction in the BLA network. 
In line with this hypothesis, TNFa and IL-1b, other immune proteins displaying neuromodulatory activity, were demonstrated to impair specifically PV-expressing neurons in the striatum.
It led to disturbance of network homeostasis manifested as a reduction in GABAergic transmission and abnormal neuronal firing [@rossi_2011].

Moreover, the external capsule contains mainly cortical fibers [@mahanty_1999].<!-- inputs from cortex-->
Besides targeting principal cells, monosynaptic connections from the cortex recruit local interneurons *via* feed-forward circuits.<!--There are monosynaptic connections from cortex to the BLA, and, in addition to principal cells, they can recruit local interneurons *via* feed-forward circuits. // Monosynaptic cortical – BLA projections exist, and can recruit not only principal cells, but also local interneurons *via* feed-forward circuits, but the role of AACs remains unclear (Bazelot et al , 2015; Hübner et al , 2014). sprawdzić te cytowania i to przemyśleć...-->
In addition, chandelier cells were shown to form reciprocal connections with PCs, and thereby they could also be part of local feedback circuits [@veres_2014].<!--Given that cortical afferents represent only a minor part of BLA afferents substantial part of BLA inputs and AACs were reported to form reciprocal connections with PCs, they could also be part of local feedback circuits.// However, vSub afferents represent (for example, Canteras et al , 1992) and AACs are also reciprocally connected to projections neurons, suggesting they could also be part of local feedback circuits (Veres et al , 2014).-->
Accordingly, both types of network mechanisms might be involved when stimulating the external capsule.<!-- this form of synaptic plasticity in the BLA may be also shaped by intra-amygdalar local inhibitory networks.-->

Of note, during fear conditioning, conditioned stimuli (CS) were reported to activate PV-expressing interneurons, which in turn inhibited SOM-positive interneurons, resulting in a disinhibition of PCs dendrites which facilitate excitatory synaptic plasticity (Wolff et al., 2014).<!-- inaczej napisać Interestingly, it has been shown that conditioned stimuli (CS) activate PV INs during fear conditioning, which in turn inhibit SOM INs, resulting in a disinhibition of PN dendrites which facilitates excitatory synaptic plasticity (Wolff et al., 2014).-->
Hence, in line with the hypothesis that CX3CL1 specifically acts on chandelier cells, it is tempting to speculate that the inhibition of this subpopulation activity could prevent disinhibition.
Consistently, it could contribute to the impaired long-term potentiation, and thus lead to anxiolytic effects.<!--poprawić-->


The brain comprises an excitatory/inhibitory (E/I) neuronal network that maintains a finely tuned balance of activity critical for normal functioning. 
Consistently, disruption of GABAergic inhibition in the BLA causes a disturbance of the E/I balance and has been implicated in many neurobiological diseases, such as anxiety, emotional dysregulation, or epilepsy (for a comprehensive review: @prager_2016).<!-- // original: Pathological disruption of GABA~A~ receptors causes a disruption of the excitatory/inhibitory balance and has been increasingly implicated in neurological and neurodegenerative diseases (Deidda et al., 2014) // The brain comprises an excitatory/inhibitory neuronal network that maintains a finely tuned balance of activity critical for normal functioning. --><!-- BLA hyperexcitability manifests behaviorally as an increase in anxiety, emotional dysregulation, or development of seizure activity.--><!-- Moreover, GABAergic regulation in the amygdala plays a key role in epilepsy.citation--><!-- Aroniadou et al. reported a key role of the amygdala’s GABAergic control in epilepsy. The stress-induced damage to the noradrenergic system, promoting GABA release in the BLA, may underlie the stress-induced exacerbation of seizure activity in epileptic patients (Aroniadou-Anderjaska et al., 2007).-->
It can occur *via* a loss of local GABAergic interneurons, an alteration in GABA~A~receptor activation, or a dysregulation of mechanisms that modulate BLA GABAergic inhibition.<!--Disruption in GABAergic inhibition in the BLA can occur when there is a loss of local GABAergic interneurons, an alteration in GABA~A~receptor activation, or a dysregulation of mechanisms that modulate BLA GABAergic inhibition. from review @prager_2016-->
Hence, the GABAergic inhibitory system is the main target of therapeutic treatments to reduce anxiety or seizures and maintain homeostasis.<!-- zmienić // the GABAergic inhibitory system is one target of therapeutic treatments to reduce anxiety and maintain homeostasis.-->
For example, benzodiazepines, which allosterically enhance postsynaptic actions of GABA~A~ receptors, are an early treatment for anxiety and seizure disorders [@farb_2014].<!-- which allosterically enhance postsynaptic actions of GABA~A~receptors at the inhibitory type A GABA receptor (GABAAreceptor), are one first-line treatment for anxiety (Farb and Ratner, 2014) and seizure disorders.-->
Noting that various GABAergic neuron types of the amygdala cooperate to control principal cell firing during fear-related and other behaviors, a better understanding of their specialized roles is of high importance. 

Considering the previously reported CX3CL1 modulation of GABA~A~ receptors in epileptic tissue [@roseti_2013; @yeo_2011], together with increasing evidence of its regulation of excitatory/inhibitory circuits balance (@sheridan_2014, and this study), strongly indicate this molecule as a potential candidate for altering neuronal network excitability in epilepsy. <!--Various chemokines and their receptors are increased in both parenchymal brain cells and leukocytes in human and experimental epilepsy (Cerri et al., 2017; de Vries et al., 2016; van Vliet et al., 2018). Chemokines, especially CX3CL1, are endowed with neuromodulatory actions which make them potential candidates for altering neuronal network excitability in epilepsy.zmienić In addition to their role as chemotactic molecules that govern the tissue extravasation of peripheral immune cells, chemokines are endowed with neuromodulatory actions which make them potential candidates for altering neuronal network excitability in epilepsy.--><!-- Thus, it is possible that present data, together with the reported role of GABAergic dysfunctions in the BLA in the pathophysiology of epilepsy, support a potential involvement of CX3CL1/CX3CR1 signaling in the pathophysiology of seizures.// These data, together with the reported changes in chemokines level in brain and biofluids in epilepsy patients, support a potential involvement of chemokine signaling networks in the pathophysiology of seizures.// zmienić -->
A more complete understanding of the intrinsic excitatory/inhibitory circuit balance of the amygdala and how imbalances in inhibitory control contribute to excessive BLA excitability will guide the development of novel therapeutic approaches in neuropsychiatric diseases <!-- ładne conclusion --><!-- DODAĆ JESZCZE CHEMOKINE CONTRIBUTION???? -->
 
In addition, given that the BLA is a region highly innervated by a set of neuromodulators, together with the demonstrated ability of chemokines, including CX3CL1, to impact those systems, other neurotransmitters/neuromodulators contribution cannot be excluded.
However, many neuromodulatory inputs to the BLA are absent from coronal slices containing the amygdala.
Hence, despite the previously reported action of CX3CL1 on 5-HT neurons in the DRN, serotonin contribution to reported effects of acute exogenous application of this chemokine is unlikely. 
Nevertheless, this additional level of complexity should be strongly considered in the context of behavioral consequences of chemokine family regulation in this network.
Therefore, since ......., these early results presented in this study should trigger further investigation of the possible interactions with other neuromodulators/neuropeptides in this structure. 
<!-- dokończyć--><!--Neuromodulation?
It should be noted that immune proteins, including CX3CL1, exerts their neuromodulatory role not only by directly acting on GABAergic and glutamatergic systems or neuronal properties, but also indirectly by affecting other neurotransmitters/neuromodulators.
NE - Activation of β -receptors, which seems to be present on both pyramidal cells and interneurons at least in the amygdala (Farb, Chang, & LeDoux, 2010) induces the phosphorylation of AMPAR GluA1 subunit thereby lowering the threshold for synaptic delivery of GluA1 containing AMPARs during LTP expression. (Hu et al., 2007). 
Additionally, it has been shown that blocking of β -receptors by propranolol reduced surface expression of GluA1 containing AMPARs in the LA (Zhou et al., 2015). 
Consequently, a reduced supply of NA in TPH2− / −mice might lead to a decreased phosphorylation of AMPAR GluA1 subunits followed by a reduced surface expression of GluA1 containing AMPARs, which might cause an attenuated LTP expression. from [@gebhardt_2019] 

It is well-known that α2-receptors primarily serve as presynaptic autoreceptors. Activation of α2-receptors exerts inhibition of spontaneous activity (Buffalari & Grace, 2007) probably via inhibition of voltage-gated Ca2+channels and activation of inward rectifying K+channels and seems to inhibit both LTP and LTD in the basolateral amygdala (DeBock et al., 2003).

Thus, in mice lacking brain serotonin we found long-term plasticity changes both in the amygdala and in the hippocampus. 
Priming of LTP by prior paired pulse stimulation seemed to compensate the deficits of serotonin in the brain at the level of the functional readout.
--><!--It should be noted also that immune proteins, such as TNFalpha or IL-1b do not only exert their effect by modulating synaptic transmission, but also *via* interacting with modulatory systems. citations--><!-- These cytokines, such as tumor necrosis factor-a and interleukin-1b, not only exert their excitatory effects via upregulating excitatory synaptic transmission [30, 31], but also regulate neuronal functions via interacting with modulatory systems [32]-->



## CX3CL1 in the lateral subdivision of the central amygdala

In the present study, the CX3CL1-mediated neuromodulation in CeL circuit was identified.
Specifically, acute application of CX3CL1 on brain slices containing the amygdala resulted in cell-specific changes in the excitability of Regular-Spiking neurons, accompanied by affected membrane properties, and GABAergic transmission, while membrane properties of Late-Firing neurons were mainly unaffected in response to CX3CL1. These changes were accompanied by the regulation of GABAergic transmission by CX3CL1. 
Thus, these findings strongly suggest that CX3CL1 acts as a neuromodulator in the CeL, a limbic hub involved, among others, in fear circuitry.<!--autonomic regulation, emotion, and motivated behavior.-->

Increasing evidence in the amygdala, including CeL nuclei, elucidate the functional heterogeneity of neuronal and glial cells, reflected as 

It should be noted that - at least subset of cells - 
Similar cell-type-specificity is present during fear conditioning.
Specifically, in the CeL, SOM- and PKC`r knitr::asis_output("\U03B4")`-positive neurons account for approximately 90% of whole neuronal population.<!--citations-->
During fear conditioning, excitatory synapses onto SOM-expressing neurons are being strengthened, whereas those onto PKC`r knitr::asis_output("\U03B4")`-containing neurons are being weakened [@li_2013a].<!--We recently discovered that fear conditioning induces cell-type-specific plasticity in the CeL, with excitatory synapses onto SOM+ neurons being strengthened and excitatory synapses onto SOMneurons being weakened ( Li et al., 2013 ).-->
Moreover, when the strengthening of excitatory synapses onto SOM-expressing neurons is prevented, the fear memory formation is impaired, illustrating experience-dependent synaptic potentiation onto SOM-positive neurons in the CeL as a critical component of fear circuitry. <!--Notably, preventing the strengthening of excitatory synapses onto SOMneurons is associated with impaired fear memory formation, and activation of SOMneurons is necessary for fear memory recall and sufficient to drive fear responses.These observations indicate that experience-dependent synaptic potentiation onto SOMCeL neurons stores fear memories and enables the expression of conditioned fear responses ( Li et al., 2013 ).-->
<!--The CeL presumably gates fear expression by tonically inhibiting medial subdivision of the central amygdala (CeM), the major amygdala output to downstream fear effectors that control defensive responses ( LeDoux et al., 1988 ; Johansen et al., 2011 ). -->

In Late-Firing, CX3CL1 does not impact the parameters examined, suggesting that this chemokine selectively targets Regular-Spiking in the CeL. 

Those neurons were shown to extensively inhibit PKC`r knitr::asis_output("\U03B4")`-containing neurons within the CeL, they do not 
Interestingly, although the SOMCeL neurons can inhibit locally within CeL, strongly inhibiting SOMneurons, they neither send noticeable projections to the CeM nor inhibit CeM neurons ( Li et al., 2013 ). 
In sharp contrast, the PKC-expressing CeL neurons strongly project to and inhibit CeM neurons ( Haubensak et al., 2010 ; Li et al., 2013 ).

These findings suggest that activation of SOMneurons promotes fear expression, at least in part, by inhibiting PKC-(SOM) neurons, thereby disinhibiting CeM. They also suggest that the fear conditioning-induced synaptic modifications in CeL likely underlie the changes in cell firing in CeL and CeM during fear conditioning ( Ciocchi et al., 2010 ; Duvarci et al., 2011 ). 

CX3CL1 presented also cell-specific actions in the DRN, acting only on serotoninergic neurons [@heinisch_2009].

### Paralleled by decreased frequency of sIPSC onto Late-Firing neurons

IS might be seen often in Vip cells as a result of their high input resistance, which increases the possibility that noise, an intrinsic subthreshold oscillation, or a small synaptic input will produce sufficient depolarization to reach spike threshold. <!-- but we have decreased input resistance, BUT depolarized...-->


Further work is required to determine whether Late-Firing cells specifically express CX3CR1 receptor by some more <!--czuły-->methods such as ..... <!-- analogous -->


From microcircuit point of view, such specificity of activation of specific neuronal subpopulation ...

In this study, the identity (that is, ON or OFF cell, PKCδ+ or PKCδ−) of the CeL neurons activated by BLA terminal optical stimulation was not determined. 

<!-- vasopressin and oxitocin in the CeA -dissertation, but should be articles-->

This influence can be assumed to increase reciprocal interactions between CElon and CEloff pathways, thereby boosting the medial CE (CEm) output pathway and contributing to the anxiogenic-like action of SP in the amygdala.

In rats subjected to restraint stress, acute application of corticotropin releasing factor significantly increased inhibitory postsynaptic potentials in the CeA (Ciccocioppo et al., 2014).

Rats subjected to repeated corticosterone administration showed an increase in anxiety-like behavior, examined using the open field test. The behavioral effects caused by corticosterone injections may because of increased expression of c-Fos in the LA and CeA nuclei of the amygdala and decreased GABAA a -2 subunit density in the CeA of these rats (Skórzewska et al., 2015). These findings are consistent with those of another study (Lussier et al., 2013). Liu et al. (2014) suggested that a lasting loss of tonic but not phasic GABAA receptor currents severely contributes to the prolonged amygdala disinhibition observed after chronic stress.


 In fact, GABAergic control of the amygdala is mostly relevant to anxiety. Some animal researches have shown that administration of corticosterone into the CeA can induce anxiety-like behavior. This animal model imitate the depressed effect of chronic stress on GABAergic tonic inhibition in LA (Myers et al., 2005). There are also some studies that show an association between the amygdala’s GABA interneuronal network and alcohol addiction (Nie et al., 2004, 2009; Bajo et al., 2008). 

We would expect higher proportion of co-localization between SOM-positive and CX3CR1-expressing neurons. 
However, as there is no specific marker of Regular-Spiking neurons, the single-cell RT-PCR ? transcriptome.... ? new method
No tendency of co-localization of SOM+-expressing neurons 



A handful of studies have utilized CX3CR1-deficient mice to explore the role of this receptor in chronic stress, regarding its regulation by stress (Bollinger et al., 2016; Bollinger et al., 2017; Trojan et al., 2017), its importance for microglial morphological ramification and phagocytosis (Hellwig et al., 2016; Milior et al., 2016; Rimmerman et al., 2017), and its beneficial versus detrimental role in brain and behavioral responses to physio-pathological (Gunner et al., 2019; Lowery et al., 2017; Schecter et al., 2017) or psychosocial stressors (Hellwig et al., 2016; Milior et al., 2016; Winkler et al., 2017; Wohleb et al., 2013).
Among these, studies have showed that CX3CR1 rescued chronic stress-induced increase in microglial phagocytosis (Milior et al., 2016) and decrease in hippocampal long-term potentiation (Milior et al., 2016), while improving neurogenesis and short-term memory (Rimmerman et al., 2017).
CX3CR1-deficiency caused social withdrawal and increased repetitive behavior (Zhan et al., 2014), as well as increased fear acquisition and reinstatement (Schubert et al., 2018), implicating a beneficial function of CX3CR1 for the stressed brain. 
However, other studies showed that CX3CR1-deficient mice were resistant to chronic stress-induced depressive-like and anxiety behaviors (Hellwig et al., 2016; Milior et al., 2016; Rimmerman et al., 2017; Wohleb et al., 2017), jointly implying a detrimental role of CX3CR1 in psychiatric disorders. [@paiirainen_2021]


We also observed the regional heterogeneity of microglia and its potential importance for neurological diseases and psychiatric disorders (Li et al., 2016; Tan et al., 2020; Xuan et al., 2019). [@paiirainen_2021]

### immuno 

 Interestingly, the subcellularlocalization profile of CX3CL1 and CX3CR1 are distinct.CX3CL1 localizes as cell-filled puncta whereas its receptorlocalizes in a perinuclear pattern within neurons. This fur-ther suggests synthesis, as well as potential storage andrelease, of CX3CL1 in 5-HT neurons. In contrast, CX3CR1may require cellular activation for receptor mobilization tothe cellular membrane in order for CX3CL1-CX3CR1 in-teraction to occur. [@heinisch_2009]
 
## Microglial action in the amygdala {#microfuckingglia}

It is not possible to discuss the CX3CL1 neuromodulatory action without noting the controversy regarding the localization of its sole receptor, CX3CR1. 
Despite convincing evidence .... .
Moreover, microglia are getting much attention regarding its role beyond inflammation, and transgenic mice with knock down of CX3CR1 replaced with GFP - exclusively in microglia.
Therefore, to try to dissect the cellular contribution of CX3CL1-mediated neuromodulatory effects in this study, the slices were pre-applied with minocycline, which is commonly used to inhibit microglial activation. 
However, it was fully acknowledged that minocycline is an antibiotic, which has some other unrelated effects, including direct action on neurons.<!-- It should be noted that although minocycline is commonly used to inhibit microglial activation, there are some studies illustrating its direct neuronal action <Minocycline is used commonly to inhibit microglial activation. However, minocycline also has been reported to directly affect neurons.32,49,50 Multiple lines of evidence have shown the role of minocycline in protecting neurons from apoptosis via inhibiting p38 MAPK activity.30–32,51,52 // Our observation of increased neuronal p38 MAPK activity in the CeA raises the possibility that minocycline could have inhibited visceral hypersensitivity through an attenuation of neuronal apoptosis via a direct inhibition of p38 MAPK activity. Therefore, we applied apoptosis analysis in WAS and SHAM animals. - Yuan2020////It should be noted that minocycline, in addition to inhibiting microglial activity, has many other unrelated effects.-->
Moreover, the term "microglial activation" in the light of mounting evidence demonstrating the contribution of those cells in complex phenomena under non-inflammatory condition, presenting high level of heterogeneity not only between brain regions, but also within the same structure, is an oversimplification (comprehensive reviews and references therein: ). 
Thus, considering all these issues, unfortunately, the presented pharmacological approach in this study by using a moderately specific inhibitor is not sufficient to draw any strong conclusion in the context of neuron-microglia cross talk.
Nevertheless, a few observations in this study might be insightful in this regard, when further replicated and explored by using methods allowing for a more precise temporal and cellular manipulation, such as, for example, optogenetic/chemogenetic techniques.<!-- lepiej napisać -->

First, the CX3CL1-mediated downregulation of GABAergic transmission as well as elevated threshold current in principal cells in the BLA were not observed when minocycline was pre-applied, raising the possibility that microglia may be involved in this process.<!-- However, regardless of the presence of minocycline, the same proportion of neurons were responsive to CX3CL1(2nM), suggesting that microglia might not be involved in this process (see Fig \@ref(fig:CX3CL1BLAsEPSCfigall) in Appendix \@ref(CX3CL1sEPSCappendix)).-->
Importantly, minocycline applied alone was shown to facilitate principal cells' firing and affect the kinetics of excitatory synaptic transmission in the BLA.
<!-- many possibilities-->
Although a direct neuronal mechanism of these effects cannot be excluded, previous reports observed glial... <!-- astrocytes -->.
<!-- Jeszcze coś ? mGluR? -->



Moreover, regardless of the cellular site of this minocycline-induced glutamatergic enhancement, there is a possibility that the mechanisms underlying CX3CL1-mediated increase in threshold current and minocycline-induced actions on glutamatergic transmission and principal-cells activity are independent.
In addition, the condition where CX3CL1 and minocycline were both present, and neither of CX3CL1- nor the minocycline-mediated effects were observed, raises the interesting possibility.
In the set of experiments, minocycline alone was added to the recording ACSF and present during the 15-minutes of slice incubation and next during the whole electrophysiological recording, including the bath-application of CX3CL1.
This protocol was used according to many studies to, allegedly, inhibit the microglial activation (citations).
However, CX3CL1 was applied onto BLA neurons shortly after the minocycline-induced upregulation of glutamatergic transmission and neuronal activity.
Hence, CX3CL1 might eliminate this increased glutamatergic drive, supporting the hypothesis that their action depends on the initial activity of the network, leading to excitatory/inhibitory balance [@bertollini_2006; @sheridan_2014].
This idea is in consistent with the observed here CX3CL1 complex actions on the excitatory synaptic transmission in the BLA: CX3CL1 was shown to decrease the frequency of sEPSC onto BLA neurons with higher frequency during baseline, especially at the concentration of 5nM.
In accordance, this and other studies demonstrated the TTX-sensitive modulation of glutamatergic and/or GABAergic synaptic transmission by CX3CL1, supporting their actions at network level [@heinisch_2009].
Finally, the potential role in maintaining the E/I balance, along with rather action-dependent modulation of synaptic transmission, was also proposed to other chemokines and cytokines, including IL-1b and TNF-alfa, suggesting the similar action of the immune proteins in brain physiology (citations).<!-- --><!--In line with the hypothesis - homeostasis synaptic scaling - there is possibility that, regardless of the mechanism of minocycline-induced increase in PCs' excitability, the lack of observed effects when CX3CL1 is added to pre-applied minocycline is its "normalizing" action.CX3CL1 could decreased the previously elevated PCs' firing as well as kinetics of sEPSCThese issues findings are hard to interpret, especially when ....inspecific many explanations--> 



To sum up, findings presented in this study does not conclusively support a direct action of CX3CL1 on neurons or/and minocycline on microglia.
The possibilities that the observed effects happen as a consequence of CX3CL1-mediated activation of CX3CR1 solely on microglia or/and minocycline acts directly on neurons cannot be discounted.
Nevertheless, although the underlying cellular mechanisms and the possible regulation of local neuron-glia communication in the amygdala is still largely unknown, this study has shown that both CX3CL1 and minocycline modulates neuronal excitability and synaptic transmission in the basolateral and central nucleus of the amygdala. 
<!-- Our data does not conclusively support a direct action of CX3CL1 on neurons and we cannot discount the possibility that the effects we see on LTP and calcium influx in neuronal cell types happen as a consequence of CX3CL1-mediated activation of CX3CR1 solely on microglial cell types.<!-- analogous // Yet, our findings do not exclude the neuronal participation in releasing adenosine, thus acting in an autocrine manner, or the adenosine-mediated release of additional neuroprotective factors from glial cells.// Here, we report rapid modulatory effects of CX3CL1 on neuronal events in hippocampal tissue.--><!--Our data does not conclusively support a direct action of CX3CL1 on neurons and we cannot discount the possibility that the effects we see on LTP and calcium influx in neuronal cell types happen as a consequence of CX3CL1-mediated activation of CX3CR1 solely on microglial cell types. Sheridan2014-->
<!--If this is true, however, the ability of microglia to rapidly regulate multiple hippocampal memory-associated synaptic plasticity processes may be much more extensive than traditionally thought.  // Sheridan2014-->


<!-- adenosine receptors in the BLA-->


Considering the exceptional communication between neuronally secreted CX3CL1 and abundant CX3CR1 expression on microglial cells<!--citation?-->, together the key role of microglia in sensing neuronal microenvironment<!--( Davalos et al., 2005 ) something newer?-->, it was not surprising to discover that some of the effects of CX3CL1 are also mediated by these glial cells. <!-- Trettel 2020 --><!-- analogous?-->
Interestingly, our results regarding the impaired LTP and reduced excitability of principal cells, along with modulated morphology of dendritic spines in microglial-deprived neuronal cultures, strongly suggest primarily the neuronal effects of CX3CL1. 

On the contrary, the inhibition of microglia activation, without eliciting any effects by solely minocycline activation, prevented CX3CL1-induced reduction of principal cells' firing and GABAergic neurotransmission.
//////////////////////////////////////////////////
The deficiency in microglial CX3CR1 can cause communication defects among neurons, microglia and astrocytes during numerous CNS diseases or even injuries (Sungho_2010).<!--zmienić i zerknąć na cytowanie--> 
In addition, CX3CL1 activation is correlated with fear-related behaviors, especially elevated-plus maze, which is characteristic ... of amygdalar function. <!--the specific type of neuropathic pain induced by multiple sclerosis through interaction with cX3cR1 (Zhu_2013).--> Moreover, the levels of CX3CL1 are potentially regulated by diverse neurotoxic stimuli and its signaling is correlated with several types of cNS diseases, including HIV infection, epilepsy, and cerebral tumors among other neuropathologies (limatola_2014) [@chen_2020]

Notably, previous studies demonstrated that in vitro lipopolysaccharide- and interferon γ-induced release of multiple cytokines (i.e., IL-1β, TNFα, and IL-6) in cultured microglia can be effectively suppressed through the activity of cX3cL1 signaling. 
This suggests that cX3cL1/cX3cR1 signaling is vital in modulating upstream production and cytokine release from microglia (limatola_2014), thereby contributing to the feedback loop as well. 
By inhibiting the cx3cl1/cX3cR1 pathway, AZd8797 can suppress the role of microglia and astrocytes, thus preventing the development of the inflammatory response (biber_2014, kasama_2010).<!--SPRAWDZIĆ JESZCZE TE CYTOWANIA...--> 
/////////////////////
<!--micro-fucking-glia // On the other hand, noting that minocycline alone increased PCs' excitability (see Fig\@ref(fig:CX3CL1BLAexcitabilityadd)) and the CX3CL1 application resulted in inhibition of firing of those neurons, there is a possibility that the CX3CL1 treatment abolished prior minocycline-mediated elevated excitability of pyramidal-like neurons independently on CX3CR1 activation instead of elimination of the CX3CL1-triggered effect on neuronal firing by minocycline. 
Therefore, presented results in this condition cannot argue about microglial contribution to the observed effects.
To this end, a replication of those experiments using another method of microglial inhibition is of high relevance.
However, concerning reported abundance of CX3CR1 expression in microglial cells, along with growing recognition of microglial cells in regulation of brain functions under psychological conditions, this scenario is highly unlikely.-->


<!-- Hence, considering all these issues, the microglial contribution to observed CX3CL1-mediated effect strongly warrants further investigation. -->

<!-- Changed kinetics of sEPSC - was previously demonstrated in astrocytes when extrasynaptic AMPA receptors, too much glutamate - 
Thus, minocycline could elevate glutamate by activating extrasynaptic AMPA. 
The increase in glutamate/excitability led to disturbance in E/I balance, and thereby CX3CL1 eliminated these minocycline-induced effect to restore the homeostasis.
This is in line with what was observed when CX3CL1 was applied alone. 
It should be noted that CX3CL1 reduced sEPSC frequency mainly in those neurons which received higher number of these events during baseline.  -->

<!-- These findings suggest not only that minocycline is able to elicit effects are independent from CX3CL1/CX3CR1 signaling, but also raise the possibility that the minocycline-triggered inhibition of microglial activity might regulate principal neurons' firing in the BLA in an opposite manner to CX3CL1. -->
<!-- we acknowledge that minocycline, in addition to impairing microglial proinflammatory and phagocytic activity, has many other unrelated effects; however, our use of ICV injection at least eliminated the peripheral effects of minocycline ( Brundula et al., 2002 ; Giuliani et al., 2005 ). [@acharjee_2018] // We measured mEPSC amplitude and frequency at 	 70 mV after 20–24 h of minocycline treatment. 
We found that minocycline increased mEPSC frequency (), but not amplitude in EAE mice compared with EAE-vehicle-treated mice (). Thus, the EAE phenotype is even more apparent after additional microglial inactivation. // In the experiments presented here, it was acutely applied on brain slices, thus, the peripheral effects of minocycline does not affect presented results.-->
<!--Thus, these findings warrant further investigation, for example by using opto- or chemogenetic activation of those cells.lepiej napisać--><!-- Generally, the increase in sIPSC or sEPSC frequency enhanced the probability of neurotransmitter release from the presynaptic terminal. Thus, the effect of minocycline on SG neurons is mainly of a presynaptic origin rather than a postsynaptic origin-->

<!-- zmienić
Interestingly, by modulating the expression levels and surface diffusion of glutamate transporters, astrocytes influence synaptic transmission by controlling the glutamate spillover beyond the synapse. 
Such glutamate spillover can activate extrasynaptic metabotropic glutamate receptors (Huang et al., 2004), which shape the kinetics of excitatory postsynaptic currents (EPSCs; Murphy-Royal et al., 2015). 
Hence, changes in EPSCs have important effects on the local and temporal integration of synaptic inputs by neuronal networks, and consequently on synaptic plasticity. 
Therefore, glutamate transporters not only support synaptic homeostasis, but also contribute, at least in part, to plasticity processes at the synaptic levels (reviewed by Rose et al., 2017). <!-- analogous - microglia? we have changes in RT and DT after minocycline application-->

<!--glial impact?
By releasing glutamate, D-serine, GABA, ATP, adenosine, or tumor necrosis factor-alpha, among others, astrocytes control the basal tone of synaptic activity and the threshold for synaptic plasticity
Astrocytes may also indirectly participate in inducing LTP by microglia by cognition by releasing CCR5 ligands that act on and recruit CCR5-expressing microglia to neighboring neurons, after which the microglia engage in functions related to synaptic remodeling and modulation. 
Although the exact mechanism of CCR5-regulated microglial pruning remains unknown, microglial CCR5 is well-positioned to contribute to synaptic plasticity and resultant regulation of cognitive function.-->




We believe that our technique is well suited to investigate changes in BLA morphology and activity, which have been implicated in a number of disease states, including posttraumatic stress disorder and drug addiction (Koob et al. 2014; Mahan and Ressler 2012; Roozendaal et al. 2009). 
Posttraumatic stress disorder and other forms of chronic stress are often associated with increases in amygdala activity, resulting in the dysregulation of fear responses and causing sensitization to stressful stimuli (Mahan and Ressler 2012; Roozendaal et al. 2009). 


Previous studies have shown that emotional responses generated by the BLA may result from increased excitatory input and changes in glutamate receptor ratios (Christian et al. 2012; Hubert et al. 2014; LeDoux 2003) and repeated restraint stress can cause changes in BLA spine localization (Padival et al. 2013). 
It would be interesting to investigate whether these changes result from altered levels of not only excitatory input but also inhibitory synapses within the BLA and other nuclei within the amygdala. <!-- klenowski_2015-->

Feng et al. found another potential therapy for regulate stress is motilin which can weaken anxiety-like behavior in rats after they have been subjected to forced swimming. Whole-cell recordings from amygdala slices revealed that motilin depolarized the interneurons and promoted GABAergic transmission in the BLA (Feng et al., 2013).

 It is worth noting that the HPA axis can mediate the stress response because it is a neuroendocrine system. Some researchers looked at the effects of rapid glucocorticoid-induced acute stress in the rat BLA. Glucocorticoid administrated to amygdala slices produced a rapid, non-reversible suppression of spontaneous GABAergic synaptic currents (Di et al., 2016). The acute administration of glucocorticoid receptor agonist DEX also upregulated GABA release and GABAergic neuronal spiking (Wang et al., 2016).
 

 
 The observed level of somatic variation, dendritic organization, and spine localization is likely to provide important morphological control over the integration of synaptic inputs, which would be expected to influence cellular output and potentially contribute to differences in BLA principal cell physiology.
 
Although a number of brain areas are involved in neuronal circuits activated in the presence of a thread causing fear and anxiety (Belzung, Turiault, & Griebel, 2014; Giustino & Maren, 2015; Tovote, Fadok, & Luthi, 2015), there is a fundamental agreement that LTP-induced changes in synaptic strength in the LA occur during fear learning (Blair, Schafe, Bauer, Rodrigues, & LeDoux, 2001; Maren, 2005; Sah, Westbrook, & Luthi, 2008).
The observed reduction of LTP magnitude after CX3CL1 application might suggests that anxiety vulnerable mice may have difficulty in learning about and predicting when aversive events will occur. 
It has been shown that fear conditioning occludes LTP-induced presynaptic enhancement of synaptic transmission in the cortical pathway to the LA (Mahan & Ressler, 2012). 
Further investigations are needed to understand the mechanisms of metaplasticity at the molecular level.

Learning about motivationally important stimuli involves plasticity in the amygdala, a temporal lobe structure. Amygdala-dependent learning involves a growing number of plasticity-related signaling pathways also implicated in brain development, suggesting that learning-related signaling in juveniles may simultaneously influence development. 

Recent studies indicate that the lateral subdivision of the central amygdala (CeL) is essential for fear learning. Specifically, fear conditioning induces cell-type-specific synaptic plasticity in CeL neurons that is required for the storage of fear memories.<!--peennzoo-->

These long-range projection CeL neurons are predominantly somatostatin-positive (SOM) neurons, which can directly inhibit PAG neurons, and some of which innervate both the PAG and paraventricular nucleus of the thalamus. Notably, fear conditioning potentiates excitatory synaptic transmission onto these long-range projection CeL neurons. Thus, our study identifies a subpopulation of SOMCeL neurons that may contribute to fear learning and regulate fear expression independent of CeM.[@penzo_2014]

The central amygdala (CeL) is composed of distinct types of GABA-producing inhibitory neurons ( Cassell and Gray, 1989 ; Cassell et al., 1999 ; Ehrlich et al., 2009 ; Haubensak et al., 2010 ), among which the somatostatin-positive (SOM) neurons are a major population ( Cassell and Gray, 1989 ; Li et al., 2013 ). These are intermingled with SOMcells that are predominantly protein kinase C--expressing (PKC-) neurons ( Haubensak et al., 2010 ; Li et al., 2013 ). SOMneurons and PKC-neurons collectively constitute  90% of the entire CeL population, and the two cell types are mutually inhibitory ( Haubensak et al., 2010 ; Li et al., 2013 ). We recently discovered that fear conditioning induces cell-type-specific plasticity in the CeL, with excitatory synapses onto SOMneurons being strengthened and excitatory synapses onto SOMneurons being weakened ( Li et al., 2013 ).


<!-- zdania z dupy 

Increased anxiety and depression, accompanied by impaired sociability are considered hallmarks of abnormal stress-related neuropsychiatric manifestations in both rodents and humans (Brodkin, 2007; Ma et al., 2015; Theoharides et al., 2016). 

Meanwhile, it is noteworthy that CX3CR1 may not be universally important for all types of physiological adaptations, as indicated by its recently reported dispensability in light deprivation-induced visual cortex plasticity (Lowery et al., 2017; Schecter et al., 2017).

Other chemokines, such as MCP1, are recently found to be involved in descending facilitation of neuropathic pain. Neutralizing CCL2 with an anti-CCL2 antibody into the rostral ventromedial medulla after spinal nerve ligation significantly attenuated the established thermal and mechanical hypersensitivity

hypersensitivity. In agreement with the upregulation of CXCL1 and CXCR2, antagonism of CXCL1CXCR2 was attenuated and CXCL1 agonist stimulation enhanced the nocifensive behavior.


This synaptic potentiation is expressed as an increase in both the frequency and amplitude of mEPSCs in fear-conditioned mice compared with control mice. Whereas higher mEPSC frequency may reflect an increase in either presynaptic release probability or the number of active synapses, a change in mEPSC amplitude usually indicates a postsynaptic effect ( Kerchner and Nicoll, 2008 ; Li et al., 2013 ).

The encoding, consolidation and retrieval of memories is a multifaceted process that depends strongly on the optimal level of arousal but high levels of arousal may trigger anxiety, which negatively impacts the memory processing by the brain.

The modulation of animal behavior by chemokines is channeled through the activation of the dopaminergic and catecholaminergic system in several brain regions. citations

We speculate that the activation of A3Risan event downstream of the release of ADO from astrocytes upon CXCL16 treatment; alternatively, also in light of the emerging data on the determinant role of ADO in cytokine neuroprotection (Biber et al., 2008; Lauro et al., 2008, 2010; Moidunny et al., 2010), it can be hypothesized that ADO acts as a synergistic modulator that senses neuronal environment and, together with specific triggering events driven from single cell types, concurs to neuroprotection acting on specific ARs. However, we cannot exclude that other soluble factors might represent key mediators of CXCL16 neuroprotection, since impairing CCL2 activity dramatically reduces, but did not fully abolish, the ability of the chemokine to preserve neurons. Together these data demonstrate that CXCL16 is constitutively expressed in CNS and that, upon pathological conditions, it is able to reduce neuronal cell death through a mechanism that requires cross talk between astrocytes and neurons, representing an example of how chemokine-induced chemokine-release from astrocytes might be a phenomenon that drives beneficial effects.


Although CX3CL1 may induce monocytic infiltrates during CNS inflammation (Chapman et al., 2000), it ap-pears to exert an overall neuroprotective action.Mizuno etal. (2003)reported CX3CL1-mediated inhibition both ofneuronal apoptosis and of activated microglial nitric oxide,IL-6, and TNF-production. Interestingly, CX3CL1 is alsoup-regulated in HIV encephalitis brain tissue, indicatingthat its induction may be in response to chronic activationof the neurotoxic glutamate-mediated excitatory neuro-transmission by HIV neurotoxins platelet-activating factorand Tat (Tong et al., 2000). In fact, CX3CL1 is a reportedinhibitor of glutamate synaptic activity in the hippocampusunder basal conditions (Bertollini et al., 2006). The abilityof CX3CL1 to modulate glutamate function appears to bethe mechanism involved in its neuroprotective actions, andit provides support for a chemokine-neuromodulatory rolein the CNS (Adler and Rogers, 2005; Adler et al., 2006;Callewaere et al., 2007; Guyon and Nahon, 2007).
-->

<!-- dose 

 Pre-treatment with CX3CL1 prior to glutamate application resulted in an attenuated intracellular calcium rise in cells in the CA1 region of organotypic slice cultures (Figure
 
 In non-neuronal cells, both low(500 pM) and higher (2 nM) physiologically relevant concentrations of CX3CL1 attenuated glutamate-induced calcium influx,in a dose-dependent manner (Kruskal–Wallis
 
 While previous studies have shown that CX3CL1 causes anincrease in intracellular calcium in neurons and other cell types (Oh et al., 2002;Deiva et al., 2004; Ragozzino et al., 2006) this effect of CX3CL1 becomes apparent at concentrations of 25 nM and higher (Oh et al., 2002;Deiva et al., 2004), well above thelevels we investigated here and we observed no such increase in intracellular calcium. At a concentration of 2 nM, in both neurons and non-neurons, CX3CL1 pre-incubation suppressed glutamate-mediated rises in intracellular calcium levels. These
 
 The evidence from rats that CX3CR1 is expressed onhippocampal neuron allows the possibility that, as is the case for CX3CL1-mediated regulation of serotonergic neurons of thedorsal Raphe, glutamatergic neuron-derived CX3CL1 may actin an autocrine/paracrine fashion in the hippocampus during periods of synaptic plasticity to regulate glutamate-mediated neurotransmission tone.
 
 At physiologically relevant concentrations, CX3CL1 inhibited LTP maintenance in the DG.
This attenuation in dentate LTP was lost in the presence of GABA~A~ receptor antagonism. 
CX3CL1 also had opposing actions on glutamate-mediated rise in intracellular calcium in hippocampal organotypic slice cultures in the presence and absence of GABAA receptor/chloride channel blockade -->

<!-- The GABAAreceptor/chloride channel blocker, picrotoxin,used in the current studies would decrease GABAergic inhibitory transmission promoting depolarization in some cells with corresponding increases in intracellular calcium (Antonucci et al.,2012). Thus, the current work suggests GABAAreceptor/chloridechannel activity within the hippocampal neuronal network must be intact for CX3CL1 to attenuate glutamatergic neurotransmission or LTP. This situation is remarkably similar to that described for CX3CL1 inhibition of serotonergic neurons of the Raphe nucleus (Heinisch and Kirby, 2009). While this effect may relate to basal inhibitory tone, CX3CL1 could actually beenhancing GABAAreceptor function. For example, CX3CL1 enhances phosphorylation and activation of Akt in neurons and this serine/threonine kinase has been associated with phosphorylation of the GABAA beta2 receptor subunit, a modification that enhances activity of the receptor (Meucci et al., 2000; Wang et al.,2003). Moreover, several signaling systems can enhance GABA mediated inhibition through promotion of rapid insertion of GABAAreceptors into the post-synaptic plasma membrane (Wan et al., 1997;Nusser et al., 1998; Mizoguchi et al., 2003;Jovanovicet al., 2004).-->

<!-- neuroinflammation and Glu - but GABA?!

Neuroinflammation also alters glutamate metabolism and the function of its transporters ( Müller and Schwarz, 2007; Tilleux and Hermans, 2007; Haroon et al., 2012 ) which mediates cognition and behavior, thus leading to cognitive, behavioral, and psychiatric impairments ( Müller and Schwarz, 2007; Tilleux and Hermans, 2007; Haroon et al., 2012; Sanacora et al., 2012 ). Limited in vitro evidence suggested that inflammation or pro-inflammatory cytokines can increase CNS glutamate levels.  -->
<!-- TNF CEA 

Importantly, other investigations have provided indirect evidence for cytokine action in the CeA being capable of influencing neural activity. Inagaki et al. (2012) found that increasing cytokines in individuals with an LPS challenge induced an fMRI change in the amygdala. Prager et al. (2013) recently noted changes in electrophysiological measures as well as altered cFos levels in amygdala being induced by systemic LPS. More directly relevant, the proinflammatory cytokine, tumor-necrosis-factor-a(TNFa), applied to CeA neurons was found to increase firing rate and facilitate GABA release ( Knapp et al., 2011 ). 

In support of this increased amplitude of mEPSCs by TNFabeing due to receptor trafficking, Beattie et al. (2002) demonstrated that glial TNFainduced surface expression of AMPA receptors on neurons – a finding supported by Stellwagen et al. (2005) who demonstrated directly that TNFaincreased AMPA-receptor number on hippocampal neurons.

Interestingly, while the CRFR-antagonists blocked the ability of TNFato increase mIPSCs, the CRFR-antagonist had no effect on mIPSCs in the absence of TNFa. This latter finding indicates that under the present conditions ambient levels of CRF were not sufficient to influence GABA release (mIPSCs).
-->


<!-- Another wholecell recording study has found that application of IL-1 b (50 ng/mL) for 12–15 min in brain slices caused dual effects  on  mIPSC  frequency  and amplitude recorded from CeA neurons,  as  evidenced  by  increased mIPSC frequency in 62% neurons with decreased mIPSC frequency in 28% neurons, as well as decreased mIPSC amplitude in 38% of neurons, no effect on mIPSC amplitude in 48% of neurons and both increase in frequency and amplitude of mIPSC in 14% of neurons ( Bajo et al., 2015 ), suggesting the existence of the effect of IL-1 b on the spontaneous action  potential-independent  transmission of GABA via both pre- and post-synaptic mechanisms, with predominance of post-synaptic mechanism, in the CeA neurons. -->
<!-- MINOCYCLINE CEA mIPSC
Based upon minocycline being able to attenuate microglial ( Giuliani et al., 2005; Nikodemova et al., 2007; Nutile-McMenemy et al., 2007 ) and astrocytic activity ( McAllister and Miller, 2010 ), minocycline was tested to determine if the TNFa-induced increase in frequency of mIPSCs would be prevented. Fig. 7 shows that the TNFa-induced increase in mIPSC frequency after minocycline (60-lM)  incubation  for  1-h  was  significantly  decreased [( F (2,24) = 4.17); n = 7–13; p < 0.05 with post hoc LSD test]. Minocycline (60lM) incubation alone for 1-h had no effect on the frequency of mIPSCs (i.e., percent change in frequency of mIPSCs was 9.80 ± 8.67%) ( Fig. 7 ) Thus, TNFa-induced release of CRF from glial elements might underlie the apparent involvement of CRF suggested by the CRF-receptor antagonists blocking the TNFa- induced increase in frequency of mIPSCs.-->

<!--  striatum, cytokines, interneurons, network
Inputs from GABAergic interneurons are another important source of synaptic inhibition of MSNs, giving rise to a feed-forward inhibitory pathway that is independent of striatal output ( Koos and Tepper, 1999; Plenz, 2003; Tepper et al., 2004; Gustafson et al., 2006 ). Our data seem to indicate that the feedback and feed-forward GABAergic control over striatal output is differentially affected in EAE, because sIPSCs of larger amplitude and sensitive to TTX were predominantly reduced in these mice, as expected for a preferential involvement of inhibitory interneuronal activity ( Bennett and Bolam, 1994; Kubota and Kawaguchi, 2000; Koos et al., 2004; Gustafson et al., 2006 ). In line with this hypothesis, the total number of striatal neurons, largely composed of projection MSNs ( Kawaguchi et al., 1995; Wilson and Kawaguchi, 1996; Tepper et al., 2004 ), is not reduced in EAE ( Centonze et al., 2009 ), while we found that GABAergic interneurons are markedly underrepresented in the striatum. It is noticeable, however, that although distinct physiological properties of evoked IPSCs originating from axoncollateralsofprojectionneuronsandfromGABAergicinterneurons have been described by using paired recordings ( Koos et al., 2004 ), our recordings of sIPSCs do not allow to conclusively discriminate between the two input sources, and thus GABAergic dysfunction might also involve inputs from axon collaterals of MSNs, and might be more generalized than postulated in the present study. 
Thus, the reasons of the selective susceptibility of PV interneurons to degenerate in MS and in EAE has to be further investigated. The evidence, however, that cytokines signaling, per se, is able to alter GABAergic transmission and consequently circuit functioning, as demonstrated by ‘‘ in vitro ’’ experiments, gives additional interest to the possibility that this mechanism is at the base of late stages of MS pathogenesis. The general GABAergic down-regulation induced by cytokines chronic treatment that emerges from this study, is of impulse for the search of drugs able to control this alteration. The ‘‘ in vitro ’’ model of cortical neurons treatment with cytokines and the paradigm for GABAergic alteration study could turn to be helpful for future drug screening studies

-->

<!-- Because the presence of TTX logically eliminates TNFafrom stimulating action-potentials to release CRF from neurons to increase mIPSC-frequency, one possible explanation considered for this present outcome was that the CRFR-antagonists prevent the TNFa– induced increase in frequency of mIPSCs by blocking the action of CRF released from cells other than neurons. Consistent with this latter possibility is the demonstration that astrocytes are reported to contain CRF ( Tian and Bishop, 2003 )as well as CRF-binding protein ( Maciejeski et al., 1996; McClennen and Seasholtz, 1999 ). Further, a number of other peptides and/or their mRNAs have been localized in a variety of glial cell types including astrocytes ( Ubink et al., 2003 ). Based upon the concept that TNFacan enhance the ability of astrocytes to release transmitter ( Santello et al., 2011; Santello and Volterra, 2012 ), it was reasoned that TNFaacting on TNFa-receptors on astrocytes or other glial elements ( Yan et al., 2008 ), which are reported to contain CRF ( Tian and Bishop, 2003 ), might be involved in making CRF available to account for the CRFR-antagonists preventing the TNFa-induced frequency increase in mIPSCs. Whereas this potential influence of TNFaon glia to influence CRF availability could be either direct or indirect ( Santello et al., 2011 ), in either case glia would be involved in this action of TNFa. -->

<!-- IL-1R1 is expressed on glial cells and neurons, and thus, the overall effect of IL-1 on synaptic transmission is a combination of the direct effects of IL-1 binding to neuronal IL-1R1 and the indirect effects mediated by other signaling molecules generated and released by both neurons and glia in response to IL-1/IL-1R1 binding (e.g., cytokines, chemokines, ATP, etc.).-->

<!-- Our observations of an increase in the frequency of sEPSC and mean quantal content strongly indicate that CCL2 acts on pre-synaptic site. However, it is not clear whether CCL2 acts directly on pre-synaptic terminals, via an inhibitory interneuron, or by inhibition of glial cell uptake of glutamate. A hypothetical model of CCL2 enhancement of EPSCs is shown in Fig. 7.-->


<!-- SDF-1, as shown here, has various effects on the electrical activity of SON neurons, resulting probably from the heterogeneity of the population recorded or from a variety of actions on the AVP neuronal population (26). -->

<!-- Although the lack of somatostatin antibody which .... precluded the cellular localization of the CX3CR1 receptor in CeL neurons, <!--the clear reversibility and concentration dependency of these effects shown in this study, together with the known presence of CCR2 mRNA in CCD neurons, argue strongly that they are receptor mediated.-->

<!-- This current was not blocked by TTX, suggesting that it did not involve action potential-dependent release through the glutamate terminals. Glutamatergic terminals on DA neurones arise from the output of the subthalamic nucleus or prefrontal cortex, which are absent from our slices.-->

<!--The evidence from rats that CX3CR1 is expressed on hippocampal neuron allows the possibility that, as is the case for CX3CL1-mediated regulation of serotonergic neurons of the dorsal Raphe, glutamatergic neuron-derived CX3CL1 may act in an autocrine/paracrine fashion in the hippocampus during periods of synaptic plasticity to regulate glutamate-mediated neurotransmission tone.Sheridan2014-->


is tempting to speculate that the neuron-glia cross-talk is 
These parethe opposing trend in relation to the dendritic head width was observed, with an additional trendily reduction in dendritic length. 
Thus, those parameters led to a significant change in a dendritic head/length ratio, a parameter correlated with immature spine functions.
Therefore, these data illustrate that dendritic spine morphology was modulated by CX3CL1 leading to their subtle increase in their width, whereas reducing the number of glial cells in neuronal cultures almost deprived of those cells at the very beginning  resulted in a more prominent, however opposing, modulation of dendritic spine morphology by CX3CL1.
These observations suggest that CX3CL1 is able to modulate the dendritic spine morphology of neurons in the amygdala. 
Moreover, the opposing effect related to slight changes in glial fraction, further suggest that it may serve as 
However, its action may be these dynamics changes may be dependent on 
As the and may be a critical molecule however the glial cells are, despite their small fraction, are a critical player in CX3CL1-mediated changes the reduction in glial cells cells  has a subtle enlargening 
Thus, these data show that the CX3CL1 application led to an alterations in their morphology (namely, an enlargement and shortening of the head).<!-- zmienić // Thus, these data show that the absence of CX3CR1 leads to a decrease in the number of newborn granule neuron dendritic spines and alterations in their morphology (namely, an enlargement and shortening).-->
<!-- In addition, we also examined spine morphology because changes in spine morphology are believed to represent one mechanism by which synaptic activity leaves its imprint on neurons. This was concurrent with an increase in spines with well-defined heads, which is correlated with spine maturation.-->

Therefore, accompanying these electrophysiological ..... was the immature morphological phenotype of dendritic spines.<!--Accompanying this delay in maturation of spine density was a defect in functional maturation of hippocampal synapses as measured by the ratio of spontaneous and miniature excitatory postsynaptic current amplitude (sEPSC/mEPSC amplitude ratio), long-term depression induction, and seizure susceptibility.-->
Notably, these alterations are independent of microglia.
<!-- his review discusses spine alterations in animal models of maternal immune activation in the context of neurodevelopmental disorders-->

Spikes- high variation - CeL, interneurons, heterogeneity

# spines

In concert with electrophysiological data, the alterations in dendritic morphology was observed in the primary neuronal cultures of the amygdala.<!--Moreover, accompanying the CX3CL1-mediated LTP impairment was the immature morphology of dendritic spines.-->
Dendritic spines are small dendritic protrusions that receive most (>90%) excitatory glutamatergic inputs (Rochefort and Konnerth, 2012; Yuste, 2013; Chen et al., 2014), while GABAergic terminals contact only a low proportion of them (Kubota et al., 2007; Brusco et al., 2014, Müllner et al., 2015).<!--zmienić Dendritic spines are small dendritic protrusions that harbor most excitatory synapses in the brain. /// Spines are specialized postsynaptic elements (see also Shepherd, 1996) that receive most (>90%) excitatory glutamatergic inputs (Rochefort and Konnerth, 2012; Yuste, 2013; Chen et al., 2014). Only a low percentage of spines (although particularly important, Müllner et al., 2015) is contacted by inhibitory γ-aminobutyric acid (GABA)-containing axon terminals (Kubota et al., 2007; Brusco et al., 2014).--> 
<!--Dendritic spines provide an enhanced connectivity, modulation of synaptic processing, strength, and plasticity by considerably increasing the computational possibilities between cells (Anderson et al., 2009; Bourne and Harris, 2009; Rochefort and Konnerth, 2012; Yuste, 2013; Dall’Oglio et al., 2015; Tønnesen and Nägerl, 2016). zmienić-->
<!--The proper generation and maturation of dendritic spines are crucial for the regulation of synaptic transmission, plasticity, and formation of neuronal circuits. zmienić --> 
<!--Abnormalities in dendritic spine density and morphology are common pathologies in autism and schizophrenia. zmienić -->
A large body of evidence supports the critical role of dendritic spines and their morphology in neuronal excitability and synaptic connectivity [@harms_2007; @hering_2001; @kasai_2003].<!-- citation [42–44] zmienić--><!--Morphological features of dendritic spines change in response to environmental stimuli and have an impact on the strength of synaptic connections (Araya et al., 2014; Bosch & Hayashi, 2012).--><!--The size and geometry of the spine head and neck are believed to be main determinants in synaptic signal compartmentalization, strength and specificity [1], [18].--><!--The proper generation and maturation of dendritic spines are crucial for the regulation of synaptic transmission and formation of neuronal circuits/// zmienić/// Thus, dendritic spine morphology is tightly correlated with synaptic function [@nishiyama_2019].///Therefore, it is plausible that long-term potentiation (LTP) and depression (LTD), two major forms of synaptic plasticity, are correlated with the spine enlargement and shrinkage, respectively [@nishiyama_2019]. -->
Hence, observed changes in dendritic spine morphology further indicate a significant impact of CX3CL1 acute application on BLA physiology.<!--jakoś inaczej to napisać we wstępie na początku...-->
Indeed, spines with large, prominent heads and short necks are generally thought to be stable, express large numbers of AMPA-type glutamate receptors, and form stronger synaptic connections than thin spines [@ganeshina_2004; @harris_1992; @kasai_2003].<!--Mushroom spines with a large, prominent head and short neck are generally thought to form stronger synapses than thin spines. zmienić // Spines with large heads are stable, express large numbers of AMPA-type glutamate receptors, and contribute to strong synaptic connections. // Indeed, thin spines are motile, transient, and form weak or silent synapses, whereas spines with large heads (i.e. mushroom and stubby) are more stable and form strong synapses with larger postsynaptic densities, more AMPA-type glutamate receptor content, and larger presynaptic contacts [30,44,45].--> 
By contrast, spines with small heads and filopodial protrusions were reported to be motile and unstable, and contribute to weak or silent synaptic connections.<!--zmienić Stubby spines and filopodial protrusions are considered immature spines that dominate during development, and their percentage in the adult brain is considerably small.// By contrast, spines with small heads are motile and unstable and contribute to weak or silent synaptic connections.--><!--Therefore, it is plausible that long-term potentiation (LTP) and depression (LTD), two major forms of synaptic plasticity, are correlated with the spine enlargement and shrinkage, respectively [@nishiyama_2019].bardziej zmienić-->
This type of dendritic spine morphology dominates during development and is considered as immature.
Here, cultured primary neurons from the amygdala showed a trend toward wider dendritic heads upon CX3CL1(5nM) application. 
Intriguingly, when neurons were cultured in the additional presence of AraC, which was shown to decrease the number of glial cells in culture without altering the neurons viability [], the CX3CL1(5nM) application led to decreased length and width of dendritic spines. 
Notably, no difference between these parameters was observed between control and AraC-supplemented medium, illustrating that AraC treatment did not affect dendritic morphology.
Thus, it is possible that these unexpected findings might reflect the CX3CL1-mediated neuron-glial cross-talk.
We hypothesize that during "normal" condition, the CX3CL1 treatment activated CX3CR1 receptors on both, amygdalar neurons and the remaining glial fraction (5%), leading to observed CX3CL1-modulated wider dendritic spines.<!-- This is consistent with .... -->
Our immunostaining data showed that the CX3CR1 receptor was expressed on both neurons and astrocytes, further supporting this hypothesis.
Given that glia, especially microglia, are crucial players in the dendritic maturation<!--citations-->, together with microglial abundance of CX3CR1 expression<!-- -->, it is plausible that this trend could be more prominent when glial component is higher.

Moreover, under conditions of more decreased number of surrounding glial cells, the CX3CL1-mediated neuron-glial communication is more limited and the activation of CX3CR1 on glial cells further reduced and under those conditions CX3CL1-mediated effects led to observed shorter and thinner dendritic spines.
In support of this supposition, @basilico_2019 found that CX3CR1^-/-^ transgenic mice displayed a higher number of silent synapses in the hippocampus in comparison to their wild-type littermates.
Those synapses were characterized by an immature AMPA/NMDA ratio with defective AMPA components and decreased release probability.<!--Intriguingly, recordings from CA3-CA1 synapses in hippocampal slices of CX3CR1^-/-^ transgenic mice displayed an immature AMPA/NMDA ratio with defective AMPA components and decreased release probability compared to wild-type mice [@basilico_2019], further illustrating that neuron–microglia crosstalk profoundly impacts functional maturation of excitatory presynaptic function, and thereby modulating excitatory synaptic transmission. - blocking CX3CR1 receptor - compensatory mechanisms in the hippocampus similar to what is observed in activation of CX3CR1 without microglia in the amygdala? --> 
Noting that this knockout strain is characterized by the absence of CX3CR1 only in microglia (but the CX3CR1 expression is not observed anywhere else)<!-- citation-->, these observations implicate, similar to our findings, that the lack of microglial CX3CR1 activation, either due to transgenic deletion or by reduced number of those cells, results in immature phenotype of dendritic spines.
However, in knockout mice the compensatory mechanisms are possible, whereas in our neuronal cultures this morphology was not observed in AraC-cultured neurons in baseline conditions, but after CX3CL1 treatment, 
<!-- te badania o microgleju i komórkach -->

It is thought that the AMPAR activation can lead to spine maturation (Fischer et al., 2000; Hoshiko et al., 2012).
LTP i czemu nie widzimy nic w excitatory ?
<!-- AMPA/NMDA ratio -->

It should be noted that these findings ....<!-- sheridan -->.
However, if these hypotheses are true, the 
Moreover, in the context of dendritic morphology, CX3CL1 action is strongly mediated by glia, most probably microglia, considering that the decreased number of glial cells reduction leads to 
<!-- this switch - either neuronal component of CX3CL1 action is making them more filopodial or some other, indirect mechanism 
underlying mechanisms are unknow --> 
<!-- Nevertheless, CX3CL1 application in the presence of AraC led to more immature phenotype, suggesting a decreased functional connectivity within the amygdala. -->


Nevertheless, considering that our cultures were mainly neuronal (> 95%), this needs to be further verified in other experimental settings, such as brain slices and *in vivo*.



Nevertheless, the present study revealed CX3CL1-induced alterations involving structural remodeling of dendritic spines, which is in line with the reduced magnitude of LTP.<!-- zmienić // In conclusion, the results of the present study using the dendritic spines imaging in rat pups have provided further evidence that the anxiogenic effects of chronic stress are not apparently associated with remarkable changes of dendritic morphology in pyramidal neurons of the CeA.--><!-- zmienić // The data however have revealed more subtle CRS-induced alterations involving structural remodeling of dendritic spines, which are suggestive of a decreased functional connectivity of the CeA.-->
Although dendritic spines imaging and electrophysiological experiments were performed in two different systems (neuronal cultures vs. acute slices, respectively), the concordance of the data strongly suggests that similar mechanisms were operated by CX3CL1 in both systems.<!-- analogous to CX3CL1 dendritic spines and electrophysiology -->
 Since in the coculture experiments astrocytes were not completely devoid of microglia cells (representing 4–6% of total cells), we could not rule out that astrocytes-microglia cross talk was necessary for CXCL16mediated neuroprotection.-->
Additionally, neuronal cultures were supplemented with mitotic inhibition (cytarabine (AraC)), an inhibitor of uncontrolled proliferation of non-neuronal cells, without affecting neuronal survival or neurite outgrowth or soma diameter [@schwieger_2016].
Thus, under such conditions, the glial contribution to observed CX3CL1-induced morphological changes in dendritic spines is further decreased, highlighting mostly neuronal effects.

<!-- no layers in the amygdala
Finally, in comparison to other reasonably well-understood brain regions such as the cerebral cortex, hippocampus, and cerebellum, the amygdaloid nuclei do not show a rigid organization of its neuronal elements. Cells are not organized into layers nor do they have the striking preferred orientation of their major output neurons as described in these other brain regions. Thus it is not surprising that input-output mechanisms in the LA are regulated by the various ionic conductances in the membranes of their major output neurons rather than through mechanisms that rely on architectonics and differences in cell morphology. [@faber_2001]-->

<!--However, observed immature phenotype of dendritic spine imply an impaired synapses, which often is paralleled with decreased in glutamatergic transmission and/or synaptic plasticity. cytowania-->

<!-- Glutamatergic projection neurons within the BLA consolidate these signals and project onto downstream extended amygdala structures thereby driving the physiological manifestations of anxiety-like behaviors ( Tye et al., 2011 ) Notably, pharmacological agents that decrease excitability of BLA projection neurons, by increasing GABAergic inhibition or decreasing glutamatergic transmission, are ef fi cacious at attenuating phenotypic expressions of anxiety ( Millan, 2003 ). Additionally, there is now compelling evidence that stress and anxiety play a critical role in alcoholism ( Koob, 2013; Silberman et al., 2009 ). Acute ethanol consumption can reduce anxiety-like behaviors while withdrawal from chronic ethanol can exacerbate anxiety ( Koob, 2013; McCool et al., 2010 ). However, despite many recent advances, our understanding of the key neuromodulatory systems that regulate BLA excitability are not fully understood. -->