# Conclusions

In the present work, the effects of two structurally different chemokines, CX3CL1 and CXCL12, on neuronal electrical behavior as well as synaptic properties in the amygdala were investigated, mainly by employing a whole-cell patch-clamp technique. 
Both of these chemokines are essential during neurodevelopment, and they have been emerging as key players in neuron-glial interactions and neuromodulation during adulthood [@rauxlegoazigo_2013; @trettel_2020].
Moreover, some studies have implicated them as mediators of many neurobiological diseases, including anxiety and epilepsy [@schubert_2018; @yang_2016].<!--dodać citations z epilepsy-->
Increased anxiety and seizures are considered manifestations of amygdala's malfunctioning.
For example, several lines of evidence illustrate that BLA hyperexcitability manifests behaviorally as anxiety, emotional dysregulation, or development of seizure activity.<!--citations?-->

Findings presented in this PhD dissertation illustrate that both CX3CL1 and CXCL12 modulate the activity of the amygdala network; however, in an opposite manner.
The main findings of the study regarding CX3CL1 in the BLA are as follows:
(i) the CX3CL1 application decreased excitability and impaired LTP at the concentration of 5nM.
(ii) GABAergic synaptic transmission was downregulated following CX3CL1 treatment.
Based on these observations and previous literature regarding similar mechanisms in the BLA, we speculate that CX3CL1 acts on PV-expressing subpopulation of BLA interneurons. 
These interneurons target the AIS of principal cells, and decreased GABAergic activity in this area was shown to change the threshold current needed for eliciting an action potential [@saha_2016; @veres_2014; @wefelmeyer_2015; @zonta_2011].
At the network level, PV-containing interneurons are also implicated in the attenuation of the LTP [@saha_2016; @wolff_2014].

Moreover, reduction of GABAergic synaptic activity in AIS was shown to be mediated by microglia in the cortex [@chen_2014].
Thus, considering our findings together with the well-documented abundance of the CX3CR1 receptor in the microglia  in the CNS, it is possible that a similar mechanism could be present in the amygdala.

Similarly, CX3CL1 also displayed cell-type-specific actions in the CeL. 
Specifically, CX3CL1 was shown to reduce the input resistance and membrane time constant, decrease the excitability and induce depolarization in the Regular-Firing neurons but not in the Late-Firing neurons. 
Those electrophysiological effects are hallmarks of HCN activation.<!--citations-->
Thus, it is tempting to speculate that CX3CL1 might modulate HCN channels.
In addition, the reduced firing in the Regular-Firing cells is in good agreement with decreased frequency of sIPSCs onto Late-Firing cells, as the Regular-Spiking neurons were previously reported to send more dense and potent connections onto Late-Firing cells and *vice versa* [@hou_2016]. 

Interestingly, the pre-treatment with minocycline, probably by inhibition of microglia (for example: @peng_2016; @scianni_2013; @yuan_2020), increased the firing of principal cells in the BLA and Late-Firing in the CeL. 
These effects were eliminated after CX3CL1 application, probably due to the neuroprotective role of CX3CL1.
CX3CL1/CX3CR1 signaling is implicated with pathophysiological augmentation of glutamatergic transmission, as deletion of CX3CR1 in microglia led to neuronal death in such models as systemic inflammation, amyotrophic lateral sclerosis (ALS), and Parkinson’s disease (PD) [@cardona_2006], whereas upregulation of CX3CL1 was shown to reduce neurodegeneration in an animal model of PD [@morganti_2012] or AD [@finneran_2019].
Thus, it is possible that the elimination of minocycline-induced facilitation of principal cells' firing is also a manifestation of CX3CL1 neuroprotective actions and that this chemokine exerts anxiolytic effects in the BLA. 

The results concerning CXCL12 present a complex picture.<!--jakoś inaczej napisać..-->
In the BLA, according to @yang_2016 hypothesis, there is a tendency toward the enhanced excitability of principal cells after CXCL12 application. 
However, the CXCL12-mediated enhancement of the excitatory transmission was not replicated here, probably due to a different slice orientation and/or the GABAergic modulation of this effect. 
Indeed, the exogenous CXCL12 did affect the inhibitory synaptic transmission in a subset of principal cells, although these effects were not statistically significant. 
Nevertheless, most neurons responded with decreased frequency of sIPSCs at the concentration of 2nM in the BLA, whereas at a higher dose, the median frequency of sIPSCs was increased.

In the CeL, obtained data showed that the exogenous CXCL12 decreased threshold, and thus increasing the excitability of both Regular-Spiking and Late-Firing neurons. 
However, the excitatory synaptic transmission was upregulated only onto Regular-Spiking neurons, suggesting that either BLA principal neurons or PVN neurons preferentially innervate the Regular-Spiking, SOM-expressing neurons.
This is in line with a study showing that PVT neurons preferentially innervated SOM-positive neurons in CeL [@penzo_2015], which is in good agreement with the observed enhancement of excitatory transmission onto Regular-Spiking neurons. 
Notably, based on the concentration (2nM vs. 5nM), CXCL12 produced an opposite trend towards  decreased or increased frequency of excitatory synaptic events.
This is consistent with our data showing elevated excitability of principal neurons at higher concentration.
Intriguingly, although those cells are well-known to innervate CeL neurons, @li_2013a showed that these connections are more evident onto SOM-expressing neurons during fear-conditioning.
This may be linked with observations that intra-amygdala infusion of CXCL12 impaired the acquisition and extinction of conditioned fear response [@shi_2016].
Therefore, the underlying mechanism of CXCL12 involvement during fear-conditioning and anxiety is of importance to be further elucidated. 

Findings obtained in this study illustrated that CXCL12 also affected GABAergic system.
Specifically, CXCL12 was shown to increase the frequency of sIPSCs in Regular-Firing neurons and decreased the amplitude of those currents in the Late-Firing neurons.
Moreover, both action potential-dependent and astrocytic mechanisms were illustrated to be involved in those effects.  
This is in line with the another study, where intra-amygdala infusion of CXCL12 led to impairment of fear acquisition and extinction in a GABA~A~ and GABA~B~ receptors-dependent manner [@shi_2016].
Hence, the further investigations how CXCL12 modulate fear-conditioning and anxiety is of high importance.

 
Altogether, data presented in this PhD dissertation lay the fundamental groundwork to further investigate neuron-glia crosstalk and chemokine signaling in the amygdala.
Therefore, our results together with the published literature provide support for general hypothesis that chemokines, in addition to traditional neurotransmitters and neuropeptides, represent a neuromodulatory system in the CNS. <!--Altogether, current data add another piece to the growing body of evidence of chemokines' neuromodulatory effects in the CNS. /// CX3CL1 and other chemokines may also represent a new class of CNS neuromodulators, impacting brain function *via* their effects on traditional neurotransmitter and neuropeptide systems, including the 5-HT system (Adler and Rogers, 2005; Adler et al., 2006; Calle-waere et al., 2007; Rostene et al., 2007). --> 
Moreover, as suggested by @halbach_2002, this study is also of methodological value by highlighting the importance of using horizontal slices in electrophysiological approaches when investigating the excitatory synaptic transmission in the amygdala.<!-- or add methodological value--> 
Of note, observed opposing actions for CX3CL1/CX3CR1 and CXCL12/CXCR4 illustrated that chemokine signaling in the amygdala is highly dynamic, which is further amplified by their ability to interfere with synaptic plasticity and morphology of dendritic spines, at least for the CX3CL1. 
Hence, the understanding of the peculiar pharmacological responses of chemokine receptors in different circuits and cell types of the amygdala is of particular importance, given their potential role in the etiology of emotional disorders and their corresponding usefulness as therapeutic targets to manage emotional disorders.
<!-- Taken together, CXCL12/CXCR4 and CX3CL1/CX3CR1 network actions and the regulation of glia-neuron communication make it possible to fine-tune amygdala activity and resulting output to maintain emotional homeostasis. Taken together, the rich diversity of neuro-peptides and their receptors in the central amygdala, second only to the hypothalamus, makes it possible to fine-tune amygdala activity and resulting output to maintain emotional homeostasis. // zerżnięte z van der bourg review o peptides in CeA - analogicznie dla chemokin -->
<!--Thus, further experiments identifying the properties and functions of each of neuronal, microglial, astrocytic and, oligodendrocytic compartments remain to be addressed.--> 

<!--Nevertheless, even though chemokines are released during all pathological states, including inflammation, it is important to determine their role in physiological, non-inflammatory state. 
Even though cytokines released by stress in brain have the capability of influencing neural function, it has yet to be determined how stress in a ‘‘sterile’’ environment (i.e., in the absence of infection) can increase these cytokines in brain. This latter aspect too must be addressed before the full impact of stress in relation to cytokine influences on neural function is understood. The means by which cytokines are involved in stress is important because cytokines and stress are implicated in pain ( Fu and Neugebauer, 2008; Vachon-Presseau et al., 2013; Watkins et al., 2001 ), sleep ( Krueger et al., 2007; Churchill et al., 2008 ), depression ( Caspi et al., 2003; Hammen, 2005 ), anxiety ( Breese et al., 2008; Shin and Liberzon, 2010 ) and drug addiction ( Breese et al., 2011; Koob, 2008 ). A further understanding of the unknowns by which cytokines contribute to stress to alter neural function may allow a better appreciation of the complexity by which stress induces changes in neural transmission that contribute to the functional changes associated with stress-linked central disorders.-->



<!-- NAC modulates antioxidant, glutamatergic, inflammatory and neurotrophic pathways in the central nervous system, all of which are relevant to anxiety pathology.chemokines // conclusion?
Thus, the present efforts not only will provide further evidence that cytokines affect CeA neural function, but also will explore the means by which CeA-neural function can be associated with TNFa-induction of glutamate and GABA activity. 
Such extended information concerning actions of cytokines on CeA neurons is expected to further our understanding of the relationship stress-induction of cytokines has to facilitation of anxiety-like behavior that follows stress ( Breese et al., 2004, 2008, 2011; Knapp et al., 2011 ).-->  


\newpage

<!--The identification of AR1as downstream element responsible for beneficial effects of CX3CL1 on neuron survival against Glu neurotoxicity may represent an important challenge for management of neurological disorders including acute brain ischemia. -->
<!-- In vitro and in vivo studies have reported that both of these chemokines modulate dopamine neurotransmission in the nigrostriatal pathway, modifying the electrophysiological state of the neurons and dopamine release via the corresponding endogenous receptors -->

<!-- has received increasing interest because of its widespread function in mediating innate, as well as learned, adaptive and maladaptive behaviors.-->

<!-- Our data collectively demonstrate that B6129SF2/J mice show an ethanol phenotype similar to that of C57BL6J mice, both behaviorally and electrophysiologically, in the CeA. IL-1β modulation of CeA GABAergic transmission is complex and characterized by dual and cell-specific modulations of presynaptic GABA release and postsynaptic GABAA receptor activity. With regard to the IL-1β effects on ethanol-induced facilitation of CeA GABAergic transmission, our data indicate that IL-1β interacts with ethanol presynaptically to occlude ethanol’s enhancement of GABA signaling. Understanding these complex interactions of acute ethanol with IL-1 on GABAergic transmission are critical for shedding light on the potential role of the IL-1 neuroimmune system in the development of alcohol dependence and addiction.-->