---
output: pdf_document
---

# Introduction

## Chemokines

Chemokines (chemotactic cytokines) are a family of small (7-11 kDa) secreted proteins. They exert their biological effects through cell surface receptors that belong to the superfamily of seven-membrane domain G-protein-coupled receptors (GPCRs) and are expressed in a wide variety of cells [@Bacon2000a]. They were originally identified as serving chemotactic function on immune cells; however, recent evidence has begun to elucidate novel, brain-specific functions of these proteins, more relevant to the mechanisms of psychiatric disorders. Of particular interest is the idea that central nervous system (CNS) chemokines are not only mediators of neuroinflammation, but also function as neuromodulators or neurotransmitters in the brain [@Adler2005]. Like those systems, the chemokine system is widely but unevenly distributed in the brain and has both ligands and receptors expressed in neurons. For example, the chemokines SDF- 1α/CXCL12 and fractalkine/CX3CL1 as well as their receptors CXCR4 and CX3CR1 are expressed constitutively, even in physiological conditions, throughout the CNS [@Banisadr2002a, @Hesselgesser1999, @Schonemeier2008]. Why do cells (neurons, astrocytes, and microglia) in CNS express chemokines and chemokine receptors, and what is the neurophysiological relevance of chemokines in the CNS? The plausible explanation is that they may provide a bridge between the immune and nervous systems, which are classically viewed as two complex and distinct entities. In addition to the role of chemokines in the developing and diseased brain (for example in multiple sclerosis and Alzheimer’s disease [@Cartier2005, @Tran2003], only a handful of studies have examined the basic neurophysiological correlates of chemokine signaling in the CNS. The effects of chemokines in the brain may be due to their ability to activate chemokine receptors localized on neurons and/or glia, thus leading to changes in neuronal membrane properties and/or synaptic transmission. Specifically, chemokines may alter synaptic transmitter release [@Limatola2000, @Ragozzino2002], modulate the functional properties of ionic channels [@Lax2002, @Oh2002] and promote the release of glutamate from astrocytes [@Lax2002]. In addition, the chemokine system can alter the actions of neuronally active pharmacological agents such as opioids and the cannabinoid system [@Heinisch2011]. Moreover, chemokine receptor knockout mice (CCR6, CCR7, CXCR5) have recently been shown to exhibit behavioral and neurobiological phenotypes of relevance to psychiatric disorders, which therefore may be of value as animal models of certain psychiatric symptoms [@Harrison2014, @Jaehne2014, @Stuart2014]. Yet, recognition and characterization of chemokine effects on neurophysiology is still lacking and such studies would provide a more complete understanding of the vital role played by these immune proteins in the nervous system, and may ultimately lead to novel therapies for neuro-immune diseases.

### CX3CL1

Fractalkine, also known as CX3CL1, is a unique chemokine belonging to CX3C chemokine family that is present both as soluble and membrane-anchored form (Bajetto, Bonavia, Barbero, Florio, & Schettini, 2001). Fractalkine is the endogenous ligand for CX3CR1, a G-protein coupled receptor (GPCR) which specifically interacts with both forms of CX3CL1 (Imai et al., 1997). Recent reports confine the localization of CX3CL1 to neurons and astrocytes and CX3CR1 to neurons and microglia in many brain regions including the hippocampus, amygdala, cerebral cortex, globus pallidus, striatum and thalamus (Tarozzo et al., 2003). In physiological conditions, CX3CL1/CX3CR1 signaling is involved in different neural functions both in development (participation in functional maturation of neuronal circuits driving cell positioning) and adulthood (regulation of synaptic plasticity and cognitive functions) (Lauro, Catalano, Trettel, & Limatola, 2015). Furthermore, fractalkine seems to play an essential role in a unique neuronal-glial interaction between neurons and CX3CR1-expressing microglia under normal and pathological states (Cardona et al., 2006; Jurgens & Johnson, 2012). In fact, CX3CL1 is a confirmed inhibitor of basal glutamate synaptic activity in the hippocampus (Bertollini, Ragozzino, Gross, Limatola, & Eusebi, 2006). The ability of CX3CL1 to modulate glutamate function is thought to be responsible for some of its neuroprotective actions, and provides further support for the chemokine-neuromodulatory role in the CNS (Adler et al., 2005; Callewaere, Banisadr, Rostène, & Parsadaniantz, 2007; Guyon & Nahon, 2007).

### CXCL12

SDF-1α (CXCL12) is another chemokine which has recently attracted much attention due to its extensive distribution in the CNS as well as the fact that it can be produced not only by glial cells but also by neurons (Banisadr, Skrzydelski, Kitabgi, Rostène, & Parsadaniantz, 2003; Heinisch & Kirby, 2010; Stumm et al., 2002). This chemokine has been shown to play an essential role in brain plasticity during development but also in regulating the activity of various brain circuits in normal and pathological conditions (Merino, Bellver-Landete, Oset-Gasque, & Cubelos, 2014; Timotijević, Mostarica Stojković, & Miljković, 2012; Tiveron & Cremer, 2008). Furthermore, recent studies have shown that there are several cross-talks between the CXCL12 and with its receptor CXCR4 and other neurotransmitter systems in the brain (e.g. GABA, glutamate and endocannabinoids) (Heinisch & Kirby, 2010; Heinisch et al., 2011). The neuromodulatory actions of CXCL12 have been observed in various neuronal populations, including the hippocampus (Kasiyanov, Fujii, Tamamura, & Xiong, 2008), cerebellum (Limatola et al., 2000), MCH neurons of the lateral hypothalamus area (LHA; Guyon et al., 2005), vasopressinergic neurons of the hypothalamus (Callewaere et al., 2006), dopaminergic neurons of the substantia nigra (Guyon et al., 2006), the dorsal raphe nucleus (Silke Heinisch & Kirby, 2010) and recently the amygdala (Yang et al., 2016). What is particularly interesting, CXCL12 has often similar effects in these various circuits (increase in glutamate and/or GABA synaptic activity), however these effects occur via different mechanisms, even within one structure. For example, in the dorsal raphe nucleus CXCL12 increases the frequency of recorded spontaneous inhibitory post-synaptic currents (sIPSC) in serotonergic neurons through a pre-synaptic mechanism, but decreases sIPSC amplitude via a post-synaptic mechanism in non-serotonergic neurons (Heinisch & Kirby, 2010). Moreover, CXCL12 often appears to exert opposite effects on neuronal function depending on its concentration, e.g. in MCH-expressing neurons of the LHA, where the action potential discharge is different depending on the concentration (Guyon et al., 2005). Of particular interest is the observation that pro-inflammatory cytokine stimulation leads to elevated levels of CXCL12 and other chemokines by activation of glial or endothelial cells which in turn release chemokines (Guyon, 2014). The chemokines released bind to CXCR4 present on neurons and induce changes in excitability that could induce an adaptive response to inflammation, leading to “sickness behavior,” characterized by decreased mood, anorexia, and fatigue (Dantzer, 2001; Dantzer & Kelley, 2007). Sickness behavior is considered to be the physiological and psychological effect of immune activation during the course of infection, which is primarily mediated by the central action of peripherally released proinflammatory cytokines. Given the abundance of chemokines and their receptors in the CNS, it is not surprising that changes of cytokine/chemokine levels during inflammation are causing multiple physiological and behavioral perturbations. For example, effects of CXCL12 on dorsal raphe neurons could underlie depressive symptoms frequently observed with inflammation (Maes et al., 1998), as dysfunction of the serotoninergic systems is implicated in depression. Similarly, the effects of CXCL12 on MCH neurons which are part of the feeding behavior and metabolism control circuit (Nahon, 2006) could explain anorexia. These symptoms of sickness behavior are usually reversible when inflammation stops. Overall, this chemokine system is one of the key players in the neuro-immune interface that participates in shaping CNS responses to changes in the environment.

## Amygdala

The amygdala, a limbic region in the medial temporal lobe, may be crucial for modulating immune and stress responses. It is considered to be an essential component of the brain circuitry that forms the neural response to systemic immune activation (Gaykema, Chen, & Goehler, 2007) and it is involved in sickness behavior (Dantzer, O’Connor, Freund, Johnson, & Kelley, 2008; Goehler, Lyte, & Gaykema, 2007; Roozendaal, McEwen, & Chattarji, 2009). Amygdala activity is also critical for mood regulation and the central and peripheral stress response as well as attaching emotional valence to perceived stimuli (Duvarci & Pare, 2014; Hermans et al., 2014). The various nuclei of the amygdaloid complex can be grouped in to three major functionally different domains by their different connectivity, immunohistochemical and cytoarchitectural profiles: the basolateral complex of the amygdala (BLA), the central amygdala (CeA) and intercalated cell masses (ICM). The BLA is considered to be the main point of entry for cortical and subcortical sensory inputs into the amygdala, whereas the CeA is the main source of projections to many brain structures involved mainly in the stress response (Duvarci & Pare, 2014). These regions also differ in their cellular profile. Within the BLA, which developmentally and structurally is a cortical-like structure, approximately 80% of all neurons are glutamatergic pyramidal-like principal cells and the remaining 20% belong to a heterogeneous group of interneurons (Spampanato, Polepalli, & Sah, 2011). The pyramidal-like cells follow the electrophysiological profile of their cortical counterparts, having either a regular spiking or intrinsically bursting phenotype, with pronounced spike frequency adaptation (Sah, Faber, Lopez De Armentia, & Power, 2003). There are at least five distinct types of interneurons, which differ in their neurochemistry and electrophysiological properties and morphology, however most of them are of the fast-spiking variety, with no apparent adaptation (Spampanato et al., 2011). The CeA principal neurons are GABAergic in nature, morphologically reminiscent of striatal medium spiny neurons. Three electrophysiological subtypes of CeA neurons have been described: regular spiking, low threshold bursting and late firing (Sah, 2004). The amygdala is very densely interconnected. In the BLA, principal cells form local synapses with inhibitory interneurons. However, they also have numerous longer distance collaterals synapsing onto other principal cells (Duvarci & Pare, 2014). Principal cells in the BLA send their axons to the CeA, either directly or via intercalated GABAergic cell clusters in the intermediate capsule (Jüngling et al., 2008). The CeA network then receives these inputs and computes the inhibitory GABAergic output to various brain areas. Regarding neuroinflammation circuit, pro-inflammatory cytokines signal the brain mainly through the activation of vagal afferent fibers projecting to the nucleus of the solitary tract (NTS) and then to amygdala (Goehler et al., 2000; Quan, 2008). Therefore, it is important to get better insights into brain activity during acute and chronic immune responses.
Evidence from many animal studies indicates that LPS significantly increases c-fos expression in the central nucleus of the amygdala (CeA) and, to a lesser extent, in the basolateral nucleus of the amygdala (BLA) (Engler et al., 2011; Frenois et al., 2007; Vitkovic et al., 2000). Moreover, functional and neuroanatomical studies indicate that peripheral immune activation may also affect amygdala function in humans. For example, depressive-like symptoms and anxiety can be transiently elicited in healthy human subjects by peripheral administration of LPS (Grigoleit et al., 2011; Harrison et al., 2009; Wright, Strike, Brydon, & Steptoe, 2005). These findings suggest that in humans, similar to rodents, the amygdala is involved in the integration of behavioral and immune responses.
A recent study documented that LPS-induced anxiety in mice as well as a pronounced increase in sEPSC frequency resulting in the hyperexcitability of BLA neurons were mediated through the CXCL12/CXCR4 interaction (Yang et al., 2016), which is similar to effects elicited by corticosterone administration (Duvarci & Paré, 2007). This suggests that alterations of CXCL12 signaling in this area play critical roles in the development of anxiety induced by systemic inflammation, and that CXCR4 may be a potential therapeutic target for inflammation-induced anxiety, a key component of a sickness behavior. Several studies have indicated the relative abundance of CX3CL1 receptors within the amygdala complex, including the BLA and the CeA (Nishiyori et al., 1998; Tarozzo et al., 2003), suggesting a possible influence on amygdala function. Although CX3CL1 also modulate synaptic activity and has been shown to modulate glutamate and GABA release in the hippocampus (Ragozzino et al., 2006) and dorsal raphe nucleus (Heinisch & Kirby, 2009), its neuromodulatory role in other brain centers remains unknown. Surprisingly, so far there have been no neurophysiological studies of CX3CL1 effects in the amygdala. Therefore, the proposed experiments would be the first to analyze the possible influence of fractalkine on amygdala activity.
Given its importance as a modulator of synaptic neurotransmission and reported functions in neuron–glia
communication, valuable insight can be gained by investigating whether CX3CL1/CX3CR1 signaling is involved in modulation of the stress response in the amygdala. The possible cellular and network mechanisms of chemokine effects in the amygdala will be systematically tested in this project. Taken together, both chemokines show constitutive and diffusive expression in the rat CNS in both physiological and pathophysiological conditions. During inflammation both of them are upregulated, however, their roles may be different. So far only a few electrophysiological studies have been conducted and only in basal, ‘healthy’ conditions.

### Basolateral amygdala


### Central amygdala


## Neuro-glial interactions